src/common/KokkosKernels_IOUtils.hpp, src/common/KokkosKernels_SparseUtils.hpp, src/common/KokkosKernels_Uniform_Initialized_MemoryPool.hpp, src/sparse/impl/KokkosSparse_gauss_seidel_impl.hpp, src/sparse/impl/KokkosSparse_spgemm_impl.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_kkmem.hpp, unit_test/sparse/Test_Sparse_findRelOffset.hpp, unit_test/sparse/Test_Sparse_gauss_seidel.hpp, unit_test/sparse/Test_Sparse_replaceSumInto.hpp, unit_test/sparse/Test_Sparse_replaceSumIntoLonger.hpp, unit_test/sparse/Test_Sparse_spgemm.hpp
=> Cuda spgemm fix

src/batched/KokkosBatched_Gemm_Serial_Internal.hpp, src/batched/KokkosBatched_Gemm_Team_Internal.hpp, src/batched/KokkosBatched_Gemv_Serial_Internal.hpp, src/batched/KokkosBatched_Gemv_Team_Internal.hpp, src/batched/KokkosBatched_InnerMultipleDotProduct_Decl.hpp, src/batched/KokkosBatched_Trsm_Serial_Internal.hpp, src/batched/KokkosBatched_Trsm_Team_Internal.hpp, src/batched/KokkosBatched_Trsv_Serial_Internal.hpp, src/batched/KokkosBatched_Trsv_Team_Internal.hpp, src/batched/KokkosBatched_Util.hpp, src/batched/KokkosBatched_Vector_AVX256D.hpp, src/batched/KokkosBatched_Vector_AVX512D.hpp, unit_test/batched/Test_Batched_VectorArithmatic.hpp
@ambrad This will fix your problem in ifpack2.
=> Batched modification

src/Kokkos_ArithTraits.hpp
Warning with char in ArithTraits abs function on Power
=> Fix issue #60

src/sparse/KokkosSparse_CrsMatrix.hpp
=> Fix #11 (replaceValues / sumIntoValues bug)

src/sparse/impl/KokkosSparse_gauss_seidel_spec.hpp
=> Gauss Seidel fixing copy paste error

src/batched/KokkosBatched_AddRadial_Internal.hpp, src/batched/KokkosBatched_LU_Decl.hpp, src/batched/KokkosBatched_LU_Serial_Impl.hpp, src/batched/KokkosBatched_LU_Serial_Internal.hpp, src/batched/KokkosBatched_LU_Team_Impl.hpp, src/batched/KokkosBatched_LU_Team_Internal.hpp, src/batched/KokkosBatched_Vector.hpp, unit_test/batched/Test_Batched_VectorArithmatic.hpp
@ndellingwood this PR is needed to use complex in Ifpack2 tests.
=> KokkoBatched - add radial complex version is needed in ifpack2

perf_test/batched/KokkosBatched_Test_LU_Cuda.cpp
Required following changes from issue kokkos/kokkos#1470
Addresses issue #186
=> Replace KOKKOS_INLINE_FUNCTION_DEFAULTED with KOKKOS_INLINE_FUNCTION

src/sparse/KokkosSparse_BlockCrsMatrix.hpp, src/sparse/KokkosSparse_CrsMatrix.hpp, unit_test/cuda/Test_Cuda_Sparse_CrsMatrix.cpp, unit_test/openmp/Test_OpenMP_Sparse_CrsMatrix.cpp, unit_test/serial/Test_Serial_Sparse_CrsMatrix.cpp, unit_test/sparse/Test_Sparse_BlockCrsMatrix.hpp, unit_test/threads/Test_Threads_Sparse_CrsMatrix.cpp
Implementation of BlockCrsMatrix.
Address feature request #184
=> BlockCrsMatrix

src/sparse/KokkosSparse_BlockCrsMatrix.hpp
BlockDim ctor input variable caused shadow error due to
blockDim() member function name
=> BlockCrsMatrix: Fix gcc/4.8.4 shadow error

src/batched/KokkosBatched_Gemm_Team_Internal.hpp, src/batched/KokkosBatched_LU_Serial_Internal.hpp, src/batched/KokkosBatched_LU_Team_Internal.hpp, src/batched/KokkosBatched_Trsm_Team_Internal.hpp
This fixes SPARC problems. trilinos/Trilinos#2714
=> Little perturbation of diagonal should be applied to the reference of the diagonal values

scripts/trilinos-integration/prepare_trilinos_repos.sh
modified:   prepare_trilinos_repos.sh
=> update snapshot script path

perf_test/batched/KokkosBatched_Test_BlockCrs_Host.cpp, perf_test/batched/KokkosBatched_Test_Gemm_Host.hpp, perf_test/batched/KokkosBatched_Test_Gemm_Host_Complex.cpp, perf_test/batched/KokkosBatched_Test_Gemm_Host_Real.cpp, perf_test/batched/KokkosBatched_Test_Gemv_Host.hpp, perf_test/batched/KokkosBatched_Test_Gemv_Host_Real.cpp, perf_test/batched/KokkosBatched_Test_LU_Host.hpp, perf_test/batched/KokkosBatched_Test_LU_Host_Real.cpp, perf_test/batched/KokkosBatched_Test_Trsm_Host.hpp, perf_test/batched/KokkosBatched_Test_Trsm_Host_Real.cpp, src/batched/KokkosBatched_Gemm_Serial_Impl.hpp, src/batched/KokkosBatched_Gemv_Serial_Impl.hpp, src/batched/KokkosBatched_LU_Serial_Impl.hpp, src/batched/KokkosBatched_Trsm_Serial_Impl.hpp, src/batched/KokkosBatched_Trsv_Serial_Impl.hpp, src/batched/KokkosBatched_Util.hpp, unit_test/batched/Test_Batched_SerialTrsm_Complex.hpp
Changes made to impl files; perf_test changes still needed.
Partially addresses issue #216
=> MKL batched changes - API changes

scripts/test_all_sandia
Update gcc and xl compilers in list
=> test_all_sandia: update for White module changes

src/impl/tpls/KokkosBlas2_gemv_tpl_spec_decl.hpp, src/impl/tpls/KokkosBlas3_gemm_tpl_spec_decl.hpp
fix strides depicted in #292 and trilinos/Trilinos#3420.
=> KokkosKernels - strides error

perf_test/batched/KokkosBatched_Test_Gemm_Cuda.cpp, perf_test/batched/KokkosBatched_Test_LU_Cuda.cpp, perf_test/batched/KokkosBatched_Test_Trsm_Cuda.cpp, test_common/KokkosBatched_Test_BlockCrs.hpp
kokkos uses launch bounds and impl interface is changed. this PR follows the changes.
=> KokkosBatched - change cuda get team size according to kokkos changes

scripts/test_all_sandia
=> test_all_sandia: update compiler lists

scripts/trilinos-integration/blake_jenkins_run_script_pthread_intel, scripts/trilinos-integration/blake_jenkins_run_script_serial_intel, scripts/trilinos-integration/white_run_jenkins_script_cuda, scripts/trilinos-integration/white_run_jenkins_script_omp
Make default Kokkos branch "develop" if none given
=> Update trilinos integration scripts (2)

src/impl/tpls/KokkosBlas1_dot_tpl_spec_decl.hpp, src/impl/tpls/KokkosBlas1_scal_tpl_spec_decl.hpp, src/impl/tpls/KokkosBlas2_gemv_tpl_spec_decl.hpp, src/impl/tpls/KokkosBlas3_gemm_tpl_spec_decl.hpp, unit_test/blas/Test_Blas3_gemm.hpp
related issues
#307 ,  trilinos/Trilinos#3493
In trilinos KK, complex TPL dot is currently disabled. This fixes the problem and enables TPL dot.
=> Issue 307 - fix complex tpl local declarations and some other typos in KK

src/graph/impl/KokkosGraph_GraphColor_impl.hpp, unit_test/graph/Test_Graph_graph_color.hpp, unit_test/graph/Test_Graph_graph_color_deterministic.hpp
Fixing the issue that made the VBD and VBDBIT algorithm fail on CUDA
=> Deterministic Coloring: reactivating VBD and VBDBIT unit test

unit_test/batched/Test_Batched_VectorMath.hpp, unit_test/blas/Test_Blas1_abs.hpp, unit_test/blas/Test_Blas1_nrm2.hpp, unit_test/blas/Test_Blas1_nrm2_squared.hpp, unit_test/blas/Test_Blas1_reciprocal.hpp, unit_test/blas/Test_Blas1_scal.hpp, unit_test/blas/Test_Blas1_team_abs.hpp, unit_test/blas/Test_Blas1_team_scal.hpp, unit_test/graph/Test_Graph_graph_color_d2.hpp, unit_test/sparse/Test_Sparse_trsv.hpp
Addresses failing unit test and linking error in issue #322, also -Werror
=> Unit test fixes with float enabled

unit_test/blas/Test_Blas1_team_abs.hpp
Reimplement use of dot(r,y,y) instead of the subview and manual
dot reductions.
=> Make team abs error checking consistent with other PR #325 changes

scripts/generate_makefile.bash, src/Makefile
Updated so that calling 'make clean' works without errors.
=> src/Makefile, generate_makefile: Fixes for make clean

src/blas/impl/KokkosBlas1_abs_impl.hpp
Addressing #252 using a fix suggested by @crtrott .
=> Fix equivalent view check in KokkosBlas1_abs (issue #252)

src/batched/KokkosBatched_HessenbergQR_WithShift_Serial_Internal.hpp
Exposed by Jenkins build KokkosKernels_White_XL_16_1_OpenMP_Serial
Changes to be committed:
modified:   KokkosBatched_HessenbergQR_WithShift_Serial_Internal.hpp
=> Remove unused variable

doc/kokkos-promotion.txt
Documentation for promotion testing process
=> Add doc/kokkos-promotion.txt file

perf_test/batched/KokkosBatched_Test_Gemm_Cuda.cpp, perf_test/batched/KokkosBatched_Test_LU_Cuda.cpp, perf_test/batched/KokkosBatched_Test_Trsm_Cuda.cpp, perf_test/test_crsmatrix.cpp, perf_test/test_mv.cpp, test_common/KokkosKernels_MatrixConverter.cpp
See kokkos/kokkos#2140
Update missed fence in .cpp file
=> Update missed fence in agreement with Kokkos deprecations

src/batched/KokkosBatched_Vector_SIMD_Arith.hpp
@ndellingwood here is the fix.
=> KokkosBatched - fix cuda builtin type conversion

src/impl/tpls/KokkosBlas_gesv_tpl_spec_avail.hpp
-Werror triggered due to multi-line comment, fixed with this PR.
Changes to be committed:
modified:   KokkosBlas_gesv_tpl_spec_avail.hpp
=> Fix -Werror in gesv tpl avail check

src/sparse/impl/KokkosSparse_sptrsv_solve_impl.hpp
Detected during 2.9 Trilinos integration testing
=> sptrsv: Fix for team_size

unit_test/sparse/Test_Sparse_spadd.hpp
=> spadd unit test: Replace deprecated random_shuffle with shuffle

src/sparse/KokkosSparse_spadd.hpp
This should eliminate a suspected race condition detected by Intel Inspector, even though I don't believe is an actual bug.
Apart from that, this avoid allocating unnecessary "C rowcounts" views and removes a redundant parallel prefix sum implementation.
=> Remove redundant prefix-sum in spadd

src/sparse/KokkosSparse_gauss_seidel_handle.hpp
=> KokkosSparse_gauss_seidel_handle.hpp: fix unreachable code warning

src/sparse/impl/KokkosSparse_spgemm_impl_kkmem.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_speed.hpp, unit_test/sparse/Test_Sparse_spmv.hpp
=> spgemm: shmem alignment updates for numeric routines

src/impl/tpls/KokkosBlas3_gemm_tpl_spec_decl.hpp
This PR fixes the failures in Trilinos tests:
https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=PR-6226-test&field2=buildstarttime&compare2=84&value2=NOW
1) NaN failures are fixed by having a different case for beta=0 that actually initializes the entries of C to 0.
2) Diff failures (that happen to only occur on very short vectors -- 50 or 72 entries-- with very tight epsilon) are fixed by allowing fewer than 32 team -- 1 team in those cases. This eliminated the nondeterministic access order of the teams to C array to update the results.
=> Dot based gemm: Add different beta cases and allow fewer than 32 teams 

cm_generate_makefile.bash
Add flag to make BUILD_TYPE optional; add options to set memspaces
=> cm_generate_makefile: more improvements

unit_test/blas/Test_Blas3_gemm.hpp
=> GEMM unit test: Modify way random values set based on execution space

unit_test/sparse/Test_Sparse_spmv.hpp
This work should fix the problem described in issue #506
The new logic introduce for the spmv_struct test should lead to more consistent
checks and hopefully make the test path on GPU platforms.
=> SpMV tests: fixing the logic to detect the level of precision needed

src/impl/tpls/KokkosBlas3_gemm_tpl_spec_decl.hpp
**Description:**
This PR fixes the Trilinos issue https://github.com/trilinos/Trilinos/issues/6470.
**Testing:**
```
[sacer@kokkos-dev-2 testing]$ ../scripts/test_all_sandia --spot-check --arch=Volta70
Running on machine: sems
Going to test compilers:  gcc/5.3.0 gcc/7.2.0 intel/17.0.1 clang/3.9.0 cuda/9.2
Testing compiler gcc/5.3.0
Testing compiler gcc/7.2.0
Testing compiler intel/17.0.1
Starting job gcc-5.3.0-OpenMP-release
Starting job gcc-7.2.0-Serial-release
PASSED gcc-5.3.0-OpenMP-release
Testing compiler clang/3.9.0
Starting job intel-17.0.1-OpenMP-release
PASSED gcc-7.2.0-Serial-release
Testing compiler cuda/9.2
Starting job clang-3.9.0-Pthread_Serial-release
PASSED intel-17.0.1-OpenMP-release
PASSED clang-3.9.0-Pthread_Serial-release
Starting job cuda-9.2-Cuda_OpenMP-release …
```
=> Add the conjugate transpose support to DotBasedGEMM

src/sparse/impl/KokkosSparse_sptrsv_solve_spec.hpp
address issue showing up in Jenkins builds
=> sptrsv: fix -werror

scripts/cm_test_all_sandia, scripts/test_all_sandia
remove from testing for now due to issue reported in #559
=> test_all_sandia: remove intel/18 testing

src/blas/KokkosBlas2_gemv.hpp
=> gemv: fix for degenerate matrices

src/sparse/impl/KokkosSparse_cluster_gauss_seidel_impl.hpp, src/sparse/impl/KokkosSparse_partitioning_impl.hpp, unit_test/sparse/Test_Sparse_gauss_seidel.hpp
Tpetra graphs contain remote columns (entries) that can't be
used as row indices (so the "local" graph may be symmetric, but
entries >= #numRows must be filtered).
Added this filtering to RCM, BFS and balloon clustering.
Also added a test to Gauss-Seidel for zero-row case, where the input
row map can have length 0 or 1. Ran clean through valgrind in openmp.
Same changes Trilinos #6631, plus the zero-row test.
=> Fixed clustering, RCM, BFS accessing neighbors >= nv

src/sparse/impl/KokkosSparse_sptrsv_cuSPARSE_impl.hpp, unit_test/sparse/Test_Sparse_sptrsv.hpp
throw error when requesting to use cusparse on host-allocated data
=> sptrsv: cusparse fix

scripts/cm_test_all_sandia
=> cm_test_all_sandia: use ctest -V for increased testing output

scripts/cm_test_all_sandia
=> cm_test_all_sandia: bowman fix

scripts/cm_test_all_sandia
Also update ctest to dump verbose output upon test failure
=> cm_test_all_sandia: update mayer modules

src/common/KokkosKernels_Handle.hpp, src/sparse/KokkosSparse_gauss_seidel_handle.hpp, src/sparse/impl/KokkosSparse_twostage_gauss_seidel_impl.hpp
This PR is to fix some of undefined references errors due to PR #671 for two-stage GS (e.g., issue #673 ).
=> specifying memory space for two-stage GS

src/common/KokkosKernels_Handle.hpp, src/sparse/KokkosSparse_CrsMatrix.hpp, src/sparse/impl/KokkosSparse_gauss_seidel_spec.hpp, src/sparse/impl/KokkosSparse_twostage_gauss_seidel_impl.hpp
This PR exposes additional functionalities (e.g., use inverse_diagonal provided by Ifpack2) from the two-stage GS.
=> exposing more functionalities (e.g., to Ifpack2) from two-stage GS

unit_test/blas/Test_Blas3_trsm.hpp
Quick fix to reduce the trsm test problem size.
=> Reduce trsm test problem size

src/batched/KokkosBatched_Eigendecomposition_Serial_Internal.hpp
=> KokkosBatched_Eigendecomposition: Skip MKL code path for intel < 18

src/sparse/KokkosSparse_CrsMatrix.hpp
for raw host array constructor. It said it takes COO format, but it really takes CRS format. Also rename "rows" to "rowmap" to avoid confusion. Also remove unused parameter "pad". I'm 99% sure nobody ever passed anything in for pad, but I'm running spot checks just in case.
=> Fix 703: correct CrsMatrix documentation

scripts/cm_test_all_sandia
increase test timeout, add generic path to reproducer output for faster
copy+paste into issues
=> cm_test_all_sandia: increase make par lvl for bowman, white

src/batched/KokkosBatched_SolveUTV_TeamVector_Internal.hpp, unit_test/batched/Test_Batched_TeamVectorSolveUTV2.hpp, unit_test/batched/Test_Batched_TeamVectorSolveUTV2_Real.hpp, unit_test/cuda/Test_Cuda_Batched_TeamVectorSolveUTV_Real.cpp, unit_test/openmp/Test_OpenMP_Batched_TeamVectorSolveUTV_Real.cpp, unit_test/serial/Test_Serial_Batched_TeamVectorSolveUTV_Real.cpp
In the previous PR, I also provide a UTV solver for rank deficient problems. Previous unit test only covers a single right hand side vector. This PR include multiple right hand side case.
=> QR with column pivoting solver

src/batched/KokkosBatched_Trsv_Team_Internal.hpp
This PR is a matching PR.
https://github.com/trilinos/Trilinos/pull/7685
=> KokkosBatched - matching PR for trilinos ifpack2 #7685

example/wiki/sparse/KokkosSparse_wiki_gauss_seidel.cpp, src/common/KokkosKernels_Controls.hpp, src/impl/tpls/KokkosSparse_spmv_tpl_spec_avail.hpp, src/impl/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp, src/sparse/KokkosSparse_spmv.hpp, src/sparse/impl/KokkosSparse_spmv_spec.hpp
Includes changes from Trilinos PRs: https://github.com/trilinos/Trilinos/pull/7677 and https://github.com/trilinos/Trilinos/pull/7694
=> Backport cusparse tpl spmv changes from Trilinos

cm_generate_makefile.bash
Add --boundscheck option to enable Kokkos_ENABLE_DEBUG_BOUNDS_CHECK
Fix issue when kokkos and kokkos-kernels paths not provided
Cleanup
=> generate_makefile: add boundscheck option, fixes

scripts/cm_test_all_sandia
more kokkos-dev and sems module updates
=> cm_test_all_sandia: add cuda/11 for kokkos-dev-2

scripts/cm_test_all_sandia, scripts/update_lib.sh
add timeout input option
remove bowman
update intel/17 old gcc module swaps
=> update test scripts

src/batched/KokkosBatched_Householder_TeamVector_Internal.hpp, src/batched/KokkosBatched_QR_FormQ_TeamVector_Internal.hpp, src/batched/KokkosBatched_QR_WithColumnPivoting_TeamVector_Internal.hpp, src/batched/KokkosBatched_SetIdentity_Impl.hpp, src/batched/KokkosBatched_SetIdentity_Internal.hpp, src/batched/KokkosBatched_SolveUTV_TeamVector_Impl.hpp, src/batched/KokkosBatched_SolveUTV_TeamVector_Internal.hpp, src/batched/KokkosBatched_UTV_TeamVector_Impl.hpp, src/batched/KokkosBatched_UTV_TeamVector_Internal.hpp
=> Modified UTV, SolveUTV, and SetIdentity to support m x n matrices for QR with pivoting

.jenkins/nightly.groovy, scripts/docker/Dockerfile.hip
The job is setup [here](https://cloud.cees.ornl.gov/jenkins-ci/job/KokkosKernels/). I erased the trial builds I did when testing.  It is currently configured to run once a day between 2 and 5am ET.  It is tracking my fork but I will update after we merge.
=> Setup nightly HIP builds on ONRL's Jenkins

test_common/KokkosKernels_TestUtils.hpp
Use StridedLayout that is really consistent between the two possible result types - having the two ternary operator results be different types was causing errors in a build with scalar=float.
=> Fix view types across ternary operator

cm_generate_makefile.bash, scripts/cm_test_all_sandia, scripts/update_lib.sh
Load newer gcc with clang/9, clang/10 (needed for c++17 support and newer)
Update slurm for voltrino
Add sogpu01
=> Update testing scripts

src/Kokkos_ArithTraits.hpp
Detected during release 3.4.0 testing with Trilinos
=> Kokkos_ArithTraits.hpp: Fix isInf and isNan with complex types

src/Kokkos_ArithTraits.hpp
This pull requests cherry-picks d5f0d7e313c5100a9b884684a873b1f2d84e03a4 from #927. The fixes there are needed for https://github.com/trilinos/Trilinos/pull/9086.
=> Cherry-pick Kokkos_ArithTraits.hpp from #927

scripts/cm_test_all_sandia, scripts/update_lib.sh
Add node to for new cuda/11.1 nightly testing
=> Add semsrhel7gpu01 node

src/sparse/KokkosSparse_sptrsv_supernode.hpp
This PR tries to fix the out-of-bound errors for [issue #1016](https://github.com/kokkos/kokkos-kernels/issues/1016).
=> Supernodal SpTrsv: fix out-of-bound error

src/sparse/impl/KokkosSparse_gauss_seidel_impl.hpp
in Gauss-Seidel long rows. This bug originally appeared in Trilinos nightly testing here: https://github.com/trilinos/Trilinos/issues/9272
This PR just copies over changes from the Trilinos fix, which has more details about the issue: https://github.com/trilinos/Trilinos/pull/9278
=> Work around team size AUTO issue on kepler

cm_generate_makefile.bash, scripts/cm_test_all_sandia
Reverts kokkos/kokkos-kernels#1036
This will allow us to test the new fixes in Kokkos
=> Revert "test scripts: add option to disable kokkos desul atomics"

perf_test/blas/blas3/KokkosBlas3_common.hpp, perf_test/blas/blas3/KokkosBlas3_gemm_perf_test.hpp, perf_test/blas/blas3/KokkosBlas3_perf_test.cpp
- Refactor so that setup is not timed during armpl experiment
- Add ninter CLI option for armpl
- Remove incorrect invocation of deinterleave interface (bug)
=> perf_test/blas/blas3: Fixes for armpl dgemm

example/gmres/test_real_A.cpp
=> gmres: fix -Werror=ignored-qualifiers

scripts/cm_test_all_sandia
=> Test script updates for V100

example/gmres/README.md, example/gmres/ex_real_A.cpp, example/gmres/gmres.hpp, example/gmres/test_cmplx_A.cpp, example/gmres/test_real_A.cpp
This commit updates the GMRES example with the following:
- Adds profiling regions for the solver and orthogonalization
- Updates README with performance times
- Combines input parameters to a single struct; This will help simplify syntax when more options are added for preconditioning.  
- Minor code improvements.
=> Updates to GMRES example.

src/common/KokkosKernels_ExecSpaceUtils.hpp
Fix compilation issues on ARM architectures
Cleanup indentation
=> KokkosKernels_ExecSpaceUtils: kk_is_a64fx_mem_space add brace

unit_test/batched/Test_Batched_TeamVectorSolveUTV.hpp, unit_test/batched/Test_Batched_TeamVectorSolveUTV2.hpp, unit_test/batched/Test_Batched_TeamVectorUTV.hpp
by adding missing team barriers.
=> Fix #1089 (failing batched UTV tests)

perf_test/sparse/KokkosSparse_spadd.cpp, perf_test/sparse/KokkosSparse_spmv_struct_tuning.cpp, src/impl/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp
Change to match kokkos/kokkos#4249
=> Rename CUDA_SAFE_CALL to KOKKOS_IMPL_CUDA_SAFE_CALL

perf_test/blas/blas3/KokkosBlas3_gemm_perf_test.hpp, perf_test/blas/blas3/KokkosBlas3_trmm_perf_test.hpp, perf_test/blas/blas3/KokkosBlas_trtri_perf_test.hpp, src/blas/impl/KokkosBlas3_trmm_impl.hpp, src/blas/impl/KokkosBlas3_trsm_impl.hpp, src/blas/impl/KokkosBlas_trtri_impl.hpp
matching changes to PR #1171
see issue #1170
=> using namespace should be scoped to prevent name clashes

src/sparse/impl/KokkosSparse_spmv_bsrmatrix_impl.hpp, unit_test/sparse/Test_Sparse_spmv.hpp
The nightly tests are still reporting some issues.
This PR should take care of some of them!
=> Fixing a couple of small issue with tensor core spmv

example/wiki/graph/KokkosGraph_wiki_coarsening.cpp, example/wiki/graph/KokkosGraph_wiki_mis2.cpp, perf_test/graph/KokkosGraph_mis_d2.cpp, src/common/KokkosKernels_SimpleUtils.hpp, src/graph/KokkosGraph_MIS2.hpp, src/graph/impl/KokkosGraph_Distance2MIS_impl.hpp, src/sparse/impl/KokkosSparse_cluster_gauss_seidel_impl.hpp, unit_test/graph/Test_Graph_mis2.hpp
Bringing in newest versions from work on the IPDPS paper.
- Use better xorshift* hash function
- New coarsening algo
- Use new coarsening in cluster GS
=> Update MIS-2 and aggregation

src/batched/sparse/KokkosBatched_CG.hpp, src/batched/sparse/KokkosBatched_GMRES.hpp, src/batched/sparse/impl/KokkosBatched_CG_TeamVector_Impl.hpp, src/batched/sparse/impl/KokkosBatched_CG_Team_Impl.hpp, src/batched/sparse/impl/KokkosBatched_GMRES_TeamVector_Impl.hpp, src/batched/sparse/impl/KokkosBatched_GMRES_Team_Impl.hpp, unit_test/batched/sparse/Test_Batched_TeamCG.hpp, unit_test/batched/sparse/Test_Batched_TeamGMRES.hpp, unit_test/batched/sparse/Test_Batched_TeamVectorCG.hpp, unit_test/batched/sparse/Test_Batched_TeamVectorGMRES.hpp
This PR fixes the issue #1212 .
=> Fix issue #1212

.github/workflows/format.yml, .github/workflows/osx.yml, perf_test/sparse/KokkosSparse_gs.cpp, unit_test/sparse/Test_Sparse_gauss_seidel.hpp, unit_test/sparse/Test_Sparse_spadd.hpp, unit_test/sparse/Test_Sparse_spmv.hpp
Enable coverage of:
- OSX
- Deprecated code warnings
- Enabling both LayoutLeft and LayoutRight
- Float scalar type
=> .github/workflows: Add osx CI

scripts/cm_test_all_sandia
These can be enabled once https://github.com/kokkos/kokkos-kernels/pull/1256 merges.
=> scripts/cm_test_all_sandia: Add A64FX ci checks

src/KokkosKernels_Half.hpp, src/Kokkos_ArithTraits.hpp, test_common/KokkosKernels_TestUtils.hpp, unit_test/batched/dense/Test_Batched_BatchedGemm.hpp, unit_test/batched/dense/Test_Batched_BatchedGemm_Real.hpp, unit_test/batched/dense/Test_Batched_SerialGemm.hpp, unit_test/batched/dense/Test_Batched_SerialGemm_Real.hpp, unit_test/batched/dense/Test_Batched_TeamGemm.hpp, unit_test/batched/dense/Test_Batched_TeamGemm_Real.hpp, unit_test/batched/dense/Test_Batched_TeamVectorGemm.hpp, unit_test/batched/dense/Test_Batched_TeamVectorGemm_Real.hpp
Related to #1250.
Depends on https://github.com/kokkos/kokkos/pull/4653.
=> unit_test/batched: Add Batched GEMM bhalf tests

src/sparse/impl/KokkosSparse_spmv_blockcrsmatrix_impl.hpp, src/sparse/impl/KokkosSparse_spmv_bsrmatrix_impl.hpp
Resolves error: comparison of integers of different signs
=> Fix -Werror in clang+cuda builds

docs/Doxyfile.in, docs/index.rst, src/batched/KokkosBatched_Util.hpp, src/batched/dense/KokkosBatched_Gemm_Decl.hpp
docs:
- Doxyfile.in: Updated to generate docs for all members
- index.rst: Remove Kokkos namespace members
src/batched/dense:
- Update BatchedGemm docs to link to BatchLayout struct
- Correct doxygen-style for structs / classes
=> Small documentation updates

unit_test/sparse/Test_Sparse_spmv.hpp
Tensor core kernels use reduced precision even when the rest of Kokkos implements half as float
=> Fix issue 1314

perf_test/blas/blas3/KokkosBlas3_gemm_perf_test.hpp, src/batched/dense/impl/KokkosBatched_SVD_Serial_Internal.hpp, unit_test/batched/dense/Test_Batched_SerialSVD.hpp
=> Fix nightly builds following promotion of the math functions in Kokkos

perf_test/batched/KokkosBatched_Test_BlockJacobi_Tutorial.cpp, perf_test/batched/KokkosBatched_Test_BlockTridiagDirect.cpp, perf_test/batched/KokkosBatched_Test_BlockTridiagJacobi.cpp
=> Cleanup batched block tridiag perf test

perf_test/batched/CMakeLists.txt
=> perf_test/batched: Temporarily disable tests

perf_test/sparse/KokkosSparse_spiluk.cpp
=> KokkosSparse_spiluk.cpp perf test: add int-int guards to cusparse codes

src/sparse/KokkosSparse_getDiagCopy.hpp
=> Fix check that view has const value type

perf_test/sparse/KokkosSparse_spmv_struct_tuning.cpp, src/impl/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp
Fixes a few deprecated code warnings.
=> Fixes code deprecation warnings.

src/sparse/impl/KokkosSparse_getDiagCopyWithOffsets_impl.hpp
More fixes related to kokkos/kokkos-kernels#1367
=> Update View value_type and const_value_type for compile time checks

src/common/KokkosKernels_BlockUtils.hpp, src/common/KokkosKernels_Sorting.hpp, unit_test/sparse/Test_Sparse_bspgemm.hpp
According to comments in issue #1395 the block spgemm implementation is clean-up and should now build without error in our nightlies.
The runtime error will be investigated subsequently.
=> Bspgemm fixes

src/impl/generated_specializations_hpp/KokkosGraph_color_d1_eti_spec_avail.hpp.in, src/impl/generated_specializations_hpp/KokkosGraph_color_d1_eti_spec_decl.hpp.in
=> Fix colliding include guards (copy-paste mistake)

docs/conf.py, docs/developer/apidocs.rst, docs/developer/apidocs/batched_dense.rst, docs/developer/apidocs/batched_sparse.rst, docs/developer/apidocs/blas1.rst, docs/developer/apidocs/blas2.rst, docs/developer/apidocs/blas3.rst, docs/developer/apidocs/sparse.rst, docs/developer/build_doc.rst, docs/developer/contrib.rst, docs/developer/index.rst, docs/developer/style.rst, docs/index.rst
=> Restructure docs

src/sparse/KokkosSparse_Utils_cusparse.hpp
Attempt to fix https://github.com/kokkos/kokkos-kernels/issues/1452
=> Removes a duplicate cuda_data_type_from when KOKKOS_HALF_T_IS_FLOAT

src/blas/KokkosBlas1_axpby.hpp, src/blas/KokkosBlas1_nrm2.hpp, src/blas/impl/KokkosBlas_serial_axpy.hpp, src/blas/impl/KokkosBlas_serial_nrm2.hpp, unit_test/blas/Test_Blas.hpp, unit_test/blas/Test_Blas_serial_axpy.hpp, unit_test/blas/Test_Blas_serial_nrm2.hpp
Adding blas device calls to support upcoming Newton solver
=> Blas serial axpy and nrm2

src/sparse/KokkosSparse_Utils.hpp, unit_test/sparse/Test_Sparse_Transpose.hpp
Adding naive implementation of the transpose of a BsrMatrix after computing the transpose of its graph.
=> Sparse: bsr transpose algorithm

src/blas/impl/KokkosBlas_Newton_impl.hpp, unit_test/blas/Test_Blas.hpp, unit_test/blas/Test_Blas_Newton.hpp
This is currently experimental and does not have a polished public interface so it is kept in experimental.
Will also add a test that solves a linear system which should converge in a single iteration.
I am considering creating a new directory called solvers, that would contain various dense solvers?
=> Newton solver: serial on device implementation of Newton's method

scripts/cm_test_all_sandia
The system currently only has cuda/11.1 module available through the sems-archive pack
=> cm_test_all_sandia: update modules for sogpu

.github/workflows/format.yml, .github/workflows/osx.yml
See https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs.
=> .github: Set minimum permissions

sparse/impl/KokkosSparse_par_ilut_numeric_impl.hpp
This works around a possible compiler bug.
``cudaErrorInvalidDeviceFunction`` was raised at runtime even though these two lambdas were marked ``KOKKOS_LAMBDA`` and ``-expt-extended-lambda`` was being passed to nvcc. Strange because the code looks fine, and there are many other lambdas in the ParILUT implementation.
This issue happened with Cuda 11.6, GCC 9.1.0, Pascal61.
I tried making a smaller reproducer for this issue but couldn't replicate it.
(@jgfouca This isn't anything you did wrong in your PR, the existing code looks fine)
=> ParILUT: convert two lambdas to functors

sparse/tpls/KokkosSparse_spmv_mv_tpl_spec_decl.hpp
When the cusparse compute type selected is real (instead of complex) `conjugate_transpose` is not a valid matrix operation, instead `transpose` needs to be selected to avoid an error.
=> SPMM: fixing cuSPARSE issue with incompatible compute type and op

blas/tpls/KokkosBlas1_rotmg_tpl_spec_avail.hpp, blas/unit_test/Test_Blas1_rotmg.hpp
For the time being the TPL does not seem to return correct results which is a bit strange.
Turning it off for the time being and will talk with the AMD folks about it...
There might be some tests in rocblas that I can try to build as well for more testing?
=> ROTMG: rocblas TPL turned off

sparse/unit_test/Test_Sparse_spmv_bsr.hpp
=> sparse/unit_test: Use native spmv impl in bsr unit tests

blas/tpls/KokkosBlas1_swap_tpl_spec_decl.hpp
Fixing a pretty bad typo in the swap TPL layer...
This PR should fix the issue reported in #1623
=> SWAP: fixing obvious mistake in TPL layer : (

scripts/cm_test_all_sandia
update default cxx standard to 17
update sems-archive-env to sems-env on sogpu, sems machines 
add new compilers, drop unsupported compilers on various machines 
delete unused machine kokkos-dev
=> cm_test_all_sandia: various updates

common/src/KokkosKernels_Utils.hpp
In ``array_sum_reduce<scalar, N>``, if all of these are true:
- scalar is half_t
- half_t is actually a 2-byte type (and not just an alias for float)
- N=3, N=5 or N=7
then pad out the struct's storage array to 4 elements. The last element will be unused, but this bypasses the issues with parallel_reduce: See https://github.com/kokkos/kokkos/issues/5860 .
=> Temporary workaround for Kokkos #5860

scripts/docker/Dockerfile.sycl
Fixes https://cloud.cees.ornl.gov/jenkins-ci/blue/organizations/jenkins/KokkosKernels/detail/KokkosKernels/778/pipeline by updating the `Dockerfile` for `SYCL` to the one used in `Kokkos`.
=> Update SYCL docker file to include oneDPL

sparse/unit_test/Test_Sparse_spmv.hpp
Needed for merge-based SpMV PR https://github.com/kokkos/kokkos-kernels/pull/1501
The merge-based SpMV tests will be added to the `test_spmv_algorithms` function
=> add explicit tests of opt-in algorithms

sparse/impl/KokkosSparse_par_ilut_numeric_impl.hpp
This fixes memory errors on Cuda.
Fixes #1656
=> ParIlut: create and destroy spgemm handle for each usage

sparse/src/KokkosSparse_spgemm_symbolic.hpp
This was intended to be a temporary patch, but it will need to stay until 4.1. This means it has to be included in 4.0.1.
See https://github.com/trilinos/Trilinos/pull/11663, which fixed https://github.com/trilinos/Trilinos/issues/11655
=> Patch Trilinos #11663

.github/workflows/docs.yml, .github/workflows/format.yml, .github/workflows/osx.yml
=> .github: Update to actions/checkout@v3

docs/developer/apidocs.rst, docs/developer/apidocs/batched_dense_host.rst
=> docs: Include BatchedGemm

blas/impl/KokkosBlas3_gemm_dotbased_impl.hpp, blas/impl/KokkosBlas3_gemm_impl.hpp, blas/impl/KokkosBlas3_gemm_spec.hpp, blas/impl/KokkosBlas3_trmm_spec.hpp, blas/impl/KokkosBlas3_trsm_spec.hpp, blas/src/KokkosBlas2_gemv.hpp, blas/src/KokkosBlas3_gemm.hpp, blas/src/KokkosBlas3_trmm.hpp, blas/src/KokkosBlas3_trsm.hpp, blas/tpls/KokkosBlas3_gemm_tpl_spec_avail.hpp, blas/tpls/KokkosBlas3_gemm_tpl_spec_decl.hpp, blas/tpls/KokkosBlas3_trmm_tpl_spec_avail.hpp, blas/tpls/KokkosBlas3_trmm_tpl_spec_decl.hpp, blas/tpls/KokkosBlas3_trsm_tpl_spec_avail.hpp, blas/tpls/KokkosBlas3_trsm_tpl_spec_decl.hpp, docs/developer/apidocs/blas2.rst, docs/developer/apidocs/blas3.rst, sparse/tpls/KokkosSparse_spgemm_numeric_tpl_spec_decl.hpp
Fixing some types for gemv and gemm and also adding interface for trmm and trmv, that should be it for BLAS!
=> Blas2 and 3 on stream

docs/developer/apidocs/blas2.rst
Really not much to say beyond the fact that we forgot to do it while adding the ger function...
=> Ger: adding documentation stubs in apidocs

blas/src/KokkosBlas3_trmm.hpp, blas/src/KokkosBlas_trtri.hpp, docs/CMakeLists.txt, docs/Doxyfile.in, docs/conf.py, docs/developer/apidocs/blas1.rst, docs/developer/apidocs/blas3.rst, docs/developer/apidocs/sparse.rst, docs/developer/profiling.rst, docs/developer/testing.rst.parked, docs/index.rst, sparse/src/KokkosKernels_Handle.hpp, sparse/src/KokkosSparse_BsrMatrix.hpp, sparse/src/KokkosSparse_coo2crs.hpp, sparse/src/KokkosSparse_spmv.hpp
After resolving, #1851, I decided to enable warnings as errors in our Sphinx builds. After this merges, sphinx warnings will be caught via github-DOCS or when building the docs locally via `make Sphinx`.
=> Enable sphinx werror

scripts/cm_test_all_sandia
- remove unsupported compilers
- add new compilers
=> cm_test_all_sandia: updates for blake

batched/dense/impl/KokkosBatched_Gemv_Team_Impl.hpp
=> batched/dense: Add gesv DynRankView runtime checks

docs/_static/table_theme.css, docs/conf.py, docs/developer/index.rst, docs/developer/testing_table.rst
- Add testing table for our nightly and continuous integration test cases
- Add CSS to modify the RTD theme format for better rendering of the table. Note this formatting applies to all the developer docs pages and makes the pages fit the client's browser window.
=> docs: Add testing table

sparse/impl/KokkosSparse_mdf_impl.hpp, sparse/src/KokkosSparse_mdf.hpp
for completeness, convert final functor to hierarchical parallelism as well
=> MDF: convert remaining count functor to hierarchical parallelism

perf_test/sparse/KokkosSparse_par_ilut.cpp
=> ParILUT bench: fix unused IS_GPU warning

ode/impl/KokkosODE_RungeKutta_impl.hpp, ode/unit_test/Test_ODE_RK.hpp
A few variables were not updated in a logical way
leading to very bad and illogical performance of
the adaptive algorithms. This should now be fixed. Future work can work into reporting the number of
time steps actually taken and also some discussion around the inner sub-stepping should happen.
A new unit-test is added to test adaptivity although a criteria to measure the efficacy of the adaptive algorithm needs to be added.
=> ODE: adding adaptivity test for RK methods

sparse/unit_test/Test_Sparse_MergeMatrix.hpp
Actual fix for https://github.com/kokkos/kokkos-kernels/issues/1905 🤦
=> add missing headers, `std::vector` -> `std::vector<...>`

common/impl/KokkosKernels_ViewUtils.hpp, sparse/impl/KokkosSparse_spmv_bsrmatrix_impl_v42.hpp
Editing a bit the implementation of some utilities and bsr implementation to make it build correctly against 4.0 and 4.1 as well as develop until we release 4.2.
=> Bsr compatibility

sparse/src/KokkosSparse_BsrMatrix.hpp
Fixes https://github.com/kokkos/kokkos-kernels/issues/1915
=> remove triplicate sanity checks in BsrMatrix

sparse/unit_test/Test_Sparse_spmv_bsr.hpp
Speed up BSR spmv, spm_mv unit tests. The test problems and cases are not changed.
- Rearrange loops over cases so that matrices can be reused
- Reuse randomized BSR matrices, BSR matrices converted to CSR, and BSR transposes
This should help quite a bit with PR tests timing out, especially the Serial+Debug OSX.
On my machine, for this configuration, the total time for ``./KokkosKernels_blocksparse_serial`` went from 316s -> 149s.
```
../kokkos-kernels/cm_generate_makefile.bash \
--with-devices=Serial \
--debug --kokkos-debug \
--arch=SKX \
--compiler=g++ \
--with-scalars='double,complex_double' \
--with-ordinals=int \
--with-offsets=int,size_t \
--with-layouts=LayoutLeft
```
update: I'm not going to do more right now, but for further speedups there's a couple things we could do:
- more …
=> Speed up BSR spmv tests

sparse/impl/KokkosSparse_spmv_bsrmatrix_spec.hpp
=> Ensure CUDA is enabled

sparse/impl/KokkosSparse_spmv_struct_impl.hpp
fixes https://github.com/kokkos/kokkos-kernels/issues/1956
=> SPMV_Struct_Functor: initialize numExterior to 0

batched/dense/src/KokkosBatched_HostLevel_Gemm.hpp
Leaving `AT: WIP` applied so that only the DOCS CI check runs.
=> docs: Improve formatting

common/src/KokkosKernels_SimpleUtils.hpp, common/src/KokkosKernels_Utils.hpp, common/unit_test/Test_Common_Sorting.hpp, sparse/impl/KokkosSparse_par_ilut_numeric_impl.hpp, sparse/impl/KokkosSparse_spadd_symbolic_impl.hpp, sparse/impl/KokkosSparse_spgemm_impl_symbolic.hpp, sparse/impl/KokkosSparse_spgemm_impl_triangle.hpp, sparse/impl/KokkosSparse_twostage_gauss_seidel_impl.hpp, sparse/src/KokkosSparse_SortCrs.hpp, sparse/src/KokkosSparse_Utils.hpp
Fix for https://github.com/kokkos/kokkos-kernels/issues/1671
=> Parallel prefix sum can infer view type

sparse/impl/KokkosSparse_sptrsv_solve_impl.hpp
This PR is to add a fix for #1992.
=> Only deep_copy from device to host if supernodal sptrsv algorithms are used

blas/impl/KokkosBlas2_gemv_spec.hpp, blas/src/KokkosBlas2_gemv.hpp, blas/tpls/KokkosBlas2_gemv_tpl_spec_avail.hpp, blas/tpls/KokkosBlas2_gemv_tpl_spec_decl.hpp, blas/unit_test/Test_Blas2_gemv.hpp, docs/developer/apidocs/blas2.rst
=> Test and fix gemv stream interface

sparse/tpls/KokkosSparse_spmv_mv_tpl_spec_decl.hpp
Fix for compilation errors with cuda/11.2 and tpls enabled
Pattern match from #1991
=> Another upstream iostream removal fix

CMakeLists.txt
Update corresponding to kokkos/kokkos#6520
=> CMakeLists.txt: Update Kokkos version to 4.2.99 for version check

common/src/Kokkos_ArithTraits.hpp
=> bhalf_t fix for isnan function

CHANGELOG.md
Part of Kokkos C++ Performance Portability Programming EcoSystem 4.2
=> Adding Changelog for Release 4.2.0

sparse/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp
Fix for https://github.com/kokkos/kokkos-kernels/issues/2068
=> Async matrix release for MKL >= 2023.2 in SpMV

sparse/impl/KokkosSparse_trsv_impl.hpp, sparse/impl/KokkosSparse_trsv_spec.hpp, sparse/src/KokkosSparse_trsv.hpp, sparse/unit_test/Test_Sparse_gmres.hpp, sparse/unit_test/Test_Sparse_trsv.hpp, test_common/KokkosKernels_TestUtils.hpp
Best viewed with whitespace changes hidden.
=> Add support for BSR matrices to some trsv routines

sparse/impl/KokkosSparse_trsv_impl.hpp
=> Fix build error in trsv on gcc8

sparse/src/KokkosSparse_spmv_handle.hpp
It is part of the public interface after all.
This is a follow on to #2126
=> Use execution space operator==

blas/tpls/KokkosBlas_Cuda_tpl.cpp, blas/tpls/KokkosBlas_Magma_tpl.hpp, blas/tpls/KokkosBlas_magma.hpp, blas/tpls/KokkosBlas_tpl_spec.hpp, lapack/tpls/KokkosLapack_Magma_tpl.hpp, lapack/tpls/KokkosLapack_gesv_tpl_spec_decl.hpp
=> Resolves multiple definition of Magma and Cuda singletons

.github/dependabot.yml, .github/workflows/codeql.yml, .github/workflows/dependency-review.yml, .github/workflows/scorecards.yml
@csiefer2 let me know if you have comments on this as well?
Pretty much taking the new files from PR #2191 and re-creating it in a clean PR on top of develop with small changes relevant to our repository.
=> GH-Actions: adding security actions and scorecard

.github/workflows/docs.yml
- avoid version range check issues for release tests
=> docs.yml: change kokkos version to latest release

.github/SECURITY.md
We state were patches will be made and how to report security vulnerabilities to the project.
=> Kokkos Kernels: initial security policy

.github/workflows/bdw.yml, .github/workflows/docs.yml, .github/workflows/format.yml, .github/workflows/h100.yml, .github/workflows/mi210.yml, .github/workflows/osx.yml, .github/workflows/spr.yml, scripts/docker/Dockerfile.hip, scripts/docker/Dockerfile.sycl
This would improve our security scorecard thing see here: https://securityscorecards.dev/viewer/?uri=github.com/kokkos/kokkos-kernels
=> Kokkos Kernels: adding SHA for github actions

.github/workflows/osx.yml, scripts/docker/Dockerfile.hip, scripts/docker/Dockerfile.sycl
=> More dependencies fix

scripts/docker/Dockerfile.hip, scripts/docker/Dockerfile.sycl
=> Fix Docker files

sparse/tpls/KokkosSparse_spgemm_symbolic_tpl_spec_decl.hpp
This may be an undocumented change in the `cusparseCreateCsr` expectations.
Fixes https://github.com/kokkos/kokkos-kernels/issues/2212
=> cusparse spgemm: provide non-null row-ptr

sparse/src/KokkosSparse_spmv_deprecated.hpp
native -> SPMV_NATIVE
native-merge -> SPMV_NATIVE_MERGE_PATH
merge -> SPMV_MERGE_PATH
tpl -> SPMV_FAST_SETUP
=> In deprecated spmv, fix Controls algorithm mapping

common/unit_test/Test_Common_AlignPtrTo.hpp
=> Help gcc/8.3 with ctad issue

blas/src/KokkosBlas2_gemv.hpp, blas/tpls/KokkosBlas2_gemv_tpl_spec_decl.hpp
More sycl fixes, with these we should have everything passing on one of our SYCL + MKL build except for coo2csr.
=> Sycl gemv beta

common/src/KokkosKernels_Utils.hpp
Follow-up to https://github.com/kokkos/kokkos-kernels/pull/2262. It should be sufficient to only compute the correct offset and then increment the pointer accordingly instead of casting through `uintptr_t`. This gives the same instructions for `g++`, and `clang++` at least, see https://godbolt.org/z/or43jcr18. This is also more similar to what we are doing in https://github.com/kokkos/kokkos/blob/73ac2492d4134592ed55d92aa058c8e1107a9404/core/src/Kokkos_ScratchSpace.hpp#L103-L136.
@cwpearson Can you confirm that this works for you?
=> Unify alignPtrTo implementation

.github/workflows/release.yml
Porting the changes of https://github.com/kokkos/kokkos/pull/7231 over
=> Improve GH action to produce release artifacts

perf_test/blas/blas1/KokkosBlas_dot_mv_perf_test_benchmark.cpp, perf_test/blas/blas1/KokkosBlas_dot_perf_test.cpp, perf_test/blas/blas1/KokkosBlas_dot_perf_test_benchmark.cpp
=> Fix minor typing error.

sparse/src/KokkosSparse_coo2crs.hpp
Fix for https://github.com/kokkos/kokkos-kernels/issues/2267
=> coo2csr: add parens to function calls

sparse/impl/KokkosSparse_bspgemm_impl_kkmem.hpp
`volatile` doesn't seem necessary here 🤞 
Fix for https://github.com/kokkos/kokkos-kernels/issues/1545
=> remove unneeded volatile qualifier for Kokkos::Single

.github/workflows/bdw.yml, .github/workflows/h100.yml, .github/workflows/mi210.yml, .github/workflows/spr.yml
This should make the OSS scorecard a little happier?
=> workflow: adding permissions in workflow files

sparse/impl/KokkosSparse_sort_crs_impl.hpp
Apply change consistent with PR #2354
=> Fix compilation error, kk_is_gpu_exec_space->is_gpu_exec_space_v

.github/workflows/at2.yml, .github/workflows/volta70.yml
=> Workflow volta70

blas/tpls/KokkosBlas_Host_tpl.cpp
Fix for https://github.com/kokkos/kokkos-kernels/issues/2005
=> Blas1 asum: workaround for openblas error with short vectors

graph/impl/KokkosGraph_Distance2MIS_impl.hpp, graph/impl/KokkosGraph_ExplicitCoarsening_impl.hpp, sparse/impl/KokkosSparse_bspgemm_impl_kkmem.hpp, sparse/impl/KokkosSparse_partitioning_impl.hpp, sparse/impl/KokkosSparse_spgemm_impl_kkmem.hpp, sparse/impl/KokkosSparse_spgemm_jacobi_sparseacc_impl.hpp
In anticipation of atomic_increment() and atomic_decrement() getting deprecated
If you do not like this, it is not too late to object before https://github.com/kokkos/kokkos/pull/7458 gets merged
=> Replace atomic_{inc, dec}[rement]

batched/dense/src/KokkosBatched_Laswp.hpp, batched/dense/unit_test/Test_Batched_SerialLaswp.hpp
This PR aims at fixing some issues related to #2395
=> Fix batched serial laswp

.github/workflows/at2.yml, .github/workflows/linux.yml, .github/workflows/osx.yml
Updating our workflows to test develop against 4.5.00.
=> workflow: updating kokkos version for CI testing

sparse/unit_test/Test_Sparse_TestUtils_RandCsMat.hpp
Follow-on to https://github.com/kokkos/kokkos-kernels/pull/2416#issuecomment-2465083154
Replaces https://github.com/kokkos/kokkos-kernels/pull/2433
=> Test_Sparse_TestUtils_RandCsMat.hpp: tighten up types

graph/src/KokkosGraph_CoarsenConstruct.hpp, perf_test/sparse/KokkosSparse_run_spgemm_jacobi.hpp, perf_test/sparse/KokkosSparse_spgemm.cpp, sparse/impl/KokkosSparse_bspgemm_numeric_spec.hpp, sparse/impl/KokkosSparse_par_ilut_numeric_impl.hpp, sparse/impl/KokkosSparse_spgemm_jacobi_spec.hpp, sparse/impl/KokkosSparse_spgemm_noreuse_spec.hpp, sparse/src/KokkosSparse_spgemm.hpp, sparse/src/KokkosSparse_spgemm_numeric.hpp, sparse/src/KokkosSparse_spgemm_symbolic.hpp, sparse/unit_test/Test_Sparse_spgemm.hpp, sparse/unit_test/Test_Sparse_spgemm_jacobi.hpp
These have been around long enough and the API are stable, we should promote out of experimental
=> Sparse - spgemm: moving symbolic and numeric phases out of the experimental namespace

batched/KokkosBatched_Util.hpp, batched/dense/impl/KokkosBatched_Eigendecomposition_Serial_Internal.hpp
In favor of KOKKOSBATCHED_IMPL_ENABLE_LAPACKE
https://github.com/kokkos/kokkos-kernels/issues/2364
=> deprecate __KOKKOSBATCHED_ENABLE_LAPACKE__

test_common/KokkosKernels_TestUtils.hpp
=> KokkosKernels_TestUtils.hpp: rename reserved identifiers

.github/workflows/at2.yml, .github/workflows/mi210_rocm621.yml
@lucbv do you know how to make these optional for now?
=> PR tests on ROCm 6.2.1

common/src/KokkosKernels_HashmapAccumulator.hpp
=> KokkosKernels_HashmapAccumulator.hpp: rename reserved ids

sparse/src/KokkosSparse_coo2crs.hpp
=> remove _-prefixed include guard

docs/api_template.rst
This should make it easier for anyone to start a new documentation file for new or undocumented functions.
=> docs: adding API documentation template

docs/source/index.rst, docs/source/quick_start.rst
Update cover page to reflect this is the Kokkos **Kernels** documentation and update URL to the Core "Getting Started" page
=> [Documentation] Minor fixes

batched/dense/impl/KokkosBatched_HostLevel_Gemm_DblBuf_Impl.hpp, batched/dense/impl/KokkosBatched_HostLevel_Gemm_Serial_Impl.hpp
=> Rename some reserved identifiers

lapack/impl/KokkosLapack_svd_spec.hpp, lapack/tpls/KokkosLapack_svd_tpl_spec_decl.hpp, lapack/unit_test/Test_Lapack_svd.hpp, ode/unit_test/Test_ODE_RK.hpp
Modifying the ETI specialization to make it consistent with a LayoutLeft vector view. Fixing some issue in RK unit-test.
=> Lapack - SVD: fixing build issue, will look at test tomorrow

.github/workflows/h100_lychee.yml
@lucbv @ndellingwood could you please add the magic label for CI and restart the tests?
=> Add CUDA 12.6.2 + compute sanitizer PR test

example/batched_solve/CMakeLists.txt, example/batched_solve/serial_pttrs.cpp
This PR aims at adding a serial `pttrf/pttrs` example.
I would like to embed this in the batched documentation.
=> Add pttrf/pttrs example

batched/dense/impl/KokkosBatched_Trmm_Serial_Internal.hpp, blas/impl/KokkosBlas3_trmm_impl.hpp, common/src/KokkosKernels_BlockHashmapAccumulator.hpp, graph/impl/KokkosGraph_Distance2MIS_impl.hpp, lapack/impl/KokkosLapack_trtri_impl.hpp, sparse/impl/KokkosSparse_bspgemm_impl.hpp, sparse/impl/KokkosSparse_bspgemm_impl_speed.hpp, sparse/impl/KokkosSparse_cluster_gauss_seidel_impl.hpp, sparse/impl/KokkosSparse_gauss_seidel_impl.hpp, sparse/impl/KokkosSparse_spgemm_impl.hpp, sparse/impl/KokkosSparse_spgemm_impl_speed.hpp, sparse/impl/KokkosSparse_spmv_impl_merge.hpp, sparse/src/KokkosSparse_CrsMatrix.hpp
Haven't checked the tests and examples yet.
Each file can be taken as an atomic change, so each file can be reviewed/considered separately.
=> Rename remaining reserved identifiers in library

batched/dense/unit_test/Test_Batched_BatchedGemm.hpp, batched/dense/unit_test/Test_Batched_SerialGemm.hpp, batched/dense/unit_test/Test_Batched_TeamGemm.hpp, batched/dense/unit_test/Test_Batched_TeamVectorGemm.hpp, perf_test/blas/blas3/KokkosBlas3_gemm_perf_test.hpp, test_common/KokkosKernels_TestVanilla.hpp
=> Rename reserved IDs in KokkosKernels_TestVanilla.hpp

example/batched_solve/CMakeLists.txt, example/batched_solve/serial_getrs.cpp
This PR aims at adding a serial `getrf/getrs` example.
I would like to embed this in the batched documentation. 
See also #2655, #2659, and #2664.
=> Add getrf-getrs example

batched/sparse/impl/KokkosBatched_CG_TeamVector_Impl.hpp
=> Rename reserved identifiers in `KokkosBatched_CG_TeamVector_Impl.hpp`

blas/impl/KokkosBlas1_iamax_impl.hpp, blas/unit_test/Test_Blas1_iamax.hpp, sparse/impl/KokkosSparse_spgemm_impl_compression.hpp, sparse/impl/KokkosSparse_spgemm_impl_symbolic.hpp
@masterleinad please have a look at well
Removing some volatile attributes in spgemm and fixing issue with reduction update variable initialization which would cause access out of bound and segfaults.
=> SYCL: fixing issues revealed with icpx 2025

batched/sparse/impl/KokkosBatched_GMRES_Serial_Impl.hpp, batched/sparse/impl/KokkosBatched_GMRES_TeamVector_Impl.hpp, batched/sparse/impl/KokkosBatched_GMRES_Team_Impl.hpp, batched/sparse/src/KokkosBatched_Krylov_Handle.hpp, batched/sparse/src/KokkosBatched_Krylov_Solvers.hpp, perf_test/blas/blas1/KokkosBlas_perf_test.cpp
partial fix for https://github.com/kokkos/kokkos-kernels/issues/2364
=> Batched: rename reserved identifiers

perf_test/batched/sparse/SPMV/KokkosBatched_Test_SPMV.cpp, perf_test/blas/blas3/KokkosBlas3_gemm_perf_test.hpp, perf_test/blas/blas3/KokkosBlas_trtri_perf_test.hpp, sparse/src/KokkosSparse_LUPrec.hpp, sparse/src/KokkosSparse_MatrixPrec.hpp, sparse/src/KokkosSparse_ccs2crs.hpp, sparse/src/KokkosSparse_crs2ccs.hpp
=> variety of reserved indentifier cleanups
