kokkos/kokkos-kernels

src/impl/Kokkos_Sparse_impl_spmv_def.hpp
The headers in kokkos-kernels/src/impl/ get
installed to the include/ directory same
as the rest, so they should not include
each other as "impl/foo.hpp" because that
will not work in the installed location.
This fixes a compile error when building
Albany against current Trilinos.
@crtrott @mhoemmen 
Its pretty urgent that this gets through to Trilinos,
I'm pretty sure all compiles against installed
kokkos-kernels will fail until then.
The Albany CDash failure that spotted this is here:
http://my.cdash.org/viewBuildError.php?buildid=1146035
=> fix include in installed header

src/Kokkos_ArithTraits.hpp
using this instead of strtod() and friends
dramatically speeds up the
Kokkos::ArithTraits<T>::nan()
function.
The performance test
Trilinos/packages/minitensor/test/perf_test_01.cc
went from 5.5 seconds to 0.6 seconds.
see #35
=> use numeric_limits<T>::quiet_NaN

src/common/KokkosKernels_IOUtils.hpp, unit_test/sparse/Test_Sparse_spmv.hpp, unit_test/sparse/Test_Sparse_trsv.hpp
Some sparse tests were failing with UVM without launchblocking. This should fix them.
=> fixes to sparse test that fails with uvm without lanch blocking

src/batched/KokkosBatched_Util.hpp, src/batched/KokkosBatched_Vector.hpp, src/batched/KokkosBatched_Vector_AVX256D.hpp, src/batched/KokkosBatched_Vector_AVX512D.hpp, src/batched/KokkosBatched_Vector_SIMD.hpp, unit_test/Makefile, unit_test/batched/Test_Batched_VectorArithmatic.hpp, unit_test/cuda/Test_Cuda_Batched_SerialGemm.cpp, unit_test/cuda/Test_Cuda_Batched_SerialGemv.cpp, unit_test/cuda/Test_Cuda_Batched_SerialLU.cpp, unit_test/cuda/Test_Cuda_Batched_SerialMatUtil.cpp, unit_test/cuda/Test_Cuda_Batched_SerialTrsm.cpp, unit_test/cuda/Test_Cuda_Batched_SerialTrsv.cpp, unit_test/cuda/Test_Cuda_Batched_TeamGemm.cpp, unit_test/cuda/Test_Cuda_Batched_TeamGemv.cpp, unit_test/cuda/Test_Cuda_Batched_TeamLU.cpp, unit_test/cuda/Test_Cuda_Batched_TeamMatUtil.cpp, unit_test/cuda/Test_Cuda_Batched_TeamTrsm.cpp, unit_test/cuda/Test_Cuda_Batched_TeamTrsv.cpp
1. batched operation correctness test on cuda.
2. it has a trouble (very very weird) that incurs a segmentation error.
This is due to not being able to convert among ``enum : int ``, ``constexpr int`` and ``static const int`` when ``nvcc_wrapper`` is used. When g++ is directly used, the error does not appear. However, with ``nvcc_wrapper``, mixing the above types is dangerous. 
3. solution is to use `` static const int`` consistently.
=> Add cuda test and fix weird segmentation error coming from enum conversion.

src/sparse/impl/KokkosSparse_spgemm_mkl2phase_impl.hpp, src/sparse/impl/KokkosSparse_spgemm_mkl_impl.hpp
I needed to compile with gcc and enable MKL. I could not get the warnings with intel compiler.
I compiled it within trilinos, as I don't think we have a way of setting tpls from generate makefile -> #66
=> Fixes to MKL warning for issue #55

src/batched/KokkosBatched_Gemv_Team_Internal.hpp, src/batched/KokkosBatched_Trsv_Team_Internal.hpp, src/batched/KokkosBatched_Util.hpp
The error is revealed from TRSV, LOWER, NOTRANS, NONUNIT for complex(valuetype)/complex(scalartype). The other combinations are all passed. For snapshot without breaking unit tests, lower the default blksize ( 2-> 1) we use for CUDA.
=> Batched - for team impl, reduce blksize to 1.

perf_test/graph/KokkosGraph_color.cpp, perf_test/graph/KokkosGraph_triangle.cpp, perf_test/sparse/KokkosSparse_pcg.cpp, perf_test/sparse/KokkosSparse_spgemm.cpp, perf_test/sparse/spmv/KokkosKernels_SPMV.hpp, perf_test/sparse/spmv/Kokkos_SPMV.hpp, src/batched/KokkosBatched_Gemm_Team_Internal.hpp, src/batched/KokkosBatched_LU_Team_Internal.hpp, src/batched/KokkosBatched_Trsm_Team_Internal.hpp, src/batched/KokkosBatched_Util.hpp, src/batched/KokkosBatched_Vector_SIMD.hpp, src/common/KokkosKernels_ExecSpaceUtils.hpp, src/common/KokkosKernels_SparseUtils.hpp, src/common/KokkosKernels_Utils.hpp, src/graph/KokkosGraph_GraphColorHandle.hpp, src/sparse/KokkosSparse_CrsMatrix.hpp, src/sparse/KokkosSparse_gauss_seidel_handle.hpp, src/sparse/KokkosSparse_spgemm_handle.hpp, src/sparse/impl/KokkosSparse_gauss_seidel_impl.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_compression.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_kkmem.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_speed.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_symbolic.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_triangle.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_triangle_no_compression.hpp, src/sparse/impl/KokkosSparse_spmv_impl.hpp, src/stage/blas3/Kokkos_Blas3_impl.hpp, unit_test/batched/cuda/KokkosKernels_Test_ExecPolicy.cpp
=> Protecting lambda functions, in case cuda is enabled.

perf_test/common/KokkosKernels_TestParameters.hpp, perf_test/graph/KokkosGraph_color.cpp
Serial is now an option for all performance tests through parameters.
Fixing #93.
=>  Adding serial node to graph coloring test.

unit_test/batched/Test_Batched_VectorArithmatic.hpp
We do not provid float test for batch operation. With float test on, following tests are failed.
With floats, we have following failures.
[  PASSED  ] 378 tests.
[  FAILED  ] 14 tests, listed below:
[  FAILED  ] openmp.abs_float
[  FAILED  ] openmp.abs_mv_float
[  FAILED  ] openmp.nrm2_squared_float
[  FAILED  ] openmp.nrm2_squared_mv_float
[  FAILED  ] openmp.reciprocal_mv_float
[  FAILED  ] openmp.scal_mv_float
[  FAILED  ] openmp.sparse_trsv_mv_kokkos_complex_float_int_int_LayoutLeft_TestExecSpace
[  FAILED  ] openmp.sparse_trsv_mv_kokkos_complex_float_int64_t_int_LayoutLeft_TestExecSpace
[  FAILED  ] openmp.sparse_trsv_mv_kokkos_complex_float_int_size_t_LayoutLeft_TestExecSpace
[  FAILED  ] openmp.sparse_trsv_mv_kokkos_complex_float_int64_t_size_t_LayoutLeft_TestExecSpace
[  FAILED  ] …
=> Disable AVX float test (we do not have impl for that) -- #86

scripts/test_all_sandia
xl 14.1.0-BETA is no longer available on White for testings. Modified script to test xl 13.1.6-BETA instead.
=> Update modules avail for white in test_all_sandia script

src/batched/KokkosBatched_InnerTrsm_Serial_Impl.hpp
Original title: "Kokkos: Fix compilation with complex<float>
by adding some static casts to scalar constants"
Author:    Jonas Thies <jonas.thies@dlr.de>
Editor:    Mark Hoemmen <mhoemme@sandia.gov>
Editor's note: Both kokkos and kokkos-kernels have their own
repositories.  They are periodically snapshotted into the Trilinos
repository.  Jonas submitted his original patch to Trilinos.  In order
to turn this into pull requests for kokkos and kokkos-kernels, I had
to split the original patch into two patches, and edit paths in each.
I also changed the original title slightly.  Otherwise, I made no
other changes to the original patch.  Thanks Jonas! :-D
=> Fix compilation with complex<float> by adding some static casts

Makefile.kokkos-kernels, example/wiki/Makefile, example/wiki/blas/abs/Makefile, example/wiki/blas/abs/abs.cpp
Also fixes a small issue in Makefile.kokkos-kernels for cases where
no ETI is done (e.g. when the list of scalars to instantiate is empty).
=> Adding directory for wiki examples including generic Makefile

src/sparse/impl/KokkosSparse_spgemm_impl_kkmem.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_symbolic.hpp
Jenkins errors are fixed. 
One left which becomes an error on some compilers with -Werror flag, which should go away with: https://github.com/kokkos/kokkos/issues/1224.
=> KokkosSparse spgemm: handling some compile errors and warnings

src/sparse/impl/KokkosSparse_spgemm_impl_compression.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_def.hpp
std::make_pair seems to require casting when used numeric constants. 
Fixing with a simple cast.
=> Spgemm: Static assert failures fixed 

src/common/KokkosKernels_Handle.hpp, src/sparse/KokkosSparse_spadd.hpp, src/sparse/KokkosSparse_spadd_handle.hpp, unit_test/Makefile, unit_test/cuda/Test_Cuda_Sparse_spadd.cpp, unit_test/openmp/Test_OpenMP_Sparse_spadd.cpp, unit_test/serial/Test_Serial_Sparse_spadd.cpp, unit_test/sparse/Test_Sparse_spadd.hpp, unit_test/threads/Test_Threads_Sparse_spadd.cpp
Same interface as spgemm (separate symbolic/numeric)
Implemented in sparse/KokkosSparse_spadd.hpp
Has associated handle type (like spgemm) and unit tests
=> Sparse matrix addition (related to Trilinos pull request #1957)

src/common/KokkosKernels_HashmapAccumulator.hpp, src/common/KokkosKernels_PrintUtils.hpp, src/common/KokkosKernels_SparseUtils.hpp, src/common/KokkosKernels_Utils.hpp, src/graph/KokkosGraph_GraphColorHandle.hpp, src/graph/impl/KokkosGraph_Distance2Color_impl.hpp, src/graph/impl/KokkosGraph_GraphColor_impl.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_kkmem.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_symbolic.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_triangle.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_triangle_no_compression.hpp
Required when compiling with serial-only backed to avoid compilation
errors due to unmatched types.
decltype used to determine the type based on the input to
atomic_fetch_add; std::remove_reference needed because expressions may
return a reference type.
=> atomic_fetch_add: explicit casts needed for '1' increments

src/batched/KokkosBatched_AddRadial_Internal.hpp, src/batched/KokkosBatched_LU_Serial_Internal.hpp, src/batched/KokkosBatched_LU_Team_Internal.hpp, src/batched/KokkosBatched_Test_BlockCrs.hpp, src/batched/KokkosBatched_Test_BlockCrs_Util.hpp, unit_test/batched/Test_Batched_VectorRelation.hpp, unit_test/batched/Test_Batched_VectorView.hpp
@ndellingwood 
I tested this on my workstation (g++). Ifpack2 block cars test is compiled and tested. However, I see an weird error from ``Ifpack2_unit_tests_MPI_4``. BTW, I use trillions/ kokkos-develop branch for testing.
```
Program received signal SIGFPE, Arithmetic exception.
0x0000000002280496 in _ZN6Kokkos13MDRangePolicyIJNS_6SerialENS_4RankILj2ELNS_7IterateE2ELS3_2EEENS_9IndexTypeIiEEEEC2IimlEERKSt16initializer_listIT_ERKS9_IT0_ERKS9_IT1_E () at /home/kyukim/Work/lib/trilinos/master/kokkos/core/src/KokkosExp_MDRangePolicy.hpp:312
312	        m_tile_end[i] = static_cast<index_type>((span + m_tile[i] - 1) / m_tile[i]);
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.209.el6_9.2.x86_64
(gdb) bt
#0  0x0000000002280496 in …
```
=> missing typecast 

src/batched/KokkosBatched_Test_BlockCrs_Util.hpp
Addresses kokkos-kernels issue #173
Changes to be committed:
modified:   KokkosBatched_Test_BlockCrs_Util.hpp
=> Fix for -Wshadow error seen in gcc/4.9.3

src/batched/KokkosBatched_Test_BlockCrs_Util.hpp
Intel 14.0.4, 15.0.2. 16.0.1,3 error
KokkosBatched_Test_BlockCrs_Util.hpp(897): error: namespace "std" has no
member "runtime_error"
Fix: Added #include <stdexcept> to file
=> Fix intel error with pthreads

src/blas/impl/KokkosBlas3_gemm_impl.hpp
Error with gcc/4.8.4 and OpenMP backend
kokkos-kernels/src/blas/impl/KokkosBlas3_gemm_impl.hpp:343:0: error:
ignoring #pragma omp simd [-Werror=unknown-pragmas]
Fixed by adding preprocessor #if to remove the pragma if gnu compiler
less than 4.8.5
=> Fix pragma error with gcc/4.8.4

unit_test/CMakeLists.txt
CC: @ibaned, @mhoemmen 
This goes along with the PR #193.  This PR branch and that PR branch must be merged before the next time that KokkosKernels get snapshotted into Trilinos, it will wipe out matching changes there (and cause ATDM and other builds of Trilinos to fail).
=> Disable expensive debug openmp unit test

perf_test/graph/KokkosGraph_color_d2.cpp, src/graph/impl/KokkosGraph_Distance2Color_impl.hpp, unit_test/graph/Test_Graph_graph_color_d2.hpp
@mndevec 
This PR addresses the transpose issue we discussed in our meeting.  Per our conversation, I changed the inner loop (neighbor of neighbors) to use the transpose of the adjacency matrix (i.e., reverse the edges in the DAG).
There are 3 places in the code that this change was made:
1. [functorFindConflicts_Atomic][1]
2. [functorGreedyColor][2]
3. [resolveConflicts][3] 
- We didn't discuss (3) in our conversation but I changed it to match the pattern we're using in (1) and (2) for consistency.  
**Note**: This PR should be looked AFTER PR #197 since I branched this from the mem-fix branch... or just merge this PR and ignore #197 since this one contains the changes in that PR as well.  I split them in case you want to grab the mem error bug fix quickly but wanted to look more closely …
=> D2 Graph Coloring: Asymmetric (DAG) Transpose Fix

unit_test/graph/Test_Graph_graph_color_d2.hpp
This should fix jenkins test failures.
=> D2 coloring test:unused variable compilation error is fixed.

scripts/test_all_sandia
Typo fix for spot-check compilers used by spot-check with sems env.
=> test_all_sandia: change gcc/5.1 to 5.3 for sems env

src/common/KokkosKernels_ExecSpaceUtils.hpp, src/common/KokkosKernels_Utils.hpp, src/graph/KokkosGraph_GraphColorHandle.hpp, src/sparse/KokkosSparse_gauss_seidel_handle.hpp, src/sparse/KokkosSparse_spadd_handle.hpp, src/sparse/KokkosSparse_spgemm_handle.hpp, src/sparse/impl/KokkosSparse_spgemm_imp_outer.hpp, src/sparse/impl/KokkosSparse_spgemm_impl.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_compression.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_kkmem.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_memaccess.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_speed.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_symbolic.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_triangle.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_triangle_no_compression.hpp
KOKKOS_HAVE_PTHREADS flag seems to be removed from kokkos. All KOKKOS_HAVE_ flags are changed to KOKKOS_ENABLE in this commit. 
On Shepard the test that was previously failing:
```
./test_all_sandia intel/17.4.196 --build-list=Pthread 
Going to test compilers:  intel/17.4.196
Testing compiler intel/17.4.196
Starting job intel-17.4.196-Pthread-release
PASSED intel-17.4.196-Pthread-release
PASSED TESTS
intel-17.4.196-Pthread-release build_time=336 run_time=349
FAILED TESTS
```
I am testing on white and will post the results here.
=> Kokkoskernels sparse failures 

src/sparse/KokkosSparse_CrsMatrix.hpp
Required to support a view of crs matrices.
This may require that a corresponding PR in Kokkos be accepted first:
https://github.com/kokkos/kokkos/pull/1587
=> fix to support View of CrsMatrices

src/sparse/KokkosSparse_BlockCrsMatrix.hpp, src/sparse/KokkosSparse_CrsMatrix.hpp
This requires kokkos changes discussed in kokkos/kokkos#1581.
=> CrsMatrix: Pass memory_traits info to StaticCrsGraph

src/batched/KokkosBatched_Util.hpp, src/batched/KokkosBatched_Vector_SIMD.hpp, src/batched/KokkosBatched_Vector_SIMD_Misc.hpp, src/batched/KokkosBatched_Vector_SIMD_Relation.hpp
To assert is_convertible, it needs over-riding for complex variables and overriding std::is_convertible is forbidden by the language. So, we relax the condition and remove is_convertible.
=> KokkosKernels - remove is_convertible #250

.gitignore, perf_test/graph/KokkosGraph_color.cpp, src/blas/KokkosBlas1_dot.hpp, src/blas/impl/KokkosBlas1_team_dot_spec.hpp, src/blas/impl/KokkosBlas1_team_nrm2_spec.hpp, src/graph/KokkosGraph_GraphColorHandle.hpp, src/graph/KokkosGraph_graph_color.hpp, src/graph/impl/KokkosGraph_GraphColor_impl.hpp, unit_test/Makefile, unit_test/cuda/Test_Cuda_Graph_graph_color_deterministic.cpp, unit_test/graph/Test_Graph_graph_color_deterministic.hpp, unit_test/openmp/Test_OpenMP_Graph_graph_color_deterministic.cpp, unit_test/serial/Test_Serial_Graph_graph_color_deterministic.cpp, unit_test/threads/Test_Threads_Graph_graph_color_deterministic.cpp
@srajama1 
Adding deterministic graph coloring based on dependency list.
This is a simple version that parallelizes using range policies and uses only one atomic to update `newFrontierSize`.
In a next step I am planning on switching `bannedColors` to use a bit array that will be more compact in memory.
=> Graph: Deterministic coloring

CMakeLists.txt, cmake/Dependencies.cmake, cmake/KokkosKernels_config.h.in, src/blas/KokkosBlas.hpp, unit_test/CMakeLists.txt
Reference issue #276
- add BLAS, LAPACK, CUBLAS, CUSPARSE TPL dependence
- KokkosBlas.hpp includes gemm
- comment regarding to gtest path
- when we use override src directory, the relative path to other
package (kokkos) may not be correct.
This PR is necessary in order to remove Tpetra BLAS functions.
=> KokkosKernels - cmake modifications for TPLs

perf_test/sparse/KokkosSparse_block_pcg.cpp
There was a compile error on the perf_test for block PCG when offsets
are size_t. Minor fix.
=>  Fixes #287

src/Kokkos_ArithTraits.hpp, test_common/Test_Common_ArithTraits.hpp
Are `hasInfinity` and `infinity()` something you would consider add to `Kokkos::ArithTraits<T>`?
=> Query positive infinity value of floating-point type using Kokkos::ArithTraits

Makefile.kokkos-kernels, cmake/KokkosKernels_config.h.in
Currently, tpl blas is automatically enabled when mkl or cublas is enabled.
This is wrong when cublas is only provided without host blas library. 
This fixes the problem.
=> KokkosKernels - fix the automatic tpl blas enabling logic

src/sparse/impl/KokkosSparse_spgemm_impl_symbolic.hpp
Renaming template parameters of KokkosSPGEMM::PredicMaxRowNNZ to avoid shadowing that leads to a bad copy constructor call.
I am not too sure why gcc is allowing this to go through but clang is clearly less appreciative.
=> Fix issue #281: template parameters of functor contained in class is shadowed

unit_test/sparse/Test_Sparse_spgemm.hpp
Similar fix as in PR #290 for MKL
=> spgemm unit test: update cusparse macro check

src/sparse/KokkosSparse_gauss_seidel.hpp, src/sparse/KokkosSparse_gauss_seidel_handle.hpp, src/sparse/impl/KokkosSparse_gauss_seidel_impl.hpp, src/sparse/impl/KokkosSparse_gauss_seidel_spec.hpp, unit_test/sparse/Test_Sparse_block_gauss_seidel.hpp, unit_test/sparse/Test_Sparse_gauss_seidel.hpp
- Add damping option
- Instead of inverting the diagonal in every iteration, save the inverse of the diagonal
- Allow to pass a precomputed diagonal. 
The last item is necessary for MT GS to work correctly with Ifpack2. The diagonal of a Tpetra matrix might not be given by pairs (i, i) of local IDs (depending on the rowmap and the colmap). Moreover, this allows to use MT GS with the l1 option from Ifpack2.
I also added some routines to dump to MatrixMarket format.
This addresses Issues #221 and #240
=> MT Gauss-Seidel fixups

src/batched/KokkosBatched_Vector_SIMD.hpp
Cleanup fix for issue #309 - move includes to external headers outside of internal namespaces.
=> Cleanup fix for issue #309

scripts/generate_makefile.bash
Resolves issue #257 where configuring with only "Cuda" in the `KOKKOS_DEVICES` parameter will result in a link error.  
This fix will change the parameter from "Cuda" to "Serial,Cuda" when only "Cuda" is provided.
Resolves #257 
Relates to #256 
@srajama1 
@ndellingwood
=> generate_makefile fix for CUDA only KOKKOS_DEVICES

scripts/test_all_sandia
Fix issue when kokkos-hwloc is loaded after compilers causing
configuration failures.
=> test_all_sandia: fix module load order on sems machines

scripts/generate_makefile.bash, scripts/test_all_sandia
generate_makefile: add option for users to select layout
--with-layouts
test_all_sandia: add options for setting the scalar, ordinal, offset
types and layout
=> test_all_sandia, generate_makefile updates

src/graph/KokkosGraph_graph_color.hpp, unit_test/graph/Test_Graph_graph_color.hpp, unit_test/graph/Test_Graph_graph_color_deterministic.hpp
Added a guard to include COLORING_VBD for non Cuda tests.
This resolves #317
@ndellingwood 
I added the fix we discussed this morning.
I'm running the spot check on the Kepler nodes on White, when it completes I'll post the results.
=> Fix COLORING_VBD test failures on Cuda

example/Makefile, example/hashmap_accumulator/KokkosKernels_Example_HashmapAccumulator.cpp, perf_test/Makefile, perf_test/graph/KokkosKernels_Example_HashmapAccumulator.cpp, scripts/generate_makefile.bash, src/common/KokkosKernels_HashmapAccumulator.hpp
Initial commit of my stab at a `HashmapAccumulator` example.
This example is trying to implement a simplified version of how I'm using the `HashmapAccumulator` class in my [Distance-2 Graph Coloring work in progress branch][1].
[1]: https://github.com/william76/kokkos-kernels/blob/58bfd0891aecc85db28abb3a4bf1a3492c586822/src/graph/impl/KokkosGraph_Distance2Color_impl.hpp#L2341-L2481
=> WIP: HashmapAccumulator Example

src/CMakeLists.txt
Thanks @kyungjoo-kim for debugging and help with fix.
Potential fix for linking error exposed by Trilinos integration testing
due to undefined reference for
KokkosBlas::Impl::CudaBlasSingleton::singleton()
The object files for the tpls were not being included, added APPEND_GLOB
for the relevant files when Cuda is built for.
=> src/CMakeLists.txt: Fix for cublas

example/fenl/BoxElemFixture.hpp, example/fenl/VectorImport.hpp, example/fenl/fenl_functors.hpp, perf_test/batched/KokkosBatched_Test_Gemm_Cuda.cpp, src/batched/KokkosBatched_Test_BlockCrs_Util.hpp, src/common/KokkosKernels_Utils.hpp, src/graph/KokkosGraph_GraphColorHandle.hpp, src/sparse/KokkosSparse_gauss_seidel_handle.hpp, src/sparse/KokkosSparse_spgemm_handle.hpp, src/sparse/impl/KokkosSparse_spgemm_imp_outer.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_def.hpp, src/sparse/impl/KokkosSparse_spmv_impl.hpp, test_common/KokkosKernels_MatrixConverter.cpp
Issues:
1. team_size_max and team_size_recommended are no longer static
member functions when deprecated code is disabled; must be called as a
member function of an instantiated team policy
2. spmv sets an incorrect team_size with Cuda_Serial configuration
Changes to be committed:
modified:   src/common/KokkosKernels_Utils.hpp
modified:   src/graph/KokkosGraph_GraphColorHandle.hpp
modified:   src/sparse/KokkosSparse_gauss_seidel_handle.hpp
modified:   src/sparse/impl/KokkosSparse_spmv_impl.hpp
=> Fixes 1: code broken when deprecated code disabled

unit_test/CMakeLists.txt
This relates to the issue in Trilinos where serial builds were failing
because they tried to load the pthreads library as requested by gtest
in KokkosKernels.
This PR mirrors changes made in the Trilinos repository so that the next KokkosKernels push doesn't reintroduce the bug.
See: https://github.com/trilinos/Trilinos/issues/3773
=> Disable Pthreads in Gtest

scripts/test_all_sandia
The sems-gcc/7.3.0 module isn't currently available on sandia RHEL7 machines.
Additionally, since we're stuck with supporting gcc 7.2.0 for the foreseeable future since Trilinos must support gcc 7.2.0 because that is the gcc 7.x compiler available on at least one machine needed by customers, we should probably be testing kokkos-kernels with gcc 7.2.0.
@ndellingwood
=> test_all_sandia gcc 7.2.0

src/common/KokkosKernels_HashmapAccumulator.hpp
Added header guards to `src/common/KokkosKernels_HashmapAccumulator.hpp`
Resolves #367
=> Add header guards to HashmapAccumulator

src/sparse/impl/KokkosSparse_spgemm_imp_outer.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_compression.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_def.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_kkmem.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_speed.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_symbolic.hpp
I was getting a lot of compiler errors when I had -Werror=shadow enabled so I fixed them.
```
/Users/wcmclen/dev/kk-dev/source/KokkosKernels/src/sparse/impl/KokkosSparse_spgemm_impl_symbolic.hpp:1813:38: error: declaration of 'my_exec_space' shadows a previous local [-Werror=shadow]
KokkosKernels::Impl::ExecSpaceType my_exec_space = this->handle->get_handle_exec_space();
^~~~~~~~~~~~~
In file included from /Users/wcmclen/dev/kk-dev/source/KokkosKernels/src/sparse/impl/KokkosSparse_spgemm_symbolic_spec.hpp:55,
from /Users/wcmclen/dev/kk-dev/source/KokkosKernels/src/impl/generated_specializations_cpp/spgemm_symbolic/KokkosSparse_spgemm_symbolic_eti_spec_inst_double_size_t_int_LayoutRight_Serial_HostSpace_HostSpace.cpp:55:
/Users/wcmclen/dev/kk-dev/source/KokkosKernels/src/sparse/impl/KokkosS …
```
=> Shadowed declarations in SPGEMM

src/blas/impl/KokkosBlas3_gemm_impl.hpp
Addresses issue #368 reported by @etphipp, matches patch in
trilinos/Trilinos#4168
scratch_memory_size should call shmem_size rather than
required_allocation_size.
=> Fix GEMM scratch memory size

Makefile.kokkos-kernels, src/Makefile
If the `coreutils` package is installed on OSX via Homebrew, there will be a gnu version of cp installed which does respect the `-u` option.
This will reduce the time it takes to recompile KokkosKernels on OSX systems since we won't be updating the timestamp on all the sources every time we recompile.
=> Use homebrew's coreutils cp if available on osx

src/batched/KokkosBatched_Gemm_Decl.hpp, src/batched/KokkosBatched_Gemv_Decl.hpp, src/batched/KokkosBatched_LU_Decl.hpp, src/batched/KokkosBatched_Trsm_Decl.hpp, src/batched/KokkosBatched_Trsv_Decl.hpp, src/batched/KokkosBatched_Util.hpp
Add an interface to select between serial and team interfaces. This does not require a test as the modification is placed on decl.hpp. This modification however is required from Ifpack2.
=> KokkosBatched - add a more selective interface

src/graph/impl/KokkosGraph_Distance2Color_impl.hpp
Bugfix for the KNL error from last night's tests.
@ndellingwood I looked at the other functors in `KokkosGraph_Distance2Color_impl.hpp` and they're all have the underscore appended to the end of the `nv`, `xadj`, `adj`, `t_xadj`, and `t_adj` paramters in the functor constructors so this one was just a cut-and-paste error I think.  Interesting that it got through the spot checks I was running.
My updated spot-check script for Bowman was able to replicate this error so I'm re-running it to make sure I got all the spots corrected.  I don't think it'll take too long to run so I'll post the spot check results here when it completes.
=> D2GC: Fixing 'declaration hides member' error

src/graph/impl/KokkosGraph_Distance1Color_impl.hpp
IBM xlc related issue where we need to typecast the constant input to Kokkos atomc_fetch_add. I couldn't reproduce with the IBM compilers on white, bu @jhux2 has confirmed that this fixes the problems he is facing.
=>  Fix #401. Address failures when compiling with xlc on certain platform

perf_test/graph/KokkosGraph_color.cpp
Added a --help option to the distance-1 graph coloring test, `perf_test/graph/KokkosGraph_color.exe`
```
$ KokkosGraph_color.exe --help
Usage:
KokkosGraph_color.exe [parameters]
Parameters:
Parallelism (select one of the following):
--serial <N>        Execute serially.
--threads <N>       Use N posix threads.
--openmp <N>        Use OpenMP with N threads.
--cuda              Use CUDA
Required Parameters:
--amtx <filename>   Input file in Matrix Market format (.mtx).
--algorithm <algorithm_name>   Set the algorithm to use.  Allowable values are:
COLORING_DEFAULT  - Use the default coloring method, architecture dependent.
COLORING_SERIAL   - Use the serial algorithm.
COLORING_VB       - Use the parallel vertex-based method.
COLORING_VBBIT    - Use the parallel vertex-based with bit vectors …
```
=> Add --help for distance-1 graph coloring

src/impl/tpls/KokkosBlas3_gemm_tpl_spec_avail.hpp, src/impl/tpls/KokkosBlas3_gemm_tpl_spec_decl.hpp
Add CudaUVMSpace specializations for GEMM.  This should fix performance issues that @vbrunini noticed on CUDA.  Thanks to @kyungjoo-kim and @vbrunini for feedback.
Corresponding Trilinos patch:
https://github.com/trilinos/Trilinos/pull/4649
=> Fix #397 (Add GEMM CudaUVMSpace specializations)

perf_test/batched/KokkosBatched_Test_BlockTridiagDirect.cpp, perf_test/batched/KokkosBatched_Test_BlockTridiagJacobi.cpp
A simple fix for #407 . I tested without lambda and it compiles.
=> Fix putting ifdef guard for perf test

perf_test/graph/KokkosGraph_color.cpp, src/graph/impl/KokkosGraph_Distance1Color_impl.hpp
Replaced a couple of places where we should be using `KokkosGraph_Distance1ColorHandle.hpp` instead of the older headers.  I probably should have done this in #375 but I just missed them.
Running spot-check now, I'll update results in comments.
FYI @ndellingwood
=> D2GC: Fix headers for Distance-1 use cases

src/batched/KokkosBatched_Vector.hpp
Most important part in memory efficiency is keeping 32 byte cacheline.
By reducing the length, we can increase occupancy for smaller problems
and sparc is the case.
=> KokkosBatched - reduce vector length from 16 to 8.

unit_test/graph/Test_Graph_graph_color_distance2.hpp
Reduces the size of the 'test' graph for D2GC by 10x and removes the message to stdout when the distance-2 coloring is validated as correct.
=> D2GC: Reduce unit test problem size

src/common/KokkosKernels_IOUtils.hpp
read_mtx() loads a list of (row,col) pairs, sorts them, and then inserts
into the CRS structure one row at a time. The loop over entries in the
current row only checked if the next entry matches the current row, but NOT
that the end of the pair array has been reached. This caused an invalid
read just after inserting the last entry in the matrix.
=> Fixed out-of-bounds read in read_mtx()

src/sparse/impl/KokkosSparse_spgemm_impl_def.hpp
For SPGEMM_KK algorithm on CUDA, entry compression has a bug
(for some inputs, the row map from symbolic has too few entries per
row). This commit disables compression on CUDA as a workaround (other
ExecSpaces are not affected)
=> Cuda: disable compression in SPGEMM symbolic

src/sparse/impl/KokkosSparse_spmv_struct_impl.hpp, test_common/KokkosKernels_Test_Structured_Matrix.hpp
This issue was originally reported in PR #452 
After extensive testing and code modification, this appears to be a compiler optimization bug.
Currently running the spot_check to verify that nothing else got disturbed by the fix.
=> SpMV struct: fixing bug with intel/17.0.1

src/common/KokkosKernels_IOUtils.hpp
- read_mtx now supports pattern, complex, array, Hermitian, symmetric,
and skew-symmetric (the full MatrixMarket specification). Before, it just
supported "matrix coordinate real general".
- support Kokkos::complex scalar type in write_graph_mtx()
- support non-host accessible views in write_kokkos_crst_matrix, by
getting a host mirror
There are no tests that use the matrix IO, so the spot check doesn't help evaluate these changes. However, once we migrate to CMake for testing, a "copy files to binary dir" will make it easy to test each possible format/field/symmetry combination for read_mtx.
For now, I tested the I/O manually by running the following matrices from the SuiteSparse collection through the SPGEMM testing driver:
- 130bit (pattern, general)
- aa01 (pattern, general)
- can_73 …
=> Full MatrixMarket support for read_mtx()

src/common/KokkosKernels_Utils.hpp
With Kokkos deprecated off, the KokkosKernels suggested team size was sometimes 0 (especially for small matrices, like in some unit tests). A team of size 0 obviously can't do any work, so this commit just makes sure the #teams is at least 1. This was caught because some of the symmetrize utility functions divide by the team size to divide up work, causing div-by-zero/floating point exceptions in the sparse and graph unittests.
This fixes #468.
Bowman spot check:
PASSED TESTS
intel-16.4.258-Pthread-release build_time=1521 run_time=587
intel-16.4.258-Pthread_Serial-release build_time=2472 run_time=1250
intel-16.4.258-Serial-release build_time=1470 run_time=622 …
=> With kokkos deprecated off, fix sugg teamsize = 0 (#468)

src/batched/KokkosBatched_Vector.hpp
This set a vector length (4 doubles) for ARM architectures. For Ifpack2 block tridiagonal solver, using 256 bit length is better than 128 bit length. For quick test, I already submit a PR for Trilinos and this is a matching PR in KokkosKernels.
=> KokkosBatched - vector length adjustment for ARM

perf_test/sparse/KokkosSparse_run_spgemm.hpp, src/common/KokkosKernels_Utils.hpp, src/graph/KokkosGraph_Distance1ColorHandle.hpp
A permanent fix for #474, replacing the temporary one in #472. When Kokkos deprecated is off and the execution space is CUDA, ``KokkosKernels::Impl::get_suggested_team_size()`` uses ``TeamPolicy::team_size_recommmended()``, which calls ``cudaOccupancyMaxActiveBlocksPerMultiprocessor()``. This should be a good heuristic, and will definitely never produce a team size too high to launch, since the CUDA runtime knows exactly how many registers a kernel uses.
This change doesn't affect SPGEMM, SPMV or Blas. ``KokkosKernels::Impl::get_suggested_team_size()`` is only used in the utility functions ``symmetrize_and_get_lower_diagonal_edge_list()`` and ``symmetrize_graph_symbolic_hashmap()``, as well as ``get_lower_diagonal_edge_list()`` used during Dist1 coloring setup.
Bowman spot check: …
=> Use up-to-date Kokkos features to get team size

src/common/KokkosKernels_IOUtils.hpp
Bowman spot check:
PASSED TESTS
intel-16.4.258-Pthread-release build_time=1523 run_time=583
intel-16.4.258-Pthread_Serial-release build_time=2437 run_time=1261
intel-16.4.258-Serial-release build_time=1468 run_time=622
intel-17.2.174-OpenMP-release build_time=1967 run_time=385
intel-17.2.174-OpenMP_Serial-release build_time=2833 run_time=1156
intel-17.2.174-Pthread-release build_time=1313 run_time=620
intel-17.2.174-Pthread_Serial-release build_time=2371 run_time=1252
intel-17.2.174-Serial-release build_time=1370 run_time=662
intel-18.2.199-OpenMP-release build_time=1595 run_time=436
intel-18.2.199-OpenMP_Serial-release build_time=2735 run_time=1031 …
=> Fix unreachable warning in IOUtils (#481)

src/common/KokkosKernels_ExecSpaceUtils.hpp
The local part of a matrix can have zero rows. Fixes https://github.com/trilinos/Trilinos/issues/6264.
=> Fix suggested vector size when nr == 0

src/common/KokkosKernels_Handle.hpp, src/common/KokkosKernels_Utils.hpp, src/sparse/KokkosSparse_gauss_seidel.hpp, src/sparse/KokkosSparse_gauss_seidel_handle.hpp, src/sparse/impl/KokkosSparse_cluster_gauss_seidel_impl.hpp, src/sparse/impl/KokkosSparse_gauss_seidel_impl.hpp, src/sparse/impl/KokkosSparse_gauss_seidel_spec.hpp, unit_test/sparse/Test_Sparse_block_gauss_seidel.hpp, unit_test/sparse/Test_Sparse_gauss_seidel.hpp
This PR adds rank-2 vector support to all variants of parallel Gauss-Seidel (point-coloring, block, cluster-coloring). This should be a significant speedup for Ifpack2 MTSGS with multivectors. Rank-1 support is not affected from the user's perspective.
The ETI for Gauss-Seidel apply() has been changed to just instantiate for a rank-2 apply (both LayoutLeft and LayoutRight, in the normal ETI configuration). As before, the user's X and Y vectors are internally converted to unmanaged views with the appropriate scalar, space and layout. If a rank-1 view is provided, the apply is done internally on an Nx1 multivector.
Test coverage for Gauss-Seidel has been improved - both Rank-1 and Rank-2 X/Y, and all apply types (forward/backward/symmetric) are now tested. The versions with lazy setup …
=> Gauss-Seidel: rank-2 X/Y support

src/batched/KokkosBatched_LU_Serial_Internal.hpp
Detected during Trilinos integration testing.
=> batched_lu_serial: fix for ambiguous ? operation error

src/common/KokkosKernels_Sorting.hpp, src/sparse/KokkosSparse_spadd.hpp, test_common/Test_Common_Sorting.hpp, unit_test/CMakeLists.txt, unit_test/cuda/Test_Cuda_Common_Sorting.cpp, unit_test/openmp/Test_OpenMP_Common_Sorting.cpp, unit_test/openmp/Test_OpenMP_Common_float128.cpp, unit_test/serial/Test_Serial_Common_Sorting.cpp, unit_test/serial/Test_Serial_Common_float128.cpp, unit_test/threads/Test_Threads_Common_Sorting.cpp, unit_test/threads/Test_Threads_Common_float128.cpp
This commit adds a new utils file "KokkosKernels_Sorting.hpp". This adds some useful sorting routines for situations where Kokkos::sort can't be used (but may in the future, so these changes are in the Impl namespace).
- 16-bucket radix sort for integers (radixSort). The sorting can be called from inside a parallel region (RangePolicy, TeamPolicy or TeamThreadRange).
- Version of the above radix sort "radixSort2" that applies the same swaps to another array, of arbitrary type
- [Bitonic sort](https://en.wikipedia.org/wiki/Bitonic_sorter) implementation "bitonicSortTeam" that works within a TeamPolicy. This runs in parallel using a TeamThreadRange. This supports any data type that supports "operator<", "operator=", and copy constructor on device. A custom comparator can optionally be …
=> Sorting utilities

unit_test/sparse/Test_Sparse_gauss_seidel.hpp
Add a simple test for sequential successive over-relaxation (aka Gauss-Seidel since omega=1).
White spot check:
PASSED TESTS
cuda-10.0.130-Cuda_Serial-release build_time=1119 run_time=1485
cuda-9.2.88-Cuda_OpenMP-release build_time=1216 run_time=1101
gcc-6.4.0-OpenMP_Serial-release build_time=577 run_time=1308
gcc-7.2.0-OpenMP-release build_time=390 run_time=488
gcc-7.2.0-OpenMP_Serial-release build_time=598 run_time=1551
gcc-7.2.0-Serial-release build_time=294 run_time=650
gcc-7.4.0-OpenMP-release build_time=405 run_time=527
ibm-16.1.0-Serial-release build_time=1305 run_time=1004
FAILED TESTS …
=> Test sequential SOR (#494)

unit_test/sparse/Test_Sparse_block_gauss_seidel.hpp
This resolves unit test failures like the following:
*sparse_block_gauss_seidel_rank1_double_int_int_TestExecSpace
Constructor for Kokkos View 'Y VECTOR' has mismatched number of arguments.
Number of arguments = 2 but dynamic rank = 1
=> block-sgs unit test: Fix case for rank-1 view accepting 2 args

unit_test/sparse/Test_Sparse_gauss_seidel.hpp
Use auto instead of explicity type when calling create_mirror_view
This fixes compilation errors of type
"Incompatible View copy construction" when UVM is enabled
=> Test_Sparse_gauss_seidel: UVM Fix

src/impl/tpls/KokkosBlas3_gemm_tpl_spec_decl.hpp, unit_test/blas/Test_Blas3_gemm.hpp
**Description:**
This PR matches the Trilinos PR https://github.com/trilinos/Trilinos/pull/6427.
**Testing:**
```
[sacer@kokkos-dev-2 unit_test]$ ./KokkosKernels_UnitTest_Cuda --gtest_filter=cuda.gemm_*
Kokkos::OpenMP::initialize WARNING: OMP_PROC_BIND environment variable not set
In general, for best performance with OpenMP 4.0 or better set OMP_PROC_BIND=spread and OMP_PLACES=threads
For best performance with OpenMP 3.1 set OMP_PROC_BIND=true
For unit testing set OMP_PROC_BIND=false
Note: Google Test filter = cuda.gemm_*
[==========] Running 2 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 2 tests from cuda
[ RUN      ] cuda.gemm_double
[       OK ] cuda.gemm_double (3865 ms)
[ RUN      ] cuda.gemm_complex_double
[       OK ] cuda.gemm_complex_double …
```
=> Fix DotBasedGEMM bug encountered in Trilinos issue 6418

unit_test/sparse/Test_Sparse_gauss_seidel.hpp
Fix to ensure View ctor called with number of args matching dynamic rank
=> Test_Sparse_gauss_seidel: Fix for disabled deprecated code

unit_test/CMakeLists.txt
Gtest should not be building with PTHREAD on. Somewhere the definition to turn off pthreads got lost in the CMake. This brings back the correct behavior, allowing serial-only tests to pass.
=> Fixed pthread definitions for gtest

src/batched/KokkosBatched_Trsm_Serial_Impl.hpp, src/batched/KokkosBatched_Trsm_Team_Impl.hpp
Upper vs Lower incorrectly marked in some routines.
Matches patch to Trilinos PR trilinos/Trilinos#6076
=> KokkosBatched_Trsm: serial and team fixes

src/blas/impl/KokkosBlas3_gemm_impl.hpp, src/common/KokkosKernels_Sorting.hpp, test_common/Test_Common_Sorting.hpp, unit_test/Makefile, unit_test/sparse/Test_Sparse_gauss_seidel.hpp, unit_test/sparse/Test_Sparse_spadd.hpp
Fix major bug/typo in BitonicSort2 where a key was compared with itself, so the swap was never happening.
Add Test_DEVICE_Common_Sorting.o to unit test executables in
Makefile-based build.
Improve test coverage in sorting tests that would have caught this, rather than relying on spadd tests to catch it indirectly. Fixed spadd tests to actually verify result indices are sorted.
=> Fix major bug in TeamBitonicSort2.

src/blas/impl/KokkosBlas3_gemm_impl.hpp, unit_test/blas/Test_Blas3_gemm.hpp
**Description:**
This PR fixes the fallback gemm resulting in large diffs with complex scalar type when input random matrices have reasonably large values.
This defect was exposed when the upper bound of the random number generator (for A, B, and C matrices) in KokkosKernels gemm unit test was increased from `10` to `Kokkos::Random_XorShift64_Pool<...>::max()`. This PR includes this change too.
**Testing:**
`[sacer@white29 testing]$ ../scripts/test_all_sandia --spot-check --arch=Power8,Pascal60`
```
Running on machine: white
Going to test compilers:  gcc/6.4.0 gcc/7.2.0 gcc/7.4.0 ibm/16.1.0 cuda/9.2.88 cuda/10.0.130
Testing compiler gcc/6.4.0
Testing compiler gcc/7.2.0
Starting job gcc-6.4.0-OpenMP_Serial-release
Starting job gcc-7.2.0-OpenMP-release
PASSED gcc-7.2.0-OpenMP-release …
```
=> Fix fallback gemm for complex scalar types

unit_test/sparse/Test_Sparse_block_gauss_seidel.hpp, unit_test/sparse/Test_Sparse_gauss_seidel.hpp
Prevent tests from timing out (#547, and Trilinos #6464). Spot checks running...
=> Shrink Gauss-Seidel test matrices

src/sparse/impl/KokkosSparse_spgemm_impl_compression.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_speed.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_symbolic.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_triangle.hpp
- For UniformMemoryPools, sure there is a release_chunk()
corresponding to every allocate_chunk()
- Assign global values inside a single(PerThread), in a GPU kernel
where vector_size > 1
- Pass back to release_chunk the same pointer returned by
allocate_chunk - not strictly necessary but makes things clearer
=> Fix spgemm memory pool leaks, minor memory bugs

src/blas/KokkosBlas2_gemv.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_triangle.hpp
Address issue #540, problems with degenerate matrix cases when
blas tpls enabled.
=> gemv: call fallback impl in transpose mode with M==0

scripts/cm_test_all_sandia
Add -Wno-pass-failed to remove warnings with Cuda_OpenMP builds
with clang/8 + cuda/10 in kokkos-dev-2
=> cm_test_all_sandia: update clang8 flags for clang+cuda builds

src/common/KokkosKernels_Sorting.hpp, src/sparse/KokkosSparse_spadd.hpp, test_common/Test_Common_Sorting.hpp
Now, the serial radix sorts enforce at compile time that the key is an unsigned integer.
This was really the assumption all along (that values were always
nonnegative). No longer adding a bias to the keys while sorting, since all the keys are at least 0.
This was causing the char radix sort unit test to fail in an OpenMP debug configuration - I think because of undefined overflow behavior when the chars were normalized from range (min, max) to range (0, max-min). This PR sorts only nonnegative chars and reinterprets as ``unsigned char``, which is safe.
=> Fix radix test failure involving integer sign

src/blas/KokkosBlas2_gemv.hpp
=> gemv: call scal for degenerate matrices

src/sparse/KokkosSparse_spadd.hpp
-Making sure last entry of rowcount view is correct, if Crowmap on input
wasn't initialized (a bug affecting Tpetra!)
-Remove unnecessary view initializations (was taking up to 50% of the
spadd time!)
-Remove unnecessary fences
-Still have fences at the end of user-facing functions,
so that timers on host accurately reflect kernel times
-Use idiomatic deep_copy to scalar for accessing views, rather than
making a host mirror of a single-element subview
-Negligible impact, but avoid View reference count increments (pass-by-ref to functor ctor)
=> spadd bugfix, cleanup for performance

src/Kokkos_InnerProductSpaceTraits.hpp, src/blas/KokkosBlas1_dot.hpp, src/blas/impl/KokkosBlas1_dot_impl.hpp
For vectors of `float`, the two-argument overload of `KokkosBlas::dot` (that takes two vectors (rank-1 Views) as input, and returns the dot product result as a scalar value on host) gets inaccurate results on Mac Clang.  This commit fixes that overload of `KokkosBlas::dot` so that if the dot product result type is `float` resp. `complex<float>`, the function uses `double` resp. `complex<double>` as the type for intermediate sums.
This change, when applied to Trilinos in Pull Request https://github.com/trilinos/Trilinos/pull/6634, fixes Trilinos issue https://github.com/trilinos/Trilinos/issues/6633.
Closes #574
=> Fix #574 (improve KokkosBlas::dot accuracy for float & complex<float>)

scripts/cm_test_all_sandia
Requested in #576 
- Spot check only does "Serial" on IBM as OpenMP takes way too long (about 30x longer than a CUDA build)
- Add CUDA 10.1.105 as a build in both spot-check and full-check
- CUDA 10.1 has CUDA graph support which we'll be using soon
- CUDA 9.2 and 10.1 now done in spot check
- CUDA 9.2, 10.0 and 10.1 now done in full check
- All IBM builds (Serial, Serial_OpenMP, and OpenMP) on two compiler versions are still done in full checks
I thought I should test this on both RIDE and white since their software environments aren't exactly identical (for example, RIDE has CUDA 10.1.105 and 10.1.243, while white only has 10.1.105.
Bowman spot check, just to make sure testing on other machines didn't change:
```
PASSED TESTS …
```
=> Update cm_test_all_sandia on white/ride (#576)

src/graph/impl/KokkosGraph_Distance1Color_impl.hpp
Distance-1 coloring with parallel prefix sum worklist used to require 2 passes: a scan to get new worklist index view, and a for to populate the worklist. The original paper about it even says that the 2-pass approach is a downside of PPS compared to atomics.
This makes PPS use a single scan pass that scatters directly to the new worklist without an index view. This saves some time, one kernel launch per iteration and a significant amount of memory: ``(num_edges / 2) * sizeof(nnz_lno_t)`` for EB, and ``num_rows * sizeof(nnz_lno_t)`` for VB.
Also, renamed ``_conflictlist`` member to ``_conflictlist_scheme`` for clarity - it's not a list, it's an enum representing how the worklist is built. I also use those actual enum constants (``COLORING_NOCONFLICT``, ``COLORING_ATOMIC``, …
=> Dist1 coloring PPS improvements

src/sparse/impl/KokkosSparse_spgemm_impl_kkmem.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_speed.hpp
Address issue #587
Integration testing with Trilinos exposed issues with handling of
shmem alignment with ensemble types.
This PR:
1. reverts how thread_memory is computed during functor construction
2. removes throws within functors when shmem unaligned
3. adds warning message and throws prior to kernel launch for cases
with inappropriate shmem sizes
4. guards shmem realignment with KOKKOS_ENABLE_COMPLEX_ALIGN
this keeps behavior consistent with Trilinos, but will
need to be further addressed
5. some formatting cleanup and comments added
=> spgemm: more shmem alignment related fixes

src/common/KokkosKernels_IOUtils.hpp, src/common/KokkosKernels_Utils.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_compression.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_symbolic.hpp, unit_test/sparse/Test_Sparse_spgemm.hpp
The behavior fixes were to define the the average and maximum nonzeros per row for a zero-row matrix to be zero, not INT_MIN.
Added SPGEMM unit test for zero row case that would have caught this.
This is a high priority issue affecting EMPIRE.
Bowman spot checks passed. RIDE spot checks failed due to #598 - this affects develop branch and isn't related to these changes.
However, #598 won't affect Trilinos because shared memory alignment logic goes through a different path in order to work with ensemble scalar types. @ndellingwood and I are working on a permanent fix for that.
=> Fixed SPGEMM for zero rows in several places

src/sparse/impl/KokkosSparse_spgemm_impl_compression.hpp
Mirror of https://github.com/trilinos/Trilinos/pull/6780
Bowman
PASSED TESTS
intel-16.4.258-Pthread-release build_time=738 run_time=1060
intel-16.4.258-Pthread_Serial-release build_time=1065 run_time=1982
intel-16.4.258-Serial-release build_time=716 run_time=937
intel-17.2.174-OpenMP-release build_time=889 run_time=563
intel-17.2.174-OpenMP_Serial-release build_time=1236 run_time=1468
intel-17.2.174-Pthread-release build_time=820 run_time=885
intel-17.2.174-Pthread_Serial-release build_time=1126 run_time=1810
intel-17.2.174-Serial-release build_time=783 run_time=895
RIDE
PASSED TESTS …
=> Fixed divide-by-zero with compression flops

src/blas/KokkosBlas3_gemm.hpp
xref: https://github.com/trilinos/Trilinos/pull/6512
=> Fixup B0 on certain MacOSX SDKs

src/common/KokkosKernels_Utils.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_kkmem.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_speed.hpp
Explicitly align scalar_t pointers in hashmaps.
Account for the few extra bytes of padding (in practice, up to 4)
in every calculation of shared memory and pool chunk size.
@ndellingwood If you're OK with the changes I'll build and run Stokhos unit tests to make sure ensemble types work. Complex had 16-byte alignment for these tests (``KOKKOS_ENABLE_COMPLEX_ALIGN`` is on) so alignPtr is doing the correct thing here.
RIDE spot checks (double,complex_double)
PASSED TESTS
cuda-10.1.105-Cuda_OpenMP-release build_time=507 run_time=414
cuda-10.1.105-Cuda_Serial-release build_time=543 run_time=521
cuda-9.2.88-Cuda_OpenMP-release build_time=556 run_time=422 …
=> Permanent fix for scalar memory alignment for hashmaps

src/sparse/impl/KokkosSparse_trsv_impl.hpp
addresses issue #607 reported by Mike Glass
replace /= compound assignment operators
=> trsv: workaround intel/19.0.4 interal compiler error

perf_test/sparse/CMakeLists.txt, perf_test/sparse/KokkosSparse_spmv_struct.cpp, perf_test/sparse/KokkosSparse_spmv_struct_tuning.cpp, perf_test/sparse/KokkosSparse_spmv_struct_tunning.cpp, src/sparse/impl/KokkosSparse_spmv_struct_impl.hpp, unit_test/sparse/Test_Sparse_spmv.hpp
I'm adding a slightly modified heuristic that improves performance of the SpMV struct algorithm.
I also cleaned up the code, removing some pointer arithmetic where it does not help performance.
Finally I improved correctness by using appropriate types for temporary variables (should allow mix-arithmetic to work correctly).
Finally I also fixed an omission regarding the complex conjugate mode.
The spot_check is currently running on white, bowman and kokkos-dev, I'll post results when everything is clean.
=> SpMV Struct performance and clean-up

src/common/KokkosKernels_ExecSpaceUtils.hpp
Taken from kokkos perf_test:
https://github.com/kokkos/kokkos/blob/3e51447871eaec53ac4adc94d4d5376b7345b360/core/perf_test/PerfTest_ExecSpacePartitioning.cpp#L7-L36
=> ExecSpaceUtils: Add execution space instance creators

src/sparse/KokkosSparse_spgemm_handle.hpp, src/sparse/impl/KokkosSparse_spgemm_cuSPARSE_impl.hpp, src/sparse/impl/KokkosSparse_sptrsv_cuSPARSE_impl.hpp
This allows us to update the `cm_sandia_test_all` script to test tpls on kokkos-dev with the cuda-clang build.
=> Small clean-up in spgemm and sptrsv for clang 7 cuda build with tpls

src/graph/impl/KokkosGraph_Distance2Color_impl.hpp
Raw malloc'd buffer "forbidden" was read in this loop:
``while(forbidden[c] == v) c++;``
but forbidden was not initialized. If it happened to be filled with 0,
then when coloring the first vertex this loop would read past the end
of the array. This caused random crashes (#634 is an example).
kokkos-dev2:
PASSED TESTS
clang-8.0-Pthread_Serial-release build_time=89 run_time=371
cuda-10.1-Cuda_OpenMP-release build_time=274 run_time=525
gcc-7.3.0-OpenMP-release build_time=83 run_time=119
gcc-7.3.0-Pthread-release build_time=65 run_time=239
gcc-8.3.0-Serial-release build_time=64 run_time=182
gcc-9.1-OpenMP-release build_time=72 run_time=114
gcc-9.1-Serial-release build_time=65 …
=> Fixed D2 resolveConflictsSerial() memory safety (#634)

scripts/cm_test_all_sandia
This update to cm_test_all_sandia adds testing with UVM in cuda/9.2.* builds
Testing on white:
```
bash-4.2$ ../../scripts/cm_test_all_sandia cuda/9.2 --build-list=Cuda_Serial
Running on machine: white
M scripts/cm_test_all_sandia
Repository Status:  1e96163c8225380675cf1bc5a7047fc8e7c914c8 cm_test_all_sandia: enable UVM for cuda/9.2 builds
Going to test compilers:  cuda/9.2.88
Testing compiler cuda/9.2.88
Starting job cuda-9.2.88-Cuda_Serial-release
kokkos options: 
kokkos devices: Cuda,Serial
kokkos cxx: -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized 
PASSED cuda-9.2.88-Cuda_Serial-release
PASSED TESTS …
```
=> Testall cudauvm

perf_test/sparse/KokkosSparse_spmv_struct_tuning.cpp
Kokkos does not enable lambdas by default when Cuda is enabled.
This test was using lambdas without proper guards, this PR adds guard.
Detected during tpl spot-check nightly testing.
=> KokkosSparse_spmv_struct_tuning: add lambda guard

scripts/cm_test_all_sandia, src/sparse/KokkosSparse_sptrsv_handle.hpp, src/sparse/impl/KokkosSparse_spiluk_numeric_impl.hpp, src/sparse/impl/KokkosSparse_sptrsv_solve_impl.hpp, src/sparse/impl/KokkosSparse_sptrsv_symbolic_impl.hpp, test_common/Test_Common_Sorting.hpp, unit_test/sparse/Test_Sparse_block_gauss_seidel.hpp, unit_test/sparse/Test_Sparse_gauss_seidel.hpp
Also removing CUDA_LAUNCH_BLOCKING and CUDA_MANAGED_FORCE_DEVICE_ALLOC environment variables from the cm_test_all_sandia builds where UVM is enabled as the default space for Cuda device.
This fixes #636.
To avoid fencing inside a loop, in SPTRSV and SPILUK I replaced some host mirrors with HostSpace views. The weird thing about this case was, I believe that some small UVM views were placed on the same page, so when one view was accessed on device, the other view also became inaccessible on host without a fence. This is why a fence would have been required each iteration.
kokkos-dev2 spot check (the one failure is due to #645):
PASSED TESTS
clang-8.0-Pthread_Serial-release …
=> Fix UVM errors (generally, missing fences) in several places

perf_test/sparse/KokkosSparse_spmv_struct_tuning.cpp, src/impl/tpls/KokkosSparse_spmv_tpl_spec_avail.hpp, src/impl/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp, src/sparse/impl/KokkosSparse_spmv_spec.hpp, unit_test/sparse/Test_Sparse_spmv.hpp
Adding cusparse backend for SpMV to allow users to benefit from latest improvement in nvidia code.
This will potentially provide better performance across different GPU architectures as it is complicated to tune the SpMV kernel for all graphic cards and compute versions.
The support will be provided for cuda 9.2 and 10 to begin with.
=> Spmv cusparse tpl

unit_test/sparse/Test_Sparse_block_gauss_seidel.hpp
(an example of #478, which is incorrect integer division with rounding up)
This caused the X vector to have the wrong length. I replicated #648 locally and checked that this fixed it.
RIDE:
PASSED TESTS
cuda-10.1.105-Cuda_OpenMP-release build_time=541 run_time=398
cuda-10.1.105-Cuda_Serial-release build_time=551 run_time=508
cuda-9.2.88-Cuda_OpenMP-release build_time=531 run_time=545
cuda-9.2.88-Cuda_Serial-release build_time=571 run_time=647
gcc-6.4.0-OpenMP_Serial-release build_time=207 run_time=382
gcc-7.2.0-OpenMP-release build_time=130 run_time=126
gcc-7.2.0-OpenMP_Serial-release build_time=183 run_time=356
gcc-7.2.0-Serial-release build_time=122 run_time=226 …
=> Fixed block row formula in block GS test (Fix #648)

src/batched/KokkosBatched_Gemm_Serial_Impl.hpp, src/batched/KokkosBatched_Gemv_Serial_Impl.hpp, src/batched/KokkosBatched_LU_Serial_Impl.hpp, src/batched/KokkosBatched_Trsm_Serial_Impl.hpp, src/batched/KokkosBatched_Util.hpp, src/batched/KokkosBatched_Vector_SIMD_View.hpp
This corresponds to trilinos 6959.
https://github.com/trilinos/Trilinos/issues/6957#issuecomment-594785867
=> KokkosBatched - PR to match trilinos 6959

src/CMakeLists.txt
Missing alias `Kokkos::kokkoskernels` for in-tree builds. Addresses issue #621.
=> Add missing alias library/match Wiki directions

scripts/cm_test_all_sandia
addresses -Werror with newer armclang not seen in previous versions
=> cm_test_all_sandia: temporarily remove -Werror from armclang on mayer

src/impl/tpls/KokkosBlas_trtri_tpl_spec_avail.hpp
@ndellingwood: Thank you for the detailed bug report!
This patch fixes the `gcc/5.3 OpenMP Build`. Would you check that it fixes the `clang/7+cuda/9.2 Cuda_OpenMP Build` as well?
=> trtri patch

src/sparse/KokkosSparse_CrsMatrix.hpp
Replace "execution_space" with "device_t" for the StaticCrsGraph typedef inside CrsMatrix. This is important for when the device type uses a different memory space than the default for the exec space (which Tpetra will want to do with CudaSpace soon).
kokkos-dev2:
PASSED TESTS
clang-8.0-Pthread_Serial-release build_time=68 run_time=373
cuda-10.1-Cuda_OpenMP-release build_time=246 run_time=325
cuda-9.2-Cuda_Serial-release build_time=309 run_time=435
gcc-7.3.0-OpenMP-release build_time=54 run_time=374
gcc-7.3.0-Pthread-release build_time=58 run_time=203
gcc-8.3.0-Serial-release build_time=54 run_time=193
gcc-9.1-OpenMP-release build_time=78 run_time=195
gcc-9.1-Serial-release …
=> Fix #665 (Graph's device type inside CrsMatrix)

scripts/cm_test_all_sandia, scripts/spack/kokkos-dev-2.packages.yaml
This allows spack builds to be invoked instead of the usual tests.  Tests are invoked in exactly the same way except that the `--spack` option is given invokes Spack.
=> Initial testing infrastructure for Spack

src/common/KokkosKernels_IOUtils.hpp
**Description:**
This PR fixes two problems with the diagonally-dominant matrices generated by the kk_generate_diagonally_dominant_sparse_matrix function. So the new function makes sure the following:
1. Each row has at least one nonzero entry. In the case there is exactly one nonzero entry, it is the diagonal entry. This makes sure all diagonal entries have nonzero values.
2. The entries in each row are unique, i.e., there are no duplicate entries.
**The respective issue:** 
https://github.com/kokkos/kokkos-kernels/issues/678
**Testing results:**
```
[sacer@white30 kokkos-kernels]$ scripts/cm_test_all_sandia --spot-check --arch=Power8,Pascal60
Running on machine: white
M src/common/KokkosKernels_IOUtils.hpp
KokkosKernels Repository …
```
=> Fix Issue #678: kk_generate_diagonally_dominant_sparse_matrix

src/batched/KokkosBatched_Eigendecomposition_Serial_Internal.hpp, src/batched/KokkosBatched_Vector_SIMD_Arith.hpp, unit_test/batched/Test_Batched_TeamVectorQR.hpp
As seen in #691 , it reports three failure cases. 
1) With TPL, the code goes into my test code. This part is work-in-progress and it is better not to be included in the test. Anyway, I fixed it. 
2) QR is failed. This turns out that some random matrices are badly conditioned and it exceed the error threshold. I made the random matrices diagonal dominant and evaluate the correctness element-wisely so that the error does not proportionally increase with the problem size.
3) Vectorization on kokkos complex. When testing odd number of vector size (e.g., 3), the aggressive vectorization with complex is failed. This is supposed to be failed as the vectorization does not care about the correctness but it issued a vector instruction. Somehow this passes the test so far and it pops up now. I …
=> Fix the problem in QR.

perf_test/sparse/KokkosSparse_spgemm.cpp, perf_test/sparse/KokkosSparse_spgemm_jacobi.cpp, perf_test/sparse/KokkosSparse_spmv_struct.cpp, perf_test/sparse/KokkosSparse_sptrsv_superlu.cpp, src/batched/KokkosBatched_Eigendecomposition_Serial_Internal.hpp, src/batched/KokkosBatched_Householder_TeamVector_Internal.hpp, src/batched/KokkosBatched_Vector_SIMD.hpp, src/batched/KokkosBatched_Vector_SIMD_Arith.hpp, src/blas/impl/KokkosBlas3_gemm_impl.hpp, src/common/KokkosKernels_Macros.hpp, test_common/Test_Common_Sorting.hpp, unit_test/batched/Test_Batched_TeamVectorQR.hpp
See #696 for discussion. Fixes all Intel 17 builds on kokkos-dev2 (which only run in a full check, not spot check).
Fix warning on GCC <= 4.8.5 due to "pragma omp simd" being unrecognized. Made a generalized macro ``KOKKOSKERNELS_ENABLE_OMP_SIMD`` in a new file src/common/KokkosKernels_Macros.hpp. This is defined iff the pragma can be used (OpenMP enabled, CUDA not enabled, and compiler version is new enough if GCC).
Fix several  typedef shadow warnings in the spgemm, spgemm_jacobi, and spmv_struct perf tests. Also fix a weird unused variable warning in the serial eigendecomposition impl (is_U) which was used inside an assert (a macro) condition, but I guess that doesn't count as referencing it.
Add pthread support to spgemm and spgemm_jacobi perf tests. It was always enabled in the …
=> Intel 17 bug workaround, fix team QR random failure, fix several warnings

scripts/cm_test_all_sandia
On each machine, add the command(s) to load the full module environment (e.g. loading the local modulefile, running SEMS scripts) to the ``reload_modules.sh`` script for reproducing. This way, the reproducer instructions should work no matter what state the environment is in.
=> Fix705: load module environment in reproducer script

scripts/cm_test_all_sandia
Needed to use "eval $MODULE_ENVIRONMENT" instead of "$MODULE_ENVIRONMENT" to get the right behavior with compound commands, like "commandA ; commandB". Spot check is running now on kokkos-dev2 from a clean environment (which #706 broke, and it passed because the environment was already set up).
=> Fix module environment setup in cm_test_all_sandia

unit_test/batched/Test_Batched_SerialTrmm_Complex.hpp, unit_test/openmp/Test_OpenMP_Batched_SerialTrmm_Real.cpp
Fix typos in the complex and OpenMP+real test headers for SerialTRMM.
Running kokkos-dev2 spot check with double+complex_float, so that the code with the first issue is enabled.
=> Fix Serial TRMM build

scripts/cm_test_all_sandia
This is just a one-line change to cm_test_all_sandia. It fixes the reproducer instructions for bowman, which was saying "module intel/18... conflicts with loaded module...". This matches the actual behavior of the testing script, which purges module before each build.
=> Add "module purge" to reproducer reload_modules.sh

perf_test/blas/blas/KokkosBlas_perf_test.cpp, perf_test/blas/blas/KokkosBlas_trtri_perf_test.hpp, perf_test/blas/blas3/KokkosBlas3_perf_test.cpp, perf_test/blas/blas3/KokkosBlas3_trmm_perf_test.hpp
- Also fixes:
- `-r` command line options
- `__do_setup` for CUDA.
Fixes #727.
Running spot checks now.
=> Fix compile error for CUDA in TRMM and TRTRI perf tests

src/common/KokkosKernels_SparseUtils.hpp
``sort_crs_matrix`` uses avg degree, but there was no check that ``numRows != 0`` before dividing by it. This adds those checks.
This is a fix copied over from https://github.com/trilinos/Trilinos/pull/7464 .
Running kokkos-dev2 spot checks now.
=> Fix divide by zero in sort_crs_matrix, for 0 rows

perf_test/blas/blas/KokkosBlas_perf_test.cpp, perf_test/blas/blas/KokkosBlas_trtri_perf_test.hpp, perf_test/blas/blas3/KokkosBlas3_perf_test.cpp, perf_test/blas/blas3/KokkosBlas3_trmm_perf_test.hpp
perf_test/blas:
- Fix -b and -e options.
- Always print device.
- Ifdef serial routines to only run on host.
- Initialize trmm_args.alpha.
```
<snip>
?? build/
?? testing/
KokkosKernels Repository Status:  d9819c39cbdd163583397ee5a964e65ca5f0acdf perf_test/blas:
Kokkos Repository Status:  794c6df49008102b3237ad4f11e05f0aba89e021 Merge pull request #2997 from jjwilke/amd-zen-flags
Going to test compilers:  gcc/6.4.0 gcc/7.2.0 ibm/16.1.1 cuda/9.2.88 cuda/10.1.105
<snip>
PASSED TESTS
cuda-10.1.105-Cuda_OpenMP-release build_time=639 run_time=172
cuda-10.1.105-Cuda_Serial-release build_time=587 run_time=187 …
```
=> TRMM and TRTRI perf test bug fixes and improvements

src/sparse/KokkosSparse_spadd.hpp, src/sparse/KokkosSparse_spgemm_numeric.hpp
Also fix the static_assert messages in spgemm_numeric to say they're in numeric, not symbolic.
kokkos-dev2:
PASSED TESTS
clang-8.0-Cuda_OpenMP-release build_time=353 run_time=85
clang-8.0-Pthread_Serial-release build_time=127 run_time=49
clang-9.0.0-Pthread-release build_time=83 run_time=24
clang-9.0.0-Serial-release build_time=89 run_time=24
cuda-10.1-Cuda_OpenMP-release build_time=445 run_time=84
cuda-9.2-Cuda_Serial-release build_time=438 run_time=97
gcc-4.8.4-OpenMP-release build_time=76 run_time=27
gcc-7.3.0-OpenMP-release build_time=95 run_time=26
gcc-7.3.0-Pthread-release build_time=79 run_time=24
gcc-8.3.0-Serial-release build_time=89 run_time=25
gcc-9.1-OpenMP-release …
=> Allow const-valued C rowmap in spgemm/add numeric (Fix #744)

example/wiki/sparse/CMakeLists.txt, example/wiki/sparse/KokkosSparse_wiki_spadd.cpp, example/wiki/sparse/KokkosSparse_wiki_spgemm.cpp, example/wiki/sparse/KokkosSparse_wiki_spmv.cpp, src/sparse/KokkosSparse_spadd.hpp, src/sparse/KokkosSparse_spgemm.hpp, src/sparse/KokkosSparse_spgemm_numeric.hpp
@srajama1 @seheracer 
I would like to provide a simplified SpGEMM interface, it only requires the CrsMatrices (A, B and C), the kernel handle and flags for the potential transposition of A and/or B.
The proposed interface wraps both symbolic and numeric calls as it is a fairly common use case (typically need to do so at least the first time around).
I am also adding an example that I want to put in the wiki once/if this PR merges, it simplifies the example and actually compiles and run.
Finally I am not sure how we want to test this? Right now I only have the wiki example as this is simply an interface that does not add any algorithmic component but I could add something in the SpGEMM unit test too?
=> Simplified SpADD/SpGEMM interface

perf_test/sparse/KokkosSparse_sptrsv_cholmod.cpp, perf_test/sparse/KokkosSparse_sptrsv_superlu.cpp, src/common/KokkosKernels_Handle.hpp, src/sparse/KokkosSparse_sptrsv_cholmod.hpp, src/sparse/KokkosSparse_sptrsv_handle.hpp, src/sparse/KokkosSparse_sptrsv_superlu.hpp, src/sparse/KokkosSparse_sptrsv_supernode.hpp, src/sparse/impl/KokkosSparse_sptrsv_solve_impl.hpp
This PR
- adds "partitioned-inverse" option based on SpMV through Cholmod interface
- merge some changes for improving performance
=> Supernode-based SpTrsv updates

scripts/cm_test_all_sandia
Disable pgi and intel toolchains that have been resulting in unit test failures.
=> scripts/cm_test_all_sandia: Disable failing toolchains

perf_test/sparse/KokkosSparse_spmv_merge.cpp
This way, times are reported in seconds. Since no units are printed this is what the user would expect to see.
=> Fix time reporting in SPMV merge-path test: don't scale times by 0.001

perf_test/sparse/KokkosSparse_run_spgemm.hpp, src/common/KokkosKernels_HashmapAccumulator.hpp, src/common/KokkosKernels_Utils.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_compression.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_kkmem.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_seq.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_speed.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_symbolic.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_triangle.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_triangle_no_compression.hpp, src/sparse/impl/KokkosSparse_spgemm_jacobi_sparseacc_impl.hpp, src/sparse/impl/KokkosSparse_spgemm_symbolic_spec.hpp, unit_test/sparse/Test_Sparse_spgemm.hpp
The following changes were made to the HashmapAccumulator class:
1. `max_value_size` changed to `private` member `__max_value_size`.
2. `hash_key_size` was removed.
3. `used_size` was removed.
4. Hashes are now computed within the `HashmapAccumulator` insertion routines:
- `__hashOpRHS` was added as a `private` member. 
- `__compute_hash` was added as a `private` member. This function is selected at compile time via a templated argument to the `HashmapAccumulator` constructor.
- `vector_atomic_insert_into_hash_mergeAdd_with_team_level_list_length` does not compute hashes internally due to the special use-case in `KokkosSparse_spgemm_impl_speed.hpp:operator GPUTag`.
Fixes #508.
```
<snip>
?? build/
?? testing/
KokkosKernels Repository …
```
=> First iteration of HashmapAccumulator cleanup

src/impl/tpls/KokkosBlas1_iamax_tpl_spec_avail.hpp, src/impl/tpls/KokkosBlas1_iamax_tpl_spec_decl.hpp, src/impl/tpls/KokkosBlas1_scal_tpl_spec_avail.hpp, src/impl/tpls/KokkosBlas1_scal_tpl_spec_decl.hpp
Addressing #758. This is needed by ADELUS and GEMMA.
=> Add UVM specializations for iamax and scal

src/batched/KokkosBatched_Copy_Internal.hpp
Some utility functions can have the same thread distributions. To match the distribution, this change is required and it can remove team barrier when copy and set identity is used in a sequence. This is matching PR with https://github.com/trilinos/Trilinos/pull/7738.
=> KokkosBatched - copy and set identity

unit_test/sparse/Test_Sparse_block_gauss_seidel.hpp
so that tests don't time out. Decreased number of rows by 4x, and entries per row by a third.
In a build with -g, non optimized, and Kokkos
debug, this reduced the time to run all block GS tests from 43s to 3.2s.
I don't think the test coverage is any worse, and anyway block GS is not used anywhere currently.
PASSED TESTS
clang-8.0-Cuda_OpenMP-release build_time=712 run_time=438
clang-8.0-Pthread_Serial-release build_time=223 run_time=128
clang-9.0.0-Pthread-release build_time=131 run_time=58
clang-9.0.0-Serial-release build_time=136 run_time=51
cuda-10.1-Cuda_OpenMP-release build_time=976 run_time=149
cuda-9.2-Cuda_Serial-release build_time=899 run_time=165 …
=> Shrink size of block GS test matrix

perf_test/sparse/KokkosSparse_run_spadd.hpp, src/sparse/KokkosSparse_spadd.hpp, src/sparse/KokkosSparse_spadd_handle.hpp, unit_test/sparse/Test_Sparse_spadd.hpp
- Remove "max_nnz_in_result" and its getter/setter from SpADD handle. It was really a duplicate of "c_nnz". Max is a bad name for this since it is not an upper bound, it is always exact. This will need to be propagated to Tpetra_MatrixMatrix_def.hpp when we do promotion.
- Remove team size/vector length stuff from SpADD handle, since SpADD only uses range policy. This was just copied from SpGEMM handle without needing it
- No longer require C's scalar values to be zero-initialized when they are passed in (#694)
- If A and/or B have unmerged rows (aka repeated column in a row), the resulting C is now always merged. Before, it would produce the correct sum but could only merge one entry from A and one entry from B. Now, it can merge an arbitrary number of entries from A and B (#685)
- …
=> Cleanup spadd (#685, #694)

unit_test/batched/Test_Batched_SerialTrmm.hpp, unit_test/batched/Test_Batched_SerialTrmm_Complex.hpp, unit_test/batched/Test_Batched_SerialTrtri.hpp, unit_test/batched/Test_Batched_SerialTrtri_Complex.hpp
* Reduce the default batch size from 1024 to 512.
* For complex scalars, use a batch size of 128.
```
?? build-develop/
?? build-issue-508/
?? build-issue-757/
?? build.750fe245/
?? build/
?? do-cmake.sh
?? do-test.sh
?? install-develop/
?? install-issue-757/
?? issue-727/
?? testing/
KokkosKernels Repository Status:  c7f7f483e36b14bb255d14dc1b95e51b81060daa unit_test/batched: Reduce batch size for trmm and trtri
Kokkos Repository Status:  b973b126183f6ea756c7b02591cecaa445e85a8f Merge pull request #3158 from masterleinad/fIx_hip_abort_warning
Going to test compilers:  gcc/7.3.0
Testing compiler gcc/7.3.0
Starting job gcc-7.3.0-OpenMP-release
kokkos devices: OpenMP
kokkos arch: SNB,Volta70
kokkos options: disable_deprecated_code
kokkos …
```
=> Reduce batched trmm and trtri unit test sizes

src/common/KokkosKernels_SimpleUtils.hpp, unit_test/sparse/Test_Sparse_spgemm.hpp, unit_test/sparse/Test_Sparse_spgemm_jacobi.hpp
This PR replaces the absolute error with the relative error computed during the spgemm and jacobi tests. This need was arisen when the tests of the new jacobi kernel failed on float types. This was more of an issue for jacobi because the values of the input matrix entries are much larger for the jacobi tests due to using diagonally dominant matrices as input. 
Testing:
kokkos-kernels/scripts/cm_test_all_sandia --spot-check
```
PASSED TESTS
clang-8.0-Cuda_OpenMP-release build_time=623 run_time=152
clang-8.0-Pthread_Serial-release build_time=206 run_time=97
clang-9.0.0-Pthread-release build_time=121 run_time=44
clang-9.0.0-Serial-release build_time=128 run_time=51 …
```
=> Use relative errors in the spgemm and jacobi tests 

cm_generate_makefile.bash
Line 583 was doing ``$(ls $KOKKOS_PATH)``, which was trying to interpret
the results of the ls as a command. Since kokkos always contains ``algorithms, bin, ...``,
it said something like ``error: command "algorithms" not found``.
Since the command is run in a subshell, this wasn't a fatal error, but the output makes it look like one.
This line can just be removed since
the check for existence of ``$KOKKOS_PATH/CMakeLists.txt`` also implies that
``$KOKKOS_PATH`` exists.
@ndellingwood If I misunderstood the intent of this line, I'm sure I could come up
with a way to do the same thing but avoid the bash error.
PASSED TESTS
clang-8.0-Cuda_OpenMP-release build_time=659 run_time=133 …
=> Remove bash error from cm_generate_makefile

src/common/KokkosKernels_SimpleUtils.hpp
This PR fixes a minor bug in the relative error computation. With this change, the normalization is performed only when both of the entries have nonzero values.
This PR is expected to get rid of the failures in https://github.com/kokkos/kokkos-kernels/issues/780. 
**Spot check on white:**
```
PASSED TESTS
cuda-10.1.105-Cuda_OpenMP-release build_time=639 run_time=137
cuda-10.1.105-Cuda_Serial-release build_time=613 run_time=183
cuda-9.2.88-Cuda_OpenMP-release build_time=673 run_time=157
cuda-9.2.88-Cuda_Serial-release build_time=649 run_time=203
gcc-6.4.0-OpenMP_Serial-release build_time=221 run_time=138
gcc-7.2.0-OpenMP-release build_time=151 run_time=45 …
```
=> Fix the relative error computation (used in SpGEMM and Jacobi-fused SpGEMM tests)

src/sparse/impl/KokkosSparse_spgemm_numeric_spec.hpp, unit_test/sparse/Test_Sparse_spgemm.hpp
This PR adds the new SpGEMM interfaces to the unit tests in addition to the old interfaces. The new interfaces take three CrsMatrix objects as input while the old ones take up to nine Kokkos Views instead.
This integration required adding new ETI stuff for numeric, because the old numeric interface requires a **non-const** row_mapC, whereas the new interface requires a **const** row_mapC.
SpGEMM tests are passing on kokkos-dev-2 and white.
=> Add new SpGEMM interfaces to the unit tests

CHANGELOG.md, CMakeLists.txt
Part of Kokkos C++ Performance Portability Programming EcoSystem 3.2
Update Kokkos version macros to 3.2.0
=> Adding Changelog for Release 3.2.00

CMakeLists.txt
find_package should not be getting called for inline builds
This logic got lost in the install testing refactor. It was still working for Trilinos.
=> Fix install testing refactor for inline builds

src/Kokkos_ArithTraits.hpp
The goal is to replace undefined calls to math functions with the HIP backend.
Hopefully the pre-processor logic makes sense?
=> HIP: fix ArithTraits to support HIP backend, see issue #807

src/batched/KokkosBatched_Util.hpp, test_common/Test_Common_ArithTraits.hpp
I checked the compiling failure owing to the absence of hip space specialization and this PR fix the issue. 
One compile failure is due to complex abs which should be excluded from hip compiling as like cuda.
To compile KokkosKernels, I temporarily modified Kokkos as described in
https://github.com/kokkos/kokkos/issues/3386#issuecomment-693007713
This does not test with spotcheck as the spotcheck does not include an amd machine.
=> KokkosBatched - hip specialization

scripts/cm_test_all_sandia
Broken for absolute paths, causing update_libs.sh to not be called on some systems
=> cm_test_all_sandia: fix determination of CM_ALL_SCRIPT_PATH var

src/common/KokkosKernels_SparseUtils.hpp, src/graph/KokkosGraph_ExplicitCoarsening.hpp, src/graph/impl/KokkosGraph_Distance1Color_impl.hpp, src/graph/impl/KokkosGraph_ExplicitCoarsening_impl.hpp, src/sparse/impl/KokkosSparse_cluster_gauss_seidel_impl.hpp
This adds explicit graph coarsening as a standalone feature (given a graph and coarse labels, construct a new graph were all vertices of a given label are collapsed). This has been buried in Cluster Gauss-Seidel for a while but Gordon Moon would like to use it, so this provides a clean interface for it. There isn't a unit test for this but it's tested through cluster Gauss-Seidel.
I also added sort_and_merge_crs_graph() to SparseUtils, since the coarsened graph can optionally be merged. This shares most code with sort_and_merge_crs_matrix(), but doesn't process values, and it takes rowmap/colinds views as input (using StaticCrsGraph would have been too messy since it forces the rowmap to be const-valued).
PASSED TESTS …
=> Factor out coarsening

perf_test/sparse/KokkosSparse_spmv_struct_tuning.cpp, src/sparse/impl/KokkosSparse_spgemm_cuSPARSE_impl.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_def.hpp
Fix for spmv_struct_tunning perf_test that uses cusparse SpMV.
Temporary fix for spGEMM, this will require rewritting the interface for it to work properly but for the moment everything builds correctly.
=> cuSPARSE 11: fix spgemm and spmv_struct_tunning, see issue #803

unit_test/sparse/Test_Sparse_spmv.hpp
Add tests for SpMV modes conjugate (C), transpose (T) and conjugate transpose (H). The new tests use the same matrix as the existing normal (N) mode test. Added 1D and 2D vector versions but didn't touch the structured spmv tests, they may still need more tests.
PASSED TESTS
clang-8.0-Cuda_OpenMP-release build_time=812 run_time=108
clang-8.0-Pthread_Serial-release build_time=223 run_time=154
clang-9.0.0-Pthread-release build_time=133 run_time=67
clang-9.0.0-Serial-release build_time=141 run_time=52
cuda-10.1-Cuda_OpenMP-release build_time=918 run_time=130
cuda-11.0-Cuda_OpenMP-release build_time=1157 run_time=1177
cuda-9.2-Cuda_Serial-release build_time=943 run_time=196 …
=> Test spmv transpose (Fix #829)

src/impl/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp, src/sparse/KokkosSparse_spmv.hpp, src/sparse/impl/KokkosSparse_spgemm_cuSPARSE_impl.hpp, src/sparse/impl/KokkosSparse_spmv_spec.hpp, src/sparse/impl/KokkosSparse_sptrsv_cuSPARSE_impl.hpp, unit_test/sparse/Test_Sparse_spmv.hpp
- Improve SpMV unit test:
- generate random complex values with nonzero imaginary component
- catch exceptions in spmv
- Add "spmv_native" support to the cusparse spmv file (this calls KokkosKernels spmv)
- Fall back to native for mode 'C' (which cusparse doesn't have), or modes 'T'/'H' for CUDA 9 (fixing #833)
- Fix some minor type casts/checks in spgemm/sptrsv cusparse wrappers - now those builds and tests succeed with all 4 possible combinations of offset/ordinal width
=> Add fallback condition to use spmv_native when cuSPARSE won't work

src/sparse/KokkosSparse_sptrsv_supernode.hpp
This PR integrates the "batched" TRTRI & TRTRM from [PR #697](https://github.com/kokkos/kokkos-kernels/pull/697) for sptrsv-supernode setup (it still runs on host, but now uses parallel-for for smaller blocks).
=> Use "batched" TRTRI & TRMM for Supernode-sptrsv setup

src/common/KokkosKernels_Sorting.hpp, src/graph/KokkosGraph_Distance1ColorHandle.hpp, src/sparse/impl/KokkosSparse_cluster_gauss_seidel_impl.hpp, src/sparse/impl/KokkosSparse_gauss_seidel_impl.hpp, src/sparse/impl/KokkosSparse_partitioning_impl.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_kkmem.hpp, src/sparse/impl/KokkosSparse_spgemm_jacobi_sparseacc_impl.hpp
Resolves messages of form:
error: implicit capture of ‘this’ via ‘[=]’ is deprecated in C++20
[-Werror=deprecated]
=> Fixes -Werror for gcc with c++20

src/blas/impl/KokkosBlas_gesv_spec.hpp
We don't have fallback implementation for GESV. If no TPL provides
it, throw an exception. Partial fix for #837 - I would like to write a serial fallback when I get some time.
PASSED TESTS
clang-8.0-Cuda_OpenMP-release build_time=711 run_time=135
clang-8.0-Pthread_Serial-release build_time=221 run_time=146
clang-9.0.0-Pthread-release build_time=138 run_time=65
clang-9.0.0-Serial-release build_time=151 run_time=53
cuda-10.1-Cuda_OpenMP-release build_time=918 run_time=136
cuda-11.0-Cuda_OpenMP-release build_time=973 run_time=136
cuda-9.2-Cuda_Serial-release build_time=921 run_time=197
gcc-7.3.0-OpenMP-release build_time=150 run_time=47
gcc-7.3.0-Pthread-release build_time=125 …
=> Throw an exception if BLAS GESV is not enabled (#837)

src/common/KokkosKernels_BitUtils.hpp, src/sparse/KokkosSparse_CrsMatrix.hpp
A couple of issues have appeared in the HIP build using rocm/3.8.0, nothing bit though
1. typo: Kokkos::HIP instead of Kokkos::Experimental::HIP
2. __ffsll is not overloaded in HIP so need to cast the input correctly
=> HIP: fixing a couple of issues on AMD

perf_test/graph/KokkosGraph_color.cpp
I missed this one in #828. I built with this PR on caraway and the D1 coloring perftest does seem to work (tried COLORING_SERIAL, COLORING_VBBIT, COLORING_EB on a pretty big graph). Also running spot check on kokkos-dev2 just in case.
=> Add hip support to dist-1 coloring perftest

src/Kokkos_ArithTraits.hpp, src/batched/KokkosBatched_Gemm_TeamVector_Internal.hpp, src/batched/KokkosBatched_Gemm_Team_Internal.hpp, src/batched/KokkosBatched_InnerGemmFixC_Serial_Impl.hpp, unit_test/batched/Test_Batched_SerialGemm.hpp, unit_test/batched/Test_Batched_TeamGemm.hpp, unit_test/batched/Test_Batched_TeamVectorGemm.hpp
Related to https://github.com/kokkos/kokkos/pull/3593
It was decided to remove implicit conversions from half_t -> T to prevent implicit downcasting to `half_t` in mixed precision expressions.
=> Half_t explicit conversions

src/Kokkos_ArithTraits.hpp, src/Kokkos_InnerProductSpaceTraits.hpp
`isinf` and `isnan` are not defined for long double with HIP.
The input parameter is casted to avoid ambiguous function call.
The function is also defined as __device __ so it needs to be decorated with KOKKOS_FORCE_INLINE_FUNCTION.
@crtrott @brian-kelley any idea why this issue would only appear on Tulip?
It is using rocm-3.8.0 so I am not sure why this would not be an issue on caraway?
Maybe because of the gcc toolchain?
=> New issue with HIP and Kokkos_ArithTraits

example/wiki/graph/CMakeLists.txt, example/wiki/graph/KokkosGraph_wiki_9pt_stencil.hpp, example/wiki/graph/KokkosGraph_wiki_rcm.cpp, src/graph/KokkosGraph_RCM.hpp, src/graph/impl/KokkosGraph_BFS_impl.hpp, unit_test/cuda/Test_Cuda_Graph_rcm.cpp, unit_test/graph/Test_Graph_rcm.hpp, unit_test/hip/Test_HIP_Graph_rcm.cpp, unit_test/openmp/Test_OpenMP_Graph_rcm.cpp, unit_test/serial/Test_Serial_Graph_rcm.cpp, unit_test/threads/Test_Threads_Graph_rcm.cpp
Add reverse Cuthill-McKee reordering to replace the broken one that I took out of cluster Gauss-Seidel impl. Needed by MueLu.
Has unit test and wiki example.
PASSED TESTS
clang-8.0-Cuda_OpenMP-release build_time=751 run_time=141
clang-8.0-Pthread_Serial-release build_time=241 run_time=133
clang-9.0.0-Pthread-release build_time=153 run_time=62
clang-9.0.0-Serial-release build_time=166 run_time=50
cuda-10.1-Cuda_OpenMP-release build_time=912 run_time=144
cuda-11.0-Cuda_OpenMP-release build_time=930 run_time=143
cuda-9.2-Cuda_Serial-release build_time=881 run_time=229
gcc-7.3.0-OpenMP-release build_time=166 run_time=48
gcc-7.3.0-Pthread-release build_time=135 run_time=62 …
=> Add permanent RCM reordering interface, and a basic serial implementation

perf_test/blas/blas3/KokkosBlas3_common.hpp, perf_test/blas/blas3/KokkosBlas3_gemm_perf_test.hpp, perf_test/blas/blas3/KokkosBlas3_perf_test.cpp, perf_test/blas/blas3/KokkosBlas3_trmm_perf_test.hpp, perf_test/blas/blas3/README.md, src/blas/impl/KokkosBlas3_trmm_spec.hpp
Adds support for timing batched gemm interfaces to inform implementation of new gemm interface.
Depends on #794. #794 should be merged first.
TODOs:
=> Add batched gemm performance tests

src/graph/KokkosGraph_Distance1ColorHandle.hpp
In PR #828, I changed the default D1 coloring algorithm for CUDA
from EB to VBBIT. Although VBBIT is usually faster for balanced/regular
problems, it is causing an increase in MTGS + GMRES iterations
in some Ifpack2 tests compared to EB. This causes random failures
since the tests expect convergence within a certain number of iters.
This PR puts back the old defaults (SERIAL for Serial, VB for parallel CPU, and EB for GPU).
This fixes the Ifpack2 tests on CUDA. A long term solution could be to let
Ifpack2 Relaxation's parameter list select a coloring algorithm, then EB could be
selected for these tests and VBBIT could be the general default for coloring.
=> Restore distance-1 default algos from 3.2.0

src/sparse/KokkosSparse_spadd.hpp
Was causing linker errors on IBM xl (see https://github.com/trilinos/Trilinos/issues/8418 and https://github.com/trilinos/Trilinos/pull/8443 for all details). This is just bringing those changes to KokkosKernels. I am running spot checks for this but I don't expect any issues since I've built serial/cuda/openmp on my workstation and serial on vortex.
=> spadd: remove static constexpr member var

src/impl/tpls/KokkosBlas1_axpby_tpl_spec_avail.hpp, src/impl/tpls/KokkosBlas1_dot_tpl_spec_avail.hpp, src/impl/tpls/KokkosBlas1_iamax_tpl_spec_avail.hpp, src/impl/tpls/KokkosBlas1_nrm1_tpl_spec_avail.hpp, src/impl/tpls/KokkosBlas1_nrm2_tpl_spec_avail.hpp, src/impl/tpls/KokkosBlas1_nrminf_tpl_spec_avail.hpp, src/impl/tpls/KokkosBlas1_scal_tpl_spec_avail.hpp, src/impl/tpls/KokkosBlas1_scal_tpl_spec_decl.hpp, src/impl/tpls/KokkosBlas2_gemv_tpl_spec_avail.hpp, src/impl/tpls/KokkosBlas3_gemm_tpl_spec_avail.hpp, src/impl/tpls/KokkosBlas3_trmm_tpl_spec_avail.hpp, src/impl/tpls/KokkosBlas3_trsm_tpl_spec_avail.hpp, src/impl/tpls/KokkosBlas_gesv_tpl_spec_avail.hpp, src/impl/tpls/KokkosBlas_trtri_tpl_spec_avail.hpp, src/impl/tpls/KokkosSparse_spmv_tpl_spec_avail.hpp
``*_tpl_spec_decl.hpp`` files instantiate all type combinations allowed by the TPL, even those which are not enabled in KokkosKernels ETI type. ``*_tpl_spec_avail.hpp`` was restricting to ETI type combinations, but they should match what is actually getting instantiated in *_spec__decl.
If a user called with non-ETI types, they would silently get the Kokkos implementation instantiated for them on-demand, even though the TPL wrapper was actually compiled into libkokkoskernels.
Regular checks:
PASSED TESTS
clang-8.0-Cuda_OpenMP-release build_time=736 run_time=113
clang-8.0-Pthread_Serial-release build_time=245 run_time=134
clang-9.0.0-Pthread-release build_time=155 run_time=63 …
=> Make tpl avail type combinations match tpl decl

src/common/KokkosKernels_SparseUtils.hpp, test_common/Test_Common_Sorting.hpp
Fixes a bug found by Mike Gilbert on slack.
Also add a test that replicated the issue.
PASSED TESTS
clang-8.0-Cuda_OpenMP-release build_time=730 run_time=142
clang-8.0-Pthread_Serial-release build_time=242 run_time=132
clang-9.0.0-Pthread-release build_time=156 run_time=61
clang-9.0.0-Serial-release build_time=164 run_time=50
cuda-10.1-Cuda_OpenMP-release build_time=911 run_time=144
cuda-11.0-Cuda_OpenMP-release build_time=924 run_time=142
cuda-9.2-Cuda_Serial-release build_time=878 run_time=226
gcc-7.3.0-OpenMP-release build_time=166 run_time=47
gcc-7.3.0-Pthread-release build_time=144 run_time=62
gcc-8.3.0-Serial-release build_time=164 run_time=52
gcc-9.1-OpenMP-release …
=> Fix >1024 team size error in sort_crs_*

src/sparse/impl/KokkosSparse_spiluk_symbolic_impl.hpp
PR matching changes to kokkos-kernels needed for trilinos/Trilinos#8547
=> Fixing seg fault with empty matrix in kspiluk

src/impl/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp, src/sparse/KokkosSparse_spmv.hpp
This was causing the entire native impl to get instantiated once
every time KokkosSparse_spmv.hpp was included.
This fix is also getting patched into the 3.3.1 Kokkos promotion since the code
size was causing a TrilinosCouplings test to run out of device memory.
Intel 17 only failed because it couldn't validate the license. This is with ``--spot-check-tpls --with-scalars=double,complex_double``.
PASSED TESTS
clang-8.0-Cuda_OpenMP-release build_time=736 run_time=144
clang-8.0-Pthread_Serial-release build_time=248 run_time=135
clang-9.0.0-Pthread-release build_time=152 run_time=64
clang-9.0.0-Serial-release build_time=169 run_time=51
cuda-10.1-Cuda_OpenMP-release build_time=969 …
=> Move spmv fallback branch out of TPL layer

perf_test/sparse/spmv/OpenMPSmartStatic_SPMV.hpp, src/sparse/impl/KokkosSparse_spmv_impl_omp.hpp
With the new check we are making sure that the IntelClang compilers that do not define this function (icpx/dpc++) are not generating build errors in the OpenMP backend (would likely be a problem for OpenMP Target too since it uses the same compilers).
This fixes an issue in Kokkos Kernels on the iris/yarrow platforms see issue #877 , a more permanent solution will be available with the c++20 standard which defines: `std::assume_aligned<>()`.
This was tested on iris/yarrow, will now run checks on kokkos-dev2.
=> IntelClang guarding __assume_aligned with !defined(__clang__)

test_common/KokkosKernels_MatrixConverter.cpp
Small change but we no longer get an error while running this.
=> Matrix Converter: fixing issue with deallocation after Kokkos::fininalize()

src/sparse/KokkosSparse_spgemm.hpp
Fix the number of columns of C in the simplified SpGEMM interface.
```
PASSED TESTS
clang-8.0-Cuda_OpenMP-release build_time=731 run_time=142
clang-8.0-Pthread_Serial-release build_time=246 run_time=132
clang-9.0.0-Pthread-release build_time=157 run_time=61
clang-9.0.0-Serial-release build_time=167 run_time=49
cuda-10.1-Cuda_OpenMP-release build_time=927 run_time=144
cuda-11.0-Cuda_OpenMP-release build_time=938 run_time=144
cuda-9.2-Cuda_Serial-release build_time=896 run_time=225
gcc-7.3.0-OpenMP-release build_time=173 run_time=47
gcc-7.3.0-Pthread-release build_time=144 run_time=62
gcc-8.3.0-Serial-release build_time=172 run_time=53
gcc-9.1-OpenMP-release build_time=222 …
```
=> Construct SpGEMM C with correct #cols

src/sparse/KokkosSparse_sptrsv_handle.hpp, src/sparse/impl/KokkosSparse_sptrsv_solve_impl.hpp
Fix SpMV link errors in a build with supernodal SpTRSV by using ``Device<exec, mem>`` as the device type for matrices and vectors, so that ETI type combinations are used. This configuration now builds and passes all tests:
```
cmake \
-DKokkos_DIR=... \
-DCMAKE_CXX_FLAGS=-Wall \
-DKokkosKernels_ENABLE_TESTS=ON \
-DKokkosKernels_ENABLE_EXAMPLES:BOOL=ON \
-DKokkosKernels_ENABLE_TPL_CUSPARSE=OFF \
-DKokkosKernels_ENABLE_TPL_CUBLAS=OFF \
-DKokkosKernels_ENABLE_TPL_BLAS=ON \
-DKokkosKernels_ENABLE_TPL_CHOLMOD=ON \
-DKokkosKernels_ENABLE_TPL_SUPERLU=ON \
-DKokkosKernels_ENABLE_SUPERNODAL_SPTRSV=ON \
-DCMAKE_BUILD_TYPE=RELEASE \
../kokkos-kernels
```
=> Fixed supernodal SpTRSV build with serial+openmp+cuda

src/sparse/impl/KokkosSparse_sptrsv_solve_impl.hpp
One line follow up to #884 that makes the functor work_view_t typedefs all consistent. This change doesn't affect whether supernodal sptrsv build/tests succeed.
=> Make work_view_t typedef consistent

src/impl/KokkosKernels_helpers.hpp, src/impl/tpls/KokkosSparse_spmv_tpl_spec_avail.hpp, src/impl/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp, src/sparse/KokkosSparse_spmv.hpp
Support calling MKL spmv. Available for rank-1 X/Y, scalar = float/double/complex_float/complex_double, ordinal = int, offset = int, HostSpace.
To avoid needing specializations for both LayoutLeft/LayoutRight (no difference for rank-1 X/Y), change GetUnifiedLayout to always give LayoutLeft for contiguous rank-1 views.
This means we could start to replace separate LayoutLeft/LayoutRight instantiations with just LayoutLeft for other things that take rank-1 views (e.g. cusparse spmv).
=> Add MKL SpMV wrapper

src/sparse/impl/KokkosSparse_spmv_impl.hpp
The current spmv with transpose uses atomic updates and follows the generic interface with parallel for. This significantly lowers the performance as seen in https://github.com/trilinos/Trilinos/issues/8658.
This PR address the performance issue of serial implementation of spmv.
=> Serial code path for spmv

src/sparse/impl/KokkosSparse_spmv_impl.hpp
As reported in #896, the complex build somehow does not understand the memset and sizeof function in the nightly test. This replace the memset function with a for loop. I personally prefer memset as the function is simply vectorized but it turns out that some compilers are picky and it does not work with the kokkos complex. This PR is the fix for the problem but it may indicate that the compiler or kokkos complex has an inssue with sizeof function. The sizeof function should be able to figure out the data object size though.
=> KokkosSparse - fix for nightly test failure

src/graph/KokkosGraph_Distance1ColorHandle.hpp, src/graph/KokkosGraph_Distance2ColorHandle.hpp, src/graph/KokkosGraph_ExplicitCoarsening.hpp, src/graph/KokkosGraph_MIS2.hpp, unit_test/graph/Test_Graph_mis2.hpp
Fixes:
- When doing MIS2 coarsening with sort+merge, actually return the
sorted+merged graph instead of the raw coarsened one.
- Fix typo: ``std:cout`` -> ``std::cout`` (in verbose path of D1/D2 coloring), same as https://github.com/trilinos/Trilinos/pull/8859
- Set numClusters to 0 in MIS2 coarsening when graph has 0 vertices
Test coverage improvements, which verify the above fixes:
- Test MIS-2 based coarsening (fine graph -> labels) for zero row case
- Test explicit coarsening (fine graph, labels -> coarse graph), was not tested before
- Test with zero row case
- Test with and without compression (this PR also fixes that)
- The test graph actually does exercise compression e.g. the
uncompressed graph actually has duplicate entries per row.
=> Small but important fixes and testing coverage (mainly in graph coarsening)

src/sparse/KokkosSparse_sptrsv.hpp, src/sparse/KokkosSparse_sptrsv_superlu.hpp, src/sparse/KokkosSparse_sptrsv_supernode.hpp, src/sparse/impl/KokkosSparse_sptrsv_solve_impl.hpp, src/sparse/impl/KokkosSparse_sptrsv_symbolic_impl.hpp
This PR aims to reduce the SpTRSV symbolic time by keep track of nonzero entries in generate_supernodal_graph (using deep-copy of the whole vector can be expensive for a large matrix).
Spot-checks on White:
-  ../scripts/cm_test_all_sandia --spot-check --arch=Power8,Pascal60 --num=1
> #######################################################
PASSED TESTS
cuda-10.1.105-Cuda_OpenMP-release build_time=701 run_time=165
cuda-10.1.105-Cuda_Serial-release build_time=742 run_time=233
cuda-9.2.88-Cuda_OpenMP-release build_time=690 run_time=192
cuda-9.2.88-Cuda_Serial-release build_time=712 run_time=260
gcc-6.4.0-OpenMP_Serial-release build_time=243 run_time=171
gcc-7.2.0-OpenMP-release build_time=189 run_time=59
gcc-7.2.0-OpenMP_Serial-release …
=> Supernodal SpTRSV, improve symbolic performance

src/blas/impl/KokkosBlas1_nrm1_impl.hpp, src/impl/tpls/KokkosBlas1_nrminf_tpl_spec_avail.hpp, src/impl/tpls/KokkosBlas1_nrminf_tpl_spec_decl.hpp, test_common/KokkosKernels_TestUtils.hpp, unit_test/blas/Test_Blas1_abs.hpp, unit_test/blas/Test_Blas1_asum.hpp, unit_test/blas/Test_Blas1_axpby.hpp, unit_test/blas/Test_Blas1_axpy.hpp, unit_test/blas/Test_Blas1_dot.hpp, unit_test/blas/Test_Blas1_iamax.hpp, unit_test/blas/Test_Blas1_mult.hpp, unit_test/blas/Test_Blas1_nrm1.hpp, unit_test/blas/Test_Blas1_nrm2.hpp, unit_test/blas/Test_Blas1_nrm2_squared.hpp, unit_test/blas/Test_Blas1_nrminf.hpp, unit_test/blas/Test_Blas1_reciprocal.hpp, unit_test/blas/Test_Blas1_scal.hpp, unit_test/blas/Test_Blas1_sum.hpp, unit_test/blas/Test_Blas1_team_dot.hpp, unit_test/blas/Test_Blas1_team_nrm2.hpp, unit_test/blas/Test_Blas1_team_scal.hpp, unit_test/blas/Test_Blas1_team_update.hpp, unit_test/blas/Test_Blas1_update.hpp, unit_test/blas/Test_Blas2_gemv.hpp, unit_test/blas/Test_Blas2_team_gemv.hpp, unit_test/blas/Test_Blas3_gemm.hpp, unit_test/blas/Test_Blas3_trmm.hpp, unit_test/blas/Test_Blas3_trsm.hpp
- (#914) Made nrm1 compute the sum of all absolute real and imaginary parts
to match BLAS/MKL/CUBLAS behavior, rather than sum of magnitudes. Change its test to verify that - passes with both TPL and KokkosKernels impls now.
- Removed CUBLAS impl of nrminf (maximum magnitude). This was implemented in terms of i*amax (since cublas doesn't have nrminf), and was just returning the maximal element without applying abs to it. Rather than do the abs on host or in a 1-element RangePolicy, we might as well just use the KokkosKernels impl which computes the correct nrminf in a single parallel_reduce. Someone on the slack channel ran into this bug a while back.
- Improved blas unit tests
- verify each output element is correct, not just dotprod of output with itself
- for complex, create randomized …
=> Fixed nrm1 (#914), removed cublas nrminf, improved blas tests

perf_test/blas/blas3/KokkosBlas3_gemm_perf_test.hpp, src/batched/KokkosBatched_Vector_SIMD.hpp
- For GEMM, copy out LayoutRight SIMD sub-batches properly for
verification.
- The verification option for device is not correct.
It will always compare 0s from the HostMirror views since
the data was never copied to the host.
Related to #848.
=> perf_test/blas/blas3: Fix device verify

src/sparse/KokkosSparse_CrsMatrix.hpp, unit_test/sparse/Test_Sparse_CrsMatrix.hpp
Make CrsMatrix constructors taking StaticCrsGraph more permissive on the graph type (if the entries and rowmap views can be shallow copied, it will work). This allows CrsMatrix::HostMirror to be constructed using a CrsMatrix::StaticCrsGraphType::HostMirror (#917), which is needed by Tpetra.
Also add deep copy constructor for CrsMatrix at @lucbv suggestion. Takes a label and
any other CrsMatrix<...>, and will work as long as it has same scalar/index/offset types.
=> Fix #917: ctor CrsMat mirror with CrsGraph mirror

src/graph/impl/KokkosGraph_Distance1Color_impl.hpp
Using `new` and `delete` is not supported by all backends. Hence, this pull request allocates global memory instead. Scratch memory would potentially be more in line with the previous implementation but we can't use that for `RangePolicy`.
=> Workaround using new/delete in kernel code

src/batched/KokkosBatched_Eigendecomposition_Serial_Internal.hpp, src/batched/KokkosBatched_Eigendecomposition_TeamVector_Internal.hpp, unit_test/batched/Test_Batched_SerialEigendecomposition.hpp, unit_test/batched/Test_Batched_SerialEigendecomposition_Real.hpp, unit_test/batched/Test_Batched_TeamVectorEigendecomposition.hpp, unit_test/batched/Test_Batched_TeamVectorEigendecomposition_Real.hpp
so that users know it's not supported yet. Disable the unit tests for it.
Serial eigendecomposition on host with LAPACK enabled will still work.
This would at least tell users right away (like in #873) that they can't use it yet.
=> Add static_assert/throw in batched eigendecomp

.jenkins/nightly.groovy
I just noticed that the merge of https://github.com/kokkos/kokkos/pull/3809 broke the [HIP nightly builds](https://cloud.cees.ornl.gov/jenkins-ci/blue/organizations/jenkins/KokkosKernels/detail/KokkosKernels/84/pipeline/) on ORNL's Jenkins CI.
=> Fixup HIP nightly builds

src/sparse/impl/KokkosSparse_spmv_impl.hpp
CPUs always use RangePolicy, GPUs always use TeamPolicy. With a runtime branch, both paths are instantiated even though only one is ever taken. Replace with enable_if so that the not-taken branch never gets compiled.
This can have a pretty big impact on library size:
Serial+OpenMP+Cuda release: -8.5% (-31 MB)
Serial only: no change, I think the compiler is smart enough to do dead code elimination.
=> Prevent redundant spmv kernel instantiations (reduce library size)

cmake/KokkosKernels_config.h.in, unit_test/cuda/Test_Cuda_Batched.cpp
This is becoming increasingly necessary to check if code can be compiled on device or only on host.
This macro provides a simpler version to express that.
Also cleaning up an unused macro.
Next step will be to clean-up some code so that we start using it instead of the current
```c++
#if !defined(KOKKOS_ENABLE_CUDA) && !defined(KOKKOS_ENABLE_HIP)
host code
#endif
```
=> host only macro: adding macro to checks for any device backend

unit_test/batched/Test_Batched_SerialGemm.hpp, unit_test/batched/Test_Batched_SerialGemm_Real.hpp, unit_test/batched/Test_Batched_TeamGemm.hpp, unit_test/batched/Test_Batched_TeamGemm_Real.hpp, unit_test/batched/Test_Batched_TeamVectorGemm.hpp, unit_test/batched/Test_Batched_TeamVectorGemm_Real.hpp
With the merge of https://github.com/kokkos/kokkos/pull/3922, the _half functions can be removed from the batched gemm unit tests. 
These changes also update the gemm unit tests to compare against the vanilla gemm reference implementation in our test utils, rather than comparing results against the KokkosBatched implementations themselves.
All the formatting changes are from a pre-commit hook that applies clang-format using https://github.com/kokkos/kokkos-kernels/blob/master/.clang-format.
Fixes #846.
=> unit_test/batched: Remove *_half fns from gemm unit tests

src/sparse/impl/KokkosSparse_spmv_impl.hpp, unit_test/sparse/Test_Sparse_spmv.hpp
Mirrors fix to Trilinos: https://github.com/trilinos/Trilinos/pull/9074
Added a heavy test path for spmv (only on small matrices) that tests alpha, beta in {0, 1, -1, 2.5} to exercise all possible paths.
=> Fix serial spmv for beta -1. Add test to catch bug

src/graph/KokkosGraph_Distance1Color.hpp, src/graph/KokkosGraph_Distance1ColorHandle.hpp, src/graph/KokkosGraph_Distance2ColorHandle.hpp, src/graph/impl/KokkosGraph_Distance1Color_impl.hpp, src/graph/impl/KokkosGraph_Distance2Color_impl.hpp
These code changes allow KokkosKernels' coloring routines to accept partial colorings and prevent any previously-colored vertex from being recolored. These changes do not significantly impact the existing interface or performance of the coloring code, to my knowledge. Zoltan2's distributed coloring depends on these changes.
~/fork.kokkos-kernels-coloring/scripts/cm_test_all_sandia --kokkoskernels-path=/ascldap/users/ibogle/fork.kokkos-kernels-coloring/ --kokkos-path=/ascldap/users/ibogle/kokkos --arch=Power8,Kepler80 cuda/10.1.105 --spot-check
Running on machine: white
M src/graph/KokkosGraph_Distance1Color.hpp
M src/graph/KokkosGraph_Distance1ColorHandle.hpp
M src/graph/KokkosGraph_Distance2ColorHandle.hpp
M …
=> Added code to allow KokkosKernels coloring to accept partial colorings

perf_test/blas/blas3/CMakeLists.txt, perf_test/blas/blas3/KokkosBlas3_gemm_standalone_perf_test.cpp, src/blas/KokkosBlas3_gemm.hpp, unit_test/blas/Test_Blas3_gemm.hpp
Add a special code path to KokkosBlas::gemm for when B and C have only 1 column, and neither A or B are transposed. In this case, a KokkosBlas::gemv can be called instead and gets better performance.
See https://github.com/trilinos/Trilinos/issues/8923 for the original request, and #929 for more details. With this PR, ``KokkosBlas::gemm()`` now gets the better performance numbers from the last 2 columns of the table in #929 . The perf test command to measure these results (in perf_test/blas/blas3):
```
./KokkosBlas3_gemm_perf_test --cuda 0 --m 1000000 --n 1 --k 1 --repeat 1000
./KokkosBlas3_gemm_perf_test --cuda 0 --m 1000000 --n 50 --k 1 --repeat 1000
```
=> GEMM: call GEMV instead in certain cases

perf_test/sparse/KokkosSparse_spadd.cpp
Replacing the call to the offending function with the new function call that is not from the Impl namespace.
See issue #953
=> Deprecation: a deprecated function is called in the SpADD perf_test

src/blas/impl/KokkosBlas2_gemv_impl.hpp, src/sparse/KokkosSparse_spadd.hpp
Removes "error: implicit capture of ‘this’ via ‘[=]’ is deprecated in C++20"
=> Fix -Werror=deprecated errors with c++20 standard

src/blas/impl/KokkosBlas2_gemv_impl.hpp, test_common/KokkosKernels_TestUtils.hpp, unit_test/blas/Test_Blas2_gemv.hpp
This was silently succeeding on Volta but failed on Pascal. Running
under cuda-memcheck, or kokkos view bounds checking, on Volta showed the issue.
=> Fix invalid mem accesses in new GEMV kernel

src/sparse/impl/KokkosSparse_spiluk_symbolic_impl.hpp
This PR matches changes to kokkos-kernels needed for trilinos/Trilinos#9088:
- move sort operations in Ifpack2's RILUK compute phase to Kokkos Kernels spiluk_symbolic,
- explicitly create host mirror on host memory in Kokkos Kernels spiluk_symbolic to make sure it is running on host.
=> Add sort and make sure using host mirror on host memory in kspiluk_symbolic

src/sparse/KokkosSparse_CrsMatrix.hpp, unit_test/sparse/Test_Sparse_CrsMatrix.hpp
See #949. This was the only necessary KokkosKernels change to get Tpetra working on HIP (in https://github.com/trilinos/Trilinos/pull/9090).
=> Cherry pick #949: fix CrsMatrix raw ptr ctor

src/sparse/impl/KokkosSparse_spgemm_imp_outer.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_compression.hpp, src/sparse/impl/KokkosSparse_spgemm_mkl2phase_impl.hpp
Looking at all the builds we have that failed over night starting with Weaver, then KokkosDev and eventually KokkosDev2.
=> Warning: unused-parameter warning generates error in nightly builds

perf_test/graph/KokkosGraph_color_d2.cpp, src/common/KokkosKernels_default_types.hpp, src/impl/KokkosKernels_helpers.hpp
Can build library, examples, perf tests and unit tests with ``--no-default-eti``. Unit tests are all empty since TEST_ETI_ONLY is ON by default, but the everything else is still completely functional. The default types used by examples and perf tests in this build are double/int/int/LayoutLeft.
=> Fix build for no-ETI build

src/common/KokkosKernels_BitUtils.hpp, src/common/KokkosKernels_IOUtils.hpp
This fixes #957
switching on KOKKOS_COMPILER_MSVC
src/common/KokkosKernels_IOUtils.hpp:
Change struct stat to struct _stat on Windows.
src/common/KokkosKernels_BitUtils.hpp:
Define pop_count and least_set_bit on for _MSC_VER.
These need intrin.h included.
Will remove old PR.
=> this is a PR for 4005 vs2019build, which fixes a few things on Windows.

cmake/kokkoskernels_tpls.cmake
```bash
cmake -DCMAKE_CXX_FLAGS=-O3 \
-DCMAKE_INSTALL_PREFIX=$HOME/local/magma-2.5.4/install \
-DGPU_TARGET=Volta \
-DBLA_VENDOR=cuBLAS \
-DLAPACK_LIBRARIES="$CUDA_ROOT/lib64/liblapack_static.a;$HOME/local/OpenBLAS-0.3.13/install/lib64/libopenblas.a" \
$HOME/local/magma-2.5.4
```
And kokkos configured via cmake:
```bash
cmake -DCMAKE_CXX_COMPILER=$HOME/KOKKOS.base/kokkos/install-develop/bin/nvcc_wrapper -DCMAKE_INSTALL_PREFIX=$PWD/../install-issue991 -DCMAKE_BUILD_TYPE:STRING=RELEASE -DKokkos_DIR=$HOME/KOKKOS.base/kokkos/install-develop/lib64/cmake/Kokkos -DKokkosKernels_INST_COMPLEX_DOUBLE:BOOL=ON -DKokkosKernels_ENABLE_TPL_MAGMA:BOOL=ON -DKokkosKernels_MAGMA_ROOT:PATH=$HOME/local/magma-2.5.4/install ..
<snip>
make
<snip>
[100%] Built target kokkoskernels
```
Fixes #991
=> cmake/kokkoskernels_tpls: Remove trilinos check

perf_test/sparse/KokkosSparse_sptrsv_superlu.cpp, perf_test/sparse/KokkosSparse_sptrsv_supernode.cpp, src/common/KokkosKernels_Handle.hpp, src/sparse/KokkosSparse_sptrsv_cholmod.hpp, src/sparse/KokkosSparse_sptrsv_handle.hpp, src/sparse/KokkosSparse_sptrsv_superlu.hpp, src/sparse/KokkosSparse_sptrsv_supernode.hpp, unit_test/sparse/Test_Sparse_sptrsv.hpp
This PR adds an option to run KokkosKernels::TRMM on device for setting up supernode-based sparse-triangular solve.
=> Supernodal SpTRSV: run TRMM on device for setup

src/graph/KokkosGraph_Distance2Color.hpp
Was referring to KokkosGraph::Impl:: as Impl:: from inside KokkosGraph::Experimental,
and this confused the compiler (both clang and gcc) in a Trilinos build
with no ETI. Not sure why.
See discussion at https://github.com/trilinos/Trilinos/issues/5729 about the errors, and https://github.com/trilinos/Trilinos/pull/9183 for the Trilinos PR identical to this one.
=> Give full namespace path for D2 coloring

perf_test/sparse/KokkosSparse_sptrsv_aux.hpp
In my opinion we should simply not call the function if the TPL
is not enabled this way we would not need the two definition as
it is in this PR.
=> SpTRSV: removing the call with unused parameters to check_cusparse

perf_test/blas/blas3/KokkosBlas3_gemm_perf_test.hpp
- Add armpl invocation to the 'experimental' test type.
- Related to #874.
=> perf_test/blas/blas3: Add dgemm armpl experiment

src/KokkosKernels_Macros.hpp
#1003 is due to moving the contents of `src/common/KokkosKernels_Macros.hpp` into `src/KokkosKernels_Macros.hpp`; before this change, `KOKKOSKERNELS_ENABLE_OMP_SIMD` was never defined since `src/KokkosKernels_Macros.hpp` was always included rather than `src/common/KokkosKernels_Macros.hpp`.
```bash
PASSED TESTS
clang-10.0.0-OpenMP-release build_time=181 run_time=47
clang-10.0.0-Pthread-release build_time=176 run_time=75
clang-10.0.0-Serial-release build_time=169 run_time=55
PASSED TESTS
gcc-7.2.0-OpenMP-release build_time=222 run_time=85
```
Fixes #1003
=> Fix nightly build errors in KokkosBlas3_Gemm_impl.hpp

cm_generate_makefile.bash, scripts/cm_test_all_sandia
Disables Kokkos desul atomics by default until incorporated by kokkos-kernels, see #1035 
Adds option to enable in cm_generate_makefile and cm_test_all_sandia
=> test scripts: add option to disable kokkos desul atomics

perf_test/sparse/KokkosSparse_spmv.cpp, perf_test/sparse/spmv/ArmPL_SPMV.hpp, perf_test/sparse/spmv/KokkosKernels_spmv_data.hpp
The goal is to be able to perform comparison between native implementation of Kokkos Kernels and ArmPL implementations of SpMV
=> Adding ArmPL option to spmv perf_test

src/blas/impl/KokkosBlas3_trsm_impl.hpp
Fix #559 (trsm for conjugate transpose mode with Intel 18). I think this is a compiler bug after all, since one fix was just to replace two ternary expressions ``a = cond ? b : c;`` with ``a = c; if(cond) a = b;``. And evaluating b/c have no side effects. But the simpler fix was to just get rid of the ternaries, since whenever ``cond`` is false here, the pointer ``a`` is never dereferenced (if ``iend == 0``, the loop from 0...iend doesn't run).
BTW, In #559 I found that Intel 16/17 didn't have this issue, and I just tried 19 and GCC 9.2 and they didn't either. So it really seems to be a bug only in Intel18.
=> Fix559: Intel 18 has trouble with pointer in ternary expr

src/sparse/KokkosSparse_BlockCrsMatrix.hpp
The graph.row_map view is not guaranteed to be on the host, so an explicit copy is needed.
Remove unused CrsMatrix values view.
=> Fix host accessing View in non-host space.

scripts/cm_test_all_sandia
=> cm_test_all_sandia: Exit with non-zero on errors

example/gmres/ex_real_A.cpp, example/gmres/gmres.hpp, example/gmres/test_real_A.cpp, src/common/KokkosKernels_IOUtils.hpp
=> Updates for running GMRES example with half precision

src/blas/impl/KokkosBlas1_axpby_impl.hpp
In order to support mixed precision with `Kokkos::Experimental::half_t` we must use explicit casts from `half_t` to other types in certain expressions. The reason we cannot support implicit conversion operators from `half_t` to `T` is that when selecting an operator overload, the toolchain encounters multiple valid operators and without a precedence. In this case, if we supported implicit conversions from `half_t` -> `T`, `T = half_t Op half_t` the toolchain would consider the following options:
- `T = half_t Op half_t`
- `T = T Op T`
and produce a compile time error.
What we can and DO support is upcasting for binary arithmetic involving float and double:
- `float_or_double` = `half_t Op float_or_double`
- `float_or_double` = `float_or_double Op half_t`
related to #1049.
=> src/blas/impl: Explicitly cast to LHS type for axpby

example/wiki/sparse/CMakeLists.txt, example/wiki/sparse/KokkosSparse_wiki_bsrmatrix.cpp, src/sparse/KokkosSparse_BsrMatrix.hpp, src/sparse/impl/KokkosSparse_BsrMatrix_impl.hpp, unit_test/sparse/Test_Sparse.hpp, unit_test/sparse/Test_Sparse_BsrMatrix.hpp
Rebased version of #1031 
Closes #1030
=> 1030 new bsrmatrix

src/sparse/KokkosSparse_BsrMatrix.hpp
Address -Werror with clang compilers
=> KokkosSparse_BsrMatrix.hpp: Silence unused parameter warnings

src/blas/impl/KokkosBlas2_gemv_impl.hpp
This avoid atomics with half_t, which are currently very slow on CUDA
(use lock tables, not native atomics).
This also improves the numerical accuracy of the output for all modes
(not just TwoLevel/LayoutLeft, which was using the atomics).
On 1M x 10 matrix, V100, LayoutLeft GEMV with half_t: was getting 1.3 mflops (!) but now gets 140-150 gflops which is about what float gets.
=> Use float as accumulator for GEMV on half_t (Fix #1081)

perf_test/blas/blas3/KokkosBlas3_gemm_perf_test.hpp
=> perf_test/blas/blas3: Disable simd verify for cuda/10.2.2

src/blas/KokkosBlas3_gemm.hpp, unit_test/blas/Test_Blas3_gemm.hpp
@kddevin @srajama1 
Fix for issue #1088, this will need to be patched in Trilinos later if accepted.
The GEMM algorithm should perform a quick return if C is empty.
Otherwise if A and/or B are empty a simple scaling of C by beta can be performed before exiting.
=> Blas GEMM: fix early exit logic, see issue #1088

src/common/KokkosKernels_IOUtils.hpp
Allow reading "integer" values from matrix market files into floating-point type `T` (either `std::is_floating_point<T>::value == true` or `T` is `Kokkos__Experimental::half_t`.
Though it is possible that the integer value may not be accurately representable as a float (for example, `100,000` and `half_t`), that limitation is already implicitly accepted by the current code. For example, reading a mtx "real" matrix with a ascii entry of `0.1` into a `float` is accepted, despite how the value 0.1 cannot be represented as a `float`.
=> Allow reading integer mtx files into floating-point matrices

src/sparse/KokkosSparse_spadd.hpp, unit_test/sparse/Test_Sparse_spadd.hpp
and add a test to check this. Before the numCols was computed using ``maximum_entry(entries) + 1`` but in symbolic, entries have not yet been computed so this value was meaningless.
=> Fix C's numCols in spadd simplified interface

src/batched/dense/KokkosBatched_SVD_Decl.hpp, src/batched/dense/impl/KokkosBatched_SVD_Serial_Impl.hpp, src/batched/dense/impl/KokkosBatched_SVD_Serial_Internal.hpp, test_common/KokkosKernels_TestUtils.hpp, unit_test/batched/dense/Test_Batched_Dense.hpp, unit_test/batched/dense/Test_Batched_SerialSVD.hpp
Completes #909.
Implement batched serial singular value decomposition, based on Golub/van Loan. It only supports double/float right now but could be extended to complex in the future. It uses existing batched routines (mainly Givens/Householder) where possible.
Has modes now for computing full decomposition (U, sigma, V^T) and just singular values. Modes for U/sigma and sigma/V^T could be easily added in the future too. It computes the full SVD where U is ``m*m`` and V^T is ``n*n``, and sigma (singular values) is length ``min(m, n)``.
```
//Usage:
KokkosBatched::SerialSVD::invoke(KokkosBatched::SVD_USV_Tag(), A, U, sigma, Vt, work);
KokkosBatched::SerialSVD::invoke(KokkosBatched::SVD_S_Tag(), A, sigma, work);
```
@ndellingwood This was a request from Questa so it would be nice if this …
=> Batched serial SVD

src/impl/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp
Use KOKKOS_COMPILE_LIBRARY (true while building library, and false when external app is using prebuilt libkokkoskernels)
as the "eti avail" template parameter for SpMV TPL wrappers (cuSPARSE and MKL). Before, this was hardcoded to true,
causing undefined reference errors when the TPL was available but ETI was not. Since ``spmv_eti_spec_avail<...>::value`` was false, it was trying to call ``SPMV<..., true, false>`` but only ``SPMV<..., true, true>`` could actually be instantiated on demand because of the hardcoding.
Tested by building the spmv example with cuSPARSE (with and without ETI) and with MKL (again with and without ETI). All of these behaved as expected (TPL was called correctly when available).
=> Fix #1111: spmv tpl instantiations

src/sparse/KokkosSparse_CrsMatrix.hpp, unit_test/sparse/Test_Sparse_CrsMatrix.hpp
We have only one constructor that does not accept ncols as an input (except for default constructor).
Additionally that constructor does extra work to compute that value without really telling the user.
The changes deprecate that behavior and move some code around to group more logically attributes and methods in the class.
=> CrsMatrix: deprecate constructor without ncols input

src/common/KokkosKernels_HashmapAccumulator.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_compression.hpp
by enabling the code paths required for "independent thread scheduling"
that was introduced with Volta. Tested on Perlmutter A100 - the spgemm unit tests went from failing to passing with this change.
Should fix https://github.com/trilinos/Trilinos/issues/9155 .
To keep the #if condition on one line, I removed ``KOKKOS_ARCH_VOLTA_70`` and ``KOKKOS_ARCH_VOLTA_72`` since these are redundant (``KOKKOS_ARCH_VOLTA`` covers both cases).
=> Fix SpGEMM for Nvidia Turing/Ampere

example/gmres/gmres.hpp, src/batched/KokkosBatched_Util.hpp, src/batched/dense/KokkosBatched_Gemm_Decl.hpp, src/batched/dense/impl/KokkosBatched_Gemm_DblBuf_Impl.hpp, unit_test/batched/dense/Test_Batched_BatchedGemm.hpp
1d2a09a addresses feedback from #1095. 
2cc1485 fixes #1121 - see build no. 348 for the cuda-9 test results and build no. 31 for the XL test results.
=> Fix BatchedDlbBuf build with cuda-9 and XL toolchains

example/gmres/CMakeLists.txt
Related to https://github.com/kokkos/kokkos/issues/4376
=> gmres: disable examples for builds with ibm/xl

src/sparse/impl/KokkosSparse_sptrsv_solve_impl.hpp
Providing explicit template args to some calls to TeamGemv::invoke within the supernodal sptrsv helps workaround compiler issue deducing the types
Occurs with Intel builds of Trilinos
=> Workaround error with intel

src/sparse/KokkosSparse_spmv.hpp
We are checking for KOKKOSKERNELS_INST_LAYOUTLEFT to generate the LayoutRight specialization of the algorithm. 
This does not make sense, fixing the issue by modifying the #ifdef close.
This should fix issue #1148.
=> SpMV: mismatch in #ifdef check and kernel specialization

perf_test/blas/blas3/KokkosBlas3_gemm_perf_test.hpp, perf_test/blas/blas3/KokkosBlas3_trmm_perf_test.hpp, perf_test/blas/blas3/KokkosBlas_trtri_perf_test.hpp, src/blas/impl/KokkosBlas3_trmm_impl.hpp, src/blas/impl/KokkosBlas3_trsm_impl.hpp, src/blas/impl/KokkosBlas_trtri_impl.hpp
Introducing a whole namespace in a public is dangerous due to the potential for name clashes with other libraries.
Removing such usage from trmm, trsm and trtri resolves build issues observed by users in Trilinos, see issue #1170
=> using namespace should be scoped to prevent name clashes, see issue #1170

src/sparse/KokkosSparse_spmv.hpp
As usually removing names of parameters from function signature.
=> SpMV: fix catch all case to avoid compiler warnings

src/sparse/impl/KokkosSparse_spmv_bsrmatrix_impl.hpp
Removed unused Ordinal typdef to prevent -Werror compile errors with
clang compilers
=> KokkosSparse_spmv_bsrmatrix_impl: remove unused typedef

unit_test/sparse/Test_Sparse_findRelOffset.hpp, unit_test/sparse/Test_Sparse_trsv.hpp
These tests have already been disabled for `HIP` and `CUDA`.
=> Use KOKKOS_IMPL_DO_NOT_USE_PRINTF instead of printf in kernels

perf_test/sparse/KokkosSparse_pcg.cpp
``./sparse_pcg --openmp N ...`` should set the number of threads to N,
but it was setting this to 0 no matter what argument was passed on command line.
It was using the thread count for Pthreads (``--threads N``) instead, and this defaulted to 0.
This caused a crash in parallel_scan halfway through Gauss-Seidel setup.
Fixes https://github.com/kokkos/kokkos-kernels/issues/1168 .
See https://github.com/kokkos/kokkos/issues/4512 for a request that Kokkos check that ``InitArguments::num_threads != 0``.
=> Fix #threads setting in pcg for OpenMP

src/sparse/KokkosSparse_BsrMatrix.hpp
Previously, the unassigned `blockDim_` would be checked.
=> Fix assert in src/sparse/KokkosSparse_BsrMatrix.hpp

src/common/KokkosKernels_Handle.hpp, src/sparse/KokkosSparse_BlockCrsMatrix.hpp, src/sparse/KokkosSparse_BsrMatrix.hpp, src/sparse/KokkosSparse_CrsMatrix.hpp
At compile time, check that the ordinal type is signed, for Crs/Bsr/BlockCrs matrix and KokkosKernelHandle.
This is required by at least 2 algorithms (SpGEMM and MIS2).
Note that you can only ETI for ordinal being signed (int and int64_t).
Having an unsigned ordinal gives warnings now. It might take some work to make everything fully support unsigned.
=> Check that ordinal types are signed

scripts/cm_test_all_sandia
=> scripts/cm_test_all_sandia: add clang/10.0.1 spot check

src/common/KokkosKernels_Handle.hpp, src/common/KokkosKernels_IOUtils.hpp, src/common/KokkosKernels_Sorting.hpp, src/sparse/KokkosSparse_gauss_seidel_handle.hpp, src/sparse/impl/KokkosSparse_cluster_gauss_seidel_impl.hpp, src/sparse/impl/KokkosSparse_gauss_seidel_impl.hpp, unit_test/sparse/Test_Sparse_gauss_seidel.hpp
(both point and cluster)
- Allow the two overloads of KokkosKernelsHandle::create_gs_handle to take a coloring algorithm (it's the last argument, and defaults to COLORING_DEFAULT, so it's backwards compatible)
- Add coloring algorithm as argument to Point/Cluster gauss seidel handle, and getter/setter
- Test for GS using a custom algorithm (existing tests still use default)
This is needed in order to do https://github.com/trilinos/Trilinos/issues/8441 (add coloring as an option to Ifpack2 MTGS). Then it will be possible to fix random failures in Ifpack2::Relaxation - right now, non-deterministic coloring can make the number of GS iterations change slightly from run to run.
=> Allow choosing coloring algorithm in multicolor GS

perf_test/blas/blas2/KokkosBlas2_gemv_perf_test.cpp, src/blas/KokkosBlas2_gemv.hpp, src/impl/tpls/KokkosBlas2_gemv_tpl_spec_avail.hpp, src/impl/tpls/KokkosBlas2_gemv_tpl_spec_decl.hpp, unit_test/blas/Test_Blas2_gemv.hpp
Fix GEMV for complex/LayoutRight: this isn't supported by cuBLAS or rocBLAS, so call the fallback option instead of just throwing. To test this, change the unit test to not catch and ignore exceptions.
Add HIP support to GEMV perftest.
This basically takes care of #1083 . Here are some performance measurements for double, 10k x 10k matrix, based on 100 repetitions:
MI100 native impl: 1.74 e+11 flops
MI100 rocBLAS: 2.48 e+11 flops
V100 cuBLAS: 2.18 e+11 flops
=> Add rocBLAS GEMV wrapper

example/gmres/gmres.hpp, example/gmres/test_cmplx_A.cpp, src/sparse/impl/KokkosSparse_spmv_bsrmatrix_impl.hpp
=> example/gmres: Use fabs

src/blas/KokkosBlas1_abs.hpp, src/blas/KokkosBlas1_dot.hpp, src/blas/KokkosBlas1_nrm1.hpp, src/blas/KokkosBlas1_nrm2w.hpp, src/blas/KokkosBlas1_nrm2w_squared.hpp, src/blas/KokkosBlas1_nrminf.hpp, src/blas/KokkosBlas1_reciprocal.hpp, src/blas/KokkosBlas1_update.hpp, src/sparse/KokkosSparse_spmv.hpp, src/stage/blas3/Kokkos_Blas3.hpp
Rational: It is not "legal" to reach into the `Kokkos::Impl::` namespace and the same functionality is provided by `<type_traits>` standard library header since C++11
=> Replace `Kokkos::Impl::if_c -> std::conditional`

perf_test/blas/blas1/CMakeLists.txt, perf_test/blas/blas1/KokkosBlas_dot_mv_perf_test.cpp, src/blas/impl/KokkosBlas1_dot_mv_impl.hpp, src/blas/impl/KokkosBlas1_dot_spec.hpp, src/blas/impl/KokkosBlas1_iamax_impl.hpp, src/blas/impl/KokkosBlas1_nrm1_impl.hpp, src/blas/impl/KokkosBlas1_nrm2_impl.hpp, src/blas/impl/KokkosBlas1_nrm2w_impl.hpp, src/blas/impl/KokkosBlas1_nrminf_impl.hpp, src/blas/impl/KokkosBlas1_sum_impl.hpp, src/blas/impl/KokkosBlas3_gemm_dotbased_impl.hpp, src/blas/impl/KokkosBlas_util.hpp
Where possible, have multiple teams contribute to each reduction using
atomics, just like dot-based GEMM (~3x speedup on Cuda).
Otherwise, process each column in the multivector using a single reduction
(this is still faster on GPU)
Works around https://github.com/trilinos/Trilinos/issues/9856 (original Trilinos issue) and https://github.com/kokkos/kokkos/issues/4461. Also, Kokkos doesn't support array reductions in OpenMPTarget so this is one step closer to running with that backend.
=> Replace array reductions in BLAS-1 MV reductions

src/sparse/KokkosSparse_BsrMatrix.hpp
We add 'src/sparse/impl' to the include path for the library, so doing ``#include "impl/foo.hpp"`` isn't necessary. We install impl/ files directly to the include dir, so in an installed KokkosKernels the impl/foo.hpp include doesn't work.
=> Fix 1216: remove 'impl/' from #include path

perf_test/graph/KokkosGraph_color.cpp
- Make "--serial" flag work without a nonzero integer after it, e.g.
"--serial 1". This matches the --help text (it didn't say that you needed the number).
- Print the mean time over all trials at the end.
=> Improve graph color perf test

src/common/KokkosKernels_Controls.hpp, src/common/KokkosKernels_SparseUtils_rocsparse.hpp, src/impl/tpls/KokkosSparse_spmv_tpl_spec_avail.hpp, src/impl/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp, src/sparse/KokkosSparse_spmv.hpp
rocSPARSE is declared as a TPL for HIP backend and hooks are in place to call the TPL when the library supports it (mode and types restrictions apply). This should provide reasonable performance to the users when the TPL is available while we work on further tuning the native launch parameters of SpMV.
The unit-tests are passing fine, the performance test is now too old and outdated to be updated easily. Further work will be  needed to get that done.
This was tested on spock with all unit-test passing.
=> SpMV: adding support for rocSPARSE TPL

src/common/KokkosKernels_ExecSpaceUtils.hpp, src/sparse/KokkosSparse_spgemm_handle.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_compression.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_kkmem.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_speed.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_symbolic.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_triangle.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_triangle_no_compression.hpp, src/sparse/impl/KokkosSparse_spgemm_jacobi_denseacc_impl.hpp, src/sparse/impl/KokkosSparse_spgemm_jacobi_sparseacc_impl.hpp
The backend was removed in Kokkos 3.1 (see kokkos/kokkos#2738)
=> Remove all references to the Kokkos QThreads backend

cmake/KokkosKernelsConfig.cmake.in
It is not legal to define Kokkos variables from KokkosKernels.  These are properly defined from the Kokkos side https://github.com/kokkos/kokkos/blob/ae5fc649ef4b62b48a01123759ed066bff227b43/cmake/KokkosConfigCommon.cmake.in#L9-L11
=> Do not set Kokkos variables when exporting CMake configuration

src/common/KokkosKernels_ExecSpaceUtils.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_compression.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_kkmem.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_speed.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_symbolic.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_triangle.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_triangle_no_compression.hpp, src/sparse/impl/KokkosSparse_spgemm_jacobi_denseacc_impl.hpp, src/sparse/impl/KokkosSparse_spgemm_jacobi_sparseacc_impl.hpp
With that change, `git grep -n -i pthread src/` prints
```
src/common/KokkosKernels_default_types.hpp:94:#elif defined(KOKKOS_ENABLE_PTHREAD) || defined(KOKKOS_ENABLE_THREADS
```
so this finishes cleaning up the change pthread -> threads initiated by Kokkos
=> Rename enumerator `Impl::Exec_{PTHREADS -> THREADS}`

scripts/docker/Dockerfile.sycl
Corresponds to https://github.com/kokkos/kokkos/pull/4631. Just to be able to run the CI again, this also currently includes the changes in #1234.
=> Update SYCL compiler version in CI

src/common/KokkosKernels_PrintUtils.hpp, unit_test/common/Test_Common.hpp, unit_test/common/Test_Common_IOUtils.hpp
Let's make `kk_print_1Dview()` useful also where displayed view can be either single- or multi-vector.
* Print Nx1 rank-2 vectors same like rank-1 vectors;
* Display multi-vector dimensions like: `[504x2 multi-vector]`.
GCC compilation error which is not very helpful if ones single vector gets turned somewhere into Nx1 rank-2 vector to be dispatched through generic multi-vector interface. The message looks like:
```shell
/kokkos-kernels/src/common/KokkosKernels_PrintUtils.hpp:113:24: error: no match for call to ‘(host_type {aka
Kokkos::View<double**, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace> >}) (idx&)’
113 |         os << host_view(i) << sep;
|               ~~~~~~~~~^~~
In file included from /install/kokkos/include/Kokkos_Parallel.hpp:54,
from …
```
=> Fix compilation errors for multi-vectors in kk_print_1Dview()

test_common/KokkosKernels_Test_Structured_Matrix.hpp
In structured matrix explicit construction, be more consistent with integer types. Use ``ordinal_type`` for rows, nodes and grid points, and use ``size_type`` to index over matrix entries.
This also works around a bug in hipcc for release builds. When you compute both a/b and a%b (division with remainder), where a is size_t and b is int, the quotient comes out wrong. This broke the structured spmv tests when size_type = size_t and ordinal_type = int.
=> Work around hipcc size_t/int division with remainder bug

src/sparse/impl/KokkosSparse_spmv_bsrmatrix_spec.hpp
This should fix the other nightly build failure, see https://cloud.cees.ornl.gov/jenkins-ci/blue/organizations/jenkins/KokkosKernels/detail/KokkosKernels/366/pipeline.
We also define `CUDA` architectures for `SYCL`, in particular in the SYCL CI that we are running on `NVidia` devices. The class in question, `BsrMatrixSpMVTensorCoreDispatcher`, is only defined for `CUDA+VOLTA` or `CUDA+AMPERE`, see https://github.com/kokkos/kokkos-kernels/blob/6c786cd6900b977e7b3b19a1f88c0c433a49cbcc/src/sparse/impl/KokkosSparse_spmv_bsrmatrix_impl.hpp#L48-L49 but we are missing the check for `CUDA` in the lines changed in this pull request.
=> Restrict BsrMatrix specialization for AMPERE and VOLTA to CUDA

src/batched/dense/KokkosBatched_Gemm_Decl.hpp
Based on the data collection done yesterday, this condition update gives produces the best performance.
square matrix dims|KokkosLL|KokkosLR
| ----------- | ----------- | ----------- |
30|1058.316667|1271.95
32|1468.17|1577.553333
34|611.2006667|738.5043333
36|684.4183333|839.801
38|762.6296667|933.2223333
40|850.706|1046.363333
square matrix dims|KokkosLL|KokkosLR
| ----------- | ----------- | ----------- |
30|1055.953333|1276.933333
32|1467.28|1578.036667
34|610.9443333|924.128
36|687.4673333|998.7813333
38|760.513|949.824
40|848.4526667|1049.49
=> src/batched: Use SerialOpt2 for 33 to 39 square matrices

perf_test/graph/KokkosGraph_mis_d2.cpp, perf_test/sparse/CMakeLists.txt
When building with float only (double disabled), a couple of tests are not building properly.
=> Examples: fixing some issues related to type checking

src/Kokkos_InnerProductSpaceTraits.hpp, src/batched/dense/impl/KokkosBatched_Eigendecomposition_Serial_Internal.hpp, src/batched/dense/impl/KokkosBatched_Eigendecomposition_TeamVector_Internal.hpp, src/sparse/impl/KokkosSparse_spmv_struct_impl.hpp
See kokkos/kokkos#4668
Replace uses of `#ifdef KOKKOS_ACTIVE_EXECUTION_MEMORY_SPACE_*` macro guards that are not in `<Kokkos_ArithTraits.hpp>`
I do not intend to change `Kokkos::[Details::]ArithTraits` as part of this pull request.  I expect this will be fixed as part of its refactoring (see #870)
=> Avoid using `#ifdef KOKKOS_ACTIVE_EXECUTION_MEMORY_SPACE_*` macro guards

src/batched/sparse/KokkosBatched_JacobiPrec.hpp, src/batched/sparse/impl/KokkosBatched_GMRES_TeamVector_Impl.hpp, unit_test/batched/sparse/Test_Batched_TeamCG.hpp, unit_test/batched/sparse/Test_Batched_TeamGMRES.hpp, unit_test/batched/sparse/Test_Batched_TeamVectorCG.hpp, unit_test/batched/sparse/Test_Batched_TeamVectorGMRES.hpp
This commit fixes some typos in the TeamVector GMRES, in the preconditioner, and in the unit tests.
@srajama1 @lucbv
=> Fix some typos related to the sparse batched linear solvers

src/graph/KokkosGraph_Distance1ColorHandle.hpp, src/graph/impl/KokkosGraph_Distance1Color_impl.hpp, unit_test/graph/Test_Graph_graph_color.hpp, unit_test/graph/Test_Graph_graph_color_distance2.hpp, unit_test/graph/Test_Graph_mis2.hpp
(except EB coloring - VBBIT is used as the default algo
instead and EB is disabled in the test for now)
=> Changes to make graph run on SYCL

src/batched/KokkosBatched_Util.hpp, src/batched/dense/KokkosBatched_Vector_SIMD.hpp, src/batched/dense/impl/KokkosBatched_Gemm_Serial_Internal.hpp, src/batched/dense/impl/KokkosBatched_Gemm_Team_Internal.hpp, src/batched/dense/impl/KokkosBatched_Gemv_Serial_Internal.hpp, src/batched/dense/impl/KokkosBatched_Gemv_Team_Internal.hpp, src/batched/dense/impl/KokkosBatched_LU_Serial_Internal.hpp, src/batched/dense/impl/KokkosBatched_LU_Team_Internal.hpp, src/batched/dense/impl/KokkosBatched_Trsm_Serial_Internal.hpp, src/batched/dense/impl/KokkosBatched_Trsm_Team_Internal.hpp, src/batched/dense/impl/KokkosBatched_Trsv_Serial_Internal.hpp, src/batched/dense/impl/KokkosBatched_Trsv_Team_Internal.hpp, src/batched/dense/impl/KokkosBatched_Vector_SIMD_Arith.hpp, src/batched/dense/impl/KokkosBatched_Vector_SIMD_Math.hpp
See kokkos/kokkos#4668
`Kokkos::Impl:: ActiveExecutionMemorySpace` is being deprecated/removed.
Note that
```
perf_test/batched/KokkosBatched_Test_BlockTridiagDirect.cpp:78:template <typename ActiveMemorySpace>
perf_test/batched/KokkosBatched_Test_BlockTridiagDirect.cpp:95:template <typename ActiveMemorySpace>
perf_test/batched/KokkosBatched_Test_BlockTridiagDirect.cpp:280:                Kokkos::Impl::ActiveExecutionMemorySpace>
perf_test/batched/KokkosBatched_Test_BlockTridiagDirect.cpp:362:              typedef SolveModeAndAlgo<Kokkos::Impl::ActiveExecutionMemorySpace>
perf_test/batched/KokkosBatched_Test_BlockTridiagJacobi.cpp:78:template <typename ActiveMemorySpace>
perf_test/batched/KokkosBatched_Test_BlockTridiagJacobi.cpp:95:template <typename ActiveMemorySpace> …
```
=> Refactor `Algo::Level{2,3}::Blocked::mb()`

src/batched/KokkosBatched_Util.hpp
@lucbv @vqd8a
Can we replace _KokkosKernels_Utils.hpp_ include in _KokkosBatched_Util.hpp_ (introduced with 81d7f94f7dd04bfae43a5103cc46a79ee36bc5ef, for `KOKKOSKERNELS_MACRO_MIN()` I assume) with _KokkosKernels_SimpleUtils.hpp_ ?
Pulling in whole set of utilities with _KokkosKernels_Utils.hpp_ blocks other utilities from including _KokkosBatched_Util.hpp_ and can easily lead to circular dependencies issues (e.g. on #1099 I've just hit conflict with: _KokkosKernels_Utils_ → _KokkosKernels_SparseUtils_ → _KokkosKernels_BlockUtils_ (new) → _KokkosBatched_Gemm_Serial_Internal_ → _KokkosBatched_Util.hpp_)
=> Prune extra dependencies

src/blas/impl/KokkosBlas2_gemv_impl.hpp, src/blas/impl/KokkosBlas3_gemm_spec.hpp, test_common/KokkosKernels_TestUtils.hpp, unit_test/blas/Test_Blas1_iamax.hpp, unit_test/blas/Test_Blas2_gemv.hpp, unit_test/blas/Test_Blas3_gemm.hpp, unit_test/blas/Test_Blas3_trmm.hpp, unit_test/blas/Test_Blas3_trsm.hpp, unit_test/blas/Test_Blas_trtri.hpp
Enable all Blas tests for SYCL and get them working
This just involves 2 workarounds: GEMV to deal with
team_size_recommended coming back with a number that's too large for
the LayoutLeft kernel, and using a maximum vector length of 8 for SYCL.
Note: this PR has the same changes to ExecSpaceUtils as https://github.com/kokkos/kokkos-kernels/pull/1269
=> Full Blas support on SYCL

perf_test/blas/blas3/KokkosBlas3_gemm_perf_test.hpp, src/Kokkos_ArithTraits.hpp, test_common/KokkosKernels_TestUtils.hpp
- Fix ``ArithTraits<long double>::abs`` was referenced but not defined
- Fix ``cannot call __host__ function from __host__ __device__ function``.
``value_type_name<T>`` uses ``std::string`` and should only be used on host.
- Fix unused named parameter in gemm perf test
=> Fix some warnings

.jenkins/nightly.groovy
Kokkos now requires ROCm minimum version of 4.5 kokkos/kokkos#4689
=> Bump ROCm version 4.2 -> 4.5 in nightly Jenkins CI build

unit_test/sparse/Test_Sparse_spmv.hpp
Fix #1280
Support for half types is there when including `<Kokkos_Core.hpp>`
https://github.com/kokkos/kokkos/blob/39a54435ecabca16d73bd6f9d1648d8831f6b730/core/src/Kokkos_Core.hpp#L55
=> Remove private Kokkos header include (`Cuda/Kokkos_Cuda_Half.hpp`)

src/batched/KokkosBatched_Util.hpp, src/batched/dense/impl/KokkosBatched_Eigendecomposition_Serial_Internal.hpp, src/batched/dense/impl/KokkosBatched_Eigendecomposition_TeamVector_Internal.hpp, src/sparse/impl/KokkosSparse_spmv_struct_impl.hpp
We decided to rename the macro at the last Kokkos developer meeting
kokkos/kokkos#4660 has been merged so make sure you get this in ASAP so you don't get deprecation warnings in your nightly testing
=> Rename `KOKKOS_IF_{HOST,DEVICE} -> KOKKOS_IF_ON_{HOST,DEVICE}`

src/sparse/KokkosSparse_BlockCrsMatrix.hpp, src/sparse/KokkosSparse_BsrMatrix.hpp, src/sparse/KokkosSparse_CrsMatrix.hpp, src/sparse/KokkosSparse_spmv.hpp
Generic KokkosSparse::spmv (where AMatrix can be Crs, Bsr or BlockCrs)
didn't check that the dimensions of A, x and y were compatible. If it
takes the alpha=0 shortcut, this would never get checked. A Tpetra test
relied on this throwing (see #1291), so this adds that check in.
=> Add dimension checking to generic spmv interface

src/KokkosKernels_Macros.hpp, src/batched/dense/KokkosBatched_Vector_SIMD.hpp, src/batched/dense/impl/KokkosBatched_Vector_SIMD_Arith.hpp
Add macro KOKKOSKERNELS_FORCE_SIMD to attempt to force vectorization of a standard for loop, using the
pragmas that are available. It won't use "#pragma omp simd" together with
either "#pragma vector always" or "#pragma ivdep", because in the OneAPI
compilers (dpcpp and icpx) those can't be used together on the same loop.
This fixes the build with OpenMP backend using these compilers (see #1040).
Tested with OneAPI, Intel 20, and GCC+NVCC in an openmp+cuda build.
=> Add KOKKOSKERNELS_FORCE_SIMD macro (Fix #1040)

src/sparse/impl/KokkosSparse_twostage_gauss_seidel_impl.hpp
#1303 
Tested by building Trilinos with serial backend, kokkos-promotion branch, with kokkos version 72efefa. Ifpack2_SGSMT_compare_with_Jacobi_MPI_4 now passes.
=> Fix 1303: maintain correct #cols on A in twostage

src/batched/sparse/KokkosBatched_JacobiPrec.hpp, src/batched/sparse/impl/KokkosBatched_GMRES_TeamVector_Impl.hpp, src/batched/sparse/impl/KokkosBatched_GMRES_Team_Impl.hpp, unit_test/batched/sparse/Test_Batched_TeamGMRES.hpp
- Add missing team barriers
- Don't try to do atomics on local/register values in batched Jacobi
(those are private to each thread/vector lane). Instead use parallel_reduce
to sum results over all threads.
- Make the TeamGMRES test use vector length 1 in the TeamPolicy, since
it doesn't use thread-level parallelism
- With this all batched sparse tests pass on SYCL+Intel.
=> Add missing barriers to TeamGMRES, fix vector len

src/batched/dense/impl/KokkosBatched_Axpy_Impl.hpp, src/batched/sparse/KokkosBatched_JacobiPrec.hpp, src/batched/sparse/impl/KokkosBatched_Spmv_Serial_Impl.hpp, src/batched/sparse/impl/KokkosBatched_Spmv_TeamVector_Impl.hpp, src/batched/sparse/impl/KokkosBatched_Spmv_Team_Impl.hpp, unit_test/common/Test_Common_ArithTraits.hpp
Partly reverts eda2cc45ccc829528e3c9d84ce489f7a787025de in accordance with https://github.com/kokkos/kokkos/pull/4732.
Apparently, the `printf` in the global namespace only worked by accident for a few releases but is broken again in recent releases...
=> Revert "Kokkos synch up: remove macro usage"

example/gmres/gmres.hpp, example/gmres/test_cmplx_A.cpp, example/gmres/test_real_A.cpp
Most of the diff in this PR is due to running clang-format. I only changed the `ST` typedefs from `double` to `bhalf` and added the `fabs` wrappers for `bhalf`.
I used cuda 11.2.0 for these tests with the .mtx files that are hard coded in these gmres example files.
Note that bhalf falls back to float prior to cuda 11 since bhalf support was first added in cuda 11.
```
$ ./gmres_ex_real_A.d
<snip>
True relative residual for iteration 2271 is : 9.90513e-11
Ending relative residual is: 9.90513e-11
Solver converged! 
The solver completed 2272 iterations.
=========================================
Verify from main: Ending residual is 9.90513e-11
Number of iterations is: 2272
Diff of residual from main - residual from solver: 0
Convergence flag is : Converged
```
```
$ ./gmres_ex_real_A
<snip> …
```
=> example/gmres: Switch scalar to bhalf_t

src/batched/dense/impl/KokkosBatched_Gemm_DblBuf_Impl.hpp
This PR is based off of the source branch in #1256. #1256 should be merged before reviewing these changes.
- New operator indexes global and scratch memory such that accesses across vlanes are contiguous.
square matrix dims|Before (Gflop/s)|After (Gflop/s)
| ----------- | ----------- | ----------- |
2|16.8544|17.6915
4|135.402|141.826
6|170.94|169.095
8|265.219|266.223
10|283.863|272.781
12|398.604|400.089
14|327.058|331.717
16|391.265|499.418
18|430.532|562.897
20|543.968|682.534
22|649.959|780.68
24|798.063|986.864
26|780.774|947.36
28|928.002|1139.47
30|1031.92|1227.36
32|1446.63|1538.47
34|605.81|739.448
36|679.656|838.312
38|758.232|936.194
40|839.289|1048.91
42|887.601|1098.1
44|974.299|1211.74
46|1053.33|1321.66
48|1162.6|1478.52
50|1202.08|1489.85
52|1312.51|1617.37 …
=> src/batched/dense: Add Gemm_DblBuf LayoutLeft operator

src/sparse/impl/KokkosSparse_spmv_bsrmatrix_impl.hpp
can't reproduce yet, but this may fix the regression in https://github.com/kokkos/kokkos-kernels/issues/1306
=> cast literal 0 to fragment scalar type

perf_test/sparse/KokkosSparse_spmv_blockcrs.cpp, perf_test/sparse/KokkosSparse_spmv_bsr.cpp, unit_test/sparse/Test_Sparse_spmv_blockcrs.hpp, unit_test/sparse/Test_Sparse_spmv_bsr.hpp
rocBLAS and rocSparse both overload the template std::abs<T>
instead of creating specializations for each type, e.g. ``rocblas_complex_num<double>``.
This breaks calls like ``std::abs<double>(x)`` because it's now ambiguous, even if x is
double. Fix by just letting the compiler deduce which type and overload to use.
With this, 100% building and passing on Crusher :)
=> Fix std::abs calls for rocBLAS/rocSparse

src/batched/dense/impl/KokkosBatched_Dot_Internal.hpp, src/batched/dense/impl/KokkosBatched_HadamardProduct_Impl.hpp, src/batched/dense/impl/KokkosBatched_Xpay_Impl.hpp, src/batched/sparse/impl/KokkosBatched_Spmv_Serial_Impl.hpp, src/batched/sparse/impl/KokkosBatched_Spmv_TeamVector_Impl.hpp, src/batched/sparse/impl/KokkosBatched_Spmv_Team_Impl.hpp
We didn't catch these when we were reverting the removal of the `printf` workaround for SYCL, likely because they were introduced in the meantime.
=> Use the SYCL workaround for printf in a couple more places

perf_test/batched/do-not-use/KokkosBatched_Test_Gemm_Cuda.cpp, perf_test/batched/do-not-use/KokkosBatched_Test_Gemv_Host.hpp, perf_test/batched/do-not-use/KokkosBatched_Test_LU_Cuda.cpp, perf_test/batched/do-not-use/KokkosBatched_Test_Trsm_Cuda.cpp, perf_test/batched/do-not-use/KokkosBatched_Test_Trsm_Host.hpp, perf_test/sparse/KokkosSparse_spmv_blockcrs.cpp, perf_test/sparse/KokkosSparse_spmv_bsr.cpp, src/batched/KokkosBatched_Util.hpp, src/batched/dense/KokkosBatched_Test_BlockCrs_Util.hpp, src/batched/sparse/impl/KokkosBatched_GMRES_TeamVector_Impl.hpp, src/batched/sparse/impl/KokkosBatched_GMRES_Team_Impl.hpp, test_common/KokkosBatched_Test_BlockCrs.hpp
Mainly just making things consistent. In a few perf tests, also allows using scalar=complex.
=> Replace std::abs with ArithTraits::abs

src/sparse/impl/KokkosSparse_spmv_bsrmatrix_spec.hpp
=> Fix bug in `spmv_mv_bsrmatrix()` for Ampere GPU arch

src/common/KokkosKernels_SparseUtils.hpp, src/graph/impl/KokkosGraph_Distance2MIS_impl.hpp, src/sparse/KokkosSparse_gauss_seidel.hpp, src/sparse/impl/KokkosSparse_gauss_seidel_impl.hpp, src/sparse/impl/KokkosSparse_gauss_seidel_spec.hpp, unit_test/sparse/Test_Sparse_block_gauss_seidel.hpp, unit_test/sparse/Test_Sparse_gauss_seidel.hpp
> **Note:** Assumed `TwostageGaussSeidel` (`GS_TWOSTAGE`) and `ClusterGaussSeidel` (`GS_CLUSTER`) to be out of scope: two-stage doesn't support blocks (yet?) and cluster seems not to be compatible with blocks at all.
> **Note:** `PSGS` is not executed in block scenario (only in non-block one, with `GS_PERMUTED` algorithm, see `point_apply(...)`). No-tag operator in `Team_PSGS` is only called in non-block scenario and `LongRowTag` operator(s) are not allowed for blocks (symbolic phase fails if long rows are enabled with block).
Gauss-Seidel kernel already supports sparse block computation based on block CRS format, which differs from BSR only in the value ordering in `values` view (`rows` and `entries` views are identical for both formats as they index whole blocks in the same way):
<p …
=> BSR format support in block Gauss-Seidel

src/batched/dense/KokkosBatched_Kernel_Handle.hpp, src/batched/dense/impl/KokkosBatched_Gemm_Armpl_Impl.hpp, test_common/KokkosKernels_Test_Structured_Matrix.hpp
Removing the last remaining Kokkos::Impl::throw_runtime_exception and instead use the similar function defined in KokkosKernels::Impl.
=> Kokkos::Impl: removing a few more instances of throw_runtime_exception

src/common/KokkosKernels_IOUtils.hpp
Simple fix for matrix market reader so that it doesn't crash when reading a matrix into bfloat16 format.
=> Fix matrix market reader for bfloat16.

src/sparse/impl/KokkosSparse_spmv_bsrmatrix_impl.hpp
This code relies on `__device__` intrinsics, which do not work in KOKKOS_INLINE_FUNCTION functions (`__host__ __device__`).
=> Guard __device__ functions in KOKKOS_INLINE_FUNCTION for tensor core SpMV

src/common/KokkosKernels_Controls.hpp, unit_test/common/Test_Common.hpp, unit_test/common/Test_Common_Controls.hpp
Add an optional `onUnset` argument for a value to return if the key is not present.
Add supporting unit tests
=> default for Controls::getParameter and unit tests

src/sparse/impl/KokkosSparse_spmv_bsrmatrix_impl.hpp, src/sparse/impl/KokkosSparse_spmv_bsrmatrix_spec.hpp
* src/sparse/impl/KokkosSparse_spmv_bsrmatrix_impl.hpp: remove compile-time guards for GPU intrinsics. Add GPU execution space to tag-dispatch scheme to avoid host instantiation.
* src/sparse/impl/KokkosSparse_spmv_bsrmatrix_spec.hpp: refactor to reduce unused variables. Skip tensor cores for all except non-transpose.
=> Refactor tensor core SpMV to disallow certain executions and avoid non-GPU instantiation

src/blas/KokkosBlas1_nrm2w.hpp, src/blas/KokkosBlas1_nrm2w_squared.hpp, src/blas/impl/KokkosBlas1_dot_mv_impl.hpp, src/blas/impl/KokkosBlas1_dot_spec.hpp, src/blas/impl/KokkosBlas1_nrm1_impl.hpp, src/blas/impl/KokkosBlas1_nrm1_spec.hpp, src/blas/impl/KokkosBlas1_nrm2_impl.hpp, src/blas/impl/KokkosBlas1_nrm2_spec.hpp, src/blas/impl/KokkosBlas1_nrm2w_impl.hpp, src/blas/impl/KokkosBlas1_nrm2w_spec.hpp, src/blas/impl/KokkosBlas1_sum_impl.hpp, src/blas/impl/KokkosBlas1_sum_spec.hpp, unit_test/blas/Test_Blas.hpp, unit_test/blas/Test_Blas1_dot.hpp, unit_test/blas/Test_Blas1_nrm1.hpp, unit_test/blas/Test_Blas1_nrm2_squared.hpp, unit_test/blas/Test_Blas1_nrm2w.hpp, unit_test/blas/Test_Blas1_nrm2w_squared.hpp, unit_test/blas/Test_Blas1_sum.hpp
Also: test these paths, test nrm2w, and use 3-arg (async) deep copies in
the >1 column paths of these kernels.
=> Restore BLAS-1 MV paths for 1 column

src/blas/impl/KokkosBlas2_gemv_impl.hpp
(same change that was done in #1082 for scalar = half_t)
This improves answer accuracy and also performance on GPU, since
there isn't an atomic_add for these types but there is for float.
=> GEMV: accumulate in float for scalar = bhalf_t

cmake/kokkoskernels_eti_devices.cmake
Instead of instantiating for both ``<Cuda,CudaSpace>`` and ``<Cuda,CudaUVMSpace>``
by default, just instantiate for the Kokkos's default mem space
(``Cuda::memory_space``), which is controlled by the option ``Kokkos_ENABLE_CUDA_UVM``.
This is a 5 year old suggestion from Trilinos but still, I think better late than never :)
See https://github.com/trilinos/Trilinos/issues/1729
This will roughly cut the library build time in half for Cuda builds, with no downsides that I can think of. The Tpetra stack is either all-UVM or all-CudaSpace. Meanwhile our unit tests, perf tests and examples all use the default mem space for the given exec space, so we're not losing coverage with this change.
=> Only instantiate Kokkos's default Cuda mem space

perf_test/sparse/KokkosSparse_spadd.cpp, src/common/KokkosKernels_SparseUtils_mkl.hpp, src/impl/tpls/KokkosSparse_spmv_bsrmatrix_tpl_spec_decl.hpp, src/impl/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp, src/sparse/KokkosSparse_spgemm_numeric.hpp, src/sparse/impl/KokkosSparse_spgemm_mkl2phase_impl.hpp, src/sparse/impl/KokkosSparse_spgemm_mkl_impl.hpp, src/sparse/impl/KokkosSparse_spgemm_numeric_spec.hpp, src/sparse/impl/KokkosSparse_spgemm_symbolic_spec.hpp, unit_test/sparse/Test_Sparse_spgemm.hpp
@lucbv @brian-kelley 
While adding BSR matrix support to MKL implementation of SpGEMM on #1215, I decided to employ some preliminary refactoring to avoid [further] code duplication. The refactoring proposed here is based on `MKLSparseMatrix<value_type>` wrapper specialized over scalar type (we support `float` and `double`) to manage MKL calls for different matrix types internally.
=> Refactoring of MKL SpGEMM implementation

src/graph/impl/KokkosGraph_Distance1Color_impl.hpp, src/sparse/KokkosSparse_csc2csr.hpp, src/sparse/impl/KokkosSparse_spmv_impl.hpp, test_common/KokkosKernels_TestUtils.hpp, unit_test/sparse/Test_Sparse.hpp, unit_test/sparse/Test_Sparse_TestUtils_RandCscMat.hpp, unit_test/sparse/Test_Sparse_csc2csr.hpp
=> Add csc2csr

src/sparse/impl/KokkosSparse_cluster_gauss_seidel_impl.hpp
- Add necessary fences before timing blocks
- Remove unnecessary fences in apply
- Change inner apply loop to only access cluster begin/end once
These updates were from the branch I used for the MIS2 paper.
=> Minor updates to cluster Gauss-Seidel

src/sparse/KokkosSparse_csc2csr.hpp
=> sparse: Remove csc2csr copy by reference.

src/batched/dense/impl/KokkosBatched_FindAmax_Internal.hpp
Tentative fix for kokkos/kokkos#4959
Value-initialization will zero-initialize the `ValLocScalar` data members.
To be honest I don't quite see how the warning was not there before and how it is related to the "volatile" changes in Kokkos.
cc @PhilMiller
=> Value-initialize result of `MaxLoc` reduction to avoid maybe uninitialized warning

src/sparse/impl/KokkosSparse_sptrsv_symbolic_impl.hpp
Use level scheduling implementation like that from spiluk
Co-author: Vinh Dang @vqd8a
=> Improve sptrsv symb

example/gmres/ex_real_A.cpp, example/gmres/gmres.hpp, example/gmres/test_cmplx_A.cpp, example/gmres/test_prec.cpp, example/gmres/test_real_A.cpp
Adds verbosity parameter to the GMRES examples and turns it off during testing.  The output was taking over all of the other PR test output, so it may be helpful to silence it. 
Also, it seems that several files were adjusted by CLANG formatting.
=> Add verbosity parameter to GMRES example. Turn off for testing.

src/sparse/KokkosSparse_spiluk_handle.hpp, src/sparse/impl/KokkosSparse_spiluk_numeric_impl.hpp, src/sparse/impl/KokkosSparse_spiluk_symbolic_impl.hpp
This PR makes two changes in the numeric phase of SPILUK:
1. Use ```Kokkos::atomic_add``` to avoid race conditions when updating L and U values --> This helps resolve the issue of inconsistent convergence in Belos solver (tested with Aria matrices)
2. Allow computing rows in chunks at each level when dealing with large dense array used for tracking indices of CRS big matrices. Note: another implementation using shared memory hash map will be added in another PR.
=> Improve spiluk numeric phase to avoid race conditions and processing in chunks

example/batched_solve/CMakeLists.txt, example/batched_solve/examples_helper.hpp, example/batched_solve/team_GMRES.cpp, src/batched/KokkosBatched_Util.hpp, src/batched/dense/KokkosBatched_Copy_Decl.hpp, src/batched/dense/impl/KokkosBatched_Gemv_TeamVector_Impl.hpp, src/batched/dense/impl/KokkosBatched_Gemv_TeamVector_Internal.hpp, src/batched/dense/impl/KokkosBatched_Gemv_Team_Impl.hpp, src/batched/dense/impl/KokkosBatched_Gemv_Team_Internal.hpp, src/batched/sparse/KokkosBatched_CG.hpp, src/batched/sparse/KokkosBatched_CrsMatrix.hpp, src/batched/sparse/KokkosBatched_GMRES.hpp, src/batched/sparse/KokkosBatched_Identity.hpp, src/batched/sparse/KokkosBatched_JacobiPrec.hpp, src/batched/sparse/KokkosBatched_Krylov_Handle.hpp, src/batched/sparse/KokkosBatched_Krylov_Solvers.hpp, src/batched/sparse/impl/KokkosBatched_CG_TeamVector_Impl.hpp, src/batched/sparse/impl/KokkosBatched_CG_Team_Impl.hpp, src/batched/sparse/impl/KokkosBatched_GMRES_Serial_Impl.hpp, src/batched/sparse/impl/KokkosBatched_GMRES_TeamVector_Impl.hpp, src/batched/sparse/impl/KokkosBatched_GMRES_Team_Impl.hpp, src/sparse/impl/KokkosSparse_sptrsv_solve_impl.hpp, unit_test/batched/sparse/Test_Batched_SerialGMRES.hpp, unit_test/batched/sparse/Test_Batched_SerialGMRES_Real.hpp, unit_test/batched/sparse/Test_Batched_Sparse.hpp, unit_test/batched/sparse/Test_Batched_TeamCG.hpp, unit_test/batched/sparse/Test_Batched_TeamGMRES.hpp, unit_test/batched/sparse/Test_Batched_TeamVectorCG.hpp, unit_test/batched/sparse/Test_Batched_TeamVectorGMRES.hpp
This PR updates the batched GMRES as follows:
- It adds a serial batched GMRES,
- It updates the Krylov handle to preallocate memory to store Arnoldi vectors,
- It adds an example,
- It adds the option to choose the orthogonalization process,
- It allows the user to track the convergence of the systems.
=> Update Batched GMRES

src/graph/impl/KokkosGraph_Distance1Color_impl.hpp
Fix #1400 - remove variable ``total`` that was set but not used. I can see why the warning was happening, but couldn't replicate on my machine (GCC 9.1). Note that the total time of coloring is measured and stored in the handle outside the impl (in KokkosGraph_Distance1Color.hpp), so this variable really didn't need to be computed.
=> D1 coloring: remove unused but set variable

src/batched/dense/KokkosBatched_Gesv.hpp, src/batched/dense/KokkosBatched_LU_Decl.hpp, src/batched/dense/impl/KokkosBatched_Gesv_Impl.hpp
Solve points 4 and 5 of the issue #1409.
I tried the branch on Weaver and on my workstation.
=> Address #1409

unit_test/sparse/Test_Sparse_spmv.hpp
I am implementing a new formula to determine the level of accuracy to be expected when checking the correctness of the SpMV algorithm. With the new formula it seems that we do not have to lower tolerance from `Kokkos::ArithTraits<>::eps()` which is nice and a more consistent approach. Let us see if it works on other architectures.
=> SpMV: fixing issues with unit-tests tolerance

scripts/docker/Dockerfile.sycl, unit_test/sparse/Test_Sparse_spmv.hpp
This is supposed to fix the nightly tests for SYCL, see https://cloud.cees.ornl.gov/jenkins-ci/blue/organizations/jenkins/KokkosKernels/detail/KokkosKernels/502/pipeline, that were failing since 05/07(!).
=> Fix SYCL nightly test

src/common/KokkosKernels_Controls.hpp
Remove the diagnostic message printed to stdout in Controls::getParameter when the requested parameter is not set.
Fixes https://github.com/kokkos/kokkos-kernels/issues/1415
=> Change Controls::getParameter error message from stdout to stderr

scripts/docker/Dockerfile.sycl
Even after #1419, the SYCL nightly CI still doesn't work since assume a newer compiler in `Kokkos`, see https://cloud.cees.ornl.gov/jenkins-ci/blue/organizations/jenkins/KokkosKernels/detail/KokkosKernels/521/pipeline. This brings the the `Dockerfiles` for `Kokkos` and `KokkosKernels` in line again.
=> Update SYCL CI

perf_test/blas/blas2/KokkosBlas2_gemv_perf_test.cpp, src/common/KokkosKernels_Utils.hpp, src/graph/impl/KokkosGraph_Distance2MIS_impl.hpp, src/sparse/impl/KokkosSparse_gauss_seidel_impl.hpp, test_common/KokkosKernels_TestUtils.hpp
Fixing some headers dependency to remove unnecessary dependency between Common and Sparse Utils.
=> Common Utils: removing dependency on Sparse Utils in Common Utils

src/Kokkos_ArithTraits.hpp
Fix build error in ``ArithTraits<std::complex>::isNan`` and ``isInf``, when building with HIP.
=> Fix Trilinos issue #10612

src/sparse/KokkosSparse_csc2csr.hpp
Update std_algorithms header include to match renaming/reorg of
numeric headers in kokkos/kokkos#5113
=> csc2csr: update Kokkos_Numeric.hpp header inclusion

src/batched/KokkosBatched_Util.hpp, src/impl/tpls/KokkosSparse_spmv_mv_tpl_spec_avail.hpp, src/impl/tpls/KokkosSparse_spmv_mv_tpl_spec_decl.hpp, src/impl/tpls/KokkosSparse_spmv_tpl_spec_avail.hpp, src/impl/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp, src/sparse/KokkosSparse_Utils_cusparse.hpp, src/sparse/KokkosSparse_spmv.hpp, src/sparse/impl/KokkosSparse_spmv_spec.hpp
* Add TPL files for CrsMatrix-multivector product Y += AX wherever cusparseSpMM is supported:
* CUSPARSE_VERSION >= 10301
* Y is `LayoutLeft`
* X is `LayoutLeft` or `LayoutRight` (cuSparse dense matrices must be col-major, but we can sneak in a transpose operation when X is `layoutRight`)
* Scalar type is all the usual suspects + `Kokkos::Experimental::half_t`
* Index/Offset types are only `int`
This uses the generic `cusparseSpMM` interface, so in the general case it needs a `cudaMalloc`. Older cuSparse Csr functions have all been deprecated.
=> Add cuSparse TPL files for CrsMatrix-multivector product

perf_test/blas/blas1/KokkosBlas_dot_mv_perf_test.cpp, perf_test/blas/blas1/KokkosBlas_dot_perf_test.cpp
@masterleinad 
Not much needed to change, the device argument is currently ignored.
=> dot perf test: adding support for HIP and SYCL backend

example/graph/KokkosKernels_Example_Distance2GraphColor.cpp, example/hashmap_accumulator/KokkosKernels_Example_HashmapAccumulator.cpp, perf_test/blas/blas1/KokkosBlas_dot_mv_perf_test.cpp, perf_test/blas/blas1/KokkosBlas_dot_perf_test.cpp, perf_test/blas/blas1/KokkosBlas_team_dot_perf_test.cpp, perf_test/blas/blas2/KokkosBlas2_gemv_perf_test.cpp, perf_test/blas/blas3/KokkosBlas3_gemm_standalone_perf_test.cpp, perf_test/graph/KokkosGraph_color.cpp, perf_test/graph/KokkosGraph_color_d2.cpp, perf_test/graph/KokkosGraph_triangle.cpp, perf_test/sparse/KokkosSparse_block_pcg.cpp, perf_test/sparse/KokkosSparse_pcg.cpp, perf_test/sparse/KokkosSparse_spadd.cpp, perf_test/sparse/KokkosSparse_spgemm.cpp, perf_test/sparse/KokkosSparse_spgemm_jacobi.cpp, src/batched/dense/impl/KokkosBatched_Gesv_Impl.hpp, src/graph/impl/KokkosGraph_Distance2Color_impl.hpp, src/sparse/KokkosSparse_csc2csr.hpp, src/sparse/impl/KokkosSparse_spgemm_mkl2phase_impl.hpp, unit_test/common/Test_Common_set_bit_count.hpp, unit_test/sparse/Test_Sparse_spgemm.hpp, unit_test/sparse/Test_Sparse_spgemm_jacobi.hpp, unit_test/sparse/Test_Sparse_spiluk.hpp, unit_test/sparse/Test_Sparse_sptrsv.hpp
@lucbv @crtrott @kliegeois 
This PR addresses couple of issues that cause GitHub CI to fail with _unrelated_ compilation errors (i.e. broken `develop`):
* Kokkos updates:
- **Note:** Deprecated `num_numa` was being set in [_perf_test/sparse/KokkosSparse_block_pcg.cpp_](https://github.com/kokkos/kokkos-kernels/pull/1461/files#diff-1d9913f65a6408f50d3d5bf03674cddfa41b08594efa5afd48baf7d6e2ea2146L380).
* Bugs:
=> Fix GitHub CI failing on broken `develop`

perf_test/graph/KokkosGraph_mis_d2.cpp, perf_test/sparse/KokkosSparse_block_pcg.cpp, perf_test/sparse/KokkosSparse_sptrsv_supernode.cpp, src/graph/KokkosGraph_Distance2Color.hpp, src/graph/impl/KokkosGraph_Distance2MIS_impl.hpp, src/sparse/KokkosSparse_Utils.hpp, src/sparse/KokkosSparse_gauss_seidel.hpp, src/sparse/impl/KokkosSparse_gauss_seidel_impl.hpp, src/sparse/impl/KokkosSparse_gauss_seidel_spec.hpp, unit_test/graph/Test_Graph_graph_color.hpp, unit_test/graph/Test_Graph_graph_color_distance2.hpp, unit_test/sparse/Test_Sparse_Transpose.hpp, unit_test/sparse/Test_Sparse_block_gauss_seidel.hpp, unit_test/sparse/Test_Sparse_spgemm.hpp
Just making a namespace change for consistency and deprecating the old struct in the previous namespace.
=> Sparse utils namespace

src/sparse/impl/KokkosSparse_trsv_impl.hpp, test_common/KokkosKernels_TestUtils.hpp, unit_test/sparse/Test_Sparse_trsv.hpp
In trsv, don't assume the diagonal entry is first in its row if the matrix is upper triangular. Test this by randomly shuffling each row of the matrix used for testing.
Must wait until #1461 is merged.
=> trsv: remove assumptions about entry order within rows

perf_test/sparse/KokkosSparse_block_pcg.cpp
Drop struct from creation of Kokkos::InitializationSettings type
Small fix for `-Werror,-Wmismatched-tags` picked up in clang/7 nightly builds
=> Fix -Werror

unit_test/batched/dense/Test_Batched_TeamGemv_Complex.hpp, unit_test/batched/dense/Test_Batched_TeamGemv_Real.hpp
@lucbv @fnrizzi
This fix makes `KokkosBatched::TeamGEMV` unit test call `test_batched_team_gemv()` instead of `test_batched_gemv()`, which runs `SerialGEMV`.
=> Fix incorrect function call in KokkosBatched::TeamGEMV unit test

src/common/Kokkos_ArithTraits.hpp
Fixing warning being generated on IBM Power9
The warning comes from the current handling of char type that can be either signed or unsigned depending on the platform.
The new implementation uses enable_if to detect if numeric_limits<char>::is_signed is set to true or false and an appropriate implementation of abs() and nan() is selected.
=> Fix arithtraits warning

example/fenl/TestFixture.hpp, example/fenl/fenl_functors.hpp, perf_test/graph/KokkosGraph_run_triangle.hpp, src/batched/KokkosBatched_Util.hpp, src/blas/impl/KokkosBlas1_dot_impl.hpp, src/blas/impl/KokkosBlas1_iamax_impl.hpp, src/blas/impl/KokkosBlas1_nrm2_impl.hpp, src/blas/impl/KokkosBlas1_nrm2w_impl.hpp, src/blas/impl/KokkosBlas2_gemv_impl.hpp, src/common/KokkosKernels_SimpleUtils.hpp, src/common/KokkosKernels_Utils.hpp, src/graph/KokkosGraph_Distance1ColorHandle.hpp, src/sparse/impl/KokkosSparse_spgemm_imp_outer.hpp, src/sparse/impl/KokkosSparse_spgemm_impl_symbolic.hpp, unit_test/common/Test_Common_ArithTraits.hpp
Following https://github.com/kokkos/kokkos/issues/4077 et seq, none of these methods need to take `volatile`-qualified parameters any longer
This should all be good on Kokkos `develop` and releases from 3.7/4.0 onwards, but this will break compatibility with Kokkos 3.6, in case that matters.
=> Remove volatile qualifiers in reducer join(), init(), and operator+= methods

src/batched/dense/impl/KokkosBatched_Gemm_DblBuf_Impl.hpp, src/blas/KokkosBlas_trtri.hpp, src/blas/impl/KokkosBlas_trtri_spec.hpp, src/impl/tpls/KokkosBlas_trtri_tpl_spec_avail.hpp, src/impl/tpls/KokkosBlas_trtri_tpl_spec_decl.hpp
Partial fix for #1474 following merge of kokkos/kokkos#5209
cc @crtrott 
There was no point on specifying the layout of a rank-0 view.  This seems to resolve the compiler error.
I changed occurrences I could find but not all were actually showing as errors on my local build which means I did not actually compile all the code paths.
I hope this helps resolving the nightly failures.  Feel free to push more changes as necessary.
=> Fixup drop layout template param in rank-0 views

unit_test/blas/Test_Blas1_dot.hpp, unit_test/blas/Test_Blas1_iamax.hpp, unit_test/blas/Test_Blas1_nrm1.hpp, unit_test/blas/Test_Blas1_nrm2.hpp, unit_test/blas/Test_Blas1_nrm2_squared.hpp, unit_test/blas/Test_Blas1_sum.hpp
For some kernels that return results in host views the implementation is non-blocking and requires to do a Kokkos::fence() before checking the value against the reference value.
=> BLAS: fixing test that access results before synching

unit_test/common/Test_Common.hpp, unit_test/graph/Test_Graph_graph_color.hpp
With the latest dpcpp compiler drop we can turn back on a couple of test.
The ArithTraits is also mostly using Kokkos implementation of math functions and numeric traits so we should be able to blame them for new issues :p
=> sycl: re-enabling test now that dpcpp has made progress

cmake/Modules/FindTPLMKL.cmake, src/impl/tpls/KokkosSparse_spmv_bsrmatrix_tpl_spec_decl.hpp, src/impl/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp
@lucbv @fnrizzi
This PR adds (missing?) MKL include directories to CMake and fixes pointer casts causing following `gcc` errors in `Release` builds:
```shell
kokkos-kernels/src/impl/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp:586:61: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
586 |   MKL_Complex8& alpha_mkl = reinterpret_cast<MKL_Complex8&>(alpha);
|                                                             ^~~~~
```
=> Fix MKL build errors

cmake/Dependencies.cmake
@bartlettroscoe 
This was a strange oversight that creates issues with the Trilinos build of Kokkos Kernels.
=> TPLs: adding CUBLAS in the list of dependencies

src/KokkosKernels_Macros.hpp
=> Add gcc/7.3.0 to macro guard define for KOKKOSKERNELS_ENABLE_OMP_SIMD

perf_test/graph/KokkosGraph_color_d2.cpp
- change the default number of runs to 1, from 6
- for symmetric D2 coloring, verify precondition that local graph is structurally symmetric.
(local means the 0..nrows by 0..nrows submatrix, since entries in higher columns are allowed
and are ignored by the algorithms)
- verify correctness of coloring like unit test does
The symmetry test uses 64-bit hashes of edge endpoints, so there is a tiny chance of a false negative (where the graph is nonsymmetric, but the test says it is). But I think it's a low enough probability for this purpose.
These two features were needed by @cgcgcg to understand why MueLu D2 coloring based aggregation was failing.
=> Update --verbose option in D2 coloring perftest

src/common/KokkosKernels_HashmapAccumulator.hpp, src/graph/KokkosGraph_CoarsenConstruct.hpp, src/graph/KokkosGraph_CoarsenHeuristics.hpp, unit_test/graph/Test_Graph.hpp, unit_test/graph/Test_Graph_coarsen.hpp
templated classes to generate coarse graph hierarchies from an input CRS matrix, or to generate just an aggregation matrix; implements several different coarsening heuristics; optimized for highly skewed-degree graphs
=> Adding my weighted graph coarsening code into kokkos-kernels

src/graph/KokkosGraph_CoarsenConstruct.hpp
error: implicit capture of ‘this’ via ‘[=]’ is deprecated in C++20
=> Replace capture-by-value with capture-by-ref to resolve -Werror

BUILD.md, CMakeLists.txt, perf_test/CMakeLists.txt, scripts/cm_test_all_sandia, src/sparse/impl/KokkosSparse_spgemm_cuSPARSE_impl.hpp, unit_test/sparse/Test_Sparse_spmv.hpp
-    scripts/cm_test_all_sandia:
- Add spot check options for cuda11 and intel19 on 4 rhel7 machines
- Switch cuda11 modules from sems-archive-env to sems-env
- Added initial source of /etc/profile.d/modules.sh for the dev queue
-    cmake:
- Added cmake option `KokkosKernels_ENABLE_PERFTESTS`
- Note: This changes all our cmake configure to, by default, disable building `perf_test`. The default used to be to build `perf_test` but the binaries were never run in PR (or nightly?) testing. In the long run, this will save many cycles.
- Document undocumented cmake option `KokkosKernels_ENABLE_TESTS_AND_PERFSUITE`
-    src/sparse:
- Fix some warnings as errors in spmv when compiling with cuda11
- Attempted to conditionally skip spmv_mv for ARMPL PR builds
Once this merges, we can replace the …
=> Add INTEL19 and CUDA11 CI settings

src/graph/KokkosGraph_CoarsenHeuristics.hpp
=> KokkosGraph_CoarsenHeuristics: remove volatile qualifier from join

src/common/KokkosKernels_Utils.hpp
c++11 deprecated implicit copy-assign operators when a copy-constructor is defined.
array_sum_reduce is actually okay with implicit versions both copy-ctor and copy-assign, so don't define either one ourselves
=> utils: implicit copy-assign deprecated in array_sum_reduce

src/graph/KokkosGraph_CoarsenConstruct.hpp, unit_test/graph/Test_Graph.hpp, unit_test/graph/Test_Graph_coarsen.hpp
New capabilities added to perform graph coarsening rely on LAMBDA expression that are only available in CUDA when specifically enabled in Kokkos Core. Adding guards for CUDA LAMBDAs fix a compilation issue in the unit-tests.
=> Graph coarsen: fix test by adding pre-processor guards, issue #1516

src/KokkosKernels_Macros.hpp, src/batched/dense/KokkosBatched_Vector_SIMD.hpp
- A timing bug was hidden with the lengthier epilogue generated by gcc 7.2.0. This commit adds a memory barrier for GNU compilers after avx512 broadcast intrinsics to ensure the broadcasted writes land before the memory locations are read from. Fixes #1512.
https://godbolt.org/z/hG3szcaEG
There is still one test failure with these fixes, see https://github.com/kokkos/kokkos-kernels/issues/1523.
=> src/batched/dense: Barrier after broadcast

src/graph/impl/KokkosGraph_Distance2MIS_impl.hpp
A Kokkos view (aggSizes) in the phase 3 aggregation kernel was not initialized when it should have been. It needs to start out filled with 0 because it counts up from there in-place with atomics. Another view (connectivities) was initialized but actually didn't need to be. This didn't necessarily affect the correctness of the aggregation, only the quality and determinism, since aggSizes is only needed as a tiebreak in the phase 3 heuristic.
Fixes https://github.com/trilinos/Trilinos/issues/10950 and makes MIS2 unit tests run cleanly under valgrind.
=> MIS2 aggregation: fix bug with uninitialized memory

src/graph/impl/KokkosGraph_Distance1Color_impl.hpp
While doing #1528 I saw some other conditional branch on uninitialized errors in EB distance-1 coloring. tentative_color_ban was not initialized at construction but should have been.
=> Fix valgrind uninitialized errors in EB coloring

.github/workflows/format.yml, .github/workflows/osx.yml
The following changes were made:
- Removed 'labeled' and 'unlabeled' triggers in favor of manually clicking 'Re-run all jobs' when `AT: WIP` is removed. We do not want to trigger workflow runs every time any label is added or removed and it is not clear how to only trigger when the `AT: WIP` label is removed. This fixes #1491.
- Conditionally ignore triggers for certain documentation files
- Previously running workflows are now canceled when when the PR is reopened or the source branch receives a new commit
- Updated code style check to use ubuntu 20
=> .githob/workflows: Fix redundant workflow triggers

graph/impl/KokkosGraph_Distance2Color_impl.hpp, perf_test/sparse/KokkosSparse_spmv_struct.cpp, perf_test/sparse/KokkosSparse_spmv_struct_tuning.cpp
Fixing a few spots in performance tests and graph algorithms where the clang compiler on M1 macbook fails with warning as errors.
=> Warning fixes: Apple Clang complains about [-Werror,-Wunused-but-set-variable]

sparse/impl/KokkosSparse_spgemm_cuSPARSE_impl.hpp
@jczhang07
Fixing a build issue with cuda+cusparse build of spgemm, a few variables are not used in that 11040 branch of the code.
Also are we sure that version 11040 is correct, what about version 11000, is it different?
If not then we should simplify the pre-processor logic, currently spgemm is not supporting cusparse TPL for versions between 11000 and 11040
=> Fix spgemm cusparse

graph/unit_test/Test_Graph_coarsen.hpp
Potential resolution to compilation errors with size_t types in test kokkos/kokkos-kernels#1536
=> Test_Graph_coarsen: replace HostMirror usage with auto

sparse/impl/KokkosSparse_mdf_impl.hpp, sparse/src/KokkosSparse_mdf.hpp, sparse/src/KokkosSparse_mdf_handle.hpp, sparse/unit_test/Test_Sparse.hpp, sparse/unit_test/Test_Sparse_mdf.hpp
This PR aims to progress from a slow and expensive implementation of the MDF algorithm to a more reasonable one once optimization has been performed on the algorithm.
Some of the difficulties already identified are:
1. Accessing columns of A to compute fill values
2. Dynamic re-ordering of rows reduces the potential for parallelization
3. Large number for kernel launch, maybe some can be fused?
=> MDF implementation in parallel

.jenkins/nightly.groovy, scripts/docker/Dockerfile.hip
* Update docker image ROCm 4.5 -> 5.2 to satisfy the new Kokkos minimum requirements
* Use C++17
=> Fix HIP nightly build on ORNL Jenkins CI server

scripts/cm_test_all_sandia
- Update Caraway rocm compiler to version 5.2.0
- Add option to set build parallelism level
=> cm_test_all_sandia: testing updates

batched/sparse/impl/KokkosBatched_CG_TeamVector_Impl.hpp, batched/sparse/impl/KokkosBatched_CG_Team_Impl.hpp, batched/sparse/impl/KokkosBatched_GMRES_TeamVector_Impl.hpp, batched/sparse/impl/KokkosBatched_GMRES_Team_Impl.hpp, batched/sparse/impl/KokkosBatched_Spmv_TeamVector_Impl.hpp, batched/sparse/src/KokkosBatched_CrsMatrix.hpp, batched/sparse/src/KokkosBatched_Krylov_Handle.hpp, batched/sparse/src/KokkosBatched_Krylov_Solvers.hpp, batched/sparse/src/KokkosBatched_Spmv.hpp, batched/sparse/unit_test/Test_Batched_TeamVectorSpmv.hpp
Update the batched sparse kernels to add SIMD data types and options for the temporary variable allocations.
=> Batched sparse kernels update

batched/sparse/impl/KokkosBatched_Spmv_TeamVector_Impl.hpp
=> Avoid the SIMD code branch if the batched size is not a multiple of the vector length

sparse/impl/KokkosSparse_spiluk_symbolic_impl.hpp
spiluk_symbolic needs to sort the rows of the L and U graphs. Instead of using Kokkos::sort on each row (since this is meant for device-wide sorts of large arrays), use the KokkosSparse::sort_crs_graph function executing on host.
This fixes https://github.com/trilinos/Trilinos/issues/11041. The issue appeared to come from Kokkos because the default behavior of Kokkos::sort changed recently. In 3.6.1, given a UVM space view it dispatched to std::sort because it's host-accessible. In 3.7, In was dispatching to Kokkos bin sort on the GPU. This is definitely the way it should be in general given how Kokkos::sort is intended to be used, but it made this case of sorting many small arrays a lot slower. Especially when those small arrays live in UVM that's resident in host memory.
For biggest …
=> Use CRS matrix sort, instead of Kokkos::sort on each row

sparse/unit_test/Test_Sparse_spmv.hpp
All A64FX PR builds require that this test be skipped.
Depends on https://github.com/kokkos/kokkos/pull/5500.
=> sparse/unit_test: Disable spmv_mv_heavy for all A64FX builds

sparse/src/KokkosSparse_BsrMatrix.hpp
This change matches `KokkosSparse_BsrMatrix.hpp` to `KokkosSparse_CrsMatrix.hpp`, namely, using `device_type` instead of `execution_space` to define `Kokkos::StaticCrsGraph` type. This is motivated by using `BsrMatrix` in `Trilinos/tpetra/BlockCrsMatrix` where we need this change on the trilinos side in PR https://github.com/trilinos/Trilinos/pull/10965
=> Change template type for StaticCrsGraph in BsrMatrix

batched/dense/impl/KokkosBatched_Gemv_Team_Internal.hpp, batched/dense/src/KokkosBatched_Gemv_Decl.hpp
Adds the 12-arg overload of invoke, see #1435
Potential (short term?) solution to #1537
=> TeamGemvInternal: reintroduce 12-arg invoke method

scripts/cm_test_all_sandia
- Add gcc/8.3.1 to weaver (rhel8 queue option)
- Cleanup: remove unused blake compiler, remove white
=> cm_test_all_sandia: updates and cleanup

cmake/Dependencies.cmake
Matches changes in Trilinos PR https://github.com/trilinos/Trilinos/pull/11154 which fixes trilinos/Trilinos#11152.
=> KokkosKernels: Remove listing of undefined TPL deps (trilinos/Trilinos#11152)

docs/CMakeLists.txt, docs/Doxyfile.in, docs/conf.py, docs/developer/apidocs/blas3.rst, docs/developer/apidocs/sparse.rst, sparse/src/KokkosKernels_Handle.hpp
This PR corrects the source paths for the documentation build. Thanks to @ndellingwood for pointing this out!
The PR also fixes a few regressions (https://github.com/kokkos/kokkos-kernels/commit/50d812c0250f3c95f7b4b74fa47a114aa1b50d71) noted in doxygen warnings. Note that there are several more doxygen warnings that are currently being ignored.
To guard against regressions going forward, I suggest that we change: `WARN_AS_ERROR = YES` in `Doxyfile.in` and add a github actions documentation build. For example:
```
$ git diff
diff --git a/docs/Doxyfile.in b/docs/Doxyfile.in
index 5cb072a46..c3a662197 100644
--- a/docs/Doxyfile.in
+++ b/docs/Doxyfile.in
@@ -843,7 +843,7 @@ WARN_NO_PARAMDOC       = NO
-WARN_AS_ERROR          = NO
+WARN_AS_ERROR          = YES
@@ -871,7 +871,7 @@ WARN_LOGFILE …
```
=> Fix docs build

sparse/impl/KokkosSparse_mdf_impl.hpp
I need this to compile using SYCL.
=> SYCL: Use KOKKOS_IMPL_DO_NOT_USE_PRINTF instead of printf in kernels

blas/tpls/KokkosBlas1_rotg_tpl_spec_avail.hpp, blas/tpls/KokkosBlas1_rotg_tpl_spec_decl.hpp
A couple of obvious issues have made it into the repo, this simply addresses them.
Should be pretty straight-forward to merge...
=> Rotg fixes for issue #1577

sparse/impl/KokkosSparse_spgemm_cuSPARSE_impl.hpp, sparse/src/KokkosSparse_CrsMatrix.hpp, sparse/src/KokkosSparse_spgemm_handle.hpp
- Add support for SpGEMM in cuSPARSE versions 11.0-11.3. With this, all versions 10.x and 11.x are supported.
- Cleanup: remove cuSPARSE handle and matrix descriptor from CrsMatrix, since these were not used by any TPL wrappers. The cuSPARSE general handle definitely doesn't belong in the matrix, since the singleton handle (lazily created by Controls) can be used for all cuSPARSE calls. The matrix descriptor also doesn't need to be in the matrix, since it takes about 1us to create in both cuSPARSE and rocSPARSE, so caching it doesn't really provide noticeable savings even for fast-running kernels like SpMV.
Note: we can always add the matrix descriptor back into CrsMatrix, but we would need to fix several things:
- Need to have not only the ``cusparseMatDescr_t``, but also the …
=> First phase of SpGEMM TPL refactor

scripts/cm_test_all_sandia
No further errors reported beyond what's reported in #1564.
```bash
$ ../scripts/cm_test_all_sandia --spot-check-tpls cuda/11.2.2 --kokkos-path=../../kokkos --kokkoskernels-path=../ --arch=Volta70 --cxxstandard=17
<snip>
$ cd TestAll_2022-10-25_14.24.42/cuda/11.2.2/Cuda_Serial-release/
$ source ./reload_modules.sh
$ make -i -k -j48 2>&1 | grep 'error:' | sort | uniq
1 error detected in the compilation of "/path/to/KOKKOS.base/kokkos-kernels/testing/TestAll_2022-10-25_14.24.42/cuda/11.2.2/Cuda_Serial-release/sparse/eti/generated_specializations_cpp/spadd_numeric/Sparse_spadd_numeric_eti_COMPLEX_DOUBLE_ORDINAL_INT_OFFSET_SIZE_T_LAYOUTLEFT_EXECSPACE_CUDA_MEMSPACE_CUDASPACE.cpp"./path/to/KOKKOS.base/kokkos-kernels/sparse/src/KokkosSparse_spgemm_handle.hpp(238): error: identifier …
```
=> scripts/cm_test_all_sandia: Add cuda11 tpl spot check

cm_generate_makefile.bash
Tested on Caraway with rocm/5.2.0, 100% tests pass
Will add nightly tests with rocblas and rocsparse tpls enabled after this PR merges
=> cm_generate_makefile: add rocblas, rocsparse tpl options

sparse/src/KokkosSparse_Utils_mkl.hpp
(using SpGEMM with nonstandard scalar type, with MKL enabled).
Mirror of https://github.com/trilinos/Trilinos/pull/11278 (identical except this one has clang-format applied)
=> Fix Trilinos issue #11033

batched/dense/src/KokkosBatched_Gemm_Decl.hpp
=> batched/dense: Reduce register pressure

sparse/impl/KokkosSparse_sptrsv_cuSPARSE_impl.hpp, sparse/src/KokkosSparse_sptrsv_handle.hpp
Just a simple fix for seg faults encountered when destroying cuSparse SPTRSV handle without ```sptrsvcuSPARSE_symbolic``` or ```sptrsvcuSPARSE_solve```. Solution: moving these ```cusparseDestroyDnVec``` calls  out of cuSparse SPTRSV handle to the symbolic and solve phases.
=> Move destroying dense vector descriptors out of cuSparse sptrsv handle

blas/tpls/KokkosBlas1_rot_tpl_spec_avail.hpp, blas/tpls/KokkosBlas1_rotg_tpl_spec_decl.hpp, blas/tpls/KokkosBlas1_rotm_tpl_spec_decl.hpp, blas/tpls/KokkosBlas1_rotmg_tpl_spec_decl.hpp
The rotation functions now support stream execution and proper pointer mode setting in the rocBLAS TPL interface layer.
This PR should fix the issue reported in #1593 and hopefully lead to fully clean build and tests on caraway!
=> ROT* HIP: testing and improving rocBLAS support for ROT* kernels

graph/impl/KokkosGraph_Distance1Color_impl.hpp, perf_test/graph/KokkosGraph_color.cpp
Like other graph algorithms, ignore neighbors >= numVerts (when the graph is the local part of a distributed Tpetra CrsGraph, these neighbors correspond to remotes). Fixes #1596.
Also add to D1 coloring perf test in --verbose mode:
- Check that input graph (without remote edges) is structurally symmetric
- Check that coloring is valid
=> VBD/VBDBIT D1 coloring: support distributed graphs

sparse/src/KokkosSparse_Utils_cusparse.hpp
Just a minor change to fix the typo in ```cuda_data_type_from``` to return ```CUDA_C_64F``` for ```Kokkos::complex<double>```
=> Fix cuda_data_type_from to return CUDA_C_64F for Kokkos::complex<double>

sparse/src/KokkosSparse_Utils_cusparse.hpp
This PR matches changes in https://github.com/trilinos/Trilinos/pull/11308 (by @etphipp) for issue https://github.com/trilinos/Trilinos/issues/11297
=> Disable compile-time check in cuda_data_type_from on supported scalar types for cuSPARSE

sparse/impl/KokkosSparse_spgemm_rocSPARSE_impl.hpp
The way it was done initially did not cast pointers from Kokkos complex type to rocsparse complex type which leads to unknown conversion errors down the road...
=> SPGEMM: fixing the rocsparse interface

common/src/KokkosKernels_ExecSpaceUtils.hpp
https://github.com/intel/llvm/pull/6604 at least allows for querying free memory but that isn't available in most releases. This pull request updates the current implementation to allow multiple memory modules. The update closely follows the public implementation https://github.com/intel/llvm/blob/9811ef24694f8dee5c1c8b7dd43047a63f655277/sycl/plugins/level_zero/pi_level_zero.cpp#L3147-L3167.
=> Update kk_get_free_total_memory for SYCL

sparse/tpls/KokkosSparse_spgemm_symbolic_tpl_spec_decl.hpp, sparse/unit_test/Test_Sparse_spgemm.hpp
The issue was that ``cusparseSpGEMM_compute`` doesn't actually populate C rowptrs - only ``cusparseSpGEMM_copy`` does. The call to  ``cusparseSpGEMM_copy`` is only needed when rowptrs are requested. For just counting nonzeros, it doesn't need to be done until numeric (when it's used to populate values/entries).
Additionally, add specific testing for spgemm symbolic, making sure that C's rowptrs are computed correctly (when computeRowptrs=true).
Tested on cuSparse (10.1, 11.2 and 11.6, so the 3 different paths), MKL and rocSparse.
=> Fix #1627: cusparse 11.0-11.3 spgemm symbolic wrapper

perf_test/CMakeLists.txt
This replaces the usage of raw include_directories() with the wrapper KOKKOSKERNELS_INCLUDE_DIRECTORIES().
The deprecated TriBITS macro include_directories() now issues a CMake Deprecation warning.  The fix is to use tribits_include_directories() in a TriBITS build instead.
This is the same patch made in Trilinos PR trilinos/Trilinos#11380.
=> KokkosKernels: Use KOKKOSKERNELS_INCLUDE_DIRECTORIES() (TriBITSPub/TriBITS#429)

blas/unit_test/Test_Blas1_rotmg.hpp
It seems that we are having the same issue with OpenBLAS and MKL so I am changing the logic just a bit to have a slightly higher tolerance when using host BLAS in our unit-test.
I think this should work fine but since Blake is unavailable at the moment we might discover that the tolerance needs to be modified once more during testing...
In any case this should eventually fix the problem and allow us to close #1622
=> ROTMG: loosen unit-test tolerance for Host TPLs

cmake/kokkoskernels_tribits.cmake
Without that change, projects doing `find_package(KokkosKernels 3.X)` with the 3.X version argument would not be able to build against KokkosKernels release 4.0
See kokkos/kokkos#5759
=> CMake: update package COMPATIBILITY mode in anticipation of release 4.0

sparse/tpls/KokkosSparse_spmv_mv_tpl_spec_decl.hpp, test_common/Test_Cuda.hpp
Two updates are made in this PR to allow compilation with cuda/12 using cusparse tpls:
* Renaming of CUSPARSE_MM_ALG_DEFAULT to CUSPARSE_SPMM_ALG_DEFAULT when cuda version >= 12, addressing #1630 
* Renaming the class cuda to Cuda in Test_Cuda.hpp to avoid conflicts within cuda/12 of the form:
```
/ascldap/users/projects/x86-64/cuda/12.0/include/cuda/std/cstddef(26): error: "cuda" has already been declared in the current scope
1 error detected in the compilation of "/ascldap/users/ndellin/kokkos-kernels/common/unit_test/backends/Test_Cuda_Common.cpp".
```
The second change breaks class-naming conventions used for the other backends; I can update those similarly in this PR, or the second item can be addressed differently if devs have alternative suggestions.
This PR is sufficient to get …
=> Cuda/12 with CuSPARSE updates

batched/sparse/src/KokkosBatched_Krylov_Handle.hpp
Fix a documentation error.
I put the WIT label not to use CI tests.
=> Fix an error in Krylov Handle documentation

scripts/docker/Dockerfile.sycl
`Kokkos` `develop` now requires `oneAPI 2023.0.0` for `SYCL`. That's why the nightly builds are currently failing, see https://cloud.cees.ornl.gov/jenkins-ci/blue/organizations/jenkins/KokkosKernels/detail/KokkosKernels/770/pipeline/.
This pull request updates the build to use the same setup as https://github.com/kokkos/kokkos/pull/5813.
=> Update nightly SYCL setup

common/src/KokkosKernels_SimpleUtils.hpp
This prevents compiling with `SYCL`.
=> Replace printf in device code for SYCL

batched/dense/unit_test/Test_Batched_SerialTrmm.hpp, batched/dense/unit_test/Test_Batched_SerialTrtri.hpp, blas/unit_test/Test_Blas3_gemm.hpp, blas/unit_test/Test_Blas3_trmm.hpp, blas/unit_test/Test_Blas3_trsm.hpp, blas/unit_test/Test_Blas_trtri.hpp, perf_test/blas/blas3/KokkosBlas3_gemm_perf_test.hpp, perf_test/blas/blas3/KokkosBlas3_trmm_perf_test.hpp, perf_test/blas/blas3/KokkosBlas_trtri_perf_test.hpp
I am not convinced it is a good idea to use a random seed in the first place, but if you do, since the seed are being taken on the host, you can just use `std::chrono::high_resolution_clock::now().time_since_epoch().count()` directly.
=> Hands off `Kokkos::Impl::clock_tic`

sparse/impl/KokkosSparse_spmv_impl.hpp
Update in response to https://github.com/kokkos/kokkos/pull/5836.
Instead of calling a Kokkos internal function, call ``concurrency`` which is part of the public interface. The two functions have equivalent behavior.
This unblocks PR testing builds with OpenMP.
=> Call concurrency(), not impl_thread_pool_size()

.jenkins/nightly.groovy
#1860 forgot to set the path for the compiler, see https://cloud.cees.ornl.gov/jenkins-ci/blue/organizations/jenkins/KokkosKernels/detail/KokkosKernels/772/pipeline, compare https://github.com/kokkos/kokkos/blob/cba11a18fd70e8cd1c5069c30a9eaad96bab910e/.jenkins#L102-L125.
=> SYCL CI: Specify the full path to the compiler

CMakeLists.txt, perf_test/CMakeLists.txt
The cmake options ``KokkosKernels_ENABLE_PERFTESTS`` and ``KokkosKernels_ENABLE_EXAMPLES`` were not actually used. Both ``perf_test/`` and ``example/`` were always built as long as ``KokkosKernels_ENABLE_ALL_COMPONENTS=ON``.
This makes these options have an effect again. If perftests or examples are enabled but ``KokkosKernels_ENABLE_ALL_COMPONENTS=OFF``, print a message about why they can't actually be enabled.
=> Use the options ENABLE_PERFTEST, ENABLE_EXAMPLES

perf_test/sparse/CMakeLists.txt, perf_test/sparse/KokkosSparse_mdf.cpp, sparse/impl/KokkosSparse_mdf_impl.hpp, sparse/src/KokkosSparse_mdf.hpp, sparse/src/KokkosSparse_mdf_handle.hpp, sparse/unit_test/Test_Sparse_mdf.hpp
Modifying the implementation of MDF to reduce its algorithmic complexity and increase performance where possible.
The changes include the following:
1. only recomputing the discard factor for rows/columns impacted by the last factorization
2. improving the performance of the reduction to rank discard fills from smallest to largest after DF have been updated
=> Mdf alg upgrade

batched/dense/impl/KokkosBatched_Axpy_Impl.hpp, batched/dense/impl/KokkosBatched_Dot_Internal.hpp, batched/dense/impl/KokkosBatched_Gemv_TeamVector_Impl.hpp, batched/dense/impl/KokkosBatched_Gemv_Team_Impl.hpp, batched/dense/impl/KokkosBatched_Gesv_Impl.hpp, batched/dense/impl/KokkosBatched_HadamardProduct_Impl.hpp, batched/dense/impl/KokkosBatched_Xpay_Impl.hpp, batched/sparse/impl/KokkosBatched_Spmv_Serial_Impl.hpp, batched/sparse/impl/KokkosBatched_Spmv_TeamVector_Impl.hpp, batched/sparse/impl/KokkosBatched_Spmv_Team_Impl.hpp, blas/impl/KokkosBlas1_axpby_impl.hpp, blas/impl/KokkosBlas1_axpby_mv_impl.hpp, blas/impl/KokkosBlas1_axpby_spec.hpp, blas/impl/KokkosBlas2_team_gemv_spec.hpp, blas/src/KokkosBlas1_axpby.hpp, blas/src/KokkosBlas1_nrm2.hpp, blas/tpls/KokkosBlas1_axpby_tpl_spec_avail.hpp, blas/tpls/KokkosBlas1_axpby_tpl_spec_decl.hpp, blas/tpls/KokkosBlas1_dot_tpl_spec_avail.hpp, blas/tpls/KokkosBlas1_iamax_tpl_spec_avail.hpp, blas/tpls/KokkosBlas1_nrm1_tpl_spec_avail.hpp, blas/tpls/KokkosBlas1_nrm2_tpl_spec_avail.hpp, blas/tpls/KokkosBlas1_nrminf_tpl_spec_avail.hpp, blas/tpls/KokkosBlas1_scal_tpl_spec_avail.hpp
`View::Rank` is not documented and may get deprecated (see kokkos/kokkos#5870)
To be on the safe side, avoid using it.
=> Prefer `Kokkos::View::{R->r}ank`

sparse/src/KokkosSparse_Utils.hpp, sparse/unit_test/Test_Sparse.hpp, sparse/unit_test/Test_Sparse_Utils.hpp, sparse/unit_test/Test_Sparse_removeCrsMatrixZeros.hpp, sparse/unit_test/Test_Sparse_spgemm.hpp
And testing for it. It removes explicit zeros (or, entries where $|A_{ij}| \leq tol$) - tol defaults to 0 - from a matrix and returns a new matrix. If A has no entries to remove, A is returned unchanged. It does not change the matrix dimensions or the order of non-removed entries within rows.
Also move the test helper function ``is_same_matrix`` from Test_Sparse_spgemm.hpp to Test_Sparse_Utils.hpp, since I needed it for this test (and probably other tests could use it too).
=> Add utility KokkosSparse::removeCrsMatrixZeros(A, tol)

blas/src/KokkosBlas1_dot.hpp, blas/src/KokkosBlas1_nrm1.hpp, blas/src/KokkosBlas1_nrm2_squared.hpp, blas/src/KokkosBlas1_nrm2w_squared.hpp, blas/unit_test/Test_Blas1_axpby.hpp, blas/unit_test/Test_Blas1_axpy.hpp, blas/unit_test/Test_Blas1_dot.hpp, blas/unit_test/Test_Blas1_iamax.hpp, blas/unit_test/Test_Blas1_mult.hpp, blas/unit_test/Test_Blas1_nrm1.hpp, blas/unit_test/Test_Blas1_nrm2.hpp, blas/unit_test/Test_Blas1_nrm2w.hpp, blas/unit_test/Test_Blas1_nrm2w_squared.hpp, blas/unit_test/Test_Blas1_nrminf.hpp, blas/unit_test/Test_Blas1_reciprocal.hpp, blas/unit_test/Test_Blas1_scal.hpp, blas/unit_test/Test_Blas1_sum.hpp, blas/unit_test/Test_Blas1_team_update.hpp, blas/unit_test/Test_Blas1_update.hpp, blas/unit_test/Test_Blas2_gemv.hpp, blas/unit_test/Test_Blas2_gemv_util.hpp, blas/unit_test/Test_Blas3_gemm.hpp, sparse/impl/KokkosSparse_par_ilut_numeric_impl.hpp, sparse/unit_test/Test_Sparse_spmv.hpp, sparse/unit_test/Test_Sparse_spmv_bsr.hpp
Fixing some issues with blas tests when non-ETI types are tested and adding new test for mixed precision gemm
=> Gemm mixed scalars

common/src/KokkosKernels_PrintUtils.hpp
The bounds on this loop is a `Kokkos::Impl::integral_constant`, which is not appropriate for the iteration variable. So cast it to `int`.
=> cast Kokkos::Impl::integral_constant to int

blas/unit_test/Test_Blas1_nrm2w.hpp, blas/unit_test/Test_Blas1_nrm2w_squared.hpp, blas/unit_test/Test_Blas1_reciprocal.hpp, blas/unit_test/Test_Blas1_team_mult.hpp, blas/unit_test/Test_Blas1_team_update.hpp, blas/unit_test/Test_Blas2_gemv.hpp
Mostly fixing issues that stemed from not running these tests on a regular basis, for instance generating FPE because of changes in how random inputs are generated.
With the changes in this PR, Kokkos Kernels using the CI configuration for GCC1020 builds and runs fine with `-D KokkosKernels_TEST_ETI_ONLY=OFF` this would allow us to test for mixed scalar types in one of our builds...
=> Test mixed scalars: more fixes related to mixed scalar tests

blas/unit_test/Test_Blas1_team_mult.hpp
Evidently the `a` need to be cast as a magnitude type for this to make sense x)
=> team mult: fix type issue in max_error calculation

CMakeLists.txt
It appears that we need to use the upper case spelling of the variables defining the current version of Kokkos Kernels. I'm not totally sure why but it could have something to do with the fact that we are re-using the same variable names twice...
=> Kokkos Kernels version: need to use upper case variables

batched/KokkosBatched_Util.hpp
Compatibility upgrade: adding compatibility branch in code with the `#ifdef` introduced, the code will compile against 4.0.0 and develop versions of Kokkos Core.
=> 4.0.0 compatibility

blas/src/KokkosBlas1_mult.hpp, blas/src/KokkosBlas1_nrm2w.hpp, blas/src/KokkosBlas1_reciprocal.hpp
I noticed a couple documentation typos in https://kokkos-kernels.readthedocs.io/en/latest/.
Leaving the `AT: WIP` label applied here such that only github-{DOCS,FORMAT} CI checks are run. There is no need to run a full build and test.
=> blas/blas1: Fix a couple documentation typos.

sparse/src/KokkosSparse_Utils_rocsparse.hpp, sparse/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp
This uses the three-phase `rocsparse_spmv_ex` for rocm >= 5.4.0.
`rocsparse_spmv_stage_auto` is used - the first call returns the buffer size, and the second call does preprocessing and SpMV.
This PR also introduces an IMPL macro to get the rocm version.
We use this rather than the rocSparse version since the rocSparse docs are versioned in terms of the rocm release.
=> use rocsparse_spmv_ex for rocm >= 5.4.0

sparse/tpls/KokkosSparse_spmv_mv_tpl_spec_decl.hpp
This may have actually been deprecated as early as 11.0, but the online documentation is down so I can't check for sure.
=> CUSPARSE_MM_ALG_DEFAULT deprecated by cuSparse 11.1

sparse/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp
=> rocsparse spmv tpl: Fix rocsparse_spmv call for rocm < 5.4.0

common/src/KokkosKernels_Iota.hpp, common/unit_test/Test_Common.hpp, common/unit_test/Test_Common_Iota.hpp
Needed for merge-based SpMV PR https://github.com/kokkos/kokkos-kernels/pull/1501
A lightweight struct for which `operator()(i) -> i + offset`
This is a convenient substitution for an iota view that doesn't require any memory accesses.
Since it doesn't implement `deep_copy` or `subview` we don't want our users using it.
=> Adds KokkosKernels::Impl::Iota, a view-like where iota(i) = i + offset

batched/dense/impl/KokkosBatched_Eigendecomposition_Serial_Internal.hpp, sparse/impl/KokkosSparse_spmv_struct_impl.hpp
`KOKKOS_IF_ON_{HOST,DEVICE}` macros are always defined since Kokkos release 3.6 and current develop does not even build any more against Kokkos 3.7
=> Drop obsolete workaround `#ifdef KOKKOS_IF_ON_HOST`

sparse/impl/KokkosSparse_sptrsv_cuSPARSE_impl.hpp, sparse/src/KokkosSparse_sptrsv_handle.hpp, sparse/tpls/KokkosSparse_spgemm_numeric_tpl_spec_decl.hpp
This basically removes a few function parameters that are unused in the cuda branch for version higher than 11.4.
=> CUDA 11.4: fixing some failing build while trying to reproduce issue #1725

.github/workflows/docs.yml, docs/CMakeLists.txt
Makes it easier to hack on the docs locally without Sphinx.
Replaces https://github.com/kokkos/kokkos-kernels/pull/1713
=> Allow an HTML-only docs build

perf_test/Benchmark_Context.hpp, perf_test/CMakeLists.txt, perf_test/blas/blas1/KokkosBlas_dot_mv_perf_test_benchmark.cpp, perf_test/blas/blas1/KokkosBlas_dot_perf_test_benchmark.cpp, perf_test/blas/blas1/KokkosBlas_team_dot_perf_test_benchmark.cpp
This PR provides a first example converting one blas test (KokkosBlas_dot) to using google bench. 
The idea is that to show what the tests would look like and what output they generate, and if accepted, we can use the same "structure" for porting all other performance tests
Configuration to enable benchmark:
cmake .<KOKKOS-KERNELS_SOURCE_DIR> -DKokkos_DIR:DIR==<KOKKOS_INSTALL_DIR>/lib/cmake/Kokkos -DKokkosKernels_ENABLE_BENCHMARK=ON -DKokkosKernels_ENABLE_TESTS=ON -DKokkosKernels_ENABLE_ALL_COMPONENTS=ON -DKokkosKernels_ENABLE_PERFTESTS=ON
The file containing the code that was changed is this: https://github.com/kokkos/kokkos-kernels/pull/1636/files#diff-467ac095c3b5b7db0d220fbfa379fe328b2024ff6d516cd80a910cdcbeb78c1a"
See below the json output from googlebench that gives a summary of the …
=> #5 Refactor blas1 test for benchmark feature

sparse/src/KokkosSparse_IOUtils.hpp
Use bandwidth to cap the max entries per row, so that the row-filling loop doesn't run forever looking for a column that isn't already present.
=> Fix kk_generate_diagonally_dominant_sparse_matrix hang

perf_test/KokkosKernels_perf_test_utilities.hpp
Make the device ids (like ``--cuda <id>``) use zero-based numbering to be consistent with behavior of Kokkos and other perf tests.If a machine has one GPU, then ``--cuda 0`` should select it. Before, ``--cuda 1`` was necessary to select it, and ``--cuda 0`` would not enable Cuda at all.
=> perf test utils: fix device ID parsing

common/src/KokkosKernels_PrintConfiguration.hpp, common/src/KokkosKernels_TplsVersion.hpp
This PR provides a way to get and print CUBLAS and CUSPARSE TPLs version.
The idea is to print the TPL version instead of 'yes' when the TPL is activated. We still print 'no' if the TPL is not activated.
<details>
<summary> extract of the test with CUBLAS and CUSPARSE TPLs activated </summary>
```
KokkosKernels Version: 4.0.99
TPLs: 
1:   KOKKOSKERNELS_ENABLE_TPL_LAPACK: no
1:   KOKKOSKERNELS_ENABLE_TPL_BLAS: no
1:   KOKKOSKERNELS_ENABLE_TPL_CBLAS: no
1:   KOKKOSKERNELS_ENABLE_TPL_LAPACKE: no
1:   KOKKOSKERNELS_ENABLE_TPL_SUPERLU: no
1:   KOKKOSKERNELS_ENABLE_TPL_CHOLMOD: no
1:   KOKKOSKERNELS_ENABLE_TPL_MKL: no
1:   KOKKOSKERNELS_ENABLE_TPL_CUBLAS: 11.10.125
1:   KOKKOSKERNELS_ENABLE_TPL_CUSPARSE: 11.7.350
1:   KOKKOSKERNELS_ENABLE_TPL_ROCBLAS: no
1:   KOKKOSKERNELS_ENABLE_TPL_ROCSPARSE: …
```
=> #5: added TplsVersion file and  print methods

batched/dense/unit_test/Test_Batched_BatchedGemm.hpp
=> Reduce BatchedGemm test coverage

CMakeLists.txt, cmake/KokkosKernels_Version_Info.hpp.in, cmake/kokkoskernels_benchmarks.cmake, cmake/kokkoskernels_version_info.cmake, perf_test/Benchmark_Context.hpp, perf_test/CMakeLists.txt
fixes #1718 (3.)
Include google/benchmark library version in benchmark output.
Sample output (console):
```
2023-03-22T17:43:14+01:00
Running ./build/perf_test/KokkosKernels_PerformanceTest_Benchmark
(...)GIT_BRANCH: 1718-print-google-benchmark-version
GIT_CLEAN_STATUS: CLEAN
GIT_COMMIT_DATE: 2023-03-22T17:42:42+01:00
GIT_COMMIT_DESCRIPTION: Clarify comments for context helper functions
GIT_COMMIT_HASH: f1005386c
GOOGLE_BENCHMARK_VERSION: 1.6.2
(...)
```
Note: this also moves benchmark related CMake code around and cleans it up a bit (1554ee7).
=> Include `google/benchmark` lib version in benchmark output

batched/dense/impl/KokkosBatched_Axpy_Impl.hpp, batched/dense/impl/KokkosBatched_Copy_Impl.hpp, batched/dense/impl/KokkosBatched_Dot_Internal.hpp, batched/dense/unit_test/Test_Batched_TeamVectorQR.hpp, batched/dense/unit_test/Test_Batched_TeamVectorQR_WithColumnPivoting.hpp
This PR adds calls to KokkosBlas functions for 2 KokkosBatched functions when the number of systems per team is equal to 1.
This has been tested on my workstation.
=> Add calls to KokkosBlas Dot and Axpy for team batched kernels when m==1

common/src/KokkosKernels_SimpleUtils.hpp, sparse/src/KokkosSparse_SortCrs.hpp, sparse/unit_test/Test_Sparse_SortCrs.hpp
For each existing overload of the sort/sort_and_merge utilities (for crs matrix, crs graph, bsr matrix), add a version that accepts an execution space instance. The functions that don't take an instance are now implemented in terms of the ones that do. This takes care of #1724 and works towards #1119 .
Test the new overloads.
=> Add exec instance support to sort/sort_and_merge utils

common/src/KokkosKernels_SimpleUtils.hpp, sparse/src/KokkosSparse_spgemm_handle.hpp, sparse/src/KokkosSparse_spgemm_numeric.hpp, sparse/src/KokkosSparse_spgemm_symbolic.hpp, sparse/unit_test/Test_Sparse_spgemm.hpp
Resolves #1738. The graphs (rowptrs/entries) of A, B and C can't
change for a given spgemm handle (over all symbolic and numeric calls).
This adds checks to symbolic and numeric for this (the raw pointers of
rowptrs/entries are recorded in the handle, and then compared against in
all subsequent calls).
Since the A/B values views are allowed to change in between numeric calls, strengthen the spgemm reuse testing to actually reallocate those views (not just fill them with new values).
Tested on serial+openmp+cuda without TPLs, then with cusparse, rocsparse and MKL.
=> spgemm handle: check that A,B,C graphs never change

batched/dense/impl/KokkosBatched_Gesv_Impl.hpp
Explicitly initializing the reducer type avoids warning in the nightly GCC 910 build.
This work fix the problem reported in #1771
=> Batched Gesv: initializing variable to make compiler happy

sparse/src/KokkosSparse_SortCrs.hpp, sparse/unit_test/Test_Sparse_SortCrs.hpp
- Don't initialize views unnecessarily
- Early exit if no entries were merged
- More rigorous const-correctness: input rowmap always treated as const-valued, output may be const or nonconst
- View-based interface for matrices, like graph already had
- Beef up unit tests (graph, empty cases, early-exit case with zero merges)
=> Sort and merge improvements

sparse/impl/KokkosSparse_mdf_impl.hpp, sparse/src/KokkosSparse_mdf.hpp, sparse/unit_test/Test_Sparse_mdf.hpp
@lucbv 
Adds distinction between scalar_type and it's magnitude type for support of non-arithmetic types e.g. Kokkos::complex . Also skips verbose prints on non-arithmetics.
=> add support for complex data types in MDF

cmake/Modules/FindTPLMKL.cmake
This PR aims to update the FindTPLMKL.cmake in order to use a modern version of MKL.
Based on KOKKOS_ENABLE_SYCL option coming from kokkos, it permits to use MKL with sycl.
=> Refactor MKL TPL for both CPU and GPU usage

sparse/impl/KokkosSparse_par_ilut_numeric_impl.hpp, sparse/src/KokkosKernels_Handle.hpp, sparse/src/KokkosSparse_par_ilut_handle.hpp, sparse/unit_test/Test_Sparse_par_ilut.hpp
Default async updates to off since we can't trust it to work everywhere all the time, even with Atomic Ut_values. I think this is the best approach since we will likely be revisiting the compute_l_u_factors implementation anyway.
Fixes #1775
=> par_ilut: make Ut_values view atomic in compute_l_u_factors

perf_test/blas/blas3/CMakeLists.txt, perf_test/blas/blas3/KokkosBlas3_gemm_standalone_perf_test_benchmark.cpp
Note: to avoid later conflicts, this contains changes from PR #1733. Changes specific to this PR are in `blas3` directory.
Sample output:
```
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Benchmark                                                  Time             CPU   Iterations Avg GEMM (FLOP/s): Avg GEMM time (s): Memory Layout in A: LayoutLeft Memory Layout in B: LayoutLeft     OpenMP
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- …
```
=> Refactor blas3 tests to use benchmark library

.github/workflows/docs.yml
Using, `AT: WIP`. There is no need to run the other CI checks on these changes.
=> scripts: Fix github-DOCS

.github/workflows/docs.yml
Github suggests this, as the cache may be very out of date to keep builds consistent
https://docs.github.com/en/actions/using-github-hosted-runners/customizing-github-hosted-runners
=> apt-get update in hosted runner docs check

scripts/cm_test_all_sandia
When re-running CI tests locally, I had to manually set the OMP runtime settings. This PR adds those settings to reload_modules.sh, which is part of the reproducer instructions.
=> scripts: Include OMP settings

blas/impl/KokkosBlas1_abs_impl.hpp, blas/impl/KokkosBlas1_abs_spec.hpp, blas/impl/KokkosBlas1_axpby_impl.hpp, blas/impl/KokkosBlas1_axpby_mv_impl.hpp, blas/impl/KokkosBlas1_axpby_spec.hpp, blas/impl/KokkosBlas1_mult_impl.hpp, blas/impl/KokkosBlas1_mult_spec.hpp, blas/impl/KokkosBlas1_reciprocal_impl.hpp, blas/impl/KokkosBlas1_reciprocal_spec.hpp, blas/impl/KokkosBlas1_scal_impl.hpp, blas/impl/KokkosBlas1_scal_mv_impl.hpp, blas/impl/KokkosBlas1_scal_spec.hpp, blas/impl/KokkosBlas1_update_impl.hpp, blas/impl/KokkosBlas1_update_spec.hpp, blas/src/KokkosBlas1_abs.hpp, blas/src/KokkosBlas1_axpby.hpp, blas/src/KokkosBlas1_fill.hpp, blas/src/KokkosBlas1_mult.hpp, blas/src/KokkosBlas1_reciprocal.hpp, blas/src/KokkosBlas1_scal.hpp, blas/src/KokkosBlas1_update.hpp, blas/tpls/KokkosBlas1_abs_tpl_spec_avail.hpp, blas/tpls/KokkosBlas1_axpby_tpl_spec_avail.hpp, blas/tpls/KokkosBlas1_axpby_tpl_spec_decl.hpp, blas/tpls/KokkosBlas1_mult_tpl_spec_avail.hpp, blas/tpls/KokkosBlas1_reciprocal_tpl_spec_avail.hpp, blas/tpls/KokkosBlas1_scal_tpl_spec_avail.hpp, blas/tpls/KokkosBlas1_scal_tpl_spec_decl.hpp, blas/tpls/KokkosBlas1_update_tpl_spec_avail.hpp, perf_test/blas/blas3/KokkosBlas3_gemm_standalone_perf_test_benchmark.cpp
Implementing an execution space interface for BLAS1 functions that were not included in PR #1795 
Basically these are kernels that do not perform reductions and are hence a little easier to handle in my opinion.
These new interfaces will be useful for libraries and applications that use Kokkos Kernels and have already started executing there kernels on streams/queues and need to either use the same stream/queue with Kokkos Kernels or at least need to synchronize with it.
=> Blas1 on stream

blas/src/KokkosBlas1_abs.hpp, blas/src/KokkosBlas1_axpby.hpp, blas/src/KokkosBlas1_fill.hpp, blas/src/KokkosBlas1_mult.hpp, blas/src/KokkosBlas1_reciprocal.hpp, blas/src/KokkosBlas1_scal.hpp, blas/src/KokkosBlas1_update.hpp, docs/developer/apidocs/blas1.rst
updating documentation for changes in PR #1803, this PR will be rebased once #1803 is merged.
It mostly includes additional overloads of our BLAS1 functions to accept an execution space instance.
Additional documentation improvement have been made as well.
=> Blas1: docs update for PR #1803

docs/developer/apidocs/sparse.rst, docs/developer/build_doc.rst, docs/developer/contrib.rst, sparse/src/KokkosSparse_gauss_seidel.hpp, sparse/src/KokkosSparse_gmres.hpp, sparse/src/KokkosSparse_par_ilut.hpp, sparse/src/KokkosSparse_spgemm.hpp
@jgfouca: Please fill in the comment content for `par_ilut`
@jennloe: Please fill in the comment content for `gmres`
@brian-kelley: Please fill in the comment content for `gauss_seidel` and `block_gauss_seidel`
@lucbv: Please fill in the comment content for `spgemm` and `block_spgemm`
Feel free to open PRs against `more_sparse_docs` or just use the suggested changes feature.
Using `AT: WIP` since there's no need to run more than github-DOCS and github-FORMAT on these changes.
=> docs: Add stubs for some sparse APIs

perf_test/Benchmark_Context.hpp, perf_test/sparse/CMakeLists.txt, perf_test/sparse/KokkosSparse_par_ilut.cpp, sparse/impl/KokkosSparse_par_ilut_numeric_impl.hpp, sparse/unit_test/Test_Sparse_par_ilut.hpp
Change list:
1) Adds a new perf_test/sparse test, spare_par_ilut that can test performance of our par_ilut, ginkgo's par_ilut, and our spiluk.
2) Adds ability to interface KK sparse perf tests with Ginkgo via the CMake option `Ginkgo_DIR`
3) Couple other minor cleanups.
Perf test results:
All tests were done with a randomly generated NxN sparse matrix that is **1% nnz and bandwidth=5%**, taking the best time out of 4 runs.
OMP:
It looks like our OMP performance is very similar to ginkgo. Our impl seems to do comparatively better for lower thread counts and high row counts. The big surprise here is spiluk, which appears to show no speedup as threads are increased. Spiluk is much faster for low thread counts but, since it doesn't improve with more threads, gets passed by the other two …
=> New performance test for par_ilut, ginkgo::par_ilut, and spill

sparse/unit_test/Test_Sparse_spgemm.hpp
Disable issue 1738 test in spgemm, if in cuda 11.0-11.3 and cusparse is enabled. For some reason (that appears to be a compiler bug?) _other_ spgemm tests hang after this particular unit test is run.
I talked with F. Busato about this and it appears that the wrapper for the cuSPARSE non-reuse spgemm functions is correct, and the way we use it is valid. The non-reuse interface is used in this version range by all our spgemm tests. So as far as I can tell there isn't an actual code bug here.
=> Workaround for #1777 - cusparse spgemm test hang

blas/tpls/KokkosBlas1_scal_tpl_spec_avail.hpp
Fixes ExecSpace vs EXECSPACE naming mismatch in `blas/tpls/KokkosBlas1_scal_tpl_spec_avail.hpp` following #1803 
Caught in the rocm tpl nightly build that enables rocblas and rocsparse
This change should resolve compilation errors of the form:
```
05:12:41 /home/jenkins/caraway-new/workspace/KokkosKernels_CarawayMI100_Rocm520_HipSerial_RocBlas_RocSparse/kokkos-kernels/blas/tpls/KokkosBlas1_scal_tpl_spec_avail.hpp:119:1: error: use of undeclared identifier 'ExecSpace'
```
=> Fix name mismatch with rocblas tpl spec layer for scal

docs/developer/apidocs/sparse.rst, graph/impl/KokkosGraph_Distance2MIS_impl.hpp, sparse/src/KokkosSparse_CooMatrix.hpp, sparse/src/KokkosSparse_ccs2crs.hpp, sparse/src/KokkosSparse_coo2crs.hpp, sparse/src/KokkosSparse_crs2ccs.hpp, sparse/src/KokkosSparse_crs2coo.hpp, sparse/unit_test/Test_Sparse.hpp, sparse/unit_test/Test_Sparse_TestUtils_RandCsMat.hpp, sparse/unit_test/Test_Sparse_coo2crs.hpp, sparse/unit_test/Test_Sparse_crs2coo.hpp, test_common/KokkosKernels_TestUtils.hpp
Depends on https://github.com/kokkos/kokkos/pull/5877.
Adds a coo2crs implementation which relies on `Kokkos::UnorderedMap`:
- An array of nrow unordered maps is created
- The coo entires are inserted into these unordered maps
- The coo row index determines which unordered map to insert into
- The coo col index is the key into the given unordered map
- Negative indices are ignored
- Duplicate i,j entries are summed
- The row map is computed from the size of each unordered map
- At the end we copy the values and col ids into the crs members
Adds crs2coo:
- This iterates over the crs and writes each i,j,v into the coo matrix
CooMatrix:
- This is a minimal CooMatrix for coo2crs/crs2coo convenience wrappers that accept/return a CooMatrix type.
Related to …
=> sparse: Add coo2crs, crs2coo and CooMatrix

blas/unit_test/Test_Blas_gesv.hpp, scripts/cm_test_all_sandia
cm_test_all_sandia: adds a BLAS module to load when TPLs are enabled
Changes how KokkosBlas::gesv unit tests are enabled so they are only enabled for supported backends.
=> Add `KokkosKernels_PullRequest_VEGA908_Tpls_ROCM520` support, only enable `KokkosBlas::gesv` where supported

blas/tpls/KokkosBlas1_nrm1_tpl_spec_avail.hpp, blas/tpls/KokkosBlas1_nrm1_tpl_spec_decl.hpp, blas/tpls/KokkosBlas1_scal_tpl_spec_decl.hpp, blas/tpls/KokkosBlas2_ger_tpl_spec_avail.hpp
A few more fixes to add commas missed in some macros
Resolves errors of type:
```
05:12:42 /home/jenkins/caraway-new/workspace/KokkosKernels_CarawayMI100_Rocm520_HipSerial_RocBlas_RocSparse/kokkos-kernels/blas/tpls/KokkosBlas1_scal_tpl_spec_decl.hpp:261:14: error: expected comma in macro parameter list
05:12:42     MEMSPACE ETI_SPEC_AVAIL) 
...
```
=> Fix rocblas build 2

common/src/KokkosKernels_AlwaysFalse.hpp, sparse/impl/KokkosSparse_bsr_to_crs_impl.hpp, sparse/impl/KokkosSparse_crs_to_bsr_impl.hpp, sparse/impl/KokkosSparse_spmv_bsrmatrix_spec.hpp, sparse/src/KokkosSparse_BsrMatrix.hpp, sparse/src/KokkosSparse_Utils_rocsparse.hpp, sparse/src/KokkosSparse_spmv.hpp, sparse/tpls/KokkosSparse_spmv_bsrmatrix_tpl_spec_avail.hpp, sparse/tpls/KokkosSparse_spmv_bsrmatrix_tpl_spec_decl.hpp, sparse/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp, sparse/unit_test/Test_Sparse_TestUtils_RandCsMat.hpp, sparse/unit_test/Test_Sparse_ccs2crs.hpp, sparse/unit_test/Test_Sparse_crs2ccs.hpp, sparse/unit_test/Test_Sparse_crs2coo.hpp, sparse/unit_test/Test_Sparse_rocsparse.hpp, sparse/unit_test/Test_Sparse_spmv_bsr.hpp, test_common/KokkosKernels_TestUtils.hpp
This adds 
* `rocsparse_*bsrmv` for `BsrMatrix` SpMV when rocSparse TPL is enabled.
* conversion utilities between `CrsMatrix` and `BsrMatrix`
* Expands the flexibility of the `RandCsMatrix`
* Rewrites the BsrMatrix SpMV unit test to catch basic errors (e.g. wrong nnz value)
=> Add BsrMatrix SpMV in rocSparse TPL, rewrite BsrMatrix SpMV unit tests

common/unit_test/Test_Common_LowerBound.hpp, common/unit_test/Test_Common_UpperBound.hpp, sparse/unit_test/Test_Sparse_spmv_bsr.hpp
Fix errors and warnings in cuda 11.1/gcc 8.3.0 RHEL nightly builds.
- Errors: it looks like CTAD isn't working in 8.3, because "Kokkos::pair(...)" causes build error but "Kokkos::make_pair(...)" does not
- Warnings: 8.3 is also bad at figuring out that if both branches of "if constexpr" have return statements, that the function as a whole must end in a return
=> Fix errors and warnings in sems-rhel nighly

sparse/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp
resolves compilation errors when enabling cusparse with cuda/11.1
=> spmv cusparse version check modified for cuda/11.1

perf_test/sparse/KokkosSparse_spgemm_jacobi.cpp
The `KOKKOSKERNELS_INST_MEMSPACE_CUDAHOSTPINNEDSPACE` is never defined.
=> Remove dead code guarded by `#ifdef KOKKOSKERNELS_INST_MEMSPACE_CUDAHOSTPINNEDSPACE`

sparse/tpls/KokkosSparse_spmv_bsrmatrix_tpl_spec_avail.hpp, sparse/tpls/KokkosSparse_spmv_bsrmatrix_tpl_spec_decl.hpp
Trying to close https://github.com/kokkos/kokkos-kernels/issues/1829
Don't use the `*_ex*` functions before rocm 5.4.0
=> Support rocSparse in rocm 5.2.0

scripts/cm_test_all_sandia
`cm_generate_makefile` already knows what to do with these TPLs, but `cm_test_all_sandia` was not telling it to turn them on.
=> Add `rocsparse,rocblas,` to enabled TPLs in `cm_test_all_sandia` when `--spot-check-tpls`

BUILD.md, cmake/kokkoskernels_eti_devices.cmake
Kokkos_ENABLE_OpenMP* to Kokkos_ENALBE_OPENMP*
Related to trilinos/Trilinos#11930 and kokkos/kokkos#6138
=> Update cmake option naming in docs/comments

common/CMakeLists.txt
This matches the commit https://github.com/trilinos/Trilinos/pull/11863/commits/29fab02654a91f093ecbcecc325f7e9243ecde11 in Trilinos PR:
* https://github.com/trilinos/Trilinos/pull/11863
See the commit message for more details.
=> KokkosKernels: Remove non-existent common/src/[impl,tpls] include dirs (trilinos/Trilinos#11545)

docs/developer/index.rst, docs/developer/profiling.rst
This PR adds documentation explaining how to profile compile times with ClangBuildAnalyzer.
I've added `AT: WIP` since this does not require CI testing other than github-DOCS.
Fixes #1832.
=> docs: Add profiling for compile times

batched/dense/unit_test/Test_Batched_VectorView.hpp
=> batched/unit_test: Disable simd dcomplex4 test in for intel > 19.05 and <= 2021.

common/src/KokkosKernels_Error.hpp, perf_test/sparse/CMakeLists.txt, perf_test/sparse/KokkosSparse_par_ilut.cpp, perf_test/sparse/KokkosSparse_spmv_benchmark.cpp
1) Make better use of google benchmark in par_ilut benchmark
2) Re-enable par_ilut benchmark, warnings should be fixed
3) Add new KK_USER_REQUIRE macros to KokkosKernels_Error. Makes it
convenient to check and throw a good exception for user errors.
4) Fix option help in spmv benchmark (was saying -s instead of -n)
5) Fix option parsing in spmv benchmark. Bad options were printed to cerr
but program execution was not halted.
6) Fix google bm argument list in spmv benchmark. It was always reporting
n=100000 even when that was not the case. It will still report an incorrect
n if an input A is used, but this is a step in the right direction. This
requires run_spmv to a spmv_parameters object instead of argc/argv.
7) Use register_benchmark_real_time in spmv benchmark. The code there was …
=> Benchmark cleanup for par_ilut and spmv

sparse/src/KokkosSparse_BsrMatrix.hpp
@vqd8a reported that gcc 8 is erroring out here (thanks for reporting this, @vqd8a!). This is a known gnu bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=81429.
Fixes #1862.
=> sparse/src: Work around gnu compiler bug

batched/CMakeLists.txt
This matches the commit https://github.com/bartlettroscoe/kokkos-kernels/commit/aee776e44588481b2b99cb047c1b572f77c66ef7 in Trilinos PR:
* https://github.com/trilinos/Trilinos/pull/11966
This is a clear defect that just happens to not cause a problem unless you try to use the KokkosKernelsTargets.cmake file generated for the build dir (see https://github.com/trilinos/Trilinos/pull/11966#issuecomment-1590146876).
See the log message and embedded comment for more details.
=> KokkosKernels: Don't list include for non-existant 'batched' build dir (trilinos/Trilinos#11966)

blas/unit_test/Test_Blas2_syr.hpp
The compilation error happens in kk syr unit tests, independent of any interactions with, or calls from, Trilinos.
I was able to replicate the problem at weaver with some of the information in the error email sent by Nathan. I think the key aspect causing the error was the presence of CudaUVM options in the configurations of Kokkos and kk. I will include those options in my own work from now on.
+- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
1) Environment:
ssh weaver
bsub -Is -n 1 -q rhel8 -gpu num=1 bash
source /etc/profile.d/modules.sh
source /projects/ppc64le-pwr9-rhel8/legacy-env.sh
module load git
module load cmake/3.23.1
module load cuda/11.2.2/gcc/8.3.1
module load openblas/0.3.18/gcc/8.3.1
+- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - …
=> Correcting 'syr test' bug causing compilation errors with Trilinos

blas/tpls/KokkosBlas2_serial_gemv_tpl_spec_decl.hpp, perf_test/sparse/KokkosSparse_spadd.cpp, sparse/tpls/KokkosSparse_spgemm_noreuse_tpl_spec_avail.hpp, sparse/tpls/KokkosSparse_spgemm_noreuse_tpl_spec_decl.hpp, sparse/tpls/KokkosSparse_spgemm_numeric_tpl_spec_avail.hpp, sparse/tpls/KokkosSparse_spgemm_numeric_tpl_spec_decl.hpp, sparse/tpls/KokkosSparse_spgemm_symbolic_tpl_spec_avail.hpp, sparse/tpls/KokkosSparse_spgemm_symbolic_tpl_spec_decl.hpp, sparse/tpls/KokkosSparse_spmv_bsrmatrix_tpl_spec_avail.hpp, sparse/tpls/KokkosSparse_spmv_bsrmatrix_tpl_spec_decl.hpp, sparse/tpls/KokkosSparse_spmv_tpl_spec_avail.hpp, sparse/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp
Modifying the TPL support for MKL to use the MKL_INT in favor of int when indexing sparse matrices.
This allows us to building against 32 bit and 64 bit installations of MKL
=> MKL: support indices properly

blas/tpls/KokkosBlas2_syr_tpl_spec_decl_rocblas.hpp
- Rename uploChar to uplo in fillMode for consistency with usage
- Dereference uplo in fillMode usage for comparison to char
=> Fix for rocblas builds

batched/dense/impl/KokkosBatched_HostLevel_Gemm_Impl.hpp
Guard use of `rank_dynamic` for KOKKOS_VERSION > 40099 (i.e. 4.1 and above)
=> Backward-compatible fix with kokkos@4.0

perf_test/KokkosKernels_perf_test_instantiation.hpp, perf_test/KokkosKernels_perf_test_utilities.hpp, perf_test/sparse/KokkosSparse_spadd.cpp, perf_test/sparse/KokkosSparse_spgemm.cpp
I noticed that some perf tests like graph_triangle use the common infrastructure, but weren't able to print the help text unless an available backend was selected. So now help is printed whenever the user passes "-h" or "--help", no matter what the configuration is.
- Have common infrastructure detect "-h" and "--help", and print options
- In help text, distinguish between enabled and non-enabled backends
For build with OpenMP only, ``./graph_triangle -h`` output before:
```
ERROR: Tried to run on Serial device (as no parallel backends requested), but Serial is not enabled.
```
output after:
```
Options
[Required] Backend: the available backends are:
'--openmp [numThreads]'
The following backends are not available because Kokkos was not configured with them:
'--threads [numThreads]'
... …
```
=> Improve help text in perf tests

sparse/src/KokkosSparse_Utils_mkl.hpp, sparse/src/KokkosSparse_spmv.hpp, sparse/tpls/KokkosSparse_spgemm_symbolic_tpl_spec_avail.hpp, sparse/tpls/KokkosSparse_spmv_tpl_spec_avail.hpp, sparse/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp, sparse/unit_test/Test_Sparse.hpp
@jczhang07 
Adding support for oneMKL spmv, this should provide the users with good options for their use cases.
A follow on will be needed for the multivector case but it does not need to happen at this time.
=> oneMKL spmv

batched/KokkosBatched_Util.hpp
in batched dense.
In this example, everything that should be needed to run a SerialCopy is included, but without this include the ``KOKKOSKERNELS_DEBUG_LEVEL`` macro isn't defined so static_asserts in the impl of SerialCopy are skipped when they shouldn't be.
```
#include "Kokkos_Core.hpp"
#include "KokkosBatched_Copy_Decl.hpp"
int main()
{
Kokkos::initialize();
{
Kokkos::View<double*> v1("v1", 10);
Kokkos::View<double*> v2("v2", 10);
KokkosBatched::SerialCopy<KokkosBatched::Trans::NoTranspose>::invoke(v1, v2);
}
Kokkos::finalize();
return 0;
}
```
=> Add missing KokkosKernels_Macros.hpp include

sparse/src/KokkosSparse_spgemm.hpp
It was suggested by the Trilinos project to submit a PR here for a problem I was having in Trilinos.  I don't know if MSVC is in your test matrix, but this is a simple change that shouldn't affect any results and will allow compilation on MSVC.
=> Change 'or' to '||' to fix compilation on MSVC

sparse/src/KokkosSparse_spmv.hpp
cusparse 12 requires that the y (output) vector in ``cusparseSpMV`` has 16-byte alignment (for all scalar types).
So check for this and call the native fallback if y has less than 16 bytes alignment.
This will fix https://github.com/trilinos/trilinos/issues/11926.
=> cusparse 12 spmv: check y vector alignment

ode/CMakeLists.txt
``ode/`` in the binary/build directory shouldn't be added as a header directory. This is because the ODE component has no auto-generated headers for ETI. The unit tests might be there, but contain no headers that need to be found.
This fixes errors when building against a Trilinos installation, where CMake looks for this directory that doesn't exist.
=> Remove non-existant dir from CMake include paths

perf_test/sparse/CMakeLists.txt, perf_test/sparse/KokkosSparse_spmv_bsr_benchmark.cpp, sparse/impl/KokkosSparse_crs_detect_block_size.hpp
Adds a `KokkosKernels_sparse_spmv_bsr_benchmark` binary, which uses Google Benchmark to do a BsrMatrix SpMV perf test
* Also adds `KokkosSparse::Impl::crs_detect_block_size()`, which finds the largest block size in a CrsMatrix that yields only dense blocks. This is used in the perf test to automatically detect the block size of a matrix read from disk
=> BsrMatrix SpMV Google Benchmark

sparse/unit_test/Test_Sparse_MergeMatrix.hpp
This corrects a definite omission, and may also fix https://github.com/kokkos/kokkos-kernels/issues/1905 (I don't have access to the test system yet).
=> Add missing `<vector>` include to `Test_Sparse_MergeMatrix.hpp`

common/impl/KokkosKernels_AlwaysFalse.hpp, common/impl/KokkosKernels_ViewUtils.hpp, common/src/KokkosKernels_Error.hpp, perf_test/Benchmark_Utils.hpp, perf_test/sparse/CMakeLists.txt, perf_test/sparse/KokkosSparse_spmv_bsr_benchmark.cpp, sparse/impl/KokkosSparse_crs_detect_block_size.hpp, sparse/impl/KokkosSparse_crs_to_bsr_impl.hpp, sparse/impl/KokkosSparse_spmv_bsrmatrix_impl_v42.hpp, sparse/impl/KokkosSparse_spmv_bsrmatrix_spec.hpp, sparse/src/KokkosKernels_Controls.hpp, sparse/src/KokkosSparse_BsrMatrix.hpp, sparse/src/KokkosSparse_spmv.hpp, sparse/tpls/KokkosSparse_spmv_bsrmatrix_tpl_spec_decl.hpp, sparse/unit_test/Test_Sparse_spmv_bsr.hpp
Improve performance of the native `BsrMatrix` SpMV, especially for single-vector cases.
* Adds a new `"v4.2"` BsrMatrix SpMV implementation for non-transpose mode.
* It is the default (when TPLs are disabled or not supported) on the GPU for non-transpose mode
* The old implementation is retained for all other modes
* old implementation may be requested explicitly with `controls.setParameter("algorithm", "v4.1")`
* Adds explicit invocation of old "4.1" impl to `KokkosKernels_sparse_spmv_bsr_benchmark`
* When TPLs are enabled, the new implementation may be requested anyway with `controls.setParameter("algorithm", "v4.2")`
*sp* is speedup of 4.2 vs 4.1. TPLs only support specific integer combinations. The table below summarizes the speedup achieved across various operand types
| GPU | single …
=> Improve BSR matrix SpMV Performance

ode/impl/KokkosODE_RungeKutta_impl.hpp, ode/unit_test/Test_ODE_RK.hpp, ode/unit_test/Test_ODE_RK_chem.hpp, perf_test/ode/KokkosODE_RK.cpp
The change should give better data access on CPU
@vbrunini let me know that implements the change we discussed ealier?
=> ODE: changing layout of temp mem in RK algorithms

blas/src/KokkosBlas2_gemv.hpp, blas/src/KokkosBlas3_gemm.hpp
This is actually not a required pre-requisite we only need to check that the views are accessible.
@vbrunini
=> BLAS: fix assignable check in gemv and gemm

sparse/impl/KokkosSparse_mdf_impl.hpp, sparse/src/KokkosSparse_mdf.hpp
Fixes issue with `select_pivot` functor setting potentially invalid intial guess, and returns some optional verbose output
=> mdf: fix initial value in select pivot functor

common/src/KokkosKernels_default_types.hpp, perf_test/sparse/KokkosSparse_spadd.cpp
SpAdd perf test can call cusparse and MKL TPLs directly, but this can only be done if the default ordinal and offset type are both int. Check for this ahead of time and print a decent error message.
Fixes a build error when cusparse is enabled, but offset=int is not enabled.
=> Fix SpAdd perf test when offset/ordinal is not int

ode/unit_test/Test_ODE_Newton.hpp
Attempt to resolve "error: ‘pair’ was not declared in this scope" in cuda/11.2+gcc/8.3.0 builds
=> Test_ODE_Newton: Add template parameters for Kokkos::pair

blas/impl/KokkosBlas2_ger_impl.hpp, blas/tpls/KokkosBlas2_ger_tpl_spec_avail.hpp, blas/tpls/KokkosBlas2_syr_tpl_spec_decl_rocblas.hpp, blas/unit_test/Test_Blas2_ger.hpp, blas/unit_test/Test_Blas2_syr.hpp
Also, other minor improvements: better explanations on unit tests, improved terminology on ger impl (following syr), minor improvement on syr ROC tpl.
=> Remove printouts from the unit tests of ger() and syr()

perf_test/sparse/KokkosSparse_gs.cpp, sparse/impl/KokkosSparse_gauss_seidel_impl.hpp
By default, subsequent kernel launches in a given stream block. Using the LightWeight hint ensures that the PSGS colors loop is non-blocking. This also slightly improves the performance of the GS apply function for some inputs:
```
Before adding LightWeight hint to IterativePSGS:
./perf_test/sparse/sparse_gs --cuda --amtx ~/matrix_market_files/pre2.mtx --point --sweeps 1
*** Symbolic launch time: 0.0344444
*** Symbolic compute time: 3.892e-06
*** Numeric launch time: 0.000437641
*** Numeric compute time: 0.00017407
*** Apply launch time: 0.0034026
*** Apply compute time: 0.000148458
Relative res norm: 5.79029e+37
After adding LightWeight hint to IterativePSGS:
./perf_test/sparse/sparse_gs --cuda --amtx ~/matrix_market_files/pre2.mtx --point --sweeps 1
*** Symbolic launch time: 0.0348005 …
```
=> sparse/impl: Make PSGS non-blocking

.github/workflows/docs.yml
There seems to be a bug we're hitting in versions of doxygen that are < 1.9.7.
Brian has been hitting this in https://github.com/kokkos/kokkos-kernels/pull/1932 while trying to document the spmv overloads.
To address this blocking issue, let us use doxygen 1.9.7, which is available via brew on the macos VMs.
=> .github/workflows/docs.yml: Use up-to-date doxygen version

scripts/docker/Dockerfile.sycl
The SYCL nightly regression tester has been failing for a while because 11.7.0 isn't hosted anymore, only 11.7.1 is, see https://cloud.cees.ornl.gov/jenkins-ci/job/KokkosKernels/ and https://hub.docker.com/r/nvidia/cuda/tags?page=1&name=11.7. This pull request updates the base image to use that.
=> Update SYCL docker image to Cuda 11.7.1

ode/src/KokkosODE_Types.hpp
Compiling the tests for the  SYCL backend currently fails with
```
clang++: warning: CUDA version is newer than the latest supported version 11.5 [-Wunknown-cuda-version]
clang++: warning: CUDA version is newer than the latest supported version 11.5 [-Wunknown-cuda-version]
In file included from /app/kokkos-kernels/ode/unit_test/backends/Test_SYCL_ODE.cpp:19:
In file included from /app/kokkos-kernels/test_common/Test_SYCL.hpp:17:
In file included from /app/kokkos-install/include/Kokkos_Core.hpp:43:
In file included from /app/kokkos-install/include/Kokkos_Core_fwd.hpp:28:
In file included from /app/kokkos-install/include/Kokkos_Macros.hpp:96:
In file included from /app/kokkos-install/include/KokkosCore_Config_SetupBackend.hpp:22:
In file included from …
```
=> Avoid enum without fixed underlying type to fix SYCL

docs/developer/testing_table.rst
Leaving `AT: WIP` applied to skip non-docs CI checks.
Fixes #976.
=> docs: Note which build has eti disabled

.github/workflows/docs.yml
@cwpearson, @lucbv: There appear to be some bugs in sphinx version 7.2.2, see: https://github.com/kokkos/kokkos-kernels/actions/runs/5932096448/job/16085261062?pr=1906.
If these failures continue to be a blocker for our PRs, let us pin sphinx to version 6.2.1.
=> .github/workflows: Pin sphinx version

docs/developer/apidocs/sparse.rst, perf_test/sparse/KokkosSparse_spmv_merge.cpp, perf_test/sparse/KokkosSparse_spmv_struct_tuning.cpp, sparse/impl/KokkosSparse_spmv_bsrmatrix_impl.hpp, sparse/impl/KokkosSparse_spmv_bsrmatrix_impl_v42.hpp, sparse/impl/KokkosSparse_spmv_bsrmatrix_spec.hpp, sparse/impl/KokkosSparse_spmv_impl.hpp, sparse/impl/KokkosSparse_spmv_spec.hpp, sparse/impl/KokkosSparse_spmv_struct_impl.hpp, sparse/impl/KokkosSparse_spmv_struct_spec.hpp, sparse/src/KokkosSparse_BsrMatrix.hpp, sparse/src/KokkosSparse_Utils_cusparse.hpp, sparse/src/KokkosSparse_Utils_rocsparse.hpp, sparse/src/KokkosSparse_spmv.hpp, sparse/tpls/KokkosSparse_spmv_bsrmatrix_tpl_spec_avail.hpp, sparse/tpls/KokkosSparse_spmv_bsrmatrix_tpl_spec_decl.hpp, sparse/tpls/KokkosSparse_spmv_mv_tpl_spec_avail.hpp, sparse/tpls/KokkosSparse_spmv_mv_tpl_spec_decl.hpp, sparse/tpls/KokkosSparse_spmv_struct_tpl_spec_avail.hpp, sparse/tpls/KokkosSparse_spmv_tpl_spec_avail.hpp, sparse/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp, sparse/unit_test/Test_Sparse_replaceSumIntoLonger.hpp, sparse/unit_test/Test_Sparse_spmv.hpp
including cusparse, rocsparse, onemkl wrappers. Resolves #1878
Done for spmv and spmv_mv, both CRS and BSR. Did not do structured spmv yet.
Fix some misc. bugs too:
- Fallback check for cusparse was wrong - we were only calling the TPL for mode 'N', but TPL should be used for 'T' and 'H' also
- In SYCL build, forgetting to #undef a macro caused warning in sparse tests
- Can't call cuSPARSE or MKL spmv with mode 'H' and real scalars. In this case, just switch to mode 'T' since it's equivalent
Tested on weaver (no-TPL and cusparse), caraway (rocsparse) and sunspot (onemkl).
=> Adding exec space instance to spmv

sparse/impl/KokkosSparse_spmv_bsrmatrix_impl.hpp, sparse/impl/KokkosSparse_spmv_bsrmatrix_spec.hpp
Previously, we only excluded complex types. This allowed things like Sacado's Vector types to slip through and cause compile-time errors in Trilinos when they weren't convertible to the tensor core's working precision, e.g. `Kokkos::Experimental::half_t`.
This also consolidates the logic that determines whether tensor cores should be enabled into one place.
Matches some logic added in https://github.com/trilinos/Trilinos/pull/12103 that will be overwritten in the next snapshot.
=> Disallow BsrMatrix tensor-core SpMV on non-scalar types

sparse/src/KokkosKernels_Handle.hpp
Fill in remaining create_gs_handle docs.
Leaving `AT: WIP` label applied to restrict CI checks to github-DOCS and github-FORMAT.
=> Update create_gs_handle docs

sparse/src/KokkosSparse_SortCrs.hpp, sparse/unit_test/Test_Sparse_SortCrs.hpp
``sort_and_merge_graph`` and ``sort_and_merge_matrix`` produced incorrect output if any input view (rowptrs, entries, values) was the same object as the corresponding output view. Fix this and add testing that catches the bug.
=> Fix sort_and_merge functions for in-place case

sparse/src/KokkosSparse_mdf_handle.hpp
Explicitly default to 0 verbosity to avoid false positive "uninitialized condition" Valgrind warnings (see https://github.com/trilinos/Trilinos/issues/11934#issuecomment-1721849102 ).
=> MDF: set default verbosity explicitly to avoid valgrind warnings

sparse/src/KokkosSparse_OrdinalTraits.hpp
@romintomasetti
Marking some functions as constexpr, I think this should work just fine but let us see if a compiler complains based on how some of these constant are defined.
This PR is providing the implementation outlined in issue #1952
=> OrdinalTraits: constexpr functions

batched/dense/impl/KokkosBatched_Axpy_Impl.hpp, batched/dense/impl/KokkosBatched_Copy_Impl.hpp, batched/dense/impl/KokkosBatched_Dot_Internal.hpp, batched/dense/impl/KokkosBatched_Gesv_Impl.hpp, batched/dense/impl/KokkosBatched_HadamardProduct_Impl.hpp, batched/dense/impl/KokkosBatched_Xpay_Impl.hpp, batched/sparse/impl/KokkosBatched_Spmv_Serial_Impl.hpp, batched/sparse/impl/KokkosBatched_Spmv_TeamVector_Impl.hpp, batched/sparse/impl/KokkosBatched_Spmv_Team_Impl.hpp, batched/sparse/src/KokkosBatched_JacobiPrec.hpp, blas/src/KokkosBlas1_nrm2.hpp, blas/unit_test/Test_Blas2_ger.hpp, blas/unit_test/Test_Blas2_syr.hpp, common/src/KokkosKernels_Error.hpp, common/src/KokkosKernels_SimpleUtils.hpp, common/unit_test/Test_Common_ArithTraits.hpp, common/unit_test/Test_Common_LowerBound.hpp, common/unit_test/Test_Common_UpperBound.hpp, ode/impl/KokkosODE_Newton_impl.hpp, sparse/src/KokkosSparse_spmv_team.hpp, sparse/unit_test/Test_Sparse_spmv.hpp
@masterleinad this PR will supersede #1946 
Kokkos Core is about to remove the KOKKOS_PRINTF macro in favor of Kokkos::printf function. To prepare for this we are guarding the old macro to no longer use it when compiling against newer versions of Kokkos Core.
=> KokkosKernels: switching from printf macro to function

common/src/KokkosKernels_Utils.hpp, perf_test/sparse/KokkosSparse_gs.cpp
This PR updates the sparse_gs perf test to use streams. It also updates the perf_test to partition the A matrix into nstream diagonal blocks.
```
StreamID(0): Relative res norm: 0.407859
*** Total block extraction time: 0.658307
*** Total Symbolic launch time: 0.257969
*** Total Symbolic compute time: 3.132e-06
*** Total Numeric launch time: 0.000741617
*** Total Numeric compute time: 0.00274391
*** Total Apply launch time: 0.000514701
*** Total Apply compute time: 0.0176633
*** Total launch time: 0.259225
*** Total compute time: 0.0204104
*** Total compute and launch time: 0.279635
```
```
$ ./sparse_gs --cuda --amtx ~/matrix_market_files/bone010/bone010.mtx --point --sweeps 1 --streams 8
StreamID(0): Relative res norm: 0.40769
StreamID(1): Relative res norm: 0.393488
StreamID(2): …
```
=> perf_test/sparse: Update GS perf_test for streams

perf_test/sparse/KokkosSparse_kk_spmv.cpp
- Add 5 warmup iterations before the real timed iterations (Fixes #1978). This makes a significant difference when timing cusparse spmv
- Print out the actual matrix dimensions and nnz, instead of printing out the randomized matrix settings. Because this is not what you actually run with if the matrix comes from a file.
=> Improve KokkosSparse_kk_spmv

sparse/unit_test/Test_Sparse_Controls.hpp, sparse/unit_test/Test_Sparse_spmv_bsr.hpp
Fix for https://github.com/kokkos/kokkos-kernels/issues/1943
=> Test_Sparse_spmv_bsr.hpp: replace std::optional with custom struct

scripts/cm_test_all_sandia
```
Running on machine: mi250_caraway
M scripts/cm_test_all_sandia
KokkosKernels Repository Status:  e8469fdeb6e733e34c1fef3cc5e2d1dc9497b881 Merge pull request #1974 from cwpearson/enhancement/issue-1671
Kokkos Repository Status:  41cf2e51cd8e63a614aa1b4a9564a35934b805d5 Merge pull request #6303 from thearusable/5635-threads-parallel-scan-with-value-TeamThreadRange
Going to test compilers:  rocm/5.6.0
Testing compiler rocm/5.6.0
Unrecognized compiler rocm/5.6.0 when looking for Spack variants
Unrecognized compiler rocm/5.6.0 when looking for Spack variants
Unrecognized compiler rocm/5.6.0 when looking for Spack variants
Starting job rocm-5.6.0-Hip_Serial-release
Hip IS THE KOKKOS DEVICE
kokkos devices: Hip,Serial
kokkos arch: VEGA90A …
```
=> cm_test_all_sandia: update caraway mi250 queue modules

CMakeLists.txt
While configuring Kokkos Kernels look for the Kokkos package and check that its version is compatible with the current version of Kokkos Kernels. If not we fail configuration with a helpful error message.
=> CMake: Adding logic to catch bad Kokkos version

batched/KokkosBatched_Util.hpp, example/half/xpy.cpp, sparse/src/KokkosSparse_Utils_rocsparse.hpp, sparse/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp
Without this change, we're getting build errors like:
```
kokkos-kernels/batched/KokkosBatched_Util.hpp:201:10: error: no member named 'cout' in namespace 'std'
```
Caused by: https://github.com/kokkos/kokkos/pull/6482
=> upstream iostream removal fix

common/src/KokkosKernels_Half.hpp, common/src/Kokkos_ArithTraits.hpp, common/unit_test/Test_Common_ArithTraits.hpp, test_common/KokkosKernels_TestUtils.hpp
Both half and bhalf implementation details have been moved to Kokkos Core so their implementation in ArithTraits is replaced by the macro that calls Kokkos Core math functions instead.
=> Common: remove half and bhalf implementations

perf_test/blas/blas1/KokkosBlas_dot_mv_perf_test_benchmark.cpp, perf_test/blas/blas1/KokkosBlas_dot_perf_test_benchmark.cpp
Still cleaning up a few cases of missing iostream, the perf tests and benchmarks do not build in our CI and nightly typically so we have not caught these yet...
=> iostream clean-up in benchmarks

batched/dense/impl/KokkosBatched_HostLevel_Gemm_Impl.hpp, batched/dense/src/KokkosBatched_Vector.hpp, blas/impl/KokkosBlas3_gemm_impl.hpp, blas/impl/KokkosBlas3_gemm_spec.hpp, blas/src/KokkosBlas2_gemv.hpp, blas/tpls/KokkosBlas2_gemv_tpl_spec_avail.hpp, blas/tpls/KokkosBlas2_gemv_tpl_spec_decl.hpp, blas/tpls/KokkosBlas3_gemm_tpl_spec_avail.hpp, cmake/KokkosKernels_config.h.in, cmake/kokkoskernels_eti_devices.cmake, common/src/KokkosKernels_ExecSpaceUtils.hpp, common/src/KokkosKernels_default_types.hpp, perf_test/batched/dense/KokkosBatched_Test_BlockTridiagDirect.cpp, perf_test/batched/dense/KokkosBatched_Test_BlockTridiagJacobi.cpp, perf_test/blas/blas1/KokkosBlas_dot_mv_perf_test.cpp, perf_test/blas/blas1/KokkosBlas_dot_perf_test.cpp, perf_test/blas/blas2/KokkosBlas2_gemv_perf_test.cpp, perf_test/blas/blas2/KokkosBlas2_gemv_perf_test_benchmark.cpp, perf_test/blas/blas3/KokkosBlas3_gemm_standalone_perf_test_benchmark.cpp, perf_test/graph/KokkosGraph_color.cpp, perf_test/graph/KokkosGraph_color_d2.cpp, perf_test/graph/KokkosGraph_mis_d2.cpp, perf_test/sparse/KokkosSparse_pcg.cpp, sparse/impl/KokkosSparse_spmv_impl.hpp, sparse/impl/KokkosSparse_sptrsv_solve_impl.hpp, sparse/src/KokkosSparse_CrsMatrix.hpp, sparse/src/KokkosSparse_spgemm_handle.hpp, sparse/src/KokkosSparse_spmv.hpp, sparse/tpls/KokkosSparse_spmv_tpl_spec_avail.hpp, test_common/Test_HIP.hpp
So it's a bit the PR of shame since we should really have done that when Kokkos Core 4.0.0 came out in Jan/Feb this year...
Anyway, it really does not change code that much just reflects that fact that HIP was moved out of Experimental!
I almost want to mark this as `BlockPromotion` but that's not really the case?
=> Experimental hip cleanup

scripts/cm_test_all_sandia
e.g. https://jenkins-son.sandia.gov/view/KokkosKernels/job/KokkosKernels_CarawayMI250_Rocm520_HipSerial/127/console
=> cm_test_all_sandia: allow rocm/5.2.0 for caraway vega90A builds

perf_test/sparse/KokkosSparse_spmv_struct_tuning.cpp, sparse/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp
Possible fix for https://github.com/kokkos/kokkos-kernels/issues/1967
=> CUDA 11.2.1 / cuSPARSE 11.4.0 changed SpMV enums

sparse/tpls/KokkosSparse_spmv_mv_tpl_spec_decl.hpp
Possible fix for SpMM part of https://github.com/kokkos/kokkos-kernels/issues/1967
=> CUDA 11.0.1 / cuSPARSE 11.0.0 changed SpMM enums

blas/src/KokkosBlas1_axpby.hpp
Resolve compilation errors in debug mode:
"error: no member named 'cout' in namespace 'std';"
=> KokkosBlas1_axpby: include <iostream> for debug builds

cmake/KokkosKernelsConfig.cmake.in
* Intent of these changes is to allow for building Trilinos with KokkosKernels as an external TPL
=> KokkosKernelsConfig.cmake: add all_libs target and necessary aliases

blas/impl/KokkosBlas2_gemv_impl.hpp, blas/impl/KokkosBlas2_gemv_spec.hpp, docs/developer/apidocs/sparse.rst, sparse/impl/KokkosSparse_sptrsv_cuSPARSE_impl.hpp, sparse/impl/KokkosSparse_sptrsv_solve_impl.hpp, sparse/impl/KokkosSparse_sptrsv_solve_spec.hpp, sparse/impl/KokkosSparse_sptrsv_symbolic_impl.hpp, sparse/impl/KokkosSparse_sptrsv_symbolic_spec.hpp, sparse/src/KokkosSparse_sptrsv.hpp
The twostage algorithm for https://github.com/kokkos/kokkos-kernels/issues/1860 requires sptrsv execution space overloads.
Fixes: #1994
Caused by: #1980
=> Add sptrsv execution space overloads

sparse/impl/KokkosSparse_spmv_impl.hpp, sparse/unit_test/Test_Sparse_spmv.hpp
Fix for https://github.com/kokkos/kokkos-kernels/issues/2010
Tpetra will set `controls.setParameter("algorithm", "merge")` when it detects a row-length imbalance. Before https://github.com/kokkos/kokkos-kernels/pull/1911, this would change the cuSPARSE implementation when TPLS were enabled and the datatypes were supported by cuSPARSE. After, it would additionally cause native code to use the new merge-path SpMV, which may have a small bug somewhere.
Rather than overload the meaning of "merge", let's just choose a different name.
=> hide native merge-path SpMV behind "native-merge"

lapack/unit_test/backends/Test_OpenMPTarget_Lapack.cpp, lapack/unit_test/backends/Test_SYCL_Lapack.cpp
Missing file when compilation is done with SYCL option.
=> Quick fix on 'lapack' subdirectory, for night compilation with Trilinos

blas/unit_test/Test_Blas2_syr2.hpp
Tested the fix using a Trilinos build with UVM on and all test compile correctly.
The change also makes reasonable sense to me based on the signature of adjacent functions and their respective input arguments...
Hopefully this will fix issue #2027 for good!
=> Syr2: fix2

CHANGELOG.md
* Adding Changelog for Release 4.2.0
Part of Kokkos C++ Performance Portability Programming EcoSystem 4.2
* Formatting the changelog a bit more
Mentioning more clearly LAPACK vs BLAS, grouping PRs by logical work unit, etc...
* Remove minor revisions, improve text descriptions
* Changelog: add spmv perftest detail
---------
=> Adding Changelog for Release 4.2.0 (#2031)

blas/tpls/KokkosBlas1_nrm1_tpl_spec_avail.hpp, blas/tpls/KokkosBlas1_nrm1_tpl_spec_decl.hpp, blas/unit_test/Test_Blas1_nrm1.hpp
Rewriting a bit the TPL layer of nrm1 with cuBLAS as a proof of concept to see if we would like to adopt this change as a new implementation pattern as it reduces the number of macros and the amount of code to maintain.
=> BLAS: nrm1 TPL refactor

blas/impl/KokkosBlas1_axpby_impl.hpp, blas/impl/KokkosBlas1_axpby_mv_impl.hpp, blas/unit_test/Test_Blas1_axpby_unification.hpp, blas/unit_test/Test_Blas2_syr2.hpp
This error was happening only when X and Y were rank-2, Y had nan values, b was zero, and the final Y still had nan values, even though it should not. The error was detected on the Trilinos nightly tests.
Correction:
- neglect original Y when b is zero, so that nan values are not carried out.
- Impl files on axpby are corrected now, and new unit tests were added to replicate the issue.
Thanks for the help from Nathan, Luc, and Christian Glusa (Trilinos team).
=> Axpby bug fix (issue # 2015)

CMakeLists.txt
Sometimes I want the `perf_test` and I don't want the unit tests
Before:
```
-DKokkosKernels_ENABLE_TESTS=OFF \
-DKokkosKernels_ENABLE_PERFTESTS=ON
```
results in no `perf_test`
After
```
-DKokkosKernels_ENABLE_TESTS=OFF \ # or =ON
-DKokkosKernels_ENABLE_PERFTESTS=ON
```
gets the `perf_test`
=> Allow `KokkosKernels_ENABLE_PERFTESTS=ON` to build `perf_test` without `KokkosKernels_ENABLE_TESTS=ON`

perf_test/sparse/KokkosSparse_spmv_benchmark.cpp
Can greatly impact reported timing from this benchmark (100x observed on Aurora)
=> fence Kokkos before timed iterations

BUILD.md, CMakeLists.txt, common/src/KokkosLinAlg_config.h
Two reasons:
1. we don't use it anywhere
2. Kokkos namespace
=> Deprecate `KOKKOSLINALG_OPT_LEVEL`

sparse/src/KokkosSparse_Utils_rocsparse.hpp, sparse/tpls/KokkosSparse_spmv_bsrmatrix_tpl_spec_decl.hpp, sparse/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp
The upcoming ROCm 6 will rename some calls, and move some files around. Previous deprecation warnings are now build errors. This PR addresses two changes in particular:
- The `rocm_version.h` file needs to shift to `rocm-core/rocm_version.h`
- Some `*_ex` calls have been renamed
One issue with these changes is that the `rocm-core` directory came into existence in ROCm 5.2. Attempting to build with these changes will fail for older ROCms.
=> ROCm 6 deprecation fixes for rocsparse

blas/tpls/KokkosBlas2_ger_tpl_spec_decl_blas.hpp, blas/tpls/KokkosBlas2_ger_tpl_spec_decl_cublas.hpp, blas/tpls/KokkosBlas2_ger_tpl_spec_decl_rocblas.hpp, blas/unit_test/Test_Blas1_axpby_unification.hpp, blas/unit_test/Test_Blas2_ger.hpp, blas/unit_test/Test_Blas2_syr.hpp, blas/unit_test/Test_Blas2_syr2.hpp
Corrections for ger, syr, syr2, and axpby.
Thanks to Brian Kelley for pointing out that one should have Kokkos::deep_copy(base, base) instead of Kokkos::deep_copy(view,view), when using view_stride_adpater, otherwise we get an error when using Kokkos::LayoutStride.
Compilation and execution at weaver with ETI_ONLY = OFF are now successful.
=> Correcting BLAS test failures with cuda when ETI_ONLY = OFF (issue #2061)

sparse/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp
Fix for https://github.com/kokkos/kokkos-kernels/issues/2067
This is probably not appropriate for a one-shot SpMV, but may be appropriate for a future symbolic/numeric split in SpMV
=> Don't call `optimize_gemv` for one-shot MKL spmv

blas/impl/KokkosBlas1_axpby_unification_attempt_traits.hpp, blas/src/KokkosBlas1_axpby.hpp
For performance reasons, Trilinos has tests that count the number of calls to Kokkos::deep_copy(). The counts increased with the last changes in axpby(), always when X and Y were rank 2 on device (cuda in the current tests) and 'a' and 'b' were scalars. In such cases, I should not make the internal types of 'a' and 'b' to become Kokkos views, but rather make the internal types to be scalars as well. The current PR makes such performance improvement, not only for the situation of X and Y being rank 2 on device, but also for the situation of X and Y being rank 1 on device. The unit tests at the axpby() level were already very thorough, and they all continue to pass (I temporarily put a printout out in the logic change and confirmed that the new logic is being properly exercised).
Thanks to …
=> Axpby using less deep copy (solves issue #2080)

batched/dense/impl/KokkosBatched_Trsm_Serial_Impl.hpp, batched/dense/impl/KokkosBatched_Trsm_Team_Impl.hpp, common/src/KokkosKernels_Error.hpp, sparse/impl/KokkosSparse_spiluk_numeric_impl.hpp, sparse/impl/KokkosSparse_spiluk_numeric_spec.hpp, sparse/impl/KokkosSparse_spiluk_symbolic_impl.hpp, sparse/src/KokkosKernels_Handle.hpp, sparse/src/KokkosSparse_spiluk.hpp, sparse/src/KokkosSparse_spiluk_handle.hpp, sparse/unit_test/Test_Sparse_par_ilut.hpp, sparse/unit_test/Test_Sparse_spiluk.hpp, sparse/unit_test/Test_vector_fixtures.hpp
Add support for block sparse matrices to all SPILUK algorithms (SEQLVLSCHD_RP, SEQLVLSCHD_TP1, and streams). You can use this feature with one change, providing a >0 block_size when you create your spiluk handle. The views you pass to SPILUK should match the BSR rows/entries/values.
1. There were a couple permutations of Trsm instantiations that were missing that I wanted to use, so I added them.
2. Iluk numeric impl has been encapsulated in a struct. This helps reduce the number of times you have to set up types.
3. Added a new Test_Vector_Fixtures.hpp header in `sparse/unit_test` to provide some utilities I have found to be useful for working with small fixture matrices.
4. Significant re-work of the SPILUK test to improve readability and add lots of additional checks. RP vs. TP1 are …
=> Add block support to all SPILUK algorithms

sparse/src/KokkosSparse_spiluk_handle.hpp
By making block_size default to -1, which means don't change block size.
Also, clean up some strangeness with commas being used to separate statements instead of semincolons.
Fixes #2086
=> Make spiluk_handle::reset backwards compatible

sparse/src/KokkosSparse_spadd.hpp
close https://github.com/kokkos/kokkos-kernels/issues/2089
@ndellingwood You still need to update Trilinos code to add the "m, n" arguments.
=> Fix the spadd API

batched/KokkosBatched_Util.hpp, sparse/impl/KokkosSparse_coo2crs_impl.hpp
You know the drill, anything in `Kokkos::Impl::` is considered private details of Kokkos and is subject to change without notice.  This PR fixes a couple violations I found in KokkosKernels as I was auditing Trilinos to see who is being naughty and uses `Kokkos::Impl::DeepCopy` directly.  The 2nd issue was a few occurrences of using `Kokkos::Impl::ALL_t` that reappeared.
=> Hands off namespace `Kokkos::Impl` - cleanup couple violations that snuck in

sparse/impl/KokkosSparse_gmres_impl.hpp, sparse/impl/KokkosSparse_gmres_spec.hpp, sparse/src/KokkosSparse_gmres.hpp, sparse/unit_test/Test_Sparse_gmres.hpp
Also, add a test for GMRES + BSR, which required a bit of refactoring of the GMRES test file in order to avoid a ton of code duplication.
A follow on PR will deal with blocked L/U preconditions and sptrsv.
=> GMRES: Add support for BSR matrices

cmake/Modules/FindTPLCUBLAS.cmake, cmake/Modules/FindTPLCUSOLVER.cmake, cmake/Modules/FindTPLCUSPARSE.cmake
Fixing issue reported by @jczhang07 
- Allow finding cusparse, cusolver based on manually provided paths
- This is necessary when using an nvhpc toolchain instead of a standard cuda toolchain
- Set header paths correctly (this is redundant in a cuda installation, in which ``$CUDA_ROOT/include`` is already a system include dir, but needed with nvhpc)
Tested by:
- configuring/building with a normal Cuda toolchain install, using the default paths from ``FIND_PACKAGE(CUDA)``
- configuring/building with a copy of the include/lib in a nonstandard location, by setting ``CUBLAS_ROOT`` etc.
- configuring/building with the nvhpc toolchain, where the headers and libraries can't be found by default
=> Fix Cuda TPL finding

lapack/unit_test/Test_Lapack_svd.hpp
Currently we still run the tests on U, S and Vt which does not make sense since we actively skip this test because cuSOLVER does not support more columns than rows...
This should fix the problem with CUDA builds reported in issue #2105
=> Lapack - SVD: adding quick return when cuSOLVER is skipped

batched/dense/src/KokkosBatched_Vector_SIMD.hpp
On Perlmutter@NERSC, I met this error
/usr/lib64/gcc/x86_64-suse-linux/12/include/avx512fp16intrin.h(38): error: vector_size attribute requires an arithmetic or enum type
typedef __half __v8hf __attribute__ ((__vector_size__ (16)));
The workaround was mentioned at https://forums.developer.nvidia.com/t/including-cub-header-breakes-compilation-with-gcc-12-and-sse2-or-better/255018
=> Add a workaround for compilation errors with cuda-12.2.0 + gcc-12.3

blas/tpls/KokkosBlas3_gemm_tpl_spec_decl.hpp, blas/tpls/KokkosBlas_Host_tpl.cpp, blas/tpls/KokkosBlas_Host_tpl.hpp, lapack/unit_test/Test_Lapack_svd.hpp
This is really a problem with our implementation of the BLAS interface when MKL is enabled since MKL redefines the function signatures of blas functions using MKL_INT instead if int...
This sill needs to be tested with openblas to check that it does not break anything in that case, especially with the fortran compilation/linking. Otherwise this might be an approach that can be generalize to the whole BLAS interface.
This should also fix the MKL part of issue #2105
=> Lapack - SVD: fix for unit-test when MKL is enabled

example/wiki/sparse/KokkosSparse_wiki_bsrmatrix.cpp
When building with
KokkosKernels_ENABLE_EXPERIMENTAL=ON
I'm finding that this file is missing an include statement.
=> Fix for missing STL inclusion

blas/tpls/KokkosBlas_Host_tpl.cpp, blas/tpls/KokkosBlas_Host_tpl.hpp
MKL redefines the BLAS interface based on how MKL_INT is defined we need to wrap that definition with our own Kokkos Kernels INT type to make both compatible with regular BLAS.
This should clean-up significantly some of our nightly oneAPI builds, hopefully the serial+openmp should actually pass now!
=> BLAS - MKL: fixing HostBlas calls to handle MKL_INT type

sparse/impl/KokkosSparse_trsv_impl.hpp
It seemed to have a problem with these deep_copies, so just do the copy by hand like it was being done before my recent trsv PR.
Fixes #2114 
Tested a build on weaver and it appears to fix the problem.
=> Fix weird Trilinos compiler error

perf_test/sparse/KokkosSparse_spiluk.cpp, sparse/impl/KokkosSparse_spiluk_numeric_impl.hpp, sparse/impl/KokkosSparse_spiluk_symbolic_impl.hpp, sparse/src/KokkosSparse_LUPrec.hpp, sparse/src/KokkosSparse_spiluk_handle.hpp, sparse/unit_test/Test_Sparse_spiluk.hpp, sparse/unit_test/Test_vector_fixtures.hpp
I took a second look at the gemm interface and realized it did exactly what I needed without needing the temporary scratch space, so that resolves one of my main concerns with the previous PR.
I removed support for the range policy algorithm, which cleaned up a bunch of code.
I added some larger-scale testing.
My main concern now is that I'm still seeing highish residuals, even with bigger matrices:
```
For nrows=9, unblocked had residual: 5.21667e-05
For nrows=3, block_size=3 had residual: 0.0266588
For nrows=5000, unblocked had residual: 7.1784e-05
For nrows=500, block_size=10 had residual: 0.0374661
```
I thought, with bigger matrix, the big difference between blocked and unblocked residuals would go away, but that does not appear to be the case. Is there a definitive test I can do to …
=> Block spiluk follow up

graph/unit_test/CMakeLists.txt
Graph unit tests are unique in that they use default_scalar for the KokkosKernelsHandle. So if test-eti-only is ON, but neither float nor double is instatiated, then error out for the graph unit tests.
Users can still build without float or double if they want, but only if they turn off tests or the graph component.
This resolves the KokkosKernels aspect of this issue: https://github.com/trilinos/Trilinos/issues/12750
Unlike Tpetra, it is perfectly fine to use the KokkosKernels library (and any non-ETI functionality like perftests and examples) with a complex type enabled and its corresponding magnitude type not enabled.
=> CMake: error out in certain case

lapack/unit_test/Test_Lapack_gesv.hpp
Increase tolerance by 50%.
And uncomment the verbose output for when tolerance is exceeded, since that helps debug this sort of issue.
This is only printed at most once so it won't spam the output if the entire vector is wrong.
=> Increase tolerance on gesv test (Fix #2123)

perf_test/sparse/KokkosSparse_spmv_benchmark.cpp
First we need to update the interface so that the spmv function uses the new handle and not the control structure.
Second adding a new option: --mode, if set to "" or "auto" the benchmark will run autonomously a suite of tests, if set to "manual", the benchmark is driven by the user.
=> Benchmark: modifying spmv benchmark to fix interface and run range of spmv tests

batched/KokkosBatched_Util.hpp, batched/dense/impl/KokkosBatched_HostLevel_Gemm_Impl.hpp, batched/dense/impl/KokkosBatched_SVD_Serial_Internal.hpp, common/impl/KokkosKernels_ViewUtils.hpp, sparse/impl/KokkosSparse_coo2crs_impl.hpp, sparse/impl/KokkosSparse_spmv_bsrmatrix_impl_v42.hpp, sparse/src/KokkosSparse_coo2crs.hpp, sparse/unit_test/Test_Sparse.hpp
Since we are now in the 4.2 series we only support up to 4.1.00. Older version of Kokkos Core will require older version of Kokkos Kernels for compatibility. Once 4.3.00 is out we will move to drop support for the 4.1 series and only keep 4.2 and 4.3 series.
=> Kokkos Kernels: update version guards to drop old version of Kokkos

batched/dense/impl/KokkosBatched_Gesv_Impl.hpp, batched/dense/src/KokkosBatched_Gesv.hpp, ode/impl/KokkosODE_BDF_impl.hpp, ode/impl/KokkosODE_Newton_impl.hpp, ode/src/KokkosODE_BDF.hpp, ode/src/KokkosODE_Newton.hpp, ode/src/KokkosODE_Types.hpp, ode/unit_test/Test_ODE.hpp, ode/unit_test/Test_ODE_BDF.hpp, ode/unit_test/Test_ODE_Newton.hpp, perf_test/ode/CMakeLists.txt, perf_test/ode/KokkosODE_BDF.cpp
Adding backward difference formula methods orders 1 to 5 (coefficients for 6 exist but no accurate start-up implemented).
Also implementing a fix for the convergence criteria of the Newton solver...
Fixing some documentation related to the Newton solver input parameters.
@vbrunini when you have time please have a look
=> ODE: BDF methods

sparse/eti/generated_specializations_cpp/spmv/KokkosSparse_spmv_bsrmatrix_eti_spec_inst.cpp.in, sparse/eti/generated_specializations_cpp/spmv/KokkosSparse_spmv_mv_bsrmatrix_eti_spec_inst.cpp.in, sparse/eti/generated_specializations_hpp/KokkosSparse_spmv_bsrmatrix_eti_spec_avail.hpp.in, sparse/eti/generated_specializations_hpp/KokkosSparse_spmv_mv_bsrmatrix_eti_spec_avail.hpp.in, sparse/impl/KokkosSparse_spmv_bsrmatrix_impl.hpp, sparse/impl/KokkosSparse_spmv_bsrmatrix_spec.hpp, sparse/src/KokkosSparse_Utils_mkl.hpp, sparse/src/KokkosSparse_spmv.hpp, sparse/tpls/KokkosSparse_spmv_bsrmatrix_tpl_spec_avail.hpp, sparse/tpls/KokkosSparse_spmv_bsrmatrix_tpl_spec_decl.hpp
@maartenarnst
Moving the macro outside of namespaces to ensure that it will be interpreted correctly when called from any other location in the library.
It does not make much sense to guard Impl code in the Experimental namespace and in this case it cleans up a problem with namespace disambiguation for the compiler...
This PR now supersedes PR #2100 which will be closed when this one gets merged.
=> Sparse MKL: changing the location of the MKL_SAFE_CALL macro

scripts/cm_test_all_sandia
add rocm/5.6.1 and rocm/6.0.0, and openblas/0.3.23 as tpl
=> cm_test_all_sandia: update caraway compilers

sparse/tpls/KokkosSparse_spmv_bsrmatrix_tpl_spec_decl.hpp
This is a fix for bsr spmv using rocsparse for ROCm 6+. The matrix descriptor was changed and the rocsparse calls needed to be updated.
=> Spmv bsr matrix fix missing matrix descriptor (rocsparse)

sparse/tpls/KokkosSparse_spmv_bsrmatrix_tpl_spec_decl.hpp, sparse/tpls/KokkosSparse_spmv_mv_tpl_spec_decl.hpp, sparse/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp
Fix usage of RAII to temporarily set the stream for rocsparse, cusparse spmv.
Temporary objects like ``A();`` get destructed immediately. For the object to have scope lifetime, it needs to be a declaration like ``A a();``. This was causing spmv to always execute on the default stream, so there was incorrect timing in the spmv perf test. It only fenced the stream corresponding to default-constructed space instance, which is not necessarily the same.
@kliegeois This is why changing to ``Kokkos::fence()`` instead of ``exec.fence()`` fixed the timings yesterday.
This should definitely be included in 4.3
=> Fix usage of RAII to set cusparse/rocsparse stream

sparse/impl/KokkosSparse_spmv_bsrmatrix_spec.hpp
Resolve compilation errors in nightly cuda/12.2 A100 build
=> KokkosSparse_spmv_bsrmatrix_spec: fix Bsr_TC_Precision namespacing

perf_test/sparse/KokkosSparse_kk_spmv.cpp
- Add ``--flush`` flag to flush device caches by filling a dummy buffer before each iteration
- makes a big difference on PVC which has a huge L2!
- Add ``--non-reuse`` flag to call the non-reuse interface instead of handle/reuse interface
- Fix modes T, H in nonsquare case - make x and y the correct lengths
- Show more matrix statistics (mean, max nonzeros per row)
=> Spmv perftest improvements

sparse/impl/KokkosSparse_spmv_bsrmatrix_spec.hpp, sparse/impl/KokkosSparse_spmv_spec.hpp
This is only hit when spmv is called with integer scalars, which doesn't happen in our CI but does in Tpetra's default ETI.
@ndellingwood This is not critical as Trilinos doesn't build with ``-Werror``, and it's been there a while, but it would still be nice for 4.3
=> Fix signed/unsigned comparison warning

sparse/tpls/KokkosSparse_spmv_mv_tpl_spec_avail.hpp, sparse/tpls/KokkosSparse_spmv_mv_tpl_spec_decl.hpp, sparse/unit_test/Test_Sparse_spmv.hpp
- Don't use ``cusparseSpMM`` on CUDA 11.6.1 (aka CUSPARSE_VERSION 11702) because it produces incorrect results for a tiny (2x3) matrix
- This specific case appears in a Tpetra CrsMatrix unit test
- Add a test that replicates this
- Had to change spmv_mv test function a little bit to allow nonsquare matrices
- Reported the issue, seems to be a corner case with very small inputs, will re-enable the TPL for larger inputs if we find out for certain that it works
- In spmv_mv cusparse wrapper:
- fix leading dimension (stride) of dense matrix
- fix dimensions and stride of dense matrix for LayoutRight case, in which the X vector is implicitly transposed
- add a test for this case (only for eti-only off)
=> SPMV tpl fixes, cusparse workaround

common/src/KokkosKernels_Utils.hpp, sparse/impl/KokkosSparse_gauss_seidel_impl.hpp
One of the overload requires an unused template, removing that extraneous template and simplify how that function is called in a second overload.
@ndellingwood  We could add that in the release branch eventually?
=> KokkosKernels Utils: cleaning the zero_vector interface

sparse/src/KokkosSparse_BsrMatrix.hpp, sparse/src/KokkosSparse_CrsMatrix.hpp, sparse/src/KokkosSparse_ccs2crs.hpp, sparse/src/KokkosSparse_crs2ccs.hpp, sparse/src/KokkosSparse_crs2coo.hpp, sparse/unit_test/Test_Sparse_TestUtils_RandCsMat.hpp, sparse/unit_test/Test_Sparse_spmv_bsr.hpp, test_common/KokkosKernels_TestUtils.hpp
Now a matrix with offset unspecified (like ``CrsMatrix<Scalar, Ordinal, Device>``) will by default always use an ETI'd type combination.
Before the default offset would be the view's size_type, but this could be either size_t or unsigned int.
=> Use default_size_type as default offset in matrix types

perf_test/sparse/KokkosSparse_spmv_bsr.cpp
Move fences to before time is measured, not after
=> spmv bsr perftest: fix fences

blas/impl/KokkosBlas1_axpby_unification_attempt_traits.hpp, blas/src/KokkosBlas1_axpby.hpp
- resolves test failures in Trilinos (MueLu) that rely on gold file diff comparisons by removing extra output in debug builds
=> KokkosBlas1_axpby.hpp: change debug macro guard for printInformation

batched/dense/impl/KokkosBatched_SVD_Serial_Impl.hpp, batched/dense/impl/KokkosBatched_SVD_Serial_Internal.hpp, batched/dense/src/KokkosBatched_SVD_Decl.hpp
Hi,
I had to re-upload this PR due to some wonkiness in my setup. Apologies for the hassle. The original message is below and I have put the changes on top of the develop branch as requested in the previous PR.
Original message : 
I have have had issues with stalling when attempting to use Serial SVD. The basic behavior is that the superdiagonal entries oscillate around at really small numbers, yet they are still above the threshold checked in bidiSVD to zero them out, resulting in an infinite loop.
This PR introduces a user specified tolerance that can optionally be used to zero out tiny superdiagonal entries in bidiSVD. This change enabled the routine to work without issue for my problems. I ultimately used 2.0 * machine_eps as the tolerance rather than the value used by master.
I am …
=> Add user tolerance to Serial SVD

sparse/tpls/KokkosSparse_spmv_bsrmatrix_tpl_spec_decl.hpp, sparse/tpls/KokkosSparse_spmv_mv_tpl_spec_decl.hpp, sparse/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp
It should just be the default set by the unification layer, e.g. ``KokkosSparse::Impl::spmv_eti_spec_avail<..>::value``. Whether we're compiling the library or not doesn't affect this.
We should do something similar for other TPLs. Many of them instantiate the wrapper twice, one with eti_spec_avail = true and once with false but only one of them will ever get called.
=> spmv tpls: use correct bool for eti template param

blas/src/KokkosBlas1_axpby.hpp, lapack/unit_test/Test_Lapack_svd.hpp
- Update debug level to > 1 guarding `printInformation(...)` in KokkosBlas1_axpby.hpp to reduce noisy test output
- Loosen tolerance of lapack.svd test to avoid random failures that occur near prior tolerance level
=> Updates from feedback runnig Trilinos testing

sparse/tpls/KokkosSparse_spmv_bsrmatrix_tpl_spec_decl.hpp, sparse/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp
Fix #2167.
Classic MKL only runs on synchronous host spaces (serial, openmp) so no need to set an exec space instance in the spmv handle.
=> Don't try to use space instance in classic MKL spmv

lapack/tpls/KokkosLapack_svd_tpl_spec_decl.hpp
Resolves redefintion of struct SVD compilation errors with both MKL and LAPACK are enabled
Reported by @maartenarnst in https://github.com/trilinos/Trilinos/issues/12891
=> KokkosLapack_svd_tpl_spec_decl: defer to MKL spec when LAPACK also enabled

sparse/tpls/KokkosSparse_spmv_mv_tpl_spec_avail.hpp
Address issue #2175
Configuring with magma tpl enabled and cusparse disabled mistakenly triggers the cusparse tpl avail check to be true Guard the KOKKOSSPARSE_SPMV_MV_TPL_SPEC_AVAIL_CUSPARSE macros when CUSPARSE is enabled to prevent this
=> Add guard for cusparse spmv_mv_tpl_spec_avail

sparse/impl/KokkosSparse_trsv_impl.hpp
Fixes #2179, although some unit test coverage for this case would be nice.
=> Add early return if numRows == 0 in trsv to avoid integer divide-by-zero error

batched/dense/unit_test/Test_Batched_BatchedGemm.hpp, lapack/CMakeLists.txt, lapack/tpls/KokkosLapack_Magma_tpl.cpp
Resolve linker errors in Cuda builds with Magma enabled but Cusolver disabled. I overlooked this with #2178 (my local testing had Cusolver enabled), but was picked up in the nightly build
```
01:35:17 CMakeFiles/KokkosKernels_lapack_cuda.dir/backends/Test_Cuda_Lapack.cpp.o: In function `void KokkosLapack::Impl::magmaGesvWrapper<Kokkos::Cuda, Kokkos::View<double**, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Cuda, Kokkos::CudaSpace>, Kokkos::MemoryTraits<1u> >, Kokkos::View<double**, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Cuda, Kokkos::CudaSpace>, Kokkos::MemoryTraits<1u> >, Kokkos::View<int*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<1u> > >(Kokkos::Cuda const&, Kokkos::View<double**, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Cuda, …
```
=> magma: fix linker errors for builds without cusolver

.github/workflows/osx.yml
- test against most recent kokkos release rather than develop branch, as done with AT CI, to avoid compatibility breakages
=> workflows/osx.yml: test against most recent kokkos tag

blas/tpls/KokkosBlas2_syr2_tpl_spec_decl_blas.hpp, blas/tpls/KokkosBlas2_syr_tpl_spec_decl_blas.hpp, blas/tpls/KokkosBlas_Host_tpl.cpp, blas/tpls/KokkosBlas_Host_tpl.hpp
Stick to pattern of removing leading 'c' or 'z' in method name and relying on the template type
=> Resolve vortex compilation issue by resolving (potentially) duplicate symbol

sparse/src/KokkosSparse_BsrMatrix.hpp
It needed to have size_type.
Fixes https://github.com/trilinos/Trilinos/issues/12981
In RBILUK, I was using `local_matrix_host_type` in a few places instead of `local_matrix_device_type`. This exposed a problem where the host type had a different size_type than the device type.
=> BsrMatrix: Fix HostMirror typedef

sparse/tpls/KokkosSparse_spgemm_symbolic_tpl_spec_decl.hpp
This just improves the readability of the output from the tools as it now has a symbolic matching the numeric phase. Previously we only had spgemm in the label which is a bit confusing as it could be the whole spgemm time i.e. both symbolic and numeric, additionally we had symbolic in the MKL path but not in cusparse, rocsparse...
=> Sparse - SpGEMM: labeling spgemm_symbolic in TPL layer

common/impl/KokkosKernels_NaN.hpp, sparse/impl/KokkosSparse_spmv_impl.hpp, sparse/impl/KokkosSparse_spmv_impl_merge.hpp, sparse/src/KokkosSparse_spmv.hpp, sparse/unit_test/Test_Sparse_spmv.hpp, sparse/unit_test/Test_Sparse_spmv_bsr.hpp
Fixes https://github.com/kokkos/kokkos-kernels/issues/2166
When beta is 0, we are supposed to zero out the incoming y elements even if they are `NaN` - multiply by `0` is insufficient.
This fixes a few problems:
1. SpMV unit tests did not test against input NaN.
2. The reference SpMV implementation did not zero y when beta was 0
3. SpMV unit tests generated a single input y vector for tests of various alphas, betas, and transpose modes. However, the output of each mode was used as the input of the consecutive mode. In practice, this means that most SpMVs were tested with input y with all zeros.
4. This covered up mishandling of NaN when beta = 0 in SpmvHierarchicalMerge and spmv_beta_transpose implementations.
5. Testing is also improved to explicitly handle NaNs rather then letting them …
=> SpMV: Test NaN, fix NaN handling when beta=0

blas/tpls/KokkosBlas1_dot_tpl_spec_avail.hpp, blas/tpls/KokkosBlas1_dot_tpl_spec_decl.hpp
(not deleted, just guarded with ``#if 0`` and comments explaining)
It performs significantly worse than our native impl on 11.2, 11.8 and 12.0 on V100. This is in the dot perf test with a warm-up call.
https://github.com/trilinos/Trilinos/issues/12982 was a symptom of this.
https://github.com/trilinos/Trilinos/pull/13033 is the same patch as this, but directly into Trilinos.
=> Disable cuBLAS dot wrapper

sparse/impl/KokkosSparse_spmv_spec.hpp, sparse/src/KokkosSparse_spmv.hpp, sparse/src/KokkosSparse_spmv_handle.hpp, sparse/tpls/KokkosSparse_spmv_bsrmatrix_tpl_spec_decl.hpp, sparse/tpls/KokkosSparse_spmv_mv_tpl_spec_decl.hpp, sparse/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp
Fix spmv performance regressions caused by #2126 
- Use cusparse spmv ALG2 (better for imbalanced matrices) when SPMV_MERGE_PATH is selected, for the correct versions (up to CUDA 11.2.1)
- Because ALG2 is only available for spmv and not spmm, call the rank-1 path unconditionally for rank-2 x/y with 1 column.
- That also means the 1 column case in the SPMV_MV unification layer can go, since the rank-1 path is already taken
Tested manually with cusparse, rocsparse and oneapi on PVC.
=> Fix spmv regressions

graph/impl/KokkosGraph_Distance2Color_impl.hpp, perf_test/sparse/KokkosSparse_sptrsv.cpp, scripts/cm_test_all_sandia, sparse/impl/KokkosSparse_spgemm_impl_memaccess.hpp
Now that we require c++17 support, use [[fallthrough]] to suppress `-Wimplicit-fallthrough` and friends, and add it to `cm_test_all_sandia`
=> c++17: add [[fallthrough]] attribute

sparse/tpls/KokkosSparse_spmv_bsrmatrix_tpl_spec_decl.hpp, sparse/tpls/KokkosSparse_spmv_mv_tpl_spec_decl.hpp
- Mark rank-2 versions as "spmv_mv" not "spmv" (the native impl has this, and it's useful to know which one is being run)
- Add missing commas separating "BSRMATRIX" and the scalar type name
=> SPMV TPLs: improve profile region labels

README.md
Just adding the link to our README file so we can have it displayed for user when they get to our repo
=> README: adding link to scorecard

sparse/unit_test/Test_Sparse_Transpose.hpp
crs, bsr, graph: test cases that are 0x0, 100x0 and 0x100.
In these cases make sure the matrix generator doesn't try to insert any entries, by passing nnz = 0.
=> Add testing for transpose corner cases

sparse/impl/KokkosSparse_spmv_impl.hpp, sparse/src/KokkosSparse_spmv_handle.hpp, sparse/unit_test/Test_Sparse_spmv.hpp
``SPMV_MERGE_PATH`` is not always a native algorithm, so fix logic in ``KokkosSparse::is_spmv_algorithm_native`` for that. Add ``SPMV_NATIVE_MERGE_PATH`` to mean the KK implementation specifically. Test this new option.
Tested on Vortex with CUDA 11.2 - in this version ``SPMV_MERGE_PATH`` means ``CUSPARSE_SPMV_CSR_ALG2`` should be used. Verify that both the TPL and native merge path are used when expected.
=> Fix logic around merge path with TPLs

common/src/KokkosKernels_SimpleUtils.hpp, sparse/unit_test/Test_Sparse_spgemm.hpp
Change the distribution A, B values are sampled from so that values in C can't end up close to 0 (as the result of summing terms that are not very close to 0). The relative error metric in ``is_same_matrix`` is sensitive to this situation.
Fixes #2232, verified on blake
=> spgemm unit test: change matrix value distribution

example/wiki/sparse/CMakeLists.txt, example/wiki/sparse/KokkosSparse_wiki_bsrmatrix_2.cpp
There is already an example for this but it uses a CrsMatrix as starting point to build a BsrMatrix which is not really helpful in general as the hope is that you can use the BsrMatrix without needing the CrsMatrix as it would double the storage needed...
=> Sparse - BsrMatrix: adding new wiki example for documentation

sparse/impl/KokkosSparse_crs_to_bsr_impl.hpp
Just a quick little fix to avoid build errors with -Werror
=> Sparse - CrsToBsr: fix type mismatch

common/src/KokkosKernels_BlockUtils.hpp
When building Stokhos BlockCrs, this util function gave a warning about memcpy modifying a non-trivially-copyable type. Silence it by casting to ``char*``
=> Fix warning about memcpy

graph/impl/KokkosGraph_BFS_impl.hpp, graph/unit_test/Test_Graph_rcm.hpp
- Add a test that replicated an issue where ``findPseudoPeripheral()`` returned -1 as the starting vertex for RCM
- Add a test where the graph has 2 connected components
- Improve choice of starting vertex:
- Instead of choosing a min-degree starting vertex once, always start (or restart) with the min-degree unlabeled vertex.
- That way in graphs with multiple connected components, the starting vertex for components other than the 1st one is chosen with the same heuristic, instead of arbitrarily.
- Apply reversing as labels are computed, instead of at the end. This saves a loop over all the labels
=> RCM fixes, improvements

sparse/impl/KokkosSparse_spadd_numeric_impl.hpp, sparse/impl/KokkosSparse_spadd_symbolic_impl.hpp, sparse/src/KokkosSparse_par_ilut.hpp
also a few `std::is_same<...>::value` -> `std::is_same_v<...>` along the way
=> sparse: replace macros with constexpr bools

common/src/KokkosKernels_Utils.hpp, sparse/impl/KokkosSparse_bspgemm_impl_kkmem.hpp, sparse/impl/KokkosSparse_bspgemm_impl_speed.hpp, sparse/impl/KokkosSparse_spgemm_impl_kkmem.hpp, sparse/impl/KokkosSparse_spgemm_impl_speed.hpp, sparse/impl/KokkosSparse_spgemm_jacobi_sparseacc_impl.hpp
Previously
```c++
In *p1;
Out *p2 = alignPtr<In*, Out>(p1);
```
Now
```c++
In *p1;
Out *p2 = alignPtrTo<Out>(p1); // template argument inferred
```
=> Rename `Impl::alignPtr` to `Impl::alignPtrTo`, allow it to infer argument type

sparse/impl/KokkosSparse_spadd_symbolic_impl.hpp
This fixes some spadd unit test failures on SYCL
Closes https://github.com/kokkos/kokkos-kernels/issues/2257 and https://github.com/kokkos/kokkos-kernels/issues/2258 
Probably partial fix for https://github.com/kokkos/kokkos-kernels/issues/1961
=> sparse: spadd_symbolic fences before device values used on host

common/src/KokkosKernels_Utils.hpp, common/unit_test/Test_Common.hpp, common/unit_test/Test_Common_AlignPtrTo.hpp
This pull request provides an alternative `Impl::alignPtrTo` when SYCL is enabled.
On SYCL, `Impl::alignPtr` was providing a misaligned or otherwise incorrect pointer (even when called on an aligned pointer), and calling `Kokkos::atomic_add` on it is either a no-op or just zeros out the memory, causing an incorrect result to be produced.
From SpGEMM:
https://github.com/kokkos/kokkos-kernels/blob/0a0c04836c0ffd7cb85ab17b3f1e34ae3c919bff/sparse/impl/KokkosSparse_spgemm_impl_kkmem.hpp#L639-L640
https://github.com/kokkos/kokkos-kernels/blob/0a0c04836c0ffd7cb85ab17b3f1e34ae3c919bff/sparse/impl/KokkosSparse_spgemm_impl_kkmem.hpp#L795
This pull request also adds unit tests that assert SYCL still fails in this particular way. If those unit tests start to fail, this workaround can be revisited, …
=> sycl: use alternative `alignPtrTo` when SYCL is enabled (SpGEMM)

sparse/unit_test/Test_Sparse_spmv_bsr.hpp
Fixes https://github.com/kokkos/kokkos-kernels/issues/2268
=> handle_t* -> std::unique_ptr<handle_t> in Bsr SpMV unit tests

blas/src/KokkosBlas2_gemv.hpp
Since onemkl does not support the transpose and conjugate mode at this point we should revert back to native implementation.
=> BLAS - gemv: using fallback when mode is 't' or 'c' and onemkl is used

batched/dense/impl/KokkosBatched_Pttrf_Serial_Impl.hpp, batched/dense/impl/KokkosBatched_Pttrf_Serial_Internal.hpp, batched/dense/src/KokkosBatched_Pttrf.hpp, batched/dense/unit_test/Test_Batched_Dense.hpp, batched/dense/unit_test/Test_Batched_DenseUtils.hpp, batched/dense/unit_test/Test_Batched_SerialPttrf.hpp, batched/dense/unit_test/Test_Batched_SerialPttrf_Complex.hpp, batched/dense/unit_test/Test_Batched_SerialPttrf_Real.hpp, blas/impl/KokkosBlas_util.hpp
This PR implements [pttrf](https://netlib.org/lapack/explore-html-3.6.1/d0/d2f/group__double_p_tcomputational_gad408508a4fb3810c23125995dc83ccc1.html) function.
1. `KokkosBatched_Pttrf_Serial_Impl.hpp`: Internal interfaces
2. `KokkosBatched_Pttrf_Serial_Internal.hpp`: Implementation details
3. `KokkosBatched_Pttrf.hpp`: APIs
4. `Test_Batched_SerialPttrf.hpp`: Unit tests for that
It computes the `L*D*L**T` factorization of a real symmetric positive definite tridiagonal matrix `A`, where `A` is represented with vectors `D` and `E`.
- `D`: `(batch_count, n)`  
On entry, the `n` diagonal elements of the tridiagonal matrix
`A`. On exit, the `n` diagonal elements of the diagonal matrix
`D` from the `L*D*L**T` factorization of …
=> Implement batched serial pttrf

sparse/impl/KokkosSparse_spiluk_numeric_impl.hpp, sparse/impl/KokkosSparse_sptrsv_solve_impl.hpp, sparse/impl/KokkosSparse_sptrsv_solve_spec.hpp, sparse/src/KokkosKernels_Handle.hpp, sparse/src/KokkosSparse_sptrsv_handle.hpp
Change list:
1) Change `typedef`s to `using`s in sptrsv handle
2) Add block_size setting to handle (unused for now).
3) sptrsv_solve_impl: Wrap entire thing in a struct templated on Handle. This is a pattern I've used successfully in par_ilut and spiluk. The outer struct uses Handle to build up a set of useful types so they don't have to be defined over and over.
4) Get rid of ReturnTeamPolicyType. What it was providing was simple enough to do with a couple lines of code
5) Remove unused ReturnRangePolicyType
Recommend viewing PR with whitespace changes hidden due to the indentation change in sparse/impl/KokkosSparse_sptrsv_solve_impl.hpp
=> A little sptrsv cleanup before the main block effort

sparse/src/KokkosSparse_spmv.hpp
Using native implementation for SYCL spmv if the mode is anything but transpose as the other modes are not implemented, at least in the onemkl we are testing with...
=> Sparse - SpMV: removing calls to unsuported oneapi - MKL functions

sparse/impl/KokkosSparse_spmv_team_spec.hpp, sparse/src/KokkosSparse_spmv_team.hpp
=> Support non-squared matrice in spmv_team

.github/workflows/bdw.yml, .github/workflows/h100.yml, .github/workflows/mi210.yml, .github/workflows/spr.yml
Luc, this is ready for review.
Summary of changes:
- Every time a PR review is submitted, the BDW, H100, and MI210 checks will be triggered. These checks should only run upon PR review submission if they have not already passed on the head commit of the source branch in the given PR.
=> .github/workflows: Auto trigger AT2 ci upon review

.git-blame-ignore-revs
Now that we know what the sha is for the recent big reformat, we can add it to the skip list. I also added Evan's old commit that was also a big reformat commit.
=> Add big reformat commits to ignore revs for blame

sparse/unit_test/Test_Sparse_coo2crs.hpp
With this test deactivated everything in Kokkos Kernels passes. Let us confirm that with a nightly build and potentially create of SYCL CI-build.
=> Sparse - coo2csr: deactivating test on PVC

sparse/src/KokkosSparse_spadd_handle.hpp
From way back in #122, the SpAdd handle had the functions ``get_sort_option()`` and ``set_sort_option()`` copy-pasted from spgemm. But these try to use the member ``bool sort_option``, which never existed. Somehow these functions never produced compile errors until someone tried to call them.
=> SpAdd handle: delete sort_option getter/setter

sparse/impl/KokkosSparse_sptrsv_solve_impl.hpp, sparse/impl/KokkosSparse_sptrsv_solve_spec.hpp, sparse/src/KokkosSparse_LUPrec.hpp, sparse/src/KokkosSparse_sptrsv_handle.hpp, sparse/unit_test/Test_Sparse_spiluk.hpp, sparse/unit_test/Test_Sparse_sptrsv.hpp
* Add support for BSRs to sptrsv (#2281)
* Some compilers throw shadow warnings in static functions (#2297)
=> [4.4.00] Cherry-pick PRs 2281 and 2297

graph/unit_test/CMakeLists.txt
Graph unit tests, with TEST_ETI_ONLY=ON, require double and/or float to be enabled as scalars. Instead of erroring out the configure, just give a warning and disable the graph tests.
This way, a simple configuration like below will succeed with just the warning. This is useful in case the user only wants to build the perf tests/examples without ETI.
```
../kokkos-kernels/cm_generate_makefile.bash \
--no-default-eti
```
=> Don't error out if graph unit tests disabled

cmake/kokkoskernels_eti_offsets.cmake
If building KokkosKernels standalone, leave int as the default offset (this was the case since #2140). But if building KokkosKernels as a Trilinos/Tribits package, then make size_t the default offset because this is what the Tpetra stack currently uses.
There will be an identical non-release patch into Trilinos, and this should also be included in the next release.
=> Restore size_t as default offset, in Tribits builds

batched/dense/impl/KokkosBatched_Pttrs_Serial_Impl.hpp, batched/dense/impl/KokkosBatched_Pttrs_Serial_Internal.hpp, batched/dense/src/KokkosBatched_Pttrs.hpp, batched/dense/unit_test/Test_Batched_Dense.hpp, batched/dense/unit_test/Test_Batched_SerialPttrs.hpp, batched/dense/unit_test/Test_Batched_SerialPttrs_Complex.hpp, batched/dense/unit_test/Test_Batched_SerialPttrs_Real.hpp, blas/impl/KokkosBlas_util.hpp
This PR implements [pttrs](https://www.netlib.org/lapack//explore-html/d9/dc9/group__pttrs_ga969bdf7ff1290319fa68fd84b2bc2928.html) function.
1. `KokkosBatched_Pttrs_Serial_Impl.hpp`: Internal interfaces
2. `KokkosBatched_Pttrs_Serial_Internal.hpp`: Implementation details
3. `KokkosBatched_Pttrs.hpp`: APIs
4. `Test_Batched_SerialPttrs.hpp`: Unit tests for that
It solves the equation `A * x = b`, where `A` is a real symmetric (complex Hermitian) positive definite tridiagonal matrix `A`, represented by vectors `D` and `E`. 
Before solving the factorization `A = U**H * D * U` or `A = L * D * L**H` must be computed by Pttrf.
- `D`: `(batch_count, n)`  
On entry, the `n` diagonal elements of the tridiagonal matrix
`A`. On …
=> Implement batched serial pttrs

.github/workflows/at2.yml, .github/workflows/bdw.yml, .github/workflows/h100.yml, .github/workflows/mi210.yml, .github/workflows/spr.yml
- New reviewer workflow is:
1-review
2-approve if everything looks good
3-scroll to bottom of PR with CI statuses
4-click details on one of the github-AT2 jobs
5-click re-run all jobs
Anyone on the approved team can do this. PRs authored by and with commits solely from approved team members will still auto-run without a reviewer.
=> Remove review trigger and group github-{BDW,H100,MI201} under github-AT2

batched/dense/impl/KokkosBatched_Pbtrf_Serial_Impl.hpp, batched/dense/impl/KokkosBatched_Pbtrf_Serial_Internal.hpp, batched/dense/src/KokkosBatched_Pbtrf.hpp, batched/dense/unit_test/Test_Batched_Dense.hpp, batched/dense/unit_test/Test_Batched_DenseUtils.hpp, batched/dense/unit_test/Test_Batched_SerialPbtrf.hpp, batched/dense/unit_test/Test_Batched_SerialPbtrf_Complex.hpp, batched/dense/unit_test/Test_Batched_SerialPbtrf_Real.hpp, blas/impl/KokkosBlas_util.hpp
This PR implements [pbtrf](https://netlib.org/lapack/explore-html/dc/d58/group__pbtrf_gafd2c3ba375ecee6dba1fba62696993e0.html) function.
1. `KokkosBatched_Pbtrf_Serial_Impl.hpp`: Internal interfaces
2. `KokkosBatched_Pbtrf_Serial_Internal.hpp`: Implementation details
3. `KokkosBatched_Pbtrf.hpp`: APIs
4. `Test_Batched_SerialPbtrf.hpp`: Unit tests for that
It computes the Cholesky factorization `U**H*U` (or `L*L**H`) factorization of a real symmetric (or complex Hermitian) positive definite band matrix `A`, where `A` is stored in a [band storage](https://www.netlib.org/lapack/lug/node124.html).
- `A`: `(batch_count, ldab, n)`  
On entry, the upper or lower triangle of the symmetric band
matrix A, stored in the first KD+1 …
=> implement batched serial pbtrf

.github/workflows/mi210.yml
Clean-up a few things in the mi210 workflow as well should make it a little bit more readable and maintainable.
=> AT-2: adding non-TPL build for HIP backend

.github/workflows/at2.yml, .github/workflows/bdw.yml, .github/workflows/spr.yml
- Enable PR_BDW_CLANG1001_THREADS_SERIAL_LEFT_REL
- Enable PR_SPR_ONEAPI202310_OPENMP_LEFT_MKLBLAS_MKLLAPACK_REL
- ~~Enable PR_BDW_GNU1020_OPENMP_LEFT_REL_NOETI~~
- ~~Enable PR_BDW_GNU1020_THREADS_SERIAL_RIGHT_REL~~
- Throttle both down to `make -j8`.
=> .github/workflows: Add remaining spr and bdw checks

lapack/src/KokkosLapack_svd.hpp
This PR has minor changes for validity checks for output views U and Vt, as follows:
- if ```jobu``` = 'S', ```U``` has sizes of M x min(M,N)
- if ```jobvt``` = 'S', ```Vt``` has sizes of min(M,N) x N
(see: https://www.netlib.org/lapack/explore-3.1.1-html/zgesvd.f.html)
=> Modify validity checks for output views sizes in svd

batched/dense/impl/KokkosBatched_SVD_Serial_Internal.hpp, batched/dense/unit_test/Test_Batched_SerialSVD.hpp, example/wiki/sparse/KokkosSparse_wiki_spadd.cpp
Fix #2344, where SVD would hang due to one of the edge cases not being handled correctly.
Add tests (including the reproducer from the issue) which together exercise the two main edge cases.
Also did some miscellaneous cleanup like replace fabs (C math function) with ``Kokkos::abs``.
=> Fix #2344: SVD hanging

sparse/impl/KokkosSparse_sort_crs_impl.hpp, sparse/src/KokkosSparse_SortCrs.hpp
Don't use the bulk sort algorithm for KokkosSparse::sort_crs_matrix when we expect it to be bad:
1. On SYCL GPUs without ONEDPL support for sort_by_key
2. On AMD GPUs without ROCTHRUST sort_by_key
3. On MI300A
For 1-2, Kokkos currently falls back to a host sort implementation
For 3, ROCTHRUST was observed to be slower than the alternative sort_crs_matrix implementation (https://github.com/kokkos/kokkos-kernels/issues/2352)
=> Don't use bulk sort in KokkosSparse::sort_crs_matrix sometimes

ode/unit_test/Test_ODE_BDF.hpp
Some compilers issue a set-but-unused warning here since no field of `mySys` is actually used (`neqs` is a static member).
=> Fix set-but-unused in Test_ODE_BDF

perf_test/sparse/KokkosSparse_sort_crs.cpp
also: random_shuffle is deprecated / removed
=> sparse_sort_crs: fix column shuffle indices

.github/workflows/bdw.yml, .github/workflows/mi210.yml
For some reason depandabot only tried to bump the version without using a sha so I'm switching to sha and hoping it will keep it up to date!
=> workflows: fixing some action versions using current sha

perf_test/blas/blas3/KokkosBlas3_gemm_standalone_perf_test.cpp
Useful information for a performance test to show.
=> gemm perf_test: print matrix sizes

.github/workflows/bdw.yml, .github/workflows/volta70.yml
We are pinning the action used by sha to avoid potential security issues.
This showed up in our code scanning alerts: https://github.com/kokkos/kokkos-kernels/security/code-scanning
=> workflows: fixing dependency for checkout action in volta70.yml

common/src/KokkosKernels_HashmapAccumulator.hpp, graph/impl/KokkosGraph_Distance1Color_impl.hpp, graph/impl/KokkosGraph_ExplicitCoarsening_impl.hpp
Let Function Template Argument Deduction do its job, do not interfere.
=> Do not specify template argument when using Kokkos atomics

common/unit_test/Test_Common_float128.hpp, sparse/src/KokkosSparse_BsrMatrix.hpp, sparse/src/KokkosSparse_CrsMatrix.hpp
We are looking at deprecating atomic_assign() https://github.com/kokkos/kokkos/issues/7449 Use atomic_store() instead.
=> Prefer `atomic_assign(ptr, val) -> atomic_store(ptr, val)`

common/src/KokkosKernels_HashmapAccumulator.hpp, common/src/KokkosKernels_Uniform_Initialized_MemoryPool.hpp, graph/impl/KokkosGraph_ExplicitCoarsening_impl.hpp, graph/src/KokkosGraph_CoarsenHeuristics.hpp, sparse/impl/KokkosSparse_bspgemm_impl_kkmem.hpp, sparse/impl/KokkosSparse_partitioning_impl.hpp, sparse/impl/KokkosSparse_spgemm_impl_compression.hpp, sparse/impl/KokkosSparse_spgemm_impl_kkmem.hpp, sparse/impl/KokkosSparse_spgemm_jacobi_sparseacc_impl.hpp
Rewrote `atomic_compare_exchange_strong(ptr, expected, desired)` as `expected == atomic_compare_exchange(ptr, expected, desired)` as `atomic_compare_exchange_strong` is on its way to be deprecated/removed (see https://github.com/kokkos/kokkos/pull/7458)
=> Prefer `expected == atomic_compare_exchange(ptr, expected, desired)`

.github/workflows/at2.yml, .github/workflows/bdw.yml, .github/workflows/h100.yml, .github/workflows/mi210.yml, .github/workflows/osx.yml, .github/workflows/spr.yml, .github/workflows/volta70.yml
The variable is set directly in at2.yml so it can be uniformly applied to all the "sub-workflows" making maintenance when a new release of kokkos comes out easier.
=> workflows: adding variable to set kokkos version to test against

common/src/KokkosKernels_default_types.hpp
Fix for [2390](https://github.com/kokkos/kokkos-kernels/issues/2390)
Make intel 19 happy by not trying to deprecate a type alias.
=> remove deprecation message on intel 19

batched/KokkosBatched_Util.hpp
Fix for https://github.com/kokkos/kokkos-kernels/issues/2374: this macro is a reserved identifier, so it needs to go. See also https://github.com/kokkos/kokkos-kernels/issues/2364
It has no uses in Trilinos, but I'm deprecating this rather than outright removing it because the comment hints at some trilinos integration thing.
=> deprecate `__KOKKOSBATCHED_PROMOTION__`

sparse/impl/KokkosSparse_trsv_impl.hpp
A slightly different for loop can avoid having to separate out the last iteration in all the uppertri functions.
=> Reduce duplicated code in trsv

batched/dense/impl/KokkosBatched_Laswp_Serial_Impl.hpp, batched/dense/impl/KokkosBatched_Laswp_Serial_Internal.hpp, batched/dense/src/KokkosBatched_Laswp.hpp, batched/dense/unit_test/Test_Batched_Dense.hpp, batched/dense/unit_test/Test_Batched_SerialLaswp.hpp
This PR implements [laswp](https://www.netlib.org/lapack/explore-html/d1/d7e/group__laswp_ga5d3ea3e3cb61e32750bf062a2446aa33.html) function, which is needed for [getrf PR](https://github.com/kokkos/kokkos-kernels/pull/2331).
1. `KokkosBatched_Laswp_Serial_Impl.hpp`: Internal interfaces with implementation details
2. `KokkosBatched_Laswp.hpp`: APIs
3. `Test_Batched_SerialLaswp.hpp`: Unit tests for that
This performs a series of row interchanges on a general rectangular matrix.
- `A`: `(batch_count, m, n)` or `(batch_count, m)`
On entry, the M-by-N matrix or the length M vector. The row interchanges will be applied to the matrix of column dimension N. On exit, the permuted matrix or vector.
- `IPIV`: `(batch_count, m)`
The pivot indices; for `0 <= i < m`, row `i` …
=> Implement batched serial laswp

batched/KokkosBatched_Util.hpp
I was thinking about deprecating some other things using the same strategy and realized 2392 missed a case where `__KOKKOSBATCHED_PROMOTION__` was previously defined.
=> 2392 missed a case where __KOKKOSBATCHED_PROMOTION__ was defined

batched/dense/impl/KokkosBatched_Pbtrs_Serial_Impl.hpp, batched/dense/impl/KokkosBatched_Pbtrs_Serial_Internal.hpp, batched/dense/src/KokkosBatched_Pbtrs.hpp, batched/dense/unit_test/Test_Batched_Dense.hpp, batched/dense/unit_test/Test_Batched_SerialPbtrs.hpp, batched/dense/unit_test/Test_Batched_SerialPbtrs_Complex.hpp, batched/dense/unit_test/Test_Batched_SerialPbtrs_Real.hpp, blas/impl/KokkosBlas_util.hpp
This PR implements [pbtrs](https://www.netlib.org/lapack/explore-html/db/dec/group__pbtrs_ga1ccbe62287933e8bf693cc0e506d167f.html) function.
1. `KokkosBatched_Pbtrs_Serial_Impl.hpp`: Internal interfaces
2. `KokkosBatched_Pbtrs_Serial_Internal.hpp`: Implementation details
3. `KokkosBatched_Pbtrs.hpp`: APIs
4. `Test_Batched_SerialPbtrs.hpp`: Unit tests for that
It solves the equation `A * x = b`, where `A` is a real symmetric (complex Hermitian) positive definite band matrix `A`, where `A` is stored in a [band storage](https://www.netlib.org/lapack/lug/node124.html).
Before solving, the Cholesky factorization `A = U**H*U` or `A = L*L**H`  must be computed by Pbtrf.
- `A`: `(batch_count, ldab, n)`  
On entry, the upper or …
=> implement batched serial pbtrs

batched/dense/impl/KokkosBatched_HostLevel_Gemm_DblBuf_Impl.hpp, common/src/Kokkos_InnerProductSpaceTraits.hpp, sparse/src/KokkosSparse_BsrMatrix.hpp, sparse/src/KokkosSparse_spmv.hpp, sparse/unit_test/Test_Sparse_spmv_bsr.hpp
When result type is double and inputs are floats, one input has to be cast to double so the multiplication operator for double is used instead of the float multiplication operator that could overflow for valid double values.
@csiefer2 this should take care of the security issue you reported.
=> Fixing potential overflow issue in inner product trait

batched/KokkosBatched_Util.hpp, batched/dense/impl/KokkosBatched_Eigendecomposition_Serial_Internal.hpp, batched/dense/impl/KokkosBatched_Gemm_Serial_Impl.hpp, batched/dense/impl/KokkosBatched_InverseLU_Serial_Impl.hpp, batched/dense/impl/KokkosBatched_LU_Serial_Impl.hpp, batched/dense/impl/KokkosBatched_Trsm_Serial_Impl.hpp, batched/dense/impl/KokkosBatched_Trsv_Serial_Impl.hpp, perf_test/blas/blas3/KokkosBlas3_gemm_perf_test.hpp
In favor of KOKKOSBATCHED_IMPL_ENABLE_INTEL_MKL
One small piece of https://github.com/kokkos/kokkos-kernels/issues/2364 at a time.
=> Deprecate `__KOKKOSBATCHED_ENABLE_INTEL_MKL__`

batched/dense/impl/KokkosBatched_Iamax_Serial_Impl.hpp, batched/dense/impl/KokkosBatched_Iamax_Serial_Internal.hpp, batched/dense/src/KokkosBatched_Iamax.hpp, batched/dense/unit_test/Test_Batched_Dense.hpp, batched/dense/unit_test/Test_Batched_SerialIamax.hpp
This PR implements [iamax](https://netlib.org/lapack/explore-html/dd/d52/group__iamax_gacec03c5109f531c06b4fb301cf1a2d7a.html#gacec03c5109f531c06b4fb301cf1a2d7a) function, which is needed for [getrf PR](https://github.com/kokkos/kokkos-kernels/pull/2331).
1. `KokkosBatched_Iamax_Serial_Impl.hpp`: Internal interfaces with implementation details
2. `KokkosBatched_Iamax.hpp`: APIs
3. `Test_Batched_SerialIamax.hpp`: Unit tests for that
This returns the index of the first element having maximum absolute value.
- `X`: `(batch_count, n)`
The length N vector.
Parallelization would be made in the following manner. This is efficient only when 
A is given in `LayoutLeft` for GPUs and `LayoutRight` for CPUs (parallelized over batch direction).
```C++ …
```
=> implement batched serial iamax

batched/KokkosBatched_Util.hpp, batched/dense/impl/KokkosBatched_Gemm_Serial_Impl.hpp, batched/dense/impl/KokkosBatched_InverseLU_Serial_Impl.hpp, batched/dense/impl/KokkosBatched_LU_Serial_Impl.hpp, batched/dense/impl/KokkosBatched_Trsm_Serial_Impl.hpp, batched/dense/impl/KokkosBatched_Trsv_Serial_Impl.hpp, perf_test/blas/blas3/KokkosBlas3_gemm_perf_test.hpp
In favor of KOKKOSBATCHED_IMPL_ENABLE_INTEL_MKL_BATCHED
Once piece of https://github.com/kokkos/kokkos-kernels/issues/2364 at a time.
=> Deprecate __KOKKOSBATCHED_ENABLE_INTEL_MKL_BATCHED__

sparse/unit_test/Test_Sparse_spiluk.hpp
Just like the previous round of fixes related to multiplication overflowing when result type has wider range, this should get CodeQL to be a little happier.
=> Fix potential overflow issue in spiluk

batched/dense/unit_test/Test_Batched_SerialInverseLU.hpp
Last one of a series of fixes to clean-up the CodeQL safety issues, after that we should be all clean!
=> SerialInverseLU: fix overflow in integer multiplication

common/src/KokkosKernels_Utils.hpp
This field seems to be both unset and unused.
Possible fix for something caught in UB sanitizer.
=> remove unused `FillSymmetricLowerEdgesHashMap::lower_only`

common/src/KokkosKernels_Utils.hpp, graph/impl/KokkosGraph_Distance2Color_impl.hpp, graph/src/KokkosGraph_CoarsenConstruct.hpp, sparse/unit_test/Test_Sparse_replaceSumInto.hpp, sparse/unit_test/Test_Sparse_replaceSumIntoLonger.hpp
Fix errors with ubsan. Now all tests pass in a configuration like the new ubuntu-asan-ubsan-ci build.
- replaceSumInto tests: initialize ``bool atomic_`` member
- Fix some issues with create_reverse_map  
- Avoid shifting by negative number of bits (works in practice on tested architectures, but it's technically UB)
- Use ``Kokkos::log2`` to simplify an expression
- Avoid computing ``log2(0)``
- Take out redundant fences
- Graph coarsening: Initialize bool member of struct. If uninitialized, its memory can contain any 8-bit value, not just 0 or 1.
- D2 coloring, VBBIT: fix color interval test. The forbidden colors considered at a time should be ``[color_offset, color_offset+64)`` with an exclusive upper bound. This matches the logic in VB.
=> Fix remaining UB sanitizer errors

ode/unit_test/Test_ODE_RK_counts.hpp
Excluding the Henderson autocatalytic ODE from the set of tests on the SYCL backend. This fails on Blake PVC node while it passes on Aurora. The issue could be related to the hardware or the toolchain, hard to diagnose at this point...
=> Ode sycl fix

.github/workflows/at2.yml, .github/workflows/bdw.yml
This machine has been repurposed.
=> ci: Disable PR tests which ran on `sogpu01` at Sandia

sparse/impl/KokkosSparse_sptrsv_solve_impl.hpp, sparse/src/KokkosSparse_sptrsv_handle.hpp, sparse/unit_test/Test_Sparse_sptrsv.hpp
SPTRSV_CUSPARSE algorithm is not supported for streams, so it made no sense to add it to the list of tested algs inside test_sptrsv_streams. The result was tri_solve_streams being a no-op for this algorithm. Somehow, this was not caught until the block algorithm was being used.
Also, some minor cleanup of alg enum handling in the sptrsv handle. Use a switch statement with a default to catch unhandled enum vals. print_algorithm should just use the alg string to avoid a duplicated switch/ifelseif chain. StringToSPTRSVAlgorithm was not handling several of the enum vals and also returning strings inconsistent with the strings in return_algorithm_string. Grep revealed no one using this function, so I removed it.
I added a check in tri_solve_streams to throw an error if an unsupported alg is …
=> Sptrsv stream test fixes

graph/unit_test/Test_Graph_rcm.hpp, perf_test/graph/KokkosGraph_triangle.cpp, perf_test/sparse/KokkosSparse_spmv_struct.cpp, perf_test/sparse/KokkosSparse_spmv_struct_tuning.cpp, perf_test/sparse/KokkosSparse_spmv_test.cpp, sparse/src/KokkosSparse_BsrMatrix.hpp, sparse/src/KokkosSparse_CcsMatrix.hpp, sparse/src/KokkosSparse_CrsMatrix.hpp, sparse/src/KokkosSparse_StaticCcsGraph.hpp, sparse/src/KokkosSparse_StaticCrsGraph.hpp, sparse/unit_test/Test_Sparse.hpp, sparse/unit_test/Test_Sparse_StaticCrsGraph.hpp
This PR implements what we agreed on, that is Kokkos "Core" is deprecating `Kokkos::StaticCrsGraph` and we transition it to Kokkos Kernels into `KokkosSparse::`.
On 2nd thought we decided to give up on raising deprecation warnings because it was too tricky to guarantee same symbols and not emit diagnostics when the KokkosSparse:: versions are used.
=> Adopt `Kokkos::StaticCrsGraph` from "Core" and move `Static{Ccs,Crs}Graph` to namespace `KokkosSparse::`

batched/dense/impl/KokkosBatched_Trsv_Serial_Impl.hpp, batched/dense/impl/KokkosBatched_Trsv_Serial_Internal.hpp, batched/dense/src/KokkosBatched_Trsv_Decl.hpp, batched/dense/unit_test/Test_Batched_SerialTrsv.hpp, batched/dense/unit_test/Test_Batched_SerialTrsv_Complex.hpp, batched/dense/unit_test/Test_Batched_SerialTrsv_Real.hpp
This PR aims at improving the implementation and testing of serial Trsv.
As a TO DO task, we need to add a ConjTrans implementation of blocked version which requires a little more investigation
=> Improve batched serial trsv

batched/dense/src/KokkosBatched_Trsv_Decl.hpp
Fixes #2456
Because we moved the implementation details of `SerialTrsv` under `Impl` namespace, the definitions of aliases should also be updated
=> fix: alias for serial trsv

batched/dense/impl/KokkosBatched_Trsv_Serial_Internal.hpp, batched/dense/src/KokkosBatched_Trsv_Decl.hpp
=> Deprecated remarks to trsv serial impl

batched/dense/impl/KokkosBatched_Trsv_Serial_Impl.hpp, batched/dense/unit_test/Test_Batched_SerialTrsv.hpp
=> Allow dyn-rank-view in serial trsv

blas/impl/KokkosBlas1_rot_impl.hpp, blas/impl/KokkosBlas1_rot_spec.hpp, blas/src/KokkosBlas1_rot.hpp, blas/src/KokkosBlas1_rotg.hpp, blas/src/KokkosBlas1_scal.hpp, blas/src/KokkosBlas2_ger.hpp, blas/src/KokkosBlas3_trmm.hpp, blas/tpls/KokkosBlas1_rot_tpl_spec_avail.hpp, blas/tpls/KokkosBlas1_rot_tpl_spec_decl.hpp, blas/tpls/KokkosBlas_Host_tpl.cpp, blas/tpls/KokkosBlas_Host_tpl.hpp, blas/unit_test/Test_Blas1_rot.hpp
While writing the documentation I read a good amount of our public API and these are changes that we might want to consider to make things a bit more uniform across the library.
=> Fixes while documenting

blas/tpls/KokkosBlas1_rot_tpl_spec_decl.hpp
After changing the rot interface from using all real to a mix of real and complex coefficients, the cuBLAS call needs to be made to {Z,C}rot instead of {Zd,Cs}rot.
=> BLAS - ROT: calling appropriate cuBLAS function

batched/dense/impl/KokkosBatched_Gemm_Serial_Impl.hpp, batched/dense/impl/KokkosBatched_Gemm_Serial_Internal.hpp, batched/dense/impl/KokkosBatched_Gemm_Team_Internal.hpp, batched/dense/impl/KokkosBatched_InnerGemmFixC_Serial_Impl.hpp, batched/dense/impl/KokkosBatched_LU_Serial_Internal.hpp, batched/dense/src/KokkosBatched_Gemm_Decl.hpp, batched/dense/src/KokkosBatched_InnerGemmFixC_Decl.hpp, batched/dense/unit_test/Test_Batched_SerialGemm.hpp, batched/dense/unit_test/Test_Batched_SerialGemm_Complex.hpp, batched/dense/unit_test/Test_Batched_SerialGemm_Real.hpp, blas/impl/KokkosBlas2_serial_gemv_inner_multiple_dot.hpp, blas/impl/KokkosBlas_util.hpp, common/src/KokkosKernels_BlockUtils.hpp, sparse/impl/KokkosSparse_bspgemm_impl_seq.hpp, sparse/impl/KokkosSparse_spmv_bsrmatrix_impl.hpp
This PR aims at improving the implementation and testing of serial Gemm.
=> Improve batched serial gemm

example/wiki/blas/KokkosBlas1_wiki_rotg_rot.cpp, example/wiki/blas/KokkosBlas1_wiki_rotmg_rotm.cpp
Resolves warnings error: unused parameter 'argc'
[-Werror=unused-parameter] etc.
=> Fix -Werror in a couple wiki examples

batched/dense/impl/KokkosBatched_Getrs_Serial_Impl.hpp, batched/dense/impl/KokkosBatched_Getrs_Serial_Internal.hpp, batched/dense/src/KokkosBatched_Getrs.hpp, batched/dense/unit_test/Test_Batched_Dense.hpp, batched/dense/unit_test/Test_Batched_SerialGetrs.hpp, blas/impl/KokkosBlas_util.hpp
This PR implements [getrs](https://www.netlib.org/lapack/explore-html-3.6.1/dd/d9a/group__double_g_ecomputational_ga58e332cb1b8ab770270843221a48296d.html) function.
1. `KokkosBatched_Getrs_Serial_Impl.hpp`: Internal interfaces
2. `KokkosBatched_Getrs_Serial_Internal.hpp`: Implementation details
3. `KokkosBatched_Getrs.hpp`: APIs
4. `Test_Batched_SerialGetrs.hpp`: Unit tests for that
It solves a general N-by-N matrix `A` using the LU factorization computed by getrf.
- `A`: `(batch_count, n, n)`  
The N-by-N factorized matrix by getrf where `A = P * L * U`; the unit diagonal elements of `L` are not stored.
- `IPIV`: `(batch_count, n)`
The pivot indices from getrf. for `0 <= i < n`, row `i` of the matrix was interchanged …
=> implement batched serial getrs

batched/dense/impl/KokkosBatched_Getrs_Serial_Internal.hpp, batched/dense/impl/KokkosBatched_Laswp_Serial_Impl.hpp, batched/dense/impl/KokkosBatched_Laswp_Serial_Internal.hpp, batched/dense/unit_test/Test_Batched_SerialGetrs.hpp
Fixes #2485 
@cwpearson 
It seems fine on my env, but could you please test on your side?
=> fix: getrs serial internal implementations

perf_test/batched/sparse/cusolver/KokkosBatched_Test_cusolverSp.cpp, perf_test/sparse/KokkosSparse_spadd.cpp, perf_test/sparse/KokkosSparse_spmv_struct_tuning.cpp, sparse/impl/KokkosSparse_sptrsv_cuSPARSE_impl.hpp, sparse/src/KokkosSparse_Utils_cusparse.hpp, sparse/src/KokkosSparse_spgemm_handle.hpp, sparse/src/KokkosSparse_spmv_handle.hpp, sparse/src/KokkosSparse_sptrsv_handle.hpp, sparse/tpls/KokkosKernels_tpl_handles_def.hpp, sparse/tpls/KokkosSparse_spadd_numeric_tpl_spec_decl.hpp, sparse/tpls/KokkosSparse_spadd_symbolic_tpl_spec_decl.hpp, sparse/tpls/KokkosSparse_spgemm_noreuse_tpl_spec_decl.hpp, sparse/tpls/KokkosSparse_spgemm_numeric_tpl_spec_decl.hpp, sparse/tpls/KokkosSparse_spgemm_symbolic_tpl_spec_decl.hpp, sparse/tpls/KokkosSparse_spmv_bsrmatrix_tpl_spec_decl.hpp, sparse/tpls/KokkosSparse_spmv_mv_tpl_spec_decl.hpp, sparse/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp, sparse/unit_test/Test_Sparse_Utils_cusparse.hpp
Fix for https://github.com/kokkos/kokkos-kernels/issues/2371
=> deprecate KOKKOS_CUSPARSE_SAFE_CALL -> KOKKOSPARSE_IMPL_CUSPARSE_SAFE_CALL

perf_test/sparse/KokkosSparse_sptrsv.cpp, sparse/impl/KokkosSparse_twostage_gauss_seidel_impl.hpp, sparse/src/KokkosSparse_LUPrec.hpp, sparse/src/KokkosSparse_sptrsv.hpp, sparse/src/KokkosSparse_sptrsv_supernode.hpp, sparse/unit_test/Test_Sparse_sptrsv.hpp
Moving the generic SpTRSV kenrels out of experimental but keeping the supernodal and stream variants in experimental as they are less tested and more recent respectively.
=> Sparse - SpTRSV: moving kenerls out of Experimental

batched/dense/impl/KokkosBatched_Syr_Serial_Impl.hpp, batched/dense/impl/KokkosBatched_Syr_Serial_Internal.hpp, batched/dense/src/KokkosBatched_Syr.hpp, batched/dense/unit_test/Test_Batched_Dense.hpp, batched/dense/unit_test/Test_Batched_SerialSyr.hpp, blas/impl/KokkosBlas_util.hpp
This PR implements [syr](https://www.netlib.org/lapack/explore-html/dc/d82/group__her_ga07f0e3f8592107877f12a554a41c7413.html) function.
1. `KokkosBatched_Syr_Serial_Impl.hpp`: Internal interfaces
2. `KokkosBatched_Syr_Serial_Internal.hpp`: Implementation details
3. `KokkosBatched_Syr.hpp`: APIs
4. `Test_Batched_SerialSyr.hpp`: Unit tests for that
It performs the rank 1 operation `A:= alpha*x*x**T + A` ({s,d,c,z}syr) or `A:= alpha*x*x**H + A` ({c,z}her)
- `x`: `(batch_count, n)`  
On entry, it contains the n elements of x.
- `A`: `(batch_count, lda, n)`  
On entry, the leading n by n part of the array A must contain the matrix of coefficients. 
On exit, A is overwritten by the updated matrix. 
It should be noted that …
=> Implement batched serial syr

CTestConfig.cmake
As explained in the title, this will allow us to submit to a public cdash [here](https://my.cdash.org/index.php?project=Kokkos+Kernels) for jobs on machines that permit it.
=> Adding ctest config for cdash submissions

batched/dense/impl/KokkosBatched_Lacgv_Serial_Impl.hpp, batched/dense/impl/KokkosBatched_Lacgv_Serial_Internal.hpp, batched/dense/src/KokkosBatched_Lacgv.hpp, batched/dense/unit_test/Test_Batched_Dense.hpp, batched/dense/unit_test/Test_Batched_SerialLacgv.hpp
This PR implements [lacgv](https://www.netlib.org/lapack/explore-html/d9/d50/group__lacgv_gae42087fcabd33130fcbac2aff031de8b.html) function.
1. `KokkosBatched_Lacgv_Serial_Impl.hpp`: Internal interfaces
2. `KokkosBatched_Lacgv_Serial_Internal.hpp`: Implementation details
3. `KokkosBatched_Lacgv.hpp`: APIs
4. `Test_Batched_SerialLacgv.hpp`: Unit tests for that
Conjugates the length n complex vector.
- `x`: `(batch_count, n)`  
On entry, it contains the n elements of `x`.
On exit, `x` is overwritten with `conj(x)`.
No operation is performed if `x` is real vector.
Parallelization would be made in the following manner. This is efficient only when 
A is given in `LayoutLeft` for GPUs and `LayoutRight` for CPUs (parallelized over batch direction).
```C++ …
```
=> implement batched serial lacgv

batched/dense/impl/KokkosBatched_Pbtrs_Serial_Internal.hpp, batched/dense/impl/KokkosBatched_Tbsv_Serial_Impl.hpp, batched/dense/impl/KokkosBatched_Tbsv_Serial_Internal.hpp, batched/dense/src/KokkosBatched_Tbsv.hpp, batched/dense/unit_test/Test_Batched_SerialTbsv.hpp, batched/dense/unit_test/Test_Batched_SerialTbsv_Complex.hpp, batched/dense/unit_test/Test_Batched_SerialTbsv_Real.hpp
This PR aims at improving the implementation and testing of serial tbsv.
Added based on the discussions in #2497
=> Refactor serial tbsv implementation details and tests

.github/workflows/spr.yml
The -Wpass-fail warnings are poluting the output of the compiler this does not really tell us anything either so let us suppress these.
=> Worflow: refactoring SPR to standard cmake and suppress warnings

batched/dense/src/KokkosBatched_Vector_SIMD.hpp
There is a check missing to verify that we are not trying to compile AVX512 intrinsic in GPU code which is obviously not a good idea.
=> SYCL - SIMD: preventing AVX512 code to be compiled when targeting GPU

common/unit_test/Test_Common_AlignPtrTo.hpp
According to https://my.cdash.org/tests/255304660, this works with recent `oneAPI` compiler versions.
=> SYCL: Fix Test_Common_AlignPtrTo.hpp

docs/build_requirements.txt
Next week when dependabot asks to update the versions of our documentation tools let's ask it to stop tracking them for the time being as the new suggested versions are failing...
=> Reverting build_requirements to previous versions

batched/dense/impl/KokkosBatched_Laswp_Serial_Internal.hpp
The current guards are not appropriately working on Blake.
Adding the standard Kokkos guard for pragma unroll does the job
=> Fixing issue with pragma unroll in laswp

batched/KokkosBatched_Util.hpp, batched/dense/impl/KokkosBatched_ApplyHouseholder_Serial_Internal.hpp, batched/dense/impl/KokkosBatched_ApplyQ_Serial_Impl.hpp, batched/dense/impl/KokkosBatched_ApplyQ_Serial_Internal.hpp, batched/dense/impl/KokkosBatched_Householder_Serial_Internal.hpp, batched/dense/impl/KokkosBatched_QR_FormQ_Serial_Internal.hpp, batched/dense/impl/KokkosBatched_QR_Serial_Impl.hpp, batched/dense/impl/KokkosBatched_QR_Serial_Internal.hpp, batched/dense/impl/KokkosBatched_SVD_Serial_Internal.hpp, batched/dense/src/KokkosBatched_ApplyQ_Decl.hpp, batched/dense/src/KokkosBatched_QR_Decl.hpp, batched/dense/unit_test/Test_Batched_Dense.hpp, batched/dense/unit_test/Test_Batched_SerialQR.hpp, blas/impl/KokkosBlas_util.hpp
The serial QR algorithms does not have unit-tests and is failing for non square matrices. See issue #2328.
This first commit fixes the issue with rectangular matrices and adds a basic test for that use case.
Next will work on adding a test that exercises the interfaces on multiple matrices of different sizes within a parallel_for. Finally equivalent tests will be added for the square case as well.
Tasks:
=> batched - dense: Testing and fixing Serial QR

cmake/kokkoskernels_benchmarks.cmake
In anticipation of eventually having CI for clang-tidy, let's not run it on third-party code
=> don't run clang-tidy on google benchmark code

common/src/Kokkos_ArithTraits.hpp
Remove some uses of
* KOKKOS_ACTIVE_EXECUTION_MEMORY_SPACE_SYCL
* KOKKOS_ACTIVE_EXECUTION_MEMORY_SPACE_HOST
These uses are guarded by KOKKOS_ENABLE_SYCL, so the removal is relatively straightforward. Other sites may require some rethinking.
Partial fix for #1721
=> Remove some use of deprecated macros

perf_test/sparse/KokkosSparse_sptrsv_aux.hpp
The csrsv2 functions actually got removed from CUDA 12 as it was a major release. These are still available up to CUDA 11.8 though. This also popped up in issue #2529
=> Sparse - sptrsv: Adjusting the perf test CUDA guard see issue #2428

batched/dense/impl/KokkosBatched_Gbtrf_Serial_Impl.hpp, batched/dense/impl/KokkosBatched_Gbtrf_Serial_Internal.hpp, batched/dense/src/KokkosBatched_Gbtrf.hpp, batched/dense/unit_test/Test_Batched_Dense.hpp, batched/dense/unit_test/Test_Batched_DenseUtils.hpp, batched/dense/unit_test/Test_Batched_SerialGbtrf.hpp, batched/dense/unit_test/Test_Batched_SerialPbtrf.hpp, blas/impl/KokkosBlas_util.hpp
This PR implements [gbtrf](https://netlib.org/lapack//explore-html/df/dd6/group__gbtrf_ga725ad1dfee52c0dff571566d64e30ae8.html) function.
1. `KokkosBatched_Gbtrf_Serial_Impl.hpp`: Internal interfaces
2. `KokkosBatched_Gbtrf_Serial_Internal.hpp`: Implementation details
3. `KokkosBatched_Gbtrf.hpp`: APIs
4. `Test_Batched_SerialGbtrf.hpp`: Unit tests for that
It computes an LU factorization of a real general M-by-N band matrix `A` using partial pivoting with row interchanges.
- `A`: `(batch_count, ldab, n)`  
On entry, the matrix A in band storage. M-by-N matrix to be factored. On exit, the factors `L` and `U` from the factorization where `U` is stored as an upper triangular band matrix with KL+KU superdiagonals in rows 0 …
=> Implement batched serial gbtrf

.gitlab/olcf-gitlab-ci.yml
This adds the configuration to run nightly tests on Frontier. I've tried it on a local branch and it works (see https://my.cdash.org/index.php?project=Kokkos+Kernels). Once this is merged, I will update the configuration on OLCF side to mirror this repo instead of mine. I do get an error message because the coverage is not working. Is there a way to disable it? I get an email about it every time the tests are running
=> Add nightlyt tests on Frontier

ode/impl/KokkosODE_Newton_impl.hpp
The caller can see that this failed by inspecting the returned code and decide what to do.
=> remove log-style printf from NewtonSolve

sparse/src/KokkosSparse_StaticCrsGraph.hpp
to match the default size type for ``CrsMatrix``, ``BsrMatrix``, etc.
Fixes example provided by @MalachiTimothyPhillips that relies on ``StaticCrsGraph`` and ``CrsMatrix`` having the same default ``size_type``. (except for that we also brought ``StaticCrsGraph`` into ``KokkosSparse::``, but that's not unrelated)
=> Fix #2336: in StaticCrsGraph use default_size_type

common/src/KokkosKernels_Macros.hpp
Like all CUDA architectures since Volta, Blackwell has independent thread scheduling. I don't have access to any hardware to test this but it probably fixes SpGEMM on Blackwell (https://github.com/trilinos/Trilinos/issues/13907).
=> Assume independent thread scheduling for Blackwell

common/src/KokkosKernels_Utils.hpp, sparse/impl/KokkosSparse_spgemm_impl_memaccess.hpp
* `get_suggested_vector__size` is a reserved ID
* it seems like an unneeded wrapper
=> replace uses of get_suggested_vector__size with kk_get_suggested_vector_size

batched/dense/impl/KokkosBatched_Gbtrs_Serial_Impl.hpp, batched/dense/impl/KokkosBatched_Gbtrs_Serial_Internal.hpp, batched/dense/src/KokkosBatched_Gbtrs.hpp, batched/dense/unit_test/Test_Batched_Dense.hpp, batched/dense/unit_test/Test_Batched_SerialGbtrs.hpp, blas/impl/KokkosBlas_util.hpp
This PR implements [gbtrs](https://www.netlib.org/lapack/explore-html/d1/dd7/group__gbtrs_ga21ed607226c9690cadc991f15435fa74.html) function.
1. `KokkosBatched_Gbtrs_Serial_Impl.hpp`: Internal interfaces
2. `KokkosBatched_Gbtrs_Serial_Internal.hpp`: Implementation details
3. `KokkosBatched_Gbtrs.hpp`: APIs
4. `Test_Batched_SerialGbtrs.hpp`: Unit tests for that
It solves a general band matrix `A` using the LU factorization computed by gbtrf.
- `A`: `(batch_count, lab, n)`  
The factorized band matrix by gbtrf. The factors L and U from the factorization where U is stored as an upper triangular band matrix with KL+KU superdiagonals in rows 0 to KL+KU, and the multipliers used during the factorization are stored in rows …
=> Implement batched serial gbtrs

common/unit_test/Test_Common.hpp, common/unit_test/Test_Common_CudaIndependentThreads.hpp
Make sure we update KOKKOSKERNELS_CUDA_INDEPENDENT_THREADS for new GPU architectures.
Follow up after https://github.com/kokkos/kokkos-kernels/pull/2558
=> unit test for KOKKOSKERNELS_CUDA_INDEPENDENT_THREADS

docs/source/API/sparse-index.rst, docs/source/API/sparse/par_ilut.rst, scripts/check_api_updates.py, sparse/impl/KokkosSparse_par_ilut_numeric_impl.hpp, sparse/src/KokkosSparse_par_ilut.hpp, sparse/src/KokkosSparse_par_ilut_handle.hpp
1) Improve documentation of parameters and confusing code segments
2) Do not let leftover junk in L_entries and U_entries to cause the
sorted check to fail. Those are output-only parameters.
3) Allow the user to skip the residual computation by setting
residual_norm_delta_stop to zero (or < 0). This can save some
memory if memory is tight.
=> Par_ilut enhancements and fixes

blas/impl/KokkosBlas1_dot_impl.hpp, blas/impl/KokkosBlas1_dot_spec.hpp
This PR modernizes `KokkosBlas::Impl::DotFunctor`:
1. It's an aggregate, no need to explicitly define a constructor.
2. Remove `execution_space` from the `struct` template  arguments and move it to the template arguments of `run`.
=> blas(dot): modernize `DotFunctor`

batched/dense/impl/KokkosBatched_ApplyQ_TeamVector_Impl.hpp, batched/dense/impl/KokkosBatched_HostLevel_Gemm_Serial_Impl.hpp, batched/dense/impl/KokkosBatched_Trsm_Serial_Impl.hpp, batched/dense/impl/KokkosBatched_Trsm_TeamVector_Impl.hpp, batched/dense/impl/KokkosBatched_Trsm_Team_Impl.hpp, blas/src/KokkosBlas1_axpby.hpp, blas/src/KokkosBlas1_nrm2.hpp, blas/src/KokkosBlas1_scal.hpp, blas/src/KokkosBlas1_set.hpp
This is the initial fix for the illegal use of View::stride (and actually also View::extent going forward) reported in #2592 and #2591. I only worked on Serial on my Mac laptop. Let's see which other backends trigger stuff which fail in the testing.
=> Fix illegal use of stride

.github/workflows/at2.yml
This older rocm toolchain is very slow compared to the new rocm 6.2.1 so it is disabled in favor of that newer version.
=> Workflows: removing rocm 5.6.1 from at2

common/src/Kokkos_ArithTraits.hpp
Latest oneAPI release warn about the storage specifier (`static`) in the explicit specialization. `gcc` doesn't allow explicit specializations in classes at all while MSVC requires the duplication of the storage specifier.
We can just use `if constexpr` to avoid the need for a explicit specialization altogether.
=> Avoid warning for explicit instantiations with storage class

.github/workflows/osx.yml
Switching to implicit parallelism levels for build and installation as it may change over time based on github hardware and we don't want to muck with it everytime...
=> osx workflow: removing explicit parallelism levels

sparse/impl/KokkosSparse_sptrsv_cuSPARSE_impl.hpp, sparse/src/KokkosSparse_sptrsv_handle.hpp
This is a bug fix.
In theory, we need a new `sptrsv_numeric` to handle cases that a triangular matrix's sparsity pattern is the same but values have changed.
But because there is no  `sptrsv_numeric` now, I refactored `sptrsvcuSPARSE_symbolic` so that it could be called multiple times.
=> sptrsv_cusparse: must call cusparseSpSV_analysis when matrix values have changed

batched/KokkosBatched_Util.hpp, batched/dense/impl/KokkosBatched_Gemm_Common_Impl.hpp, batched/dense/impl/KokkosBatched_Gemm_Serial_Impl.hpp, batched/dense/impl/KokkosBatched_Gemm_Team_Impl.hpp, batched/dense/impl/KokkosBatched_Gemm_Team_Internal.hpp, batched/dense/impl/KokkosBatched_LU_Team_Internal.hpp, batched/dense/impl/KokkosBatched_Trsm_Team_Internal.hpp, batched/dense/src/KokkosBatched_Gemm_Decl.hpp, batched/dense/unit_test/Test_Batched_TeamGemm.hpp, batched/dense/unit_test/Test_Batched_TeamGemm_Complex.hpp, batched/dense/unit_test/Test_Batched_TeamGemm_Real.hpp
This PR aims at improving the implementation and testing of team Gemm (see also #2469).
Updated 1/May
=> ConjTrans support for batched team gemm

docs/source/API/lapack/gesvd.rst, lapack/src/KokkosLapack_svd.hpp, lapack/tpls/KokkosLapack_svd_tpl_spec_avail.hpp, lapack/tpls/KokkosLapack_svd_tpl_spec_decl.hpp
This reduces ETI and allows users to use any valid layout and still hit the ETI target.
=> Lapack - SVD: Unifying SVector layout to LayoutLeft

sparse/src/KokkosSparse_spmv.hpp
Suprised this was never caught but this variable was unused. It's not really necessary since AMatrix can implicitly convert to AMatrix_Internal but it's not a bad thing to be explicit.
@lucbv This changes a source header but there are no doc changes
=> Fix unused variable warning

docs/build_requirements.txt
certifi is required by requests==2.32.2, but requests does not provide a hash. This causes our --require-hashes to fail, but we don't catch it on github because certifi is pre-installed there.
Fix for https://github.com/kokkos/kokkos-kernels/issues/2600
=> Add certifi==2025.4.26 to docs `build_requirements.txt`

CMakeLists.txt
* CMakeLists.txt calls `KOKKOSKERNELS_ADD_LIBRARY(kokkoskernels)` and then `ADD_LIBRARY(Kokkos::kokkoskernels ALIAS kokkoskernels)`
* `KOKKOSKERNELS_ADD_LIBRARY` forwards to `KOKKOSKERNELS_INTERNAL_ADD_LIBRARY`
* `KOKKOSKERNELS_INTERNAL_ADD_LIBRARY` always calls `ADD_LIBRARY(Kokkos::kokkoskernels ALIAS kokkoskernels)`
Fix for #2631
=> Remove redundant `ADD_LIBRARY(Kokkos::kokkoskernels)`

batched/KokkosBatched_Util.hpp
#2392 incorrectly printed the warning message when the replacement `KOKKOSBATCHED_IMPL_PROMOTION` was used, rather than the intended behavior of when the deprecated` `__KOKKOSBATCHED_PROMOTION__` was used.
The fact that no one complained probably means this wasn't actually used anywhere.
=> Warn about __KOKKOSBATCHED_PROMOTION__ deprecation

README.md
We are still referring to the old license in our README.md. This is probably confusing for our users considering our license file clearly states we are using Apache LLVM exception...
=> Update license information in README.md

blas/impl/KokkosBlas1_axpby_unification_attempt_traits.hpp, blas/src/KokkosBlas1_axpby.hpp
Partial fix for https://github.com/kokkos/kokkos-kernels/issues/2434
* Uses the provided execution space for BLAS1 axpy for internal deep_copy and fill operations. Also rename `Impl::populateRank1Stride1ViewWithScalarOrNonStrideView`
=> Uses BLAS1 axpy execution space for internal deep_copy and fill operations

batched/KokkosBatched_Util.hpp
In support of the continuing quest to remove reserved identifiers.
This macro is going away soon (TM) anyway.
=> Don't lint deprecated macro

sparse/unit_test/Test_Sparse_spmv.hpp
Fixes https://github.com/kokkos/kokkos-kernels/issues/2679. Recent changes in Kokkos core (see https://github.com/kokkos/kokkos/pull/8114) altered the return type of `partition_space(space, 1, 1)` from `std::vector` to `std::array`. Change to calling `partition_space()` which takes a vector of weights, and has `std::vector` return type.
=> Update partition_space() call to match Kokkos core changes

common/src/Kokkos_ArithTraits.hpp
This PR aims at fixing the if constexpr condition to error out `std::complex<long double>` type for SYCL backend.
=> fix: constexpr condition to test long double complex type

example/wiki/blas/KokkosBlas1_wiki_rotg_rot.cpp, example/wiki/blas/KokkosBlas1_wiki_rotmg_rotm.cpp
Probable fix for https://github.com/trilinos/Trilinos/issues/14277
I couldn't actually reproduce it locally, but here's an example:
https://godbolt.org/z/h9Ez4Knsv
=> Fix for trilinos 14277: don't pollute global namespace
